### PR TITLE
Fix processing of forward references

### LINKED ISSUE #294: Analysis of return values does not work with forward references
`Properties.py`:
```python
class A(object):
    def methodA(self):
        return 's'

class B(object):
    def getA(self):
        return self.propA

    @property
    def propA(self):
        return A()
```
Code:
```python
x = B().getA().methodA()
```

x is nothing. This is b/c after AST walker processes class it processes functions in queue order and property `propA` is not yet known when return type of `getA` is analyzed.

Code needs to use delayed resolution or relocation tables.

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #294 

- Implement ordered processing of functions and properties. If return type is not known, process walker for that function which, in turn, can process more.
- Fix some comments and clean up code.

### CODE REVIEW

File: src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+using Microsoft.PythonTools.Parsing.Ast;
+
+namespace Microsoft.PythonTools.Interpreter.Ast {
+    /// <summary>
+    /// Represents set of function body walkers. Functions are walked after
+    /// all classes are collected. If function or property return type is unknown,
+    /// it can be walked, and so on recursively, until return type is determined
+    /// or there is nothing left to walk.
+    /// </summary>
+    class AstAnalysisFunctionWalkerSet {
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs]: Do we care about thread safety of this type?

Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs]: Module analysis is a single thread as far as I can tell, begins with `new AstPythonModule`. Existing code didn't seem to use locks.

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs [hunk 2]
```diff
@@ -346,27 +354,61 @@ sealed class NameLookupContext {
...
+            if (value == null) {
+                _log?.Log(TraceLevel.Verbose, "UnknownCallable", expr.Target.ToCodeString(Ast).Trim());
+                return new AstPythonConstant(_unknownType, GetLoc(expr));
+            }
+            return value;
+        }
+
+        private IMember GetValueFromPropertyOrFunction(IMember fn, Expression expr) {
+            switch (fn) {
+                case IPythonBoundFunction bf:
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: If we move type check into `case`:
```cs
case IPythonBoundFunction bf when bf.Function as IPythonFunction2 f: 
    GetValueFromFunction(f, expr);
```
we can get rid of null check in the `GetValueFromFunction`.

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs [hunk 3]
```diff
@@ -346,27 +354,61 @@ sealed class NameLookupContext {
...
+                    return GetValueFromFunction(bf.Function as IPythonFunction2, expr);
+                case IPythonFunction2 f:
+                    return GetValueFromFunction(f, expr);
+                case IBuiltinProperty2 p:
+                    return GetPropertyReturnType(p, expr);
+            }
+            return null;
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: Shouldn't we return `AstPythonConstant` here?

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs [hunk 4]
```diff
@@ -346,27 +354,61 @@ sealed class NameLookupContext {
...
 
             var m = GetValueFromExpression(expr.Target);
-            if (m is IPythonType type) {
-                if (type.TypeId == BuiltinTypeId.Type && type == Interpreter.GetBuiltinType(BuiltinTypeId.Type) && expr.Args.Count >= 1) {
-                    var aType = GetTypeFromValue(GetValueFromExpression(expr.Args[0].Expression));
-                    if (aType != null) {
-                        return aType;
+            IMember value = null;
+            switch (m) {
+                case IPythonType type:
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: Can save one level of nesting:
```cs
case IPythonType type when type == Interpreter.GetBuiltinType(BuiltinTypeId.Type) && expr.Args.Count >= 1:
    value = GetTypeFromValue(GetValueFromExpression(expr.Args[0].Expression, options));
    break;
case IPythonType type:
    return new AstPythonConstant(type, GetLoc(expr));
```

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs [hunk 5]
```diff
@@ -228,28 +224,40 @@ sealed class NameLookupContext {
...
+                        .Select(x => x.GetMember(Context, expr.Name))
+                        .ExcludeDefault()
+                        .FirstOrDefault();
+                    break;
+                default:
+                    value = GetValueFromPropertyOrFunction(e, expr);
+                    break;
+            }
+            if(value is IBuiltinProperty2 p) {
+                value = GetPropertyReturnType(p, expr);
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: `GetPropertyReturnType` never returns null, so `value == null` can be tested earlier.

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs (hunk 2 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: Sure

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: `GetValueFromMember` and `GetValueFromCallable` and `GetValueFromExpression` expect nulls for logging purposes I guess. However, I don't know if there is much value in it.

Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: I think point of returning nulls is to reduce amount of 'unknowns' objects. Ex if we return unknown constant it gets stuck in return types while null is skipped by `ExcludeDefault` clause

File: src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+            // Do not use foreach since walker list is dynamically
+            // modified and walkers are removed as they are done.
+            while (_functionWalkers.Count > 0) {
+                var walker = _functionWalkers.First().Value;
+                ProcessWalker(walker);
+            }
+        }
+
+        public void ProcessFunction(FunctionDefinition fn) {
+            if (_functionWalkers.TryGetValue(fn, out var w)) {
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs]: Should we remove walker from the dictionary if it was used already?

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: Perhaps we should stick with nulls to save some memory?

File: src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs (hunk 6 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs]: `ProcessWalker` removes it

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: I am actually cleaning up and returning more nulls now.

Comment (AlexanderSher) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: Ah, so that is intentional. Then ok.

File: src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+        private readonly Dictionary<FunctionDefinition, AstAnalysisFunctionWalker> _functionWalkers
+            = new Dictionary<FunctionDefinition, AstAnalysisFunctionWalker>();
+
+        public void Add(AstAnalysisFunctionWalker walker)
+            => _functionWalkers[walker.Target] = walker;
+
+        public void ProcessSet() {
+            // Do not use foreach since walker list is dynamically
+            // modified and walkers are removed as they are done.
+            while (_functionWalkers.Count > 0) {
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs]:
```cs
var walkers = _functionWalkers.Values.ToArray();
_functionWalkers.Clear();
foreach (var walker in walkers) {
    walker.Walk();
}
```

File: src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs (hunk 6 above)
Comment (AlexanderSher) [reply src/Analysis/Engine/Impl/Interpreter/Ast/AstAnalysisFunctionWalkerSet.cs]: Ok

File: src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Interpreter/Ast/NameLookupContext.cs]: Well, it got worse. `AstPythonMultipleMembers.Combine` does not accept two null while it is actually possible. For safety reasons I will stick with unknowns for now.
