### PR TITLE
Fix #1156: Unresolved import for builtin packages after reload

### LINKED ISSUE #1156: Unresolved import for builtin packages after reload
@schlamar commented on [Mon Jun 03 2019](https://github.com/microsoft/vscode-python/issues/5881)

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 2019.5
- OS and version: Windows 7
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

No errors for builtin packages.

## Actual behaviour

Import of builtin packages like `time`, `itertools` and `operator` are sometimes marked as unresolved import.

## Steps to reproduce:

Don't know, this happens randomly.

## Logs

```
Starting Microsoft Python language server.
##########Linting Output - flake8##########
[Info  - 12:19:26] GetCurrentSearchPaths C:\Python27\python.exe 
[Info  - 12:19:26] Python search paths:
[Info  - 12:19:26]     c:\python27\dlls
[Info  - 12:19:26]     c:\python27\lib
[Info  - 12:19:26]     c:\python27\lib\lib-tk
[Info  - 12:19:26]     c:\python27
[Info  - 12:19:26]     c:\python27\lib\site-packages
[Info  - 12:19:26] Configuration search paths:
[Info  - 12:19:26]     ...
[Info  - 12:19:33] Microsoft Python Language Server version 0.2.87.0
[Info  - 12:19:33] Initializing for C:\Python27\python.exe
```   

(Right now, I don't have a Console Log in case of this error. I will submit them as soon as this happens again.)

### PR DESCRIPTION
**Pull request by AlexanderSher**

### CODE REVIEW

File: src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs [hunk 1]
```diff
@@ -92,6 +83,24 @@ public sealed class PythonInterpreter : IPythonInterpreter {
...
+            get {
+                lock (_lock) {
+                    var type = _unknownType;
+                    if (type != null) {
+                        return type;
+                    }
+
+                    _unknownType = new PythonType("Unknown", new Location(_moduleResolution.BuiltinsModule), string.Empty);
+                    _builtinTypes[BuiltinTypeId.Unknown] = _unknownType;
+                    return _unknownType;
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: `Unknown` type switched to lazy initialization

File: src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs [hunk 2]
```diff
@@ -109,31 +109,30 @@ public sealed class PythonLibraryPath : IEquatable<PythonLibraryPath> {
         /// <param name="library">Root of the standard library.</param>
         /// <returns>A list of search paths for the interpreter.</returns>
         /// <remarks>New in 2.2, moved in 3.3</remarks>
-        private static List<PythonLibraryPath> GetDefaultSearchPaths(IFileSystem fs, string library) {
-            var result = new List<PythonLibraryPath>();
+        private static ImmutableArray<PythonLibraryPath> GetDefaultSearchPaths(IFileSystem fs, string library) {
```
Comment (jakebailey) [inline src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs]: Not entirely related to this PR, but I feel like we should come up with some agreement about which list types we're going to use across the board so we don't end up switching them back and forth between PRs...

**Comment by jakebailey** [comment]
When I do the same memory testing I did for #1402, the memory usage after a big session or a reload doesn't seem to go down very much (or at all), and requires something else to happen to do another GC/compact for the memory to go down again. Maybe there's some timing problem where the new code is a bit faster and things aren't ready to be compacted yet, or something, but it might hurt memory usage. (Another case #1428 would help.)

File: src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs [hunk 3]
```diff
@@ -106,31 +115,34 @@ public sealed class PythonInterpreter : IPythonInterpreter {
...
-                    return res;
+                if (_builtinTypes.TryGetValue(id, out var type) && type != null) {
+                    return type;
                 }
 
-                var bm = ModuleResolution.BuiltinsModule;
-                var typeName = id.GetTypeName(LanguageVersion);
-                if (typeName != null) {
-                    res = bm.GetMember(typeName) as IPythonType;
+                if (id == BuiltinTypeId.Unknown) {
```
Comment (MikhailArkhipov) [inline src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: Might as well move this before dictionary check

**Comment by jakebailey** [comment]
Just an example of what I'm describing:

image

1. `pip install numpy`, reloads, memory goes up.
2. `pip install -e .` (small package, no imports), reloads and redoes everything, memory is the same.
3. `pip unintsall numpy`, memory usage goes down, but not all the way.
4. `pip uninstall mypackage`, memory usage goes down to the baseline.

There are variations where the initial install doesn't drop after its session GC/compact, and some where the reload GC/compact doesn't have any affect either.

File: src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs (hunk 2 above)
Comment (MikhailArkhipov) [reply src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs]: I am OK either way but I tend to use interfaces on public surface. Is there a benefit of `Immutable` over `IReadOnly`?

Comment (AlexanderSher) [reply src/Analysis/Core/Impl/Interpreter/PythonLibraryPath.cs]: There are 3 issues with `IReadOnlyList<T>`:
1. It is read-only, but not immutable. If an object is provided to the outer context, but owner still has a reference to the object, the is no way to synchronize it anymore. E.g.:
    ```cs
    private List<SomeType> _someList;
    public IReadOnlyList<SomeType> SomeList=> _someList;
    ```
    If any code gets reference to the list through `SomeList`, it still can be changed by the owner, concurrently to the reader.
2. Adding elements. With `ImmutableArray`, adding elements create new instance of it, but it is as cheap as adding to `List<T>`. For `IReadOnlyList<T>`, it requires to create a copy of the list.
3. Enumerator. For any interface, enumerator is an object. For `ImmutableArray<T>` and `List<T>` it would be a struct. This becomes a problem when we have `foreach` loops in analysis where enumerators are promoted to Gen2.

**Comment by jakebailey** [comment]
Here's what happens when I repeat the above but modify the ForceGC function to wait a bit:

image

```csharp
private static void ForceGCIfNeeded(ILogger logger, int originalRemaining, int remaining, bool force) {
	if (force || originalRemaining - remaining > 1000) {
		Task.Run(async () => {
			await Task.Delay(500);
			logger?.Log(TraceEventType.Verbose, "Forcing full garbage collection and heap compaction.");
			GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
			GC.Collect();
		}).DoNotWait();
	}
}
```
