### PR TITLE
Fix References_GrammarTest_Statements

### LINKED ISSUE #40: References_GrammarTest_Statements test fails
Contains unexpected reference `abc.py, (0, 0) - (0, 0), Definition`

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #40 

Code is pretty confusing, with reassignments and import names same as variable names. Various apps behave differently. Basically the fix is

- Keep any reference to external files as definition (so use can navigate there)
- Keep `import abc` as reference (so use can find all usages of 'abc').

### CODE REVIEW

File: src/Analysis/Engine/Test/AnalysisTest.cs [hunk 1]
```diff
@@ -2992,12 +2991,19 @@ print abc
                 await server.SendDidOpenTextDocument(uri, text);
 
                 var references = await server.SendFindReferences(uri, 3, 12);
+
+                // External module 'abc', URI varies depending on install
+                var externalUri = references[1].uri;
+                externalUri.LocalPath.Should().Contain("abc.py");
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Test/AnalysisTest.cs]: `Contain` or `EndsWith`?

File: src/Analysis/Engine/Impl/ModuleAnalysis.cs [hunk 2]
```diff
@@ -294,15 +294,23 @@ private class VariableScopePair : Tuple<IAnalysisVariable, int> {
...
                 var defsToRefs = definitions
+                    .Except(imports)
                     .Where(d => d != mainDefinition && d.ScopeLevel <= mainDefinition.ScopeLevel)
                     .Select(v => new VariableScopePair(new AnalysisVariable(v.Variable.Variable, VariableType.Reference, v.Location), v.ScopeLevel));
 
                 var others = variables
                             .Where(v => (v.VariableType == VariableType.Reference || v.VariableType == VariableType.Value) &&
                                          v.ScopeLevel <= mainDefinition.ScopeLevel);
-                variables = new[] { mainDefinition }.Concat(others.Concat(defsToRefs));
+                variables = new[] { mainDefinition }.Concat(imports).Concat(others.Concat(defsToRefs));
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/ModuleAnalysis.cs]: Is it just rearrangement, or some of the variables will be excluded?

File: src/Analysis/Engine/Test/AnalysisTest.cs (hunk 1 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Test/AnalysisTest.cs]: EndsWith

File: src/Analysis/Engine/Impl/ModuleAnalysis.cs (hunk 2 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/ModuleAnalysis.cs]: No exclusion, just keeping imports as definitions. Before they were converted to references since they were below in the same scope such as
```python
abc = 1
import abc
```
