### PR TITLE
Fix addBrackets setting

### LINKED ISSUE #868: python.autoComplete.addBrackets does not work
Using Microsoft Python Language Server version 0.2.41.0, the setting `python.autoComplete.addBrackets` does not add parentheses for functions such as "print" and "input". Switching back to jedi fixes the issue.

See MicrosoftDocs/intellicode#80 for more details.

### LINKED ISSUE #990: when set "python.autoComplete.addBrackets": true, in the auto-completed brackets, the IntelliSense didn't work
@Loovelj commented on [Mon Dec 10 2018](https://github.com/Microsoft/vscode-python/issues/3610)

## Environment data

- VS Code version: 1.29
- Extension version (available under the Extensions sidebar): 2018.11.0
- OS and version: win10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX 
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour

so I want it like pycharm ,like
pycharm

## Actual behaviour
1.
when I "pri"+Tab,  it's addBrackets
then I want print the day,  
 the 'day'  likes a string, the IntelliSense  didn't work ,

---

@d3r3kk commented on [Tue Jan 15 2019](https://github.com/Microsoft/vscode-python/issues/3610#issuecomment-454590813)

I can repro this with `"python.jediEnabled": true` in my `settings.json` file. However, when I enable the Microsoft Python Language Server, the issue is resolved. 

Workaround: Enable the Microsoft Python Language Server by setting `"python.jediEnabled": false` in your `settings.json` file. (See #3977 to find out how to get the latest stable version).

---

@Loovelj commented on [Fri Mar 29 2019](https://github.com/Microsoft/vscode-python/issues/3610#issuecomment-477896279)

> I can repro this with `"python.jediEnabled": true` in my `settings.json` file. However, when I enable the Microsoft Python Language Server, the issue is resolved.
> 
> Workaround: Enable the Microsoft Python Language Server by setting `"python.jediEnabled": false` in your `settings.json` file. (See #3977 to find out how to get the latest stable version).

thanks, I tried set "python.jediEnabled": false, but the auto-completed brackets didn't work now, now the version is 1.33

---

@scottlovejoy3687 commented on [Fri Mar 29 2019](https://github.com/Microsoft/vscode-python/issues/3610#issuecomment-478190487)

> > I can repro this with `"python.jediEnabled": true` in my `settings.json` file. However, when I enable the Microsoft Python Language Server, the issue is resolved.
> > Workaround: Enable the Microsoft Python Language Server by setting `"python.jediEnabled": false` in your `settings.json` file. (See #3977 to find out how to get the latest stable version).
> 
> thanks, I tried set "python.jediEnabled": false, but the auto-completed brackets didn't work now, now the version is 1.33

I also get the issue with the auto-completed brackets when I disable Jedi.

---

@hackershi commented on [Thu Apr 11 2019](https://github.com/Microsoft/vscode-python/issues/3610#issuecomment-482019448)

The problem still remains

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #990 
Fixes #868

### CODE REVIEW

File: src/LanguageServer/Impl/Implementation/Server.cs [hunk 1]
```diff
@@ -209,6 +209,7 @@ public sealed partial class Server : IDisposable {
             Settings = newSettings;
 
             _symbolHierarchyMaxSymbols = Settings.analysis.symbolsHierarchyMaxSymbols;
+            _completionSource.Options = Settings.completion;
```
Comment (AlexanderSher) [inline src/LanguageServer/Impl/Implementation/Server.cs]: `PythonCompletionOptions` is a class. Do we need to check `Settings.completion` for `null` here?

File: src/LanguageServer/Test/CompletionTests.cs [hunk 2]
```diff
@@ -32,6 +32,7 @@
 using Microsoft.Python.Parsing;
 using Microsoft.Python.Parsing.Tests;
 using Microsoft.VisualStudio.TestTools.UnitTesting;
+using NSubstitute;
```
Comment (AlexanderSher) [inline src/LanguageServer/Test/CompletionTests.cs]: Do you use it here?

File: src/LanguageServer/Impl/Implementation/Server.cs (hunk 1 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.cs]: It is poopulated in 
```cs
        [JsonRpcMethod("workspace/didChangeConfiguration")]
        public async Task DidChangeConfiguration(JToken token, CancellationToken cancellationToken) {
            using (await _prioritizer.ConfigurationPriorityAsync(cancellationToken)) {
                var settings = new LanguageServerSettings();

                var rootSection = token["settings"];
                var pythonSection = rootSection?["python"];
                if (pythonSection == null) {
                    return;
                }

                var autoComplete = pythonSection["autoComplete"];
                settings.completion.showAdvancedMembers = GetSetting(autoComplete, "showAdvancedMembers", true);
                settings.completion.addBrackets = GetSetting(autoComplete, "addBrackets", false);
```
and `GetSetting` handles nulls/missing settings.
