### PR TITLE
Do not double-walk try and while statement bodies

### LINKED ISSUE #1775: unresolved-import being reported twice for the same line
## Environment data

- Language Server version: 0.4.102.0   
- OS and version: macOS Mojave
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.7.5
- VS Code 1.40.0

## Expected behaviour

To have an unresolved import reported only once (and not at all within a `try`/`except ImportError` block, but that's #1663 ).

## Actual behaviour

Failing import reported twice.

## Logs

<details><summary>Lots of log output</summary>

```
[Info  - 11:16:59 AM] Analysis cache path: /Users/brettcannon/Library/Caches/Microsoft/Python Language Server
[Info  - 11:16:59 AM] Microsoft Python Language Server version 0.4.102.0
[Info  - 11:16:59 AM] Workspace root: /Users/brettcannon/Repositories/pypa/packaging
[Info  - 11:16:59 AM] GetCurrentSearchPaths /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
[Info  - 11:16:59 AM] Interpreter search paths:
[Info  - 11:16:59 AM]     /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 11:16:59 AM]     /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 11:16:59 AM]     /Users/brettcannon/Repositories/pypa/packaging/.venv/lib/python3.7/site-packages
[Info  - 11:16:59 AM] User search paths:
[Info  - 11:17:01 AM] Initializing for /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7
Watching /Users/brettcannon/Repositories/pypa/packaging/.venv/lib/python3.7/site-packages
Watching /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7
Watching /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 11:17:02 AM] Analysis caching mode: None.
Opening document file:///Users/brettcannon/Repositories/pypa/packaging/packaging/tags.py
Code Action in file:///Users/brettcannon/Repositories/pypa/packaging/packaging/tags.py at (325, 25) - (325, 25)
Analysis of packaging.tags (User) queued. Dependencies: __future__, distutils, distutils.util, importlib.machinery, imp, logging, os, platform, re, sys, sysconfig, warnings, packaging._typing, ctypes
Import:  __future__ /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__future__.py 
Import:  distutils /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/__init__.py 
Import:  distutils.util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/util.py 
Import:  importlib.machinery /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/machinery.py 
Import:  imp /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py 
Import:  logging /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py 
Import:  os /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py 
Import:  platform /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/platform.py 
Import:  re /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py 
Create built-in compiled (scraped) module:  sys /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  sysconfig /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sysconfig.py 
Import:  warnings /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/warnings.py 
Import:  packaging._typing /Users/brettcannon/Repositories/pypa/packaging/packaging/_typing.py 
Import:  ctypes /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py 
Analysis version 2 of 1 entries has started.
Analysis of packaging.tags (User) on depth 0 completed in 38.7 ms.
Missing keys: __future__(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__future__.py), distutils(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/__init__.py), distutils.util(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/util.py), importlib.machinery(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/machinery.py), imp(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py), logging(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py), os(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py), platform(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/platform.py), re(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py), sys(), sysconfig(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sysconfig.py), warnings(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/warnings.py), packaging._typing(/Users/brettcannon/Repositories/pypa/packaging/packaging/_typing.py), ctypes(/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py)
Analysis version 2 of 1 entries has been completed in 41.42 ms.
Analysis of ctypes (Library) queued. Dependencies: ctypes (stub), os, sys, _ctypes, struct, ctypes._endian
Create compiled (scraped):  _ctypes /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Import:  struct /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/struct.py 
Import:  ctypes._endian /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/_endian.py 
Analysis version 17 of 15 entries has started.
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of imp(Library) canceled (no AST yet).
Analysis of logging(Library) canceled (no AST yet).
Analysis of os(Library) canceled (no AST yet).
Analysis of platform(Library) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of ctypes (Library) on depth 1 completed in 48.6 ms.
Analysis of distutils.util(Library) canceled (no AST yet).
Analysis of distutils(Library) canceled (no AST yet).
Analysis of __future__(Library) canceled (no AST yet).
Analysis version 17 has been completed in 51.93 ms with 14 entries analyzed and 1 entries skipped.
Analysis of ctypes._endian (Library) queued. Dependencies: sys, ctypes
Analysis version 21 of 18 entries has started.
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of imp(Library) canceled (no AST yet).
Analysis of logging(Library) canceled (no AST yet).
Analysis of os(Library) canceled (no AST yet).
Analysis of platform(Library) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of struct(Library) canceled (no AST yet).
Analysis of modules loop on depth 1 in 105.19 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of distutils.util(Library) canceled (no AST yet).
Analysis of distutils(Library) canceled (no AST yet).
Analysis of __future__(Library) canceled (no AST yet).
Analysis version 21 has been completed in 112.36 ms with 17 entries analyzed and 1 entries skipped.
Analysis of struct (Library) queued. Dependencies: struct (stub), _struct
Create compiled (scraped):  _struct /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis version 22 of 18 entries has started.
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of imp(Library) canceled (no AST yet).
Analysis of logging(Library) canceled (no AST yet).
Analysis of os(Library) canceled (no AST yet).
Analysis of platform(Library) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of struct (Library) on depth 2 completed in 0.54 ms.
Analysis of modules loop on depth 1 in 27 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of distutils.util(Library) canceled (no AST yet).
Analysis of distutils(Library) canceled (no AST yet).
Analysis of __future__(Library) canceled (no AST yet).
Analysis version 22 has been completed in 27.88 ms with 17 entries analyzed and 1 entries skipped.
Analysis of _struct (Compiled) queued. Dependencies: struct
Analysis version 24 of 19 entries has started.
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of imp(Library) canceled (no AST yet).
Analysis of logging(Library) canceled (no AST yet).
Analysis of os(Library) canceled (no AST yet).
Analysis of platform(Library) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of modules loop on depth 2 in 1.22 ms:
    struct(Library)
    _struct(Compiled)
Analysis of modules loop on depth 1 in 34.73 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of distutils.util(Library) canceled (no AST yet).
Analysis of distutils(Library) canceled (no AST yet).
Analysis of __future__(Library) canceled (no AST yet).
Analysis version 24 has been completed in 36.61 ms with 18 entries analyzed and 1 entries skipped.
Analysis of struct (Stub) queued. Dependencies: sys (stub), array (stub)
Analysis version 25 of 20 entries has started.
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of imp(Library) canceled (no AST yet).
Analysis of logging(Library) canceled (no AST yet).
Analysis of os(Library) canceled (no AST yet).
Analysis of platform(Library) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of struct (Stub) on depth 3 completed in 1.67 ms.
Analysis of modules loop on depth 2 in 1.32 ms:
    struct(Library)
    _struct(Compiled)
Analysis of modules loop on depth 1 in 31.65 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of distutils.util(Library) canceled (no AST yet).
Analysis of distutils(Library) canceled (no AST yet).
Analysis of __future__(Library) canceled (no AST yet).
Analysis of __future__ (Stub) queued. Dependencies: sys (stub)
Analysis of distutils (Stub) queued. Dependencies: 
Analysis of __future__ (Library) queued. Dependencies: __future__ (stub)
Analysis of distutils (Library) queued. Dependencies: distutils (stub), sys
Analysis of distutils.util (Stub) queued. Dependencies: 
Analysis of importlib.machinery (Library) queued. Dependencies: importlib.machinery (stub), _imp, importlib._bootstrap, importlib._bootstrap_external
Create built-in compiled (scraped) module:  _imp /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of importlib.machinery (Stub) queued. Dependencies: importlib (stub), importlib.abc (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Import:  importlib._bootstrap /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py 
Analysis of _imp (Stub) queued. Dependencies: sys (stub), types (stub), importlib.machinery (stub)
Analysis of _imp (CompiledBuiltin) queued. Dependencies: _imp (stub)
Import:  importlib._bootstrap_external /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap_external.py 
Analysis of distutils.util (Library) queued. Dependencies: distutils.util (stub), os, re, importlib, importlib.util, string, sys, distutils.errors, distutils.dep_util, distutils.spawn, distutils, distutils.log, _osx_support, distutils.sysconfig, pwd, subprocess, tempfile, py_compile, lib2to3.refactor, distutils.dir_util, distutils.file_util, distutils.filelist
Analysis of _importlib_modulespec (Stub) queued. Dependencies: abc (stub), sys (stub)
Import:  importlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py 
Analysis version 25 has been completed in 41.98 ms with 19 entries analyzed and 1 entries skipped.
Import:  importlib.util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/util.py 
Analysis version 31 of 23 entries has started.
Analysis of logging(Library) canceled (no AST yet).
Analysis of os(Library) canceled (no AST yet).
Analysis of platform(Library) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of array(Stub) canceled (no AST yet).
Import:  string /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py 
Import:  distutils.errors /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/errors.py 
Import:  distutils.dep_util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dep_util.py 
Analysis of __future__ (Stub) on depth 2 completed in 3.53 ms.
Analysis of distutils (Stub) on depth 2 completed in 0.05 ms.
Analysis of importlib._bootstrap (Library) queued. Dependencies: 
Import:  distutils.spawn /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py 
Analysis of importlib (Stub) queued. Dependencies: importlib.util (stub), importlib.abc (stub), sys (stub), types (stub)
Import:  distutils.log /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/log.py 
Import:  _osx_support /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py 
Analysis of importlib.abc (Stub) queued. Dependencies: abc (stub), os (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Import:  distutils.sysconfig /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/sysconfig.py 
Analysis of importlib._bootstrap_external (Library) queued. Dependencies: tokenize
Create built-in compiled (scraped) module:  pwd /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  subprocess /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py 
Import:  tempfile /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tempfile.py 
Import:  py_compile /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/py_compile.py 
Import:  lib2to3.refactor /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/refactor.py 
Import:  distutils.dir_util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dir_util.py 
Import:  distutils.file_util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/file_util.py 
Import:  distutils.filelist /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/filelist.py 
Analysis of abc (Stub) queued. Dependencies: 
Analysis of imp (Stub) queued. Dependencies: os (stub), sys (stub), types (stub), _imp (stub)
Import:  tokenize /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py 
Analysis of types (Stub) queued. Dependencies: sys (stub), _importlib_modulespec (stub)
Analysis of importlib.util (Stub) queued. Dependencies: importlib (stub), importlib.abc (stub), importlib.machinery (stub), sys (stub), types (stub)
Analysis of imp (Library) queued. Dependencies: imp (stub), _imp, importlib._bootstrap, importlib._bootstrap_external, importlib, importlib.machinery, importlib.util, os, sys, tokenize, types, warnings
Analysis of importlib (Library) queued. Dependencies: importlib (stub), _imp, sys, importlib._bootstrap, importlib._bootstrap_external, types, warnings
Import:  types /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/types.py 
Analysis of types (Library) queued. Dependencies: types (stub), sys, functools, _collections_abc
Import:  functools /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/functools.py 
Import:  _collections_abc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_collections_abc.py 
Analysis of _collections_abc (Library) queued. Dependencies: abc, sys
Analysis of logging (Library) queued. Dependencies: logging (stub), sys, os, time, io, traceback, warnings, weakref, collections, collections.abc, string, threading, pickle, atexit
Create built-in compiled (scraped) module:  time /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  io /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/io.py 
Import:  traceback /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py 
Import:  weakref /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/weakref.py 
Analysis of platform (Stub) queued. Dependencies: os (stub)
Analysis of importlib.util (Library) queued. Dependencies: importlib.util (stub), importlib, importlib.abc, importlib._bootstrap, importlib._bootstrap_external, contextlib, _imp, functools, sys, types, warnings
Analysis of os (Stub) queued. Dependencies: io (stub), sys (stub), posix (stub), os.path (stub)
Analysis of logging (Stub) queued. Dependencies: string (stub), time (stub), types (stub), sys (stub), threading (stub)
Import:  collections /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py 
Analysis of tokenize (Library) queued. Dependencies: tokenize (stub), codecs, collections, io, itertools, re, sys, token, argparse
Import:  collections.abc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/abc.py 
Analysis of os (Library) queued. Dependencies: os (stub), abc, sys, stat, posix, posixpath, ntpath, warnings, _collections_abc, subprocess, io
Import:  threading /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py 
Analysis of tokenize (Stub) queued. Dependencies: sys (stub), token (stub), os (stub)
Import:  pickle /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py 
Analysis of __future__ (Library) on depth 1 completed in 129.86 ms.
Analysis of distutils (Library) on depth 1 completed in 0.22 ms.
Create built-in compiled (scraped) module:  atexit /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  abc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/abc.py 
Import:  importlib.abc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/abc.py 
Analysis of modules loop on depth 2 in 2.49 ms:
    struct(Library)
    _struct(Compiled)
Analysis of string (Stub) queued. Dependencies: 
Import:  contextlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py 
Analysis of pickle (Stub) queued. Dependencies: sys (stub)
Analysis of functools (Stub) queued. Dependencies: sys (stub)
Analysis of os.path (Stub) queued. Dependencies: posix (stub), sys (stub)
Import:  codecs /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py 
Analysis of contextlib (Library) queued. Dependencies: contextlib (stub), abc, sys, _collections_abc, collections, functools
Analysis of threading (Library) queued. Dependencies: threading (stub), os, sys, _thread, time, traceback, _weakrefset, itertools, _collections, collections, warnings, _threading_local
Create built-in compiled (scraped) module:  itertools /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  token /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/token.py 
Import:  argparse /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py 
Import:  stat /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/stat.py 
Create built-in compiled (scraped) module:  posix /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  posixpath /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py 
Import:  ntpath /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ntpath.py 
Analysis of posix (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  _thread /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of _thread (Stub) queued. Dependencies: 
Import:  _weakrefset /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_weakrefset.py 
Create built-in compiled (scraped) module:  _collections /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of string (Library) queued. Dependencies: string (stub), _string, re, collections
Analysis of contextlib (Stub) queued. Dependencies: types (stub), sys (stub)
Import:  _threading_local /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_threading_local.py 
Analysis of distutils.filelist (Library) queued. Dependencies: distutils.filelist (stub), os, re, fnmatch, functools, distutils.util, distutils.errors, distutils, distutils.log, distutils.debug
Analysis of ntpath (Library) queued. Dependencies: ntpath (stub), os, sys, stat, genericpath, string
Analysis of distutils.filelist (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  _string /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of ntpath (Stub) queued. Dependencies: sys (stub)
Analysis of _threading_local (Library) queued. Dependencies: _threading_local (stub), weakref, contextlib, threading
Analysis of _threading_local (Stub) queued. Dependencies: weakref (stub)
Import:  fnmatch /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/fnmatch.py 
Analysis of _thread (CompiledBuiltin) queued. Dependencies: _thread (stub)
Analysis of importlib.abc (Library) queued. Dependencies: importlib.abc (stub), importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, abc, warnings
Import:  distutils.debug /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/debug.py 
Analysis of threading (Stub) queued. Dependencies: types (stub), sys (stub)
Import:  genericpath /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py 
Analysis of collections.abc (Library) queued. Dependencies: collections.abc (stub), _collections_abc
Analysis of genericpath (Library) queued. Dependencies: os, stat
Analysis of pickle (Library) queued. Dependencies: pickle (stub), types, copyreg, itertools, functools, sys, struct, re, io, codecs, _compat_pickle, _pickle, doctest, argparse, pprint
Analysis of distutils.debug (Library) queued. Dependencies: distutils.debug (stub), os
Import:  copyreg /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copyreg.py 
Analysis of collections.abc (Stub) queued. Dependencies: sys (stub), collections (stub)
Analysis of _collections (CompiledBuiltin) queued. Dependencies: collections
Import:  _compat_pickle /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_compat_pickle.py 
Create compiled (scraped):  _pickle /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of functools (Library) queued. Dependencies: functools (stub), _functools, abc, collections, reprlib, _thread, types, weakref
Analysis of _weakrefset (Library) queued. Dependencies: _weakrefset (stub), _weakref
Import:  doctest /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/doctest.py 
Analysis of fnmatch (Library) queued. Dependencies: fnmatch (stub), os, posixpath, re, functools
Analysis of abc (Library) queued. Dependencies: abc (stub), _abc, _py_abc
Analysis of distutils.errors (Stub) queued. Dependencies: 
Analysis of codecs (Stub) queued. Dependencies: sys (stub), abc (stub), types (stub)
Analysis of collections (Library) queued. Dependencies: collections (stub), _collections_abc, operator, keyword, sys, heapq, _weakref, itertools, reprlib, _collections, warnings, copy
Import:  pprint /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pprint.py 
Create built-in compiled (scraped) module:  _functools /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  reprlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/reprlib.py 
Create built-in compiled (scraped) module:  _weakref /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Create built-in compiled (scraped) module:  _abc /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  _py_abc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_py_abc.py 
Analysis of fnmatch (Stub) queued. Dependencies: 
Analysis of reprlib (Library) queued. Dependencies: reprlib (stub), itertools, _thread
Analysis of _string (CompiledBuiltin) queued. Dependencies: 
Import:  operator /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/operator.py 
Analysis of _functools (CompiledBuiltin) queued. Dependencies: functools
Analysis of reprlib (Stub) queued. Dependencies: array (stub)
Analysis of pprint (Library) queued. Dependencies: pprint (stub), collections, re, sys, types, io, time
Analysis of time (Stub) queued. Dependencies: sys (stub), types (stub)
Import:  keyword /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/keyword.py 
Analysis of _py_abc (Library) queued. Dependencies: _weakrefset
Analysis of time (CompiledBuiltin) queued. Dependencies: time (stub)
Analysis of _abc (CompiledBuiltin) queued. Dependencies: 
Import:  heapq /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/heapq.py 
Analysis of io (Library) queued. Dependencies: io (stub), _io, abc
Analysis of _weakref (CompiledBuiltin) queued. Dependencies: _weakref (stub)
Analysis of _weakref (Stub) queued. Dependencies: sys (stub)
Import:  copy /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py 
Analysis of _weakrefset (Stub) queued. Dependencies: 
Analysis of io (Stub) queued. Dependencies: codecs (stub), mmap (stub), sys (stub), types (stub)
Create built-in compiled (scraped) module:  _io /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of pprint (Stub) queued. Dependencies: sys (stub)
Analysis of copy (Library) queued. Dependencies: copy (stub), types, weakref, copyreg
Analysis of traceback (Stub) queued. Dependencies: types (stub), sys (stub)
Analysis of copy (Stub) queued. Dependencies: 
Analysis of atexit (Stub) queued. Dependencies: 
Analysis of distutils.errors (Library) queued. Dependencies: distutils.errors (stub)
Analysis of atexit (CompiledBuiltin) queued. Dependencies: atexit (stub)
Analysis of heapq (Library) queued. Dependencies: heapq (stub), _heapq, doctest
Analysis of mmap (Stub) queued. Dependencies: sys (stub)
Create compiled (scraped):  _heapq /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of weakref (Stub) queued. Dependencies: sys (stub), types (stub), _weakref (stub), _weakrefset (stub)
Analysis of _heapq (Compiled) queued. Dependencies: _heapq (stub)
Analysis of codecs (Library) queued. Dependencies: codecs (stub), sys, _codecs, encodings
Analysis of traceback (Library) queued. Dependencies: traceback (stub), collections, itertools, linecache, sys
Analysis of _io (CompiledBuiltin) queued. Dependencies: io
Create built-in compiled (scraped) module:  _codecs /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Import:  encodings /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__init__.py 
Import:  linecache /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py 
Analysis of doctest (Library) queued. Dependencies: doctest (stub), __future__, difflib, inspect, linecache, os, pdb, re, sys, traceback, unittest, io, collections, argparse
Import:  difflib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/difflib.py 
Import:  inspect /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py 
Import:  pdb /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py 
Import:  unittest /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/__init__.py 
Analysis of modules loop on depth 1 in 206.64 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of imp (Library) queued. Dependencies: imp (stub), _imp, importlib._bootstrap, importlib._bootstrap_external, importlib, importlib.machinery, importlib.util, os, sys, tokenize, types, warnings, io
Analysis of imp (Library) on depth 1 completed in 15.49 ms.
Analysis of importlib.machinery (Library) on depth 1 completed in 0.37 ms.
Analysis of distutils.util (Library) queued. Dependencies: distutils.util (stub), os, re, importlib, importlib.util, string, sys, distutils.errors, distutils.dep_util, distutils.spawn, distutils, distutils.log, _osx_support, distutils.sysconfig, pwd, subprocess, tempfile, py_compile, lib2to3.refactor, distutils.dir_util, distutils.file_util, distutils.filelist, io
Analysis of distutils.util (Library) on depth 1 completed in 13.4 ms.
Analysis version 31 has been completed in 372.86 ms with 21 entries analyzed and 2 entries skipped.
Analysis version 204 of 137 entries has started.
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of array(Stub) canceled (no AST yet).
Analysis of distutils.util (Stub) on depth 2 completed in 0.82 ms.
Analysis of importlib._bootstrap (Library) on depth 2 completed in 18.48 ms.
Analysis of distutils.dep_util(Library) canceled (no AST yet).
Analysis of distutils.spawn(Library) canceled (no AST yet).
Analysis of distutils.log(Library) canceled (no AST yet).
Analysis of _osx_support(Library) canceled (no AST yet).
Analysis of distutils.sysconfig(Library) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of subprocess(Library) canceled (no AST yet).
Analysis of tempfile(Library) canceled (no AST yet).
Analysis of py_compile(Library) canceled (no AST yet).
Analysis of lib2to3.refactor(Library) canceled (no AST yet).
Analysis of distutils.dir_util(Library) canceled (no AST yet).
Analysis of distutils.file_util(Library) canceled (no AST yet).
Analysis of abc (Stub) on depth 3 completed in 7.28 ms.
Analysis of weakref(Library) canceled (no AST yet).
Analysis of posix (Stub) on depth 3 completed in 3.53 ms.
Analysis of string (Stub) on depth 3 completed in 7.79 ms.
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of token(Library) canceled (no AST yet).
Analysis of argparse(Library) canceled (no AST yet).
Analysis of stat(Library) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of posixpath(Library) canceled (no AST yet).
Analysis of pickle (Stub) on depth 3 completed in 3.68 ms.
Analysis of functools (Stub) on depth 4 completed in 49.51 ms.
Analysis of _thread (Stub) on depth 4 completed in 0.39 ms.
Analysis of _string (CompiledBuiltin) on depth 3 completed in 0.32 ms.
Analysis of distutils.filelist (Stub) on depth 3 completed in 0.13 ms.
Analysis of ntpath (Stub) on depth 3 completed in 1.54 ms.
Analysis of collections.abc (Stub) on depth 3 completed in 0.31 ms.
Analysis of copyreg(Library) canceled (no AST yet).
Analysis of _compat_pickle(Library) canceled (no AST yet).
Analysis of _pickle(Compiled) canceled (no AST yet).
Analysis of _weakrefset (Stub) on depth 4 completed in 6.39 ms.
Analysis of fnmatch (Stub) on depth 4 completed in 0.26 ms.
Analysis of _abc (CompiledBuiltin) on depth 3 completed in 5.32 ms.
Analysis of distutils.errors (Stub) on depth 3 completed in 1.89 ms.
Analysis of operator(Library) canceled (no AST yet).
Analysis of keyword(Library) canceled (no AST yet).
Analysis of pprint (Stub) on depth 4 completed in 0.62 ms.
Analysis of _weakref (Stub) on depth 4 completed in 0.8 ms.
Analysis of mmap (Stub) on depth 4 completed in 4.23 ms.
Analysis of copy (Stub) on depth 4 completed in 0.33 ms.
Analysis of atexit (Stub) on depth 3 completed in 0.2 ms.
Analysis of _heapq (Compiled) on depth 4 completed in 0.19 ms.
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of encodings(Library) canceled (no AST yet).
Analysis of linecache(Library) canceled (no AST yet).
Analysis of difflib(Library) canceled (no AST yet).
Analysis of inspect(Library) canceled (no AST yet).
Analysis of pdb(Library) canceled (no AST yet).
Analysis of unittest(Library) canceled (no AST yet).
Analysis of reprlib (Stub) on depth 4 completed in 0.69 ms.
Analysis of _importlib_modulespec (Stub) on depth 3 completed in 1.3 ms.
Analysis of os.path (Stub) on depth 3 completed in 1.84 ms.
Analysis of _thread (CompiledBuiltin) on depth 3 completed in 1.01 ms.
Analysis of distutils.errors (Library) on depth 2 completed in 36.64 ms.
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 0.31 ms.
Analysis of atexit (CompiledBuiltin) on depth 2 completed in 0.15 ms.
Analysis of modules loop on depth 2 in 1.17 ms:
    struct(Library)
    _struct(Compiled)
Analysis of types (Stub) on depth 3 completed in 8.02 ms.
Analysis of reprlib (Library) on depth 3 completed in 8.3 ms.
Analysis of _weakrefset (Library) on depth 3 completed in 1.81 ms.
Analysis of time (Stub) on depth 3 completed in 2.25 ms.
Analysis of threading (Stub) on depth 3 completed in 7.3 ms.
Analysis of contextlib (Stub) on depth 4 completed in 4.2 ms.
Analysis of weakref (Stub) on depth 5 completed in 3.74 ms.
Analysis of codecs (Stub) on depth 4 completed in 4.85 ms.
Analysis of traceback (Stub) on depth 3 completed in 2.17 ms.
Analysis of _py_abc (Library) on depth 3 completed in 4.31 ms.
Analysis of time (CompiledBuiltin) on depth 2 completed in 11.32 ms.
Analysis of logging (Stub) on depth 2 completed in 13.52 ms.
Analysis of _threading_local (Stub) on depth 4 completed in 0.48 ms.
Analysis of io (Stub) on depth 3 completed in 10.59 ms.
Analysis of abc (Library) on depth 2 completed in 2.91 ms.
Analysis of os (Stub) on depth 2 completed in 31.64 ms.
Analysis of modules loop on depth 2 in 49.79 ms:
    io(Library)
    _io(CompiledBuiltin)
Analysis of importlib.abc (Stub) on depth 3 completed in 4.64 ms.
Analysis of tokenize (Stub) on depth 3 completed in 1.3 ms.
Analysis of modules loop on depth 2 in 9.23 ms:
    importlib.machinery(Stub)
    importlib(Stub)
    importlib.util(Stub)
Analysis of _imp (Stub) on depth 3 completed in 0.47 ms.
Analysis of _imp (CompiledBuiltin) on depth 2 completed in 0.26 ms.
Analysis of imp (Stub) on depth 2 completed in 0.95 ms.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of codecs (Library) on depth 3 completed in 13.45 ms.
Analysis of _collections_abc (Library) on depth 2 completed in 29.02 ms.
Analysis of collections.abc (Library) on depth 2 completed in 0.21 ms.
Analysis of re(Library) canceled (no AST yet).
Analysis of modules loop on depth 1 in 305.31 ms:
    os(Library)
    string(Library)
    types(Library)
    functools(Library)
    traceback(Library)
    collections(Library)
    ntpath(Library)
    _collections(CompiledBuiltin)
    genericpath(Library)
    doctest(Library)
    _functools(CompiledBuiltin)
    heapq(Library)
    copy(Library)
Analysis of fnmatch (Library) on depth 3 completed in 0.77 ms.
Analysis of tokenize (Library) on depth 2 completed in 26.17 ms.
Analysis of contextlib (Library) on depth 3 completed in 12.89 ms.
Analysis of pprint (Library) on depth 3 completed in 13.02 ms.
Analysis of importlib._bootstrap_external (Library) on depth 2 completed in 40.07 ms.
Analysis of modules loop on depth 2 in 18.06 ms:
    threading(Library)
    _threading_local(Library)
Analysis of pickle (Library) on depth 2 completed in 71.28 ms.
Analysis of importlib (Library) on depth 2 completed in 0.9 ms.
Analysis of logging (Library) on depth 1 completed in 30.21 ms.
Analysis of importlib.abc (Library) on depth 3 completed in 11.63 ms.
Analysis of importlib.util (Library) on depth 2 completed in 2.9 ms.
Analysis of modules loop on depth 1 in 32.6 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of distutils.debug (Library) on depth 3 completed in 0.58 ms.
Analysis of modules loop on depth 1 in 7.69 ms:
    distutils.util(Library)
    distutils.filelist(Library)
Analysis of platform(Library) canceled (no AST yet).
Analysis version 204 has been completed in 969.65 ms with 129 entries analyzed and 8 entries skipped.
Analysis of array (Stub) queued. Dependencies: sys (stub)
Analysis version 205 of 137 entries has started.
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of array (Stub) on depth 4 completed in 13.03 ms.
Analysis of distutils.dep_util(Library) canceled (no AST yet).
Analysis of distutils.spawn(Library) canceled (no AST yet).
Analysis of distutils.log(Library) canceled (no AST yet).
Analysis of _osx_support(Library) canceled (no AST yet).
Analysis of distutils.sysconfig(Library) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of subprocess(Library) canceled (no AST yet).
Analysis of tempfile(Library) canceled (no AST yet).
Analysis of py_compile(Library) canceled (no AST yet).
Analysis of lib2to3.refactor(Library) canceled (no AST yet).
Analysis of distutils.dir_util(Library) canceled (no AST yet).
Analysis of distutils.file_util(Library) canceled (no AST yet).
Analysis of weakref(Library) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of token(Library) canceled (no AST yet).
Analysis of argparse(Library) canceled (no AST yet).
Analysis of stat(Library) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of posixpath(Library) canceled (no AST yet).
Analysis of copyreg(Library) canceled (no AST yet).
Analysis of _compat_pickle(Library) canceled (no AST yet).
Analysis of _pickle(Compiled) canceled (no AST yet).
Analysis of operator(Library) canceled (no AST yet).
Analysis of keyword(Library) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of encodings(Library) canceled (no AST yet).
Analysis of linecache(Library) canceled (no AST yet).
Analysis of difflib(Library) canceled (no AST yet).
Analysis of inspect(Library) canceled (no AST yet).
Analysis of pdb(Library) canceled (no AST yet).
Analysis of unittest(Library) canceled (no AST yet).
Analysis of modules loop on depth 2 in 1.12 ms:
    struct(Library)
    _struct(Compiled)
Analysis of modules loop on depth 2 in 56.94 ms:
    io(Library)
    _io(CompiledBuiltin)
Analysis of modules loop on depth 2 in 4.69 ms:
    importlib.machinery(Stub)
    importlib(Stub)
    importlib.util(Stub)
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of re(Library) canceled (no AST yet).
Analysis of unittest (Library) queued. Dependencies: unittest (stub), unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, os
Analysis of distutils.dep_util (Stub) queued. Dependencies: 
Analysis of linecache (Library) queued. Dependencies: linecache (stub), functools, sys, os, tokenize
Import:  unittest.result /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/result.py 
Analysis of itertools (Stub) queued. Dependencies: 
Import:  unittest.case /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py 
Analysis of linecache (Stub) queued. Dependencies: sys (stub)
Analysis of encodings (Library) queued. Dependencies: encodings (stub), codecs, sys, encodings.aliases, encodings.mbcs
Analysis of _heapq (Stub) queued. Dependencies: 
Analysis of encodings (Stub) queued. Dependencies: codecs (stub)
Analysis of heapq (Stub) queued. Dependencies: sys (stub)
Analysis of weakref (Library) queued. Dependencies: weakref (stub), _weakref, _weakrefset, _collections_abc, sys, itertools, copy, atexit, gc
Analysis of keyword (Library) queued. Dependencies: keyword (stub), sys, re
Import:  unittest.suite /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py 
Import:  unittest.loader /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py 
Analysis of collections (Stub) queued. Dependencies: sys (stub), collections.abc (stub)
Analysis of platform (Library) queued. Dependencies: platform (stub), collections, sys, os, re, subprocess, warnings, plistlib, socket, struct
Import:  unittest.main /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py 
Import:  unittest.runner /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/runner.py 
Import:  unittest.signals /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/signals.py 
Import:  encodings.aliases /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/aliases.py 
Analysis of unittest.signals (Library) queued. Dependencies: signal, weakref, functools
Analysis of distutils.dep_util (Library) queued. Dependencies: distutils.dep_util (stub), os, distutils.errors, stat
Import:  encodings.mbcs /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/mbcs.py 
Analysis of _codecs (Stub) queued. Dependencies: sys (stub), codecs (stub)
Analysis of unittest.runner (Library) queued. Dependencies: sys, time, warnings, unittest, unittest.result, unittest.signals
Create built-in compiled (scraped) module:  gc /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of _codecs (CompiledBuiltin) queued. Dependencies: _codecs (stub)
Analysis of gc (CompiledBuiltin) queued. Dependencies: gc (stub)
Import:  plistlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/plistlib.py 
Import:  socket /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py 
Import:  signal /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py 
Analysis of token (Library) queued. Dependencies: token (stub), re, sys
Analysis of signal (Library) queued. Dependencies: signal (stub), _signal, functools, enum
Create built-in compiled (scraped) module:  _signal /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of re (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of unittest.main (Library) queued. Dependencies: sys, argparse, os, unittest, unittest.loader, unittest.runner, unittest.signals
Analysis of argparse (Stub) queued. Dependencies: sys (stub)
Analysis of unittest.loader (Library) queued. Dependencies: os, re, sys, traceback, types, functools, warnings, fnmatch, unittest, unittest.case, unittest.suite, unittest.util
Import:  enum /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py 
Analysis of token (Stub) queued. Dependencies: sys (stub)
Analysis of stat (Library) queued. Dependencies: stat (stub), _stat
Import:  unittest.util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/util.py 
Create built-in compiled (scraped) module:  _stat /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of _stat (CompiledBuiltin) queued. Dependencies: _stat (stub)
Analysis of _stat (Stub) queued. Dependencies: 
Analysis of argparse (Library) queued. Dependencies: argparse (stub), os, re, sys, gettext, copy, textwrap, warnings
Analysis of enum (Library) queued. Dependencies: enum (stub), sys, types, _collections, collections, warnings
Analysis of stat (Stub) queued. Dependencies: sys (stub)
Analysis of unittest.suite (Library) queued. Dependencies: sys, unittest, unittest.case, unittest.util
Analysis of distutils.spawn (Stub) queued. Dependencies: 
Analysis of posix (CompiledBuiltin) queued. Dependencies: posix (stub), os
Analysis of posixpath (Stub) queued. Dependencies: sys (stub)
Analysis of enum (Stub) queued. Dependencies: sys (stub), abc (stub)
Analysis of posixpath (Library) queued. Dependencies: posixpath (stub), os, sys, stat, genericpath, pwd, re
Analysis of unittest.util (Library) queued. Dependencies: collections, os
Import:  gettext /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gettext.py 
Analysis of distutils.spawn (Library) queued. Dependencies: distutils.spawn (stub), sys, os, distutils.errors, distutils.debug, distutils, distutils.log, distutils.sysconfig
Import:  textwrap /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/textwrap.py 
Analysis of itertools (CompiledBuiltin) queued. Dependencies: itertools (stub)
Analysis of unittest.case (Library) queued. Dependencies: sys, functools, difflib, logging, pprint, re, warnings, collections, contextlib, traceback, unittest, unittest.result, unittest.util
Analysis of modules loop on depth 1 in 520.27 ms:
    doctest(Library)
    string(Library)
    os(Library)
    types(Library)
    traceback(Library)
    collections(Library)
    ntpath(Library)
    functools(Library)
    copy(Library)
    genericpath(Library)
    heapq(Library)
    _collections(CompiledBuiltin)
    _functools(CompiledBuiltin)
Analysis of modules loop on depth 1 in 5.51 ms:
    distutils.util(Library)
    distutils.filelist(Library)
Analysis of modules loop on depth 2 in 19.49 ms:
    threading(Library)
    _threading_local(Library)
Analysis of modules loop on depth 1 in 35.47 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of platform (Library) on depth 1 completed in 35.55 ms.
Analysis version 205 has been completed in 694.01 ms with 65 entries analyzed and 72 entries skipped.
Analysis version 266 of 172 entries has started.
Analysis of warnings(Library) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of distutils.log(Library) canceled (no AST yet).
Analysis of _osx_support(Library) canceled (no AST yet).
Analysis of distutils.sysconfig(Library) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of subprocess(Library) canceled (no AST yet).
Analysis of tempfile(Library) canceled (no AST yet).
Analysis of py_compile(Library) canceled (no AST yet).
Analysis of lib2to3.refactor(Library) canceled (no AST yet).
Analysis of distutils.dir_util(Library) canceled (no AST yet).
Analysis of distutils.file_util(Library) canceled (no AST yet).
Analysis of token (Stub) on depth 4 completed in 2 ms.
Analysis of copyreg(Library) canceled (no AST yet).
Analysis of _compat_pickle(Library) canceled (no AST yet).
Analysis of _pickle(Compiled) canceled (no AST yet).
Analysis of operator(Library) canceled (no AST yet).
Analysis of heapq (Stub) on depth 4 completed in 0.59 ms.
Analysis of _heapq (Stub) on depth 5 completed in 2.69 ms.
Analysis of difflib(Library) canceled (no AST yet).
Analysis of inspect(Library) canceled (no AST yet).
Analysis of pdb(Library) canceled (no AST yet).
Analysis of unittest.result(Library) canceled (no AST yet).
Analysis of distutils.dep_util (Stub) on depth 3 completed in 0.3 ms.
Analysis of linecache (Stub) on depth 4 completed in 0.44 ms.
Analysis of itertools (Stub) on depth 4 completed in 2.61 ms.
Analysis of encodings.aliases(Library) canceled (no AST yet).
Analysis of encodings.mbcs(Library) canceled (no AST yet).
Analysis of gc (CompiledBuiltin) on depth 3 completed in 1.09 ms.
Analysis of plistlib(Library) canceled (no AST yet).
Analysis of socket(Library) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of argparse (Stub) on depth 4 completed in 11.9 ms.
Analysis of stat (Stub) on depth 3 completed in 0.55 ms.
Analysis of _stat (Stub) on depth 4 completed in 2.03 ms.
Analysis of gettext(Library) canceled (no AST yet).
Analysis of textwrap(Library) canceled (no AST yet).
Analysis of distutils.spawn (Stub) on depth 3 completed in 0.34 ms.
Analysis of posixpath (Stub) on depth 3 completed in 1.93 ms.
Analysis of modules loop on depth 3 in 25.01 ms:
    collections.abc(Stub)
    collections(Stub)
Analysis of enum (Stub) on depth 8 completed in 2.19 ms.
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 25.45 ms.
Analysis of _stat (CompiledBuiltin) on depth 3 completed in 9.27 ms.
Analysis of modules loop on depth 2 in 3.08 ms:
    struct(Library)
    _struct(Compiled)
Analysis of stat (Library) on depth 2 completed in 12.57 ms.
Analysis of encodings (Stub) on depth 5 completed in 0.29 ms.
Analysis of _codecs (Stub) on depth 5 completed in 5.56 ms.
Analysis of _codecs (CompiledBuiltin) on depth 4 completed in 0.76 ms.
Analysis of modules loop on depth 2 in 29.17 ms:
    io(Library)
    _io(CompiledBuiltin)
Analysis of platform (Stub) on depth 2 completed in 1.27 ms.
Analysis of modules loop on depth 2 in 6 ms:
    importlib.machinery(Stub)
    importlib(Stub)
    importlib.util(Stub)
Analysis of sysconfig(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of modules loop on depth 3 in 25.07 ms:
    codecs(Library)
    encodings(Library)
Analysis of re(Library) canceled (no AST yet).
Analysis of keyword (Library) on depth 3 completed in 2.71 ms.
Analysis of token (Library) on depth 3 completed in 22.16 ms.
Analysis of _signal (CompiledBuiltin) queued. Dependencies: signal
Analysis of unittest.result (Library) queued. Dependencies: io, sys, traceback, unittest, unittest.util, functools
Analysis of re (Library) queued. Dependencies: re (stub), enum, sre_compile, sre_parse, functools, _locale, copyreg, sre_constants
Analysis of textwrap (Library) queued. Dependencies: textwrap (stub), re
Analysis of signal (Stub) queued. Dependencies: sys (stub), enum (stub), types (stub)
Analysis of distutils.log (Library) queued. Dependencies: distutils.log (stub), sys
Analysis of textwrap (Stub) queued. Dependencies: 
Analysis of distutils.debug (Stub) queued. Dependencies: 
Import:  sre_compile /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_compile.py 
Analysis of sys (Stub) queued. Dependencies: types (stub), importlib.abc (stub)
Analysis of socket (Library) queued. Dependencies: socket (stub), _socket, os, sys, io, selectors, enum, errno
Analysis of unittest (Stub) queued. Dependencies: logging (stub), sys (stub), types (stub)
Analysis of copyreg (Library) queued. Dependencies: 
Analysis of _compat_pickle (Library) queued. Dependencies: 
Analysis of distutils.log (Stub) queued. Dependencies: 
Import:  sre_parse /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py 
Create built-in compiled (scraped) module:  _locale /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of pdb (Library) queued. Dependencies: pdb (stub), os, re, sys, cmd, bdb, dis, code, glob, pprint, signal, inspect, traceback, linecache, readline, shlex, runpy, pydoc, getopt
Import:  sre_constants /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_constants.py 
Create compiled (scraped):  _socket /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of _locale (CompiledBuiltin) queued. Dependencies: locale
Analysis of sre_constants (Stub) queued. Dependencies: 
Analysis of sre_constants (Library) queued. Dependencies: sre_constants (stub), _sre
Import:  selectors /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py 
Analysis of _socket (Compiled) queued. Dependencies: 
Create built-in compiled (scraped) module:  errno /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of pdb (Stub) queued. Dependencies: sys (stub)
Analysis of sre_parse (Library) queued. Dependencies: sre_parse (stub), sre_constants, warnings
Import:  cmd /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py 
Import:  bdb /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py 
Analysis of selectors (Stub) queued. Dependencies: abc (stub), socket (stub)
Import:  dis /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dis.py 
Import:  code /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py 
Import:  glob /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/glob.py 
Create compiled (scraped):  readline /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Code Action in file:///Users/brettcannon/Repositories/pypa/packaging/packaging/tags.py at (325, 25) - (325, 25)
Import:  shlex /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shlex.py 
Analysis of socket (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of sys (CompiledBuiltin) queued. Dependencies: sys (stub), _io, types
Import:  runpy /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py 
Import:  pydoc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py 
Import:  getopt /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/getopt.py 
Import:  locale /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py 
Analysis of _pickle (Compiled) queued. Dependencies: 
Analysis of cmd (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  _sre /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of _osx_support (Library) queued. Dependencies: os, re, sys, contextlib, tempfile, distutils, distutils.log
Analysis of _sre (CompiledBuiltin) queued. Dependencies: 
Analysis of selectors (Library) queued. Dependencies: selectors (stub), abc, collections, collections.abc, math, select, sys
Analysis of cmd (Library) queued. Dependencies: cmd (stub), string, sys, readline
Analysis of sysconfig (Stub) queued. Dependencies: 
Create compiled (scraped):  math /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of sre_parse (Stub) queued. Dependencies: sre_constants (stub)
Create compiled (scraped):  select /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/select.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of plistlib (Library) queued. Dependencies: plistlib (stub), binascii, codecs, contextlib, datetime, enum, io, itertools, os, re, struct, warnings, xml.parsers.expat
Analysis of doctest (Stub) queued. Dependencies: sys (stub), types (stub), unittest (stub)
Analysis of sysconfig (Library) queued. Dependencies: sysconfig (stub), os, sys, re, pprint, types, _osx_support, warnings
Analysis of locale (Library) queued. Dependencies: locale (stub), sys, encodings, encodings.aliases, re, _collections_abc, functools, _locale, warnings, os, _bootlocale
Analysis of plistlib (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of locale (Stub) queued. Dependencies: decimal (stub), sys (stub)
Analysis of sre_compile (Library) queued. Dependencies: sre_compile (stub), _sre, sre_parse, sre_constants, sys
Analysis of select (Compiled) queued. Dependencies: select (stub)
Analysis of errno (CompiledBuiltin) queued. Dependencies: errno (stub)
Analysis of sre_compile (Stub) queued. Dependencies: sys (stub), sre_parse (stub), sre_constants (stub)
Analysis of select (Stub) queued. Dependencies: sys (stub)
Analysis of errno (Stub) queued. Dependencies: sys (stub)
Create compiled (scraped):  binascii /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of math (Compiled) queued. Dependencies: math (stub)
Analysis of gettext (Library) queued. Dependencies: gettext (stub), locale, os, re, sys, warnings, struct, errno, copy
Import:  datetime /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/datetime.py 
Import:  xml.parsers.expat /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/parsers/expat.py 
Analysis of distutils.sysconfig (Stub) queued. Dependencies: distutils.ccompiler (stub)
Import:  _bootlocale /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_bootlocale.py 
Analysis of _bootlocale (Library) queued. Dependencies: sys, _locale, locale
Analysis of gettext (Stub) queued. Dependencies: 
Analysis of getopt (Library) queued. Dependencies: getopt (stub), os, gettext, sys
Analysis of math (Stub) queued. Dependencies: sys (stub)
Analysis of difflib (Stub) queued. Dependencies: sys (stub)
Analysis of dis (Stub) queued. Dependencies: sys (stub), types (stub), opcode (stub)
Analysis of distutils.sysconfig (Library) queued. Dependencies: distutils.sysconfig (stub), _imp, os, re, sys, distutils.errors, _osx_support, distutils.text_file, warnings
Analysis of bdb (Library) queued. Dependencies: fnmatch, sys, os, inspect, linecache, reprlib
Analysis of distutils.ccompiler (Stub) queued. Dependencies: 
Import:  distutils.text_file /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/text_file.py 
Analysis of inspect (Library) queued. Dependencies: inspect (stub), abc, dis, collections, collections.abc, enum, importlib, importlib.machinery, itertools, linecache, os, re, sys, tokenize, token, types, warnings, functools, operator, ast, argparse
Import:  ast /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py 
Analysis of modules loop on depth 1 in 804.97 ms:
    logging(Library)
    tokenize(Library)
    weakref(Library)
    pickle(Library)
    contextlib(Library)
    argparse(Library)
    posix(CompiledBuiltin)
    posixpath(Library)
    fnmatch(Library)
    pprint(Library)
    linecache(Library)
    unittest(Library)
    unittest.case(Library)
    unittest.suite(Library)
    unittest.loader(Library)
    unittest.main(Library)
    unittest.runner(Library)
    unittest.signals(Library)
    signal(Library)
    enum(Library)
    unittest.util(Library)
    doctest(Library)
    string(Library)
    os(Library)
    types(Library)
    traceback(Library)
    collections(Library)
    threading(Library)
    ntpath(Library)
    functools(Library)
    _threading_local(Library)
    copy(Library)
    genericpath(Library)
    heapq(Library)
    _collections(CompiledBuiltin)
    _functools(CompiledBuiltin)
Analysis of distutils.spawn (Library) on depth 2 completed in 4.32 ms.
Analysis of modules loop on depth 1 in 50.24 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of distutils.dep_util (Library) on depth 2 completed in 0.26 ms.
Analysis of modules loop on depth 1 in 11.2 ms:
    distutils.util(Library)
    distutils.filelist(Library)
Analysis version 266 has been completed in 1113.05 ms with 106 entries analyzed and 66 entries skipped.
Analysis version 352 of 223 entries has started.
Analysis of distutils (Stub) on depth 2 completed in 0.04 ms.
Analysis of distutils.util (Stub) on depth 2 completed in 0.52 ms.
Analysis of importlib._bootstrap (Library) on depth 2 completed in 17.98 ms.
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of subprocess(Library) canceled (no AST yet).
Analysis of tempfile(Library) canceled (no AST yet).
Analysis of py_compile(Library) canceled (no AST yet).
Analysis of lib2to3.refactor(Library) canceled (no AST yet).
Analysis of distutils.dir_util(Library) canceled (no AST yet).
Analysis of distutils.file_util(Library) canceled (no AST yet).
Analysis of copyreg (Library) on depth 2 completed in 0.96 ms.
Analysis of _compat_pickle (Library) on depth 3 completed in 0.63 ms.
Analysis of _pickle (Compiled) on depth 3 completed in 1.67 ms.
Analysis of distutils.debug (Stub) on depth 4 completed in 0.07 ms.
Analysis of operator(Library) canceled (no AST yet).
Analysis of difflib(Library) canceled (no AST yet).
Analysis of encodings.aliases(Library) canceled (no AST yet).
Analysis of encodings.mbcs(Library) canceled (no AST yet).
Analysis of textwrap (Stub) on depth 5 completed in 1.12 ms.
Analysis of distutils.log (Stub) on depth 3 completed in 0.52 ms.
Analysis of _socket (Compiled) on depth 3 completed in 27.83 ms.
Analysis of dis(Library) canceled (no AST yet).
Analysis of code(Library) canceled (no AST yet).
Analysis of glob(Library) canceled (no AST yet).
Analysis of readline(Compiled) canceled (no AST yet).
Analysis of shlex(Library) canceled (no AST yet).
Analysis of runpy(Library) canceled (no AST yet).
Analysis of pydoc(Library) canceled (no AST yet).
Analysis of sre_constants (Stub) on depth 3 completed in 6.45 ms.
Analysis of _sre (CompiledBuiltin) on depth 3 completed in 0.22 ms.
Analysis of cmd (Stub) on depth 6 completed in 1.36 ms.
Analysis of sysconfig (Stub) on depth 2 completed in 0.62 ms.
Analysis of binascii(Compiled) canceled (no AST yet).
Analysis of datetime(Library) canceled (no AST yet).
Analysis of xml.parsers.expat(Library) canceled (no AST yet).
Analysis of decimal(Stub) canceled (no AST yet).
Analysis of gettext (Stub) on depth 5 completed in 1.34 ms.
Analysis of distutils.ccompiler (Stub) on depth 4 completed in 3.53 ms.
Analysis of distutils.text_file(Library) canceled (no AST yet).
Analysis of modules loop on depth 2 in 88.76 ms:
    sys(Stub)
    importlib.abc(Stub)
    types(Stub)
    _importlib_modulespec(Stub)
    os(Stub)
    io(Stub)
    os.path(Stub)
    codecs(Stub)
    mmap(Stub)
Analysis of sre_parse (Stub) on depth 3 completed in 6.18 ms.
Analysis of sre_constants (Library) on depth 2 completed in 7.1 ms.
Analysis of distutils.sysconfig (Stub) on depth 3 completed in 0.6 ms.
Analysis of pdb (Stub) on depth 5 completed in 0.61 ms.
Analysis of locale (Stub) on depth 4 completed in 2.43 ms.
Analysis of select (Stub) on depth 5 completed in 5.01 ms.
Analysis of errno (Stub) on depth 4 completed in 3.52 ms.
Analysis of math (Stub) on depth 5 completed in 6.1 ms.
Analysis of modules loop on depth 3 in 22.27 ms:
    collections.abc(Stub)
    collections(Stub)
Analysis of modules loop on depth 2 in 7.53 ms:
    importlib.machinery(Stub)
    importlib(Stub)
    importlib.util(Stub)
Analysis of sre_compile (Stub) on depth 3 completed in 3.04 ms.
Analysis of signal (Stub) on depth 6 completed in 18.41 ms.
Analysis of re (Stub) on depth 2 completed in 1.6 ms.
Analysis of socket (Stub) on depth 3 completed in 10.98 ms.
Analysis of plistlib (Stub) on depth 3 completed in 1.23 ms.
Analysis of select (Compiled) on depth 4 completed in 12.03 ms.
Analysis of errno (CompiledBuiltin) on depth 3 completed in 45.88 ms.
Analysis of math (Compiled) on depth 4 completed in 1.88 ms.
Analysis of modules loop on depth 2 in 2.07 ms:
    struct(Library)
    _struct(Compiled)
Analysis of selectors (Stub) on depth 4 completed in 6.06 ms.
Analysis of unittest (Stub) on depth 5 completed in 27.95 ms.
Analysis of doctest (Stub) on depth 4 completed in 6.26 ms.
Analysis of modules loop on depth 2 in 27.45 ms:
    io(Library)
    _io(CompiledBuiltin)
Analysis of _ctypes(Compiled) canceled (no AST yet).
Analysis of packaging._typing(User) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of sre_parse (Library) on depth 2 completed in 22.47 ms.
Analysis of ast (Library) queued. Dependencies: ast (stub), _ast, inspect, collections
Create built-in compiled (scraped) module:  _ast /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of _ast (CompiledBuiltin) queued. Dependencies: _ast (stub)
Analysis of _ast (Stub) queued. Dependencies: sys (stub)
Analysis of ast (Stub) queued. Dependencies: _ast (stub)
Analysis of inspect (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of difflib (Library) queued. Dependencies: difflib (stub), heapq, collections, re, doctest
Analysis of dis (Library) queued. Dependencies: dis (stub), sys, types, collections, io, opcode, argparse
Import:  opcode /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/opcode.py 
Analysis of opcode (Library) queued. Dependencies: opcode (stub), _opcode
Create compiled (scraped):  _opcode /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_opcode.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of _opcode (Compiled) queued. Dependencies: 
Analysis of code (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of pwd (Stub) queued. Dependencies: 
Analysis of code (Library) queued. Dependencies: code (stub), sys, traceback, codeop, readline, argparse
Import:  codeop /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codeop.py 
Analysis of codeop (Library) queued. Dependencies: codeop (stub), __future__
Analysis of codeop (Stub) queued. Dependencies: types (stub)
Analysis of xml.parsers.expat (Library) queued. Dependencies: xml.parsers.expat (stub), sys, pyexpat
Analysis of warnings (Stub) queued. Dependencies: types (stub)
Analysis of opcode (Stub) queued. Dependencies: sys (stub)
Analysis of glob (Stub) queued. Dependencies: sys (stub)
Analysis of distutils.text_file (Library) queued. Dependencies: distutils.text_file (stub), sys, io
Analysis of pwd (CompiledBuiltin) queued. Dependencies: pwd (stub)
Analysis of xml.parsers.expat (Stub) queued. Dependencies: pyexpat (stub), pyexpat.errors (stub), pyexpat.model (stub)
Analysis of getopt (Stub) queued. Dependencies: 
Analysis of glob (Library) queued. Dependencies: glob (stub), os, re, fnmatch
Analysis of binascii (Stub) queued. Dependencies: sys (stub)
Analysis of readline (Stub) queued. Dependencies: sys (stub)
Analysis of readline (Compiled) queued. Dependencies: readline (stub)
Analysis of warnings (Library) queued. Dependencies: warnings (stub), sys, linecache, tracemalloc, re, traceback, _warnings
Analysis of distutils.text_file (Stub) queued. Dependencies: 
Analysis of shlex (Stub) queued. Dependencies: sys (stub)
Analysis of runpy (Stub) queued. Dependencies: 
Create compiled (scraped):  pyexpat /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/pyexpat.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of shlex (Library) queued. Dependencies: shlex (stub), os, re, sys, collections, io
Analysis of runpy (Library) queued. Dependencies: runpy (stub), sys, importlib, importlib.machinery, importlib.util, types, pkgutil, warnings
Analysis of packaging._typing (User) queued. Dependencies: 
Analysis of pyexpat (Compiled) queued. Dependencies: pyexpat (stub)
Analysis of pyexpat.errors (Stub) queued. Dependencies: sys (stub)
Analysis of tempfile (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of py_compile (Stub) queued. Dependencies: sys (stub)
Analysis of ctypes (Stub) queued. Dependencies: sys (stub)
Analysis of tempfile (Library) queued. Dependencies: tempfile (stub), functools, warnings, io, os, shutil, errno, random, weakref, _thread
Analysis of subprocess (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of _ctypes (Compiled) queued. Dependencies: 
Analysis of py_compile (Library) queued. Dependencies: py_compile (stub), enum, importlib, importlib._bootstrap_external, importlib.machinery, importlib.util, os, sys, traceback
Analysis of decimal (Stub) queued. Dependencies: 
Analysis of binascii (Compiled) queued. Dependencies: binascii (stub)
Import:  pkgutil /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py 
Analysis of pyexpat.model (Stub) queued. Dependencies: 
Analysis of subprocess (Library) queued. Dependencies: subprocess (stub), sys, io, os, time, signal, warnings, errno, threading, _posixsubprocess, select, selectors
Analysis of pyexpat (Stub) queued. Dependencies: pyexpat.errors (stub), pyexpat.model (stub)
Analysis of gc (Stub) queued. Dependencies: 
Analysis of pkgutil (Stub) queued. Dependencies: sys (stub), importlib.abc (stub)
Analysis of encodings.mbcs (Library) queued. Dependencies: codecs
Import:  tracemalloc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tracemalloc.py 
Create built-in compiled (scraped) module:  _warnings /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of pkgutil (Library) queued. Dependencies: pkgutil (stub), collections, functools, importlib, importlib.util, importlib.machinery, os, sys, types, warnings, marshal, inspect, zipimport
Import:  shutil /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py 
Import:  random /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py 
Analysis of lib2to3.refactor (Library) queued. Dependencies: io, os, pkgutil, sys, logging, operator, collections, itertools, lib2to3.pgen2, lib2to3.pgen2.driver, lib2to3.pgen2.tokenize, lib2to3.pgen2.token, lib2to3.fixer_util, lib2to3, lib2to3.pytree, lib2to3.pygram, lib2to3.btm_matcher, multiprocessing
Analysis of datetime (Stub) queued. Dependencies: sys (stub), time (stub)
Analysis of distutils.dir_util (Stub) queued. Dependencies: 
Analysis of distutils.file_util (Stub) queued. Dependencies: 
Analysis of distutils.dir_util (Library) queued. Dependencies: distutils.dir_util (stub), os, errno, distutils.errors, distutils, distutils.log, distutils.file_util
Analysis of distutils.file_util (Library) queued. Dependencies: distutils.file_util (stub), os, distutils.errors, distutils, distutils.log, distutils.dep_util, stat, errno
Analysis of operator (Stub) queued. Dependencies: sys (stub)
Analysis of _warnings (Stub) queued. Dependencies: 
Analysis of operator (Library) queued. Dependencies: operator (stub), functools, _operator
Analysis of tracemalloc (Stub) queued. Dependencies: sys (stub)
Analysis of keyword (Stub) queued. Dependencies: 
Analysis of encodings.aliases (Library) queued. Dependencies: 
Analysis of pydoc (Library) queued. Dependencies: importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, importlib.util, inspect, io, os, pkgutil, platform, re, sys, time, tokenize, urllib, urllib.parse, warnings, collections, reprlib, traceback, tempfile, subprocess, tty, pydoc_data, pydoc_data.topics, textwrap, http, http.server, email, email.message, select, threading, webbrowser, getopt
Analysis of _warnings (CompiledBuiltin) queued. Dependencies: _warnings (stub)
Create built-in compiled (scraped) module:  marshal /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of shutil (Stub) queued. Dependencies: os (stub), sys (stub)
Analysis of marshal (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  zipimport /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of random (Library) queued. Dependencies: random (stub), warnings, types, math, os, _collections_abc, hashlib, itertools, bisect, _random, time
Analysis of marshal (CompiledBuiltin) queued. Dependencies: marshal (stub)
Analysis of random (Stub) queued. Dependencies: _random (stub), sys (stub)
Analysis of zipimport (Stub) queued. Dependencies: types (stub)
Analysis of zipimport (CompiledBuiltin) queued. Dependencies: zipimport (stub)
Analysis of tracemalloc (Library) queued. Dependencies: tracemalloc (stub), collections.abc, functools, fnmatch, linecache, os, pickle, _tracemalloc
Analysis of lib2to3.pgen2 (Stub) queued. Dependencies: os (stub), sys (stub)
Import:  lib2to3.pgen2 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/__init__.py 
Analysis of lib2to3.pgen2 (Library) queued. Dependencies: lib2to3.pgen2 (stub)
Import:  lib2to3.pgen2.driver /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/driver.py 
Analysis of lib2to3.pgen2.driver (Stub) queued. Dependencies: os (stub), sys (stub), logging (stub), lib2to3.pytree (stub), lib2to3.pgen2 (stub), lib2to3.pgen2.grammar (stub)
Analysis of lib2to3.pgen2.driver (Library) queued. Dependencies: lib2to3.pgen2.driver (stub), codecs, io, os, logging, pkgutil, sys, lib2to3.pgen2, lib2to3.pgen2.grammar, lib2to3.pgen2.parse, lib2to3.pgen2.token, lib2to3.pgen2.tokenize, lib2to3.pgen2.pgen
Import:  lib2to3.pgen2.tokenize /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/tokenize.py 
Analysis of datetime (Library) queued. Dependencies: datetime (stub), time, math, sys, _strptime, _datetime
Import:  lib2to3.pgen2.token /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/token.py 
Import:  lib2to3.fixer_util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/fixer_util.py 
Analysis of lib2to3.pgen2.token (Library) queued. Dependencies: lib2to3.pgen2.token (stub)
Analysis of lib2to3.pgen2.tokenize (Stub) queued. Dependencies: lib2to3.pgen2.token (stub)
Analysis of lib2to3.pgen2.token (Stub) queued. Dependencies: sys (stub)
Analysis of lib2to3.pgen2.tokenize (Library) queued. Dependencies: lib2to3.pgen2.tokenize (stub), string, re, codecs, lib2to3.pgen2.token, lib2to3.pgen2, sys
Analysis of lib2to3.fixer_util (Library) queued. Dependencies: lib2to3.pgen2, lib2to3.pgen2.token, lib2to3.pytree, lib2to3.pygram, lib2to3, lib2to3.patcomp
Import:  lib2to3 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/__init__.py 
Analysis of lib2to3 (Stub) queued. Dependencies: 
Analysis of lib2to3 (Library) queued. Dependencies: lib2to3 (stub)
Import:  lib2to3.pytree /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pytree.py 
Import:  lib2to3.pygram /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pygram.py 
Analysis of lib2to3.pytree (Stub) queued. Dependencies: sys (stub), lib2to3.pgen2.grammar (stub)
Import:  lib2to3.btm_matcher /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/btm_matcher.py 
Analysis of lib2to3.pygram (Stub) queued. Dependencies: lib2to3.pgen2.grammar (stub)
Analysis of lib2to3.pytree (Library) queued. Dependencies: lib2to3.pytree (stub), sys, io, lib2to3.pygram
Analysis of lib2to3.pygram (Library) queued. Dependencies: lib2to3.pygram (stub), os, lib2to3.pgen2, lib2to3.pgen2.token, lib2to3.pgen2.driver, lib2to3, lib2to3.pytree
Analysis of lib2to3.btm_matcher (Library) queued. Dependencies: logging, itertools, collections, lib2to3, lib2to3.pytree, lib2to3.btm_utils, lib2to3.pygram
Analysis of shutil (Library) queued. Dependencies: shutil (stub), os, sys, stat, fnmatch, collections, errno, zlib, bz2, lzma, pwd, grp, tarfile, zipfile
Import:  multiprocessing /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/__init__.py 
Create compiled (scraped):  _posixsubprocess /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of multiprocessing (Library) queued. Dependencies: multiprocessing (stub), sys, multiprocessing.context
Analysis of _posixsubprocess (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  _operator /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of _posixsubprocess (Compiled) queued. Dependencies: _posixsubprocess (stub)
Import:  urllib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/__init__.py 
Import:  urllib.parse /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py 
Analysis of _operator (CompiledBuiltin) queued. Dependencies: _operator (stub), operator
Analysis of _operator (Stub) queued. Dependencies: sys (stub), operator (stub)
Import:  tty /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tty.py 
Import:  pydoc_data /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc_data/__init__.py 
Import:  pydoc_data.topics /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc_data/topics.py 
Analysis of urllib (Stub) queued. Dependencies: 
Analysis of urllib (Library) queued. Dependencies: urllib (stub)
Analysis of multiprocessing (Stub) queued. Dependencies: logging (stub), multiprocessing.connection (stub), multiprocessing.pool (stub), multiprocessing.synchronize (stub), multiprocessing.context (stub), multiprocessing.managers (stub), multiprocessing.process (stub), multiprocessing.queues (stub), sys (stub)
Analysis of urllib.parse (Stub) queued. Dependencies: sys (stub)
Analysis of _random (Stub) queued. Dependencies: sys (stub)
Import:  http /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/__init__.py 
Import:  http.server /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py 
Import:  email /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/__init__.py 
Import:  email.message /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/message.py 
Analysis of urllib.parse (Library) queued. Dependencies: urllib.parse (stub), re, sys, collections, unicodedata
Import:  webbrowser /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py 
Analysis of tty (Stub) queued. Dependencies: 
Import:  hashlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/hashlib.py 
Import:  bisect /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bisect.py 
Create compiled (scraped):  _random /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_random.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of tty (Library) queued. Dependencies: tty (stub), termios
Create built-in compiled (scraped) module:  _tracemalloc /Users/brettcannon/Repositories/pypa/packaging/.venv/bin/python3.7 
Analysis of pydoc_data (Library) queued. Dependencies: 
Import:  lib2to3.pgen2.grammar /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/grammar.py 
Import:  lib2to3.pgen2.parse /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/parse.py 
Import:  lib2to3.pgen2.pgen /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/pgen.py 
Import:  _strptime /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py 
Analysis of bisect (Stub) queued. Dependencies: 
Create compiled (scraped):  _datetime /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_datetime.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Import:  lib2to3.patcomp /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/patcomp.py 
Import:  lib2to3.btm_utils /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/btm_utils.py 
Create compiled (scraped):  zlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/zlib.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Import:  bz2 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bz2.py 
Import:  lzma /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lzma.py 
Create compiled (scraped):  grp /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/grp.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Import:  tarfile /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py 
Import:  zipfile /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py 
Import:  multiprocessing.context /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py 
Analysis of lib2to3.btm_utils (Library) queued. Dependencies: lib2to3, lib2to3.pytree, lib2to3.pgen2, lib2to3.pgen2.grammar, lib2to3.pgen2.token, lib2to3.pygram
Create compiled (scraped):  unicodedata /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/unicodedata.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Create compiled (scraped):  termios /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/termios.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of termios (Compiled) queued. Dependencies: termios (stub)
Analysis of termios (Stub) queued. Dependencies: 
Analysis of unicodedata (Compiled) queued. Dependencies: unicodedata (stub)
Analysis of unicodedata (Stub) queued. Dependencies: 
Analysis of http (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of zlib (Stub) queued. Dependencies: sys (stub)
Analysis of pydoc_data.topics (Library) queued. Dependencies: 
Analysis of zlib (Compiled) queued. Dependencies: zlib (stub)
Analysis of http (Library) queued. Dependencies: http (stub), enum
Analysis of bz2 (Stub) queued. Dependencies: io (stub), sys (stub), os (stub)
Analysis of bz2 (Library) queued. Dependencies: bz2 (stub), io, os, warnings, _compression, threading, _bz2
Import:  _compression /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_compression.py 
Create compiled (scraped):  _bz2 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_bz2.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of http.server (Stub) queued. Dependencies: sys (stub), socketserver (stub), email (stub), email.message (stub)
Analysis of _bz2 (Compiled) queued. Dependencies: 
Analysis of socketserver (Stub) queued. Dependencies: socket (stub), sys (stub), types (stub)
Analysis of _compression (Library) queued. Dependencies: _compression (stub), io
Analysis of _compression (Stub) queued. Dependencies: io (stub)
Analysis of http.server (Library) queued. Dependencies: http.server (stub), copy, datetime, email, email.utils, html, http, http.client, io, mimetypes, os, posixpath, select, shutil, socket, socketserver, sys, time, urllib, urllib.parse, functools, pwd, base64, binascii, subprocess, argparse
Analysis of lib2to3.patcomp (Library) queued. Dependencies: io, lib2to3.pgen2, lib2to3.pgen2.driver, lib2to3.pgen2.literals, lib2to3.pgen2.token, lib2to3.pgen2.tokenize, lib2to3.pgen2.parse, lib2to3.pgen2.grammar, lib2to3, lib2to3.pytree, lib2to3.pygram
Import:  email.utils /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/utils.py 
Import:  html /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/html/__init__.py 
Import:  http.client /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py 
Import:  mimetypes /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/mimetypes.py 
Import:  socketserver /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py 
Import:  base64 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py 
Import:  lib2to3.pgen2.literals /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/literals.py 
Analysis of lib2to3.pgen2.literals (Library) queued. Dependencies: lib2to3.pgen2.literals (stub), re
Analysis of lib2to3.pgen2.literals (Stub) queued. Dependencies: 
Analysis of multiprocessing.connection (Stub) queued. Dependencies: socket (stub), types (stub)
Analysis of base64 (Library) queued. Dependencies: base64 (stub), re, struct, binascii, warnings, sys, getopt
Analysis of base64 (Stub) queued. Dependencies: sys (stub)
Analysis of lzma (Stub) queued. Dependencies: io (stub), sys (stub), os (stub)
Analysis of email.utils (Stub) queued. Dependencies: email.charset (stub), datetime (stub)
Analysis of socketserver (Library) queued. Dependencies: socketserver (stub), socket, selectors, os, sys, threading, io, time, traceback
Analysis of _datetime (Compiled) queued. Dependencies: datetime
Analysis of multiprocessing.synchronize (Stub) queued. Dependencies: multiprocessing.context (stub), threading (stub), sys (stub)
Analysis of lib2to3.pgen2.grammar (Stub) queued. Dependencies: lib2to3.pgen2 (stub)
Analysis of _tracemalloc (CompiledBuiltin) queued. Dependencies: _tracemalloc (stub)
Analysis of _random (Compiled) queued. Dependencies: _random (stub)
Analysis of multiprocessing.pool (Stub) queued. Dependencies: 
Analysis of multiprocessing.queues (Stub) queued. Dependencies: queue (stub)
Analysis of lzma (Library) queued. Dependencies: lzma (stub), io, os, _lzma, _compression
Analysis of bisect (Library) queued. Dependencies: bisect (stub), _bisect
Analysis of html (Stub) queued. Dependencies: 
Analysis of grp (Stub) queued. Dependencies: 
Analysis of email (Library) queued. Dependencies: email (stub), email.parser
Analysis of email.message (Stub) queued. Dependencies: sys (stub), email.charset (stub), email.errors (stub), email.header (stub), email.policy (stub), email.contentmanager (stub)
Analysis of _tracemalloc (Stub) queued. Dependencies: 
Analysis of http.client (Stub) queued. Dependencies: email (stub), email.message (stub), io (stub), socket (stub), sys (stub), ssl (stub), types (stub)
Analysis of multiprocessing.managers (Stub) queued. Dependencies: queue (stub), threading (stub)
Analysis of hashlib (Library) queued. Dependencies: hashlib (stub), _sha1, _md5, _sha256, _sha512, _blake2, _sha3, _hashlib, logging
Analysis of lib2to3.pgen2.grammar (Library) queued. Dependencies: lib2to3.pgen2.grammar (stub), collections, pickle, lib2to3.pgen2, lib2to3.pgen2.token, pprint
Analysis of webbrowser (Stub) queued. Dependencies: sys (stub)
Analysis of multiprocessing.process (Stub) queued. Dependencies: multiprocessing (stub)
Create compiled (scraped):  _lzma /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_lzma.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Create compiled (scraped):  _bisect /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_bisect.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of email.charset (Stub) queued. Dependencies: 
Analysis of webbrowser (Library) queued. Dependencies: webbrowser (stub), os, shlex, shutil, sys, subprocess, threading, copy, glob, pwd, socket, tempfile, getopt
Import:  email.parser /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/parser.py 
Analysis of lib2to3.pgen2.parse (Stub) queued. Dependencies: lib2to3.pgen2.grammar (stub), lib2to3.pytree (stub)
Analysis of http.client (Library) queued. Dependencies: http.client (stub), email, email.parser, email.message, http, io, re, socket, collections, collections.abc, urllib.parse, ssl, warnings
Analysis of hashlib (Stub) queued. Dependencies: sys (stub)
Analysis of grp (Compiled) queued. Dependencies: grp (stub)
Analysis of lib2to3.pgen2.parse (Library) queued. Dependencies: lib2to3.pgen2.parse (stub), lib2to3.pgen2, lib2to3.pgen2.token
Create compiled (scraped):  _sha1 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_sha1.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Create compiled (scraped):  _md5 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_md5.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of mimetypes (Stub) queued. Dependencies: sys (stub)
Create compiled (scraped):  _sha256 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_sha256.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha512 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_sha512.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Create compiled (scraped):  _blake2 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_blake2.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha3 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_sha3.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of zipfile (Stub) queued. Dependencies: types (stub), os (stub), sys (stub)
Create compiled (scraped):  _hashlib /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_hashlib.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of multiprocessing.context (Stub) queued. Dependencies: logging (stub), multiprocessing (stub), multiprocessing.synchronize (stub), multiprocessing.queues (stub), sys (stub)
Analysis of lib2to3.pgen2.pgen (Stub) queued. Dependencies: lib2to3.pgen2 (stub), lib2to3.pgen2.grammar (stub), lib2to3.pgen2.tokenize (stub)
Analysis of email (Stub) queued. Dependencies: sys (stub), email.message (stub), email.policy (stub)
Analysis of html (Library) queued. Dependencies: html (stub), re, html.entities
Analysis of multiprocessing.context (Library) queued. Dependencies: multiprocessing.context (stub), os, sys, threading, multiprocessing, multiprocessing.process, multiprocessing.reduction, multiprocessing.managers, multiprocessing.connection, multiprocessing.synchronize, multiprocessing.queues, multiprocessing.pool, multiprocessing.sharedctypes, multiprocessing.spawn, multiprocessing.util, multiprocessing.forkserver, multiprocessing.popen_fork, multiprocessing.popen_spawn_posix, multiprocessing.popen_forkserver, multiprocessing.popen_spawn_win32
Analysis of email.utils (Library) queued. Dependencies: email.utils (stub), os, re, time, random, socket, datetime, urllib, urllib.parse, email._parseaddr, email.charset
Analysis of ssl (Stub) queued. Dependencies: socket (stub), sys (stub)
Analysis of _bisect (Compiled) queued. Dependencies: _bisect (stub)
Analysis of _lzma (Compiled) queued. Dependencies: 
Analysis of queue (Stub) queued. Dependencies: 
Analysis of email.parser (Stub) queued. Dependencies: email (stub), email.feedparser (stub), email.message (stub), email.policy (stub)
Analysis of mimetypes (Library) queued. Dependencies: mimetypes (stub), os, sys, posixpath, urllib, urllib.parse, getopt
Analysis of lib2to3.pgen2.pgen (Library) queued. Dependencies: lib2to3.pgen2.pgen (stub), lib2to3.pgen2, lib2to3.pgen2.grammar, lib2to3.pgen2.token, lib2to3.pgen2.tokenize
Analysis of email.errors (Stub) queued. Dependencies: 
Analysis of email.message (Library) queued. Dependencies: email.message (stub), re, uu, quopri, io, email, email.utils, email.errors, email._policybase, email.charset, email._encoded_words, email.generator, email.iterators, email.policy
Analysis of email.header (Stub) queued. Dependencies: email.charset (stub)
Analysis of tarfile (Stub) queued. Dependencies: os (stub), sys (stub), types (stub)
Analysis of _strptime (Library) queued. Dependencies: time, locale, calendar, re, datetime, _thread
Analysis of _hashlib (Compiled) queued. Dependencies: 
Import:  ssl /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py 
Analysis of email.parser (Library) queued. Dependencies: email.parser (stub), io, email.feedparser, email._policybase
Analysis of _sha1 (Compiled) queued. Dependencies: 
Analysis of email.policy (Stub) queued. Dependencies: abc (stub), sys (stub), email.message (stub), email.errors (stub), email.header (stub), email.contentmanager (stub)
Import:  html.entities /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/html/entities.py 
Analysis of email.contentmanager (Stub) queued. Dependencies: email.message (stub)
Import:  multiprocessing.process /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py 
Analysis of _sha3 (Compiled) queued. Dependencies: 
Analysis of ssl (Library) queued. Dependencies: ssl (stub), sys, os, collections, enum, _ssl, socket, base64, errno, warnings, time, calendar
Analysis of html.entities (Stub) queued. Dependencies: 
Analysis of _md5 (Compiled) queued. Dependencies: 
Import:  multiprocessing.reduction /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/reduction.py 
Analysis of _blake2 (Compiled) queued. Dependencies: 
Analysis of _sha512 (Compiled) queued. Dependencies: 
Analysis of _sha256 (Compiled) queued. Dependencies: 
Analysis of multiprocessing.process (Library) queued. Dependencies: multiprocessing.process (stub), os, sys, signal, itertools, threading, _weakrefset, multiprocessing, multiprocessing.util, multiprocessing.context, traceback
Import:  multiprocessing.managers /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py 
Analysis of multiprocessing.reduction (Library) queued. Dependencies: abc, copyreg, functools, io, os, pickle, socket, sys, multiprocessing, multiprocessing.context, array, multiprocessing.resource_sharer
Import:  multiprocessing.connection /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py 
Analysis of zipfile (Library) queued. Dependencies: zipfile (stub), io, os, importlib, importlib.util, sys, time, stat, shutil, struct, binascii, threading, zlib, bz2, lzma, warnings, py_compile, argparse
Import:  multiprocessing.synchronize /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py 
Import:  multiprocessing.queues /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py 
Import:  multiprocessing.pool /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py 
Import:  multiprocessing.sharedctypes /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/sharedctypes.py 
Analysis of html.entities (Library) queued. Dependencies: html.entities (stub)
Analysis of multiprocessing.queues (Library) queued. Dependencies: multiprocessing.queues (stub), sys, os, threading, collections, time, weakref, errno, queue, _multiprocessing, multiprocessing, multiprocessing.connection, multiprocessing.context, multiprocessing.util, multiprocessing.synchronize, traceback
Analysis of multiprocessing.connection (Library) queued. Dependencies: multiprocessing.connection (stub), io, os, sys, socket, struct, time, tempfile, itertools, _multiprocessing, multiprocessing, multiprocessing.util, multiprocessing.context, hmac, xmlrpc, xmlrpc.client, selectors, multiprocessing.resource_sharer
Import:  multiprocessing.spawn /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py 
Analysis of multiprocessing.pool (Library) queued. Dependencies: multiprocessing.pool (stub), threading, queue, itertools, collections, os, time, traceback, multiprocessing, multiprocessing.util, multiprocessing.dummy
Analysis of multiprocessing.sharedctypes (Library) queued. Dependencies: ctypes, weakref, multiprocessing, multiprocessing.heap, multiprocessing.context
Analysis of multiprocessing.synchronize (Library) queued. Dependencies: multiprocessing.synchronize (stub), threading, sys, tempfile, _multiprocessing, time, multiprocessing, multiprocessing.context, multiprocessing.process, multiprocessing.util, multiprocessing.semaphore_tracker, struct, multiprocessing.heap
Analysis of _bisect (Stub) queued. Dependencies: 
Import:  multiprocessing.util /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/util.py 
Import:  multiprocessing.forkserver /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py 
Analysis of multiprocessing.spawn (Library) queued. Dependencies: os, sys, runpy, types, multiprocessing, multiprocessing.process, multiprocessing.context, multiprocessing.util, multiprocessing.semaphore_tracker
Import:  multiprocessing.popen_fork /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py 
Import:  multiprocessing.popen_spawn_posix /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_spawn_posix.py 
Import:  multiprocessing.popen_forkserver /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_forkserver.py 
Analysis of tarfile (Library) queued. Dependencies: tarfile (stub), sys, os, io, shutil, stat, time, struct, copy, re, pwd, grp, warnings, zlib, bz2, lzma, gzip, argparse
Import:  multiprocessing.popen_spawn_win32 /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_spawn_win32.py 
Analysis of multiprocessing.forkserver (Library) queued. Dependencies: errno, os, selectors, signal, socket, struct, sys, threading, warnings, multiprocessing, multiprocessing.connection, multiprocessing.process, multiprocessing.context, multiprocessing.semaphore_tracker, multiprocessing.spawn, multiprocessing.util
Import:  email._parseaddr /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/_parseaddr.py 
Import:  email.charset /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/charset.py 
Analysis of multiprocessing.popen_spawn_posix (Library) queued. Dependencies: io, os, multiprocessing.context, multiprocessing, multiprocessing.popen_fork, multiprocessing.spawn, multiprocessing.util, multiprocessing.semaphore_tracker
Import:  uu /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/uu.py 
Import:  quopri /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/quopri.py 
Analysis of multiprocessing.popen_spawn_win32 (Library) queued. Dependencies: os, signal, sys, multiprocessing.context, multiprocessing, multiprocessing.spawn, multiprocessing.util
Import:  email.errors /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/errors.py 
Import:  email._policybase /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/_policybase.py 
Analysis of multiprocessing.popen_fork (Library) queued. Dependencies: os, sys, signal, multiprocessing, multiprocessing.util, multiprocessing.connection
Analysis of email.feedparser (Stub) queued. Dependencies: sys (stub), email.message (stub), email.policy (stub)
Import:  email._encoded_words /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/_encoded_words.py 
Analysis of uu (Stub) queued. Dependencies: sys (stub)
Analysis of quopri (Stub) queued. Dependencies: 
Import:  email.generator /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/generator.py 
Import:  email.iterators /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/iterators.py 
Analysis of uu (Library) queued. Dependencies: uu (stub), binascii, os, sys, optparse
Import:  email.policy /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/policy.py 
Analysis of email.errors (Library) queued. Dependencies: email.errors (stub)
Import:  calendar /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/calendar.py 
Analysis of email.charset (Library) queued. Dependencies: email.charset (stub), functools, email, email.base64mime, email.quoprimime, email.errors, email.encoders
Analysis of quopri (Library) queued. Dependencies: quopri (stub), binascii, io, sys, getopt
Import:  email.feedparser /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/feedparser.py 
Analysis of multiprocessing.popen_forkserver (Library) queued. Dependencies: io, os, multiprocessing.context, multiprocessing, multiprocessing.forkserver, multiprocessing.popen_fork, multiprocessing.spawn, multiprocessing.util, multiprocessing.connection
Analysis of email.generator (Stub) queued. Dependencies: email.message (stub), email.policy (stub)
Create compiled (scraped):  _ssl /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of email.iterators (Stub) queued. Dependencies: email.message (stub)
Analysis of email.policy (Library) queued. Dependencies: email.policy (stub), re, sys, email._policybase, email.utils, email.headerregistry, email.contentmanager, email.message
Analysis of calendar (Stub) queued. Dependencies: datetime (stub), sys (stub), time (stub)
Analysis of email.generator (Library) queued. Dependencies: email.generator (stub), re, sys, time, random, copy, io, email.utils
Analysis of email.feedparser (Library) queued. Dependencies: email.feedparser (stub), re, email, email.errors, email._policybase, collections, io, email.message
Create compiled (scraped):  array /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/array.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Import:  multiprocessing.resource_sharer /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/resource_sharer.py 
Import:  queue /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py 
Analysis of array (Compiled) queued. Dependencies: array (stub)
Create compiled (scraped):  _multiprocessing /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_multiprocessing.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of _ssl (Compiled) queued. Dependencies: 
Import:  hmac /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/hmac.py 
Import:  xmlrpc /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/__init__.py 
Analysis of multiprocessing.resource_sharer (Library) queued. Dependencies: os, signal, socket, sys, threading, multiprocessing, multiprocessing.process, multiprocessing.context, multiprocessing.util, multiprocessing.connection
Import:  xmlrpc.client /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py 
Analysis of hmac (Stub) queued. Dependencies: types (stub), sys (stub)
Analysis of queue (Library) queued. Dependencies: queue (stub), threading, collections, heapq, time, _queue
Analysis of _multiprocessing (Compiled) queued. Dependencies: 
Analysis of xmlrpc (Library) queued. Dependencies: 
Import:  multiprocessing.dummy /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/dummy/__init__.py 
Analysis of email._encoded_words (Library) queued. Dependencies: re, base64, binascii, functools, string, email, email.errors
Import:  multiprocessing.heap /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/heap.py 
Analysis of email._policybase (Library) queued. Dependencies: abc, email, email.header, email.charset, email.utils
Import:  multiprocessing.semaphore_tracker /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py 
Analysis of multiprocessing.dummy (Stub) queued. Dependencies: array (stub), sys (stub), threading (stub), weakref (stub), multiprocessing.dummy.connection (stub), queue (stub)
Import:  gzip /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py 
Import:  optparse /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py 
Analysis of multiprocessing.semaphore_tracker (Library) queued. Dependencies: os, signal, sys, threading, warnings, _multiprocessing, multiprocessing, multiprocessing.spawn, multiprocessing.util
Analysis of multiprocessing.heap (Library) queued. Dependencies: bisect, mmap, os, sys, tempfile, threading, multiprocessing.context, multiprocessing, multiprocessing.util
Analysis of gzip (Stub) queued. Dependencies: os.path (stub), _compression (stub), zlib (stub)
Analysis of multiprocessing.dummy (Library) queued. Dependencies: multiprocessing.dummy (stub), threading, sys, weakref, array, multiprocessing.dummy.connection, queue, multiprocessing.pool
Analysis of gzip (Library) queued. Dependencies: gzip (stub), struct, sys, time, os, zlib, io, _compression, warnings, errno
Analysis of hmac (Library) queued. Dependencies: hmac (stub), warnings, _operator, _hashlib, hashlib
Import:  email.base64mime /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/base64mime.py 
Import:  email.quoprimime /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/quoprimime.py 
Import:  email.encoders /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/encoders.py 
Analysis of xmlrpc.client (Library) queued. Dependencies: base64, sys, time, datetime, decimal, http, http.client, urllib, urllib.parse, xml.parsers, xml.parsers.expat, errno, io, gzip
Import:  email.headerregistry /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/headerregistry.py 
Import:  email.contentmanager /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/contentmanager.py 
Analysis of email.base64mime (Library) queued. Dependencies: base64, binascii
Create compiled (scraped):  _queue /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_queue.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of email.encoders (Stub) queued. Dependencies: email.message (stub)
Import:  email.header /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/header.py 
Analysis of email.encoders (Library) queued. Dependencies: email.encoders (stub), base64, quopri
Create compiled (scraped):  mmap /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/mmap.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of multiprocessing.util (Library) queued. Dependencies: os, itertools, sys, weakref, atexit, threading, subprocess, multiprocessing, multiprocessing.process, logging, shutil, tempfile, traceback, _posixsubprocess
Import:  multiprocessing.dummy.connection /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/dummy/connection.py 
Analysis of email.headerregistry (Stub) queued. Dependencies: datetime (stub), email.errors (stub), email.policy (stub)
Analysis of email.headerregistry (Library) queued. Dependencies: email.headerregistry (stub), types, email, email.utils, email.errors, email._header_value_parser
Analysis of calendar (Library) queued. Dependencies: calendar (stub), sys, datetime, locale, itertools, argparse
Analysis of optparse (Stub) queued. Dependencies: sys (stub)
Analysis of email.iterators (Library) queued. Dependencies: email.iterators (stub), sys, io
Analysis of email._parseaddr (Library) queued. Dependencies: time, calendar
Analysis of multiprocessing.managers (Library) queued. Dependencies: multiprocessing.managers (stub), sys, threading, array, queue, time, traceback, multiprocessing, multiprocessing.connection, multiprocessing.context, multiprocessing.pool, multiprocessing.process, multiprocessing.util
Analysis of email.quoprimime (Library) queued. Dependencies: re, string
Import:  decimal /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/decimal.py 
Import:  xml.parsers /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/parsers/__init__.py 
Import:  email._header_value_parser /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/_header_value_parser.py 
Analysis of optparse (Library) queued. Dependencies: optparse (stub), sys, os, textwrap, gettext
Analysis of multiprocessing.dummy.connection (Library) queued. Dependencies: multiprocessing.dummy.connection (stub), queue
Analysis of decimal (Library) queued. Dependencies: decimal (stub), _decimal, _pydecimal
Create compiled (scraped):  _decimal /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_decimal.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Import:  _pydecimal /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_pydecimal.py 
Analysis of email._header_value_parser (Library) queued. Dependencies: re, sys, urllib, string, collections, operator, email, email._encoded_words, email.errors, email.utils
Analysis of xml.parsers (Library) queued. Dependencies: xml.parsers (stub)
Analysis of xml.parsers (Stub) queued. Dependencies: xml (stub), xml.parsers.expat (stub)
Analysis of _pydecimal (Library) queued. Dependencies: math, numbers, sys, collections, contextvars, re, locale, itertools
Analysis of email.contentmanager (Library) queued. Dependencies: email.contentmanager (stub), binascii, email, email.charset, email.message, email.errors, email.quoprimime
Import:  numbers /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/numbers.py 
Import:  contextvars /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextvars.py 
Analysis of _decimal (Compiled) queued. Dependencies: 
Analysis of contextvars (Library) queued. Dependencies: _contextvars
Analysis of _queue (Compiled) queued. Dependencies: 
Create compiled (scraped):  _contextvars /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_contextvars.cpython-37m-darwin.so /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload 
Analysis of _contextvars (Compiled) queued. Dependencies: 
Analysis of xml (Stub) queued. Dependencies: xml.parsers (stub)
Analysis of numbers (Library) queued. Dependencies: numbers (stub), abc
Analysis of email.header (Library) queued. Dependencies: email.header (stub), re, binascii, email, email.quoprimime, email.base64mime, email.errors, email.charset
Analysis of numbers (Stub) queued. Dependencies: abc (stub), sys (stub)
Analysis of multiprocessing.dummy.connection (Stub) queued. Dependencies: queue (stub)
Analysis of mmap (Compiled) queued. Dependencies: mmap (stub)
Analysis of modules loop on depth 1 in 2252.63 ms:
    importlib.machinery(Library)
    logging(Library)
    re(Library)
    sys(CompiledBuiltin)
    importlib._bootstrap_external(Library)
    importlib(Library)
    tokenize(Library)
    _collections_abc(Library)
    weakref(Library)
    collections.abc(Library)
    pickle(Library)
    contextlib(Library)
    token(Library)
    argparse(Library)
    posix(CompiledBuiltin)
    posixpath(Library)
    fnmatch(Library)
    pprint(Library)
    keyword(Library)
    linecache(Library)
    inspect(Library)
    pdb(Library)
    unittest(Library)
    unittest.result(Library)
    unittest.case(Library)
    unittest.suite(Library)
    unittest.loader(Library)
    unittest.main(Library)
    unittest.runner(Library)
    unittest.signals(Library)
    signal(Library)
    _signal(CompiledBuiltin)
    enum(Library)
    unittest.util(Library)
    gettext(Library)
    textwrap(Library)
    sre_compile(Library)
    _locale(CompiledBuiltin)
    cmd(Library)
    bdb(Library)
    getopt(Library)
    locale(Library)
    _bootlocale(Library)
    doctest(Library)
    string(Library)
    os(Library)
    types(Library)
    traceback(Library)
    collections(Library)
    threading(Library)
    codecs(Library)
    ntpath(Library)
    encodings(Library)
    functools(Library)
    _threading_local(Library)
    copy(Library)
    genericpath(Library)
    heapq(Library)
    _collections(CompiledBuiltin)
    _functools(CompiledBuiltin)
Analysis of distutils.log (Library) on depth 2 completed in 2.17 ms.
Analysis of selectors (Library) on depth 3 completed in 16.23 ms.
Analysis of plistlib (Library) on depth 2 completed in 38.37 ms.
Analysis of modules loop on depth 1 in 45.39 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of _osx_support (Library) on depth 2 completed in 18.4 ms.
Analysis of distutils.sysconfig (Library) on depth 2 completed in 16.63 ms.
Analysis of sysconfig (Library) on depth 1 completed in 19.79 ms.
Analysis of modules loop on depth 1 in 12.58 ms:
    distutils.util(Library)
    distutils.filelist(Library)
Analysis of socket (Library) on depth 2 completed in 102.74 ms.
Analysis version 352 has been completed in 2810.83 ms with 151 entries analyzed and 72 entries skipped.
Analysis version 773 of 465 entries has started.
Analysis of posix (Stub) on depth 3 completed in 1.1 ms.
Analysis of string (Stub) on depth 3 completed in 1.62 ms.
Analysis of packaging._typing (User) on depth 0 completed in 0.56 ms.
Analysis of abc (Stub) on depth 3 completed in 2.67 ms.
Analysis of _thread (Stub) on depth 4 completed in 6.8 ms.
Analysis of _ctypes (Compiled) on depth 2 completed for library in 6 ms.
Analysis of _string (CompiledBuiltin) on depth 3 completed for library in 0.18 ms.
Analysis of distutils.filelist (Stub) on depth 3 completed in 0.14 ms.
Analysis of copyreg (Library) on depth 2 completed for library in 2.99 ms.
Analysis of distutils.debug (Stub) on depth 4 completed in 3.16 ms.
Analysis of _compat_pickle (Library) on depth 3 completed for library in 3.66 ms.
Analysis of _weakrefset (Stub) on depth 4 completed in 9.48 ms.
Analysis of _pickle (Compiled) on depth 3 completed for library in 6.9 ms.
Analysis of fnmatch (Stub) on depth 4 completed in 0.26 ms.
Analysis of _abc (CompiledBuiltin) on depth 3 completed for library in 0.26 ms.
Analysis of distutils.errors (Stub) on depth 3 completed in 3.33 ms.
Analysis of atexit (Stub) on depth 3 completed in 0.41 ms.
Analysis of copy (Stub) on depth 4 completed in 0.55 ms.
Analysis of _heapq (Stub) on depth 5 completed in 0.55 ms.
Analysis of distutils.dep_util (Stub) on depth 3 completed in 2.63 ms.
Analysis of itertools (Stub) on depth 4 completed in 9.32 ms.
Analysis of keyword (Stub) on depth 4 completed in 0.56 ms.
Analysis of gc (Stub) on depth 4 completed in 13.66 ms.
Analysis of encodings.aliases (Library) on depth 4 completed for library in 14.12 ms.
Analysis of distutils.spawn (Stub) on depth 3 completed in 0.41 ms.
Analysis of _stat (Stub) on depth 4 completed in 1.56 ms.
Analysis of textwrap (Stub) on depth 5 completed in 3.88 ms.
Analysis of _sre (CompiledBuiltin) on depth 3 completed for library in 0.35 ms.
Analysis of distutils.log (Stub) on depth 3 completed in 0.78 ms.
Analysis of cmd (Stub) on depth 6 completed in 9.57 ms.
Analysis of sre_constants (Stub) on depth 3 completed in 3.31 ms.
Analysis of _socket (Compiled) on depth 3 completed for library in 11.82 ms.
Analysis of sysconfig (Stub) on depth 2 completed in 6.24 ms.
Analysis of decimal (Stub) on depth 5 completed in 27.48 ms.
Analysis of _opcode (Compiled) on depth 7 completed for library in 0.12 ms.
Analysis of pwd (Stub) on depth 3 completed in 0.26 ms.
Analysis of gettext (Stub) on depth 5 completed in 3.28 ms.
Analysis of getopt (Stub) on depth 6 completed in 0.37 ms.
Analysis of distutils.ccompiler (Stub) on depth 4 completed in 3.9 ms.
Analysis of distutils.text_file (Stub) on depth 4 completed in 5.21 ms.
Analysis of pyexpat.model (Stub) on depth 5 completed in 0.06 ms.
Analysis of distutils.file_util (Stub) on depth 3 completed in 0.35 ms.
Analysis of _warnings (Stub) on depth 3 completed in 0.44 ms.
Analysis of runpy (Stub) on depth 6 completed in 0.46 ms.
Analysis of distutils.dir_util (Stub) on depth 3 completed in 0.25 ms.
Analysis of marshal (Stub) on depth 5 completed in 0.2 ms.
Analysis of pydoc_data (Library) on depth 6 completed for library in 0.03 ms.
Analysis of pydoc_data.topics (Library) on depth 6 completed for library in 1.02 ms.
Analysis of lib2to3 (Stub) on depth 4 completed in 0.03 ms.
Analysis of _posixsubprocess (Stub) on depth 4 completed in 0.53 ms.
Analysis of urllib (Stub) on depth 7 completed in 0.03 ms.
Analysis of multiprocessing.pool (Stub) on depth 5 completed in 9.67 ms.
Analysis of tty (Stub) on depth 7 completed in 0.47 ms.
Analysis of bisect (Stub) on depth 5 completed in 0.46 ms.
Analysis of unicodedata (Stub) on depth 8 completed in 8.13 ms.
Analysis of _bz2 (Compiled) on depth 5 completed for library in 1.25 ms.
Analysis of lib2to3.pgen2.literals (Stub) on depth 6 completed in 0.29 ms.
Analysis of termios (Stub) on depth 8 completed in 10.6 ms.
Analysis of email.charset (Stub) on depth 8 completed in 4.21 ms.
Analysis of _tracemalloc (Stub) on depth 4 completed in 0.32 ms.
Analysis of html (Stub) on depth 8 completed in 0.23 ms.
Analysis of _lzma (Compiled) on depth 5 completed for library in 2.05 ms.
Analysis of grp (Stub) on depth 5 completed in 5.88 ms.
Analysis of _md5 (Compiled) on depth 5 completed for library in 0.31 ms.
Analysis of email.errors (Stub) on depth 8 completed in 1.45 ms.
Analysis of queue (Stub) on depth 6 completed in 1.88 ms.
Analysis of _sha1 (Compiled) on depth 5 completed for library in 0.22 ms.
Analysis of _sha256 (Compiled) on depth 5 completed for library in 4 ms.
Analysis of _sha512 (Compiled) on depth 5 completed for library in 0.26 ms.
Analysis of _blake2 (Compiled) on depth 5 completed for library in 1.58 ms.
Analysis of _hashlib (Compiled) on depth 5 completed for library in 9.16 ms.
Analysis of _bisect (Stub) on depth 6 completed in 0.66 ms.
Analysis of html.entities (Stub) on depth 9 completed in 0.22 ms.
Analysis of _sha3 (Compiled) on depth 5 completed for library in 26.7 ms.
Analysis of _ssl (Compiled) on depth 9 completed for library in 41.15 ms.
Analysis of xmlrpc (Library) on depth 6 completed for library in 0.08 ms.
Analysis of _multiprocessing (Compiled) on depth 6 completed for library in 5.26 ms.
Analysis of quopri (Stub) on depth 8 completed in 0.41 ms.
Analysis of _queue (Compiled) on depth 7 completed for library in 2 ms.
Analysis of _decimal (Compiled) on depth 8 completed for library in 36.02 ms.
Analysis of _contextvars (Compiled) on depth 10 completed for library in 0.3 ms.
Analysis of atexit (CompiledBuiltin) on depth 2 completed for library in 2.94 ms.
Analysis of _heapq (Compiled) on depth 4 completed for library in 0.7 ms.
Analysis of _thread (CompiledBuiltin) on depth 3 completed for library in 1.48 ms.
Analysis of itertools (CompiledBuiltin) on depth 3 completed for library in 41.53 ms.
Analysis of gc (CompiledBuiltin) on depth 3 completed for library in 1.96 ms.
Analysis of distutils.errors (Library) on depth 2 completed for library in 50.16 ms.
Analysis of sre_parse (Stub) on depth 3 completed in 7.65 ms.
Analysis of pwd (CompiledBuiltin) on depth 2 completed for library in 12.54 ms.
Analysis of distutils.sysconfig (Stub) on depth 3 completed in 0.68 ms.
Analysis of _warnings (CompiledBuiltin) on depth 2 completed for library in 1.78 ms.
Analysis of sre_constants (Library) on depth 2 completed for library in 17.43 ms.
Analysis of marshal (CompiledBuiltin) on depth 4 completed for library in 10.34 ms.
Analysis of _posixsubprocess (Compiled) on depth 3 completed for library in 0.18 ms.
Analysis of urllib (Library) on depth 6 completed for library in 0.03 ms.
Analysis of lib2to3 (Library) on depth 3 completed for library in 0.07 ms.
Analysis of _stat (CompiledBuiltin) on depth 3 completed for library in 35.09 ms.
Analysis of unicodedata (Compiled) on depth 7 completed for library in 9.75 ms.
Analysis of email.header (Stub) on depth 8 completed in 1.21 ms.
Analysis of _tracemalloc (CompiledBuiltin) on depth 3 completed for library in 13.29 ms.
Analysis of grp (Compiled) on depth 4 completed for library in 5.28 ms.
Analysis of modules loop on depth 2 in 169.65 ms:
Analysis of termios (Compiled) on depth 7 completed for library in 73.49 ms.
    importlib.abc(Stub)
    _importlib_modulespec(Stub)
    codecs(Stub)
    os(Stub)
    os.path(Stub)
    sys(Stub)
    types(Stub)
    io(Stub)
    mmap(Stub)
Analysis of email.errors (Library) on depth 7 completed for library in 70.18 ms.
Analysis of multiprocessing.queues (Stub) on depth 5 completed in 2.44 ms.
Analysis of _bisect (Compiled) on depth 5 completed for library in 0.17 ms.
Analysis of multiprocessing.dummy.connection (Stub) on depth 8 completed in 1.76 ms.
Analysis of contextvars (Library) on depth 9 completed for library in 3.89 ms.
Analysis of platform (Stub) on depth 2 completed in 1.05 ms.
Analysis of tty (Library) on depth 6 completed for library in 5.68 ms.
Analysis of encodings (Stub) on depth 5 completed in 7.7 ms.
Analysis of html.entities (Library) on depth 8 completed for library in 50.89 ms.
Analysis of ctypes (Stub) on depth 2 completed in 63.12 ms.
Analysis of __future__ (Stub) on depth 2 completed in 0.59 ms.
Analysis of token (Stub) on depth 4 completed in 2.11 ms.
Analysis of pickle (Stub) on depth 3 completed in 10.68 ms.
Analysis of array (Stub) on depth 4 completed in 10.73 ms.
Analysis of _weakref (Stub) on depth 4 completed in 1.3 ms.
Analysis of functools (Stub) on depth 3 completed in 8.16 ms.
Analysis of pprint (Stub) on depth 3 completed in 1.12 ms.
Analysis of ntpath (Stub) on depth 3 completed in 6.75 ms.
Analysis of heapq (Stub) on depth 4 completed in 0.87 ms.
Analysis of linecache (Stub) on depth 3 completed in 0.9 ms.
Analysis of _codecs (Stub) on depth 5 completed in 5.47 ms.
Analysis of stat (Stub) on depth 3 completed in 0.63 ms.
Analysis of enum (Stub) on depth 3 completed in 12.33 ms.
Analysis of posixpath (Stub) on depth 3 completed in 14.7 ms.
Analysis of pdb (Stub) on depth 5 completed in 0.58 ms.
Analysis of locale (Stub) on depth 4 completed in 2.42 ms.
Analysis of select (Stub) on depth 4 completed in 2.76 ms.
Analysis of sre_compile (Stub) on depth 3 completed in 0.56 ms.
Analysis of argparse (Stub) on depth 4 completed in 25.52 ms.
Analysis of errno (Stub) on depth 4 completed in 10.56 ms.
Analysis of math (Stub) on depth 5 completed in 2.94 ms.
Analysis of difflib (Stub) on depth 5 completed in 2.92 ms.
Analysis of opcode (Stub) on depth 7 completed in 1.57 ms.
Analysis of _ast (Stub) on depth 7 completed in 34.11 ms.
Analysis of pyexpat.errors (Stub) on depth 5 completed in 0.34 ms.
Analysis of glob (Stub) on depth 6 completed in 0.47 ms.
Analysis of binascii (Stub) on depth 4 completed in 1.4 ms.
Analysis of shlex (Stub) on depth 6 completed in 3.6 ms.
Analysis of readline (Stub) on depth 6 completed in 2.79 ms.
Analysis of py_compile (Stub) on depth 3 completed in 5.4 ms.
Analysis of pkgutil (Stub) on depth 4 completed in 1.41 ms.
Analysis of operator (Stub) on depth 4 completed in 11.42 ms.
Analysis of lib2to3.pgen2 (Stub) on depth 4 completed in 0.28 ms.
Analysis of lib2to3.pgen2.token (Stub) on depth 4 completed in 1.4 ms.
Analysis of tracemalloc (Stub) on depth 3 completed in 2.81 ms.
Analysis of _random (Stub) on depth 5 completed in 0.76 ms.
Analysis of shutil (Stub) on depth 4 completed in 4.32 ms.
Analysis of urllib.parse (Stub) on depth 7 completed in 5.91 ms.
Analysis of base64 (Stub) on depth 8 completed in 1.22 ms.
Analysis of zlib (Stub) on depth 5 completed in 1.75 ms.
Analysis of hashlib (Stub) on depth 5 completed in 2.38 ms.
Analysis of webbrowser (Stub) on depth 7 completed in 6.44 ms.
Analysis of numbers (Stub) on depth 10 completed in 2.1 ms.
Analysis of uu (Stub) on depth 8 completed in 0.81 ms.
Analysis of mimetypes (Stub) on depth 8 completed in 2 ms.
Analysis of optparse (Stub) on depth 9 completed in 22.13 ms.
Analysis of modules loop on depth 7 in 24.54 ms:
    email.message(Stub)
    email.policy(Stub)
    email.contentmanager(Stub)
Analysis of time (Stub) on depth 3 completed in 2.63 ms.
Analysis of threading (Stub) on depth 3 completed in 9.02 ms.
Analysis of contextlib (Stub) on depth 4 completed in 12.11 ms.
Analysis of code (Stub) on depth 6 completed in 1.91 ms.
Analysis of codeop (Stub) on depth 7 completed in 0.54 ms.
Analysis of traceback (Stub) on depth 3 completed in 2.97 ms.
Analysis of warnings (Stub) on depth 2 completed in 5.87 ms.
Analysis of tempfile (Stub) on depth 3 completed in 1.47 ms.
Analysis of inspect (Stub) on depth 5 completed in 9.77 ms.
Analysis of modules loop on depth 3 in 25.67 ms:
    collections.abc(Stub)
    collections(Stub)
Analysis of subprocess (Stub) on depth 3 completed in 12.25 ms.
Analysis of zipimport (Stub) on depth 5 completed in 1.03 ms.
Analysis of hmac (Stub) on depth 7 completed in 3.05 ms.
Analysis of zipfile (Stub) on depth 5 completed in 2.9 ms.
Analysis of bz2 (Stub) on depth 5 completed in 0.75 ms.
Analysis of tarfile (Stub) on depth 5 completed in 8.01 ms.
Analysis of _compression (Stub) on depth 6 completed in 0.78 ms.
Analysis of lzma (Stub) on depth 5 completed in 8.73 ms.
Analysis of modules loop on depth 2 in 10 ms:
    importlib.machinery(Stub)
    importlib(Stub)
    importlib.util(Stub)
Analysis of bisect (Library) on depth 4 completed for library in 0.85 ms.
Analysis of __future__ (Library) on depth 1 completed for library in 17.15 ms.
Analysis of tokenize (Stub) on depth 3 completed in 2.14 ms.
Analysis of mmap (Compiled) on depth 7 completed for library in 21.3 ms.
Analysis of struct (Stub) on depth 3 completed in 1.33 ms.
Analysis of reprlib (Stub) on depth 4 completed in 1.36 ms.
Analysis of array (Compiled) on depth 6 completed for library in 11.36 ms.
Analysis of weakref (Stub) on depth 3 completed in 16.23 ms.
Analysis of _weakref (CompiledBuiltin) on depth 3 completed for library in 0.37 ms.
Analysis of _codecs (CompiledBuiltin) on depth 4 completed for library in 1.26 ms.
Analysis of signal (Stub) on depth 4 completed in 6.53 ms.
Analysis of stat (Library) on depth 2 completed for library in 15.48 ms.
Analysis of re (Stub) on depth 2 completed in 15.13 ms.
Analysis of plistlib (Stub) on depth 3 completed in 4.51 ms.
Analysis of http (Stub) on depth 7 completed in 5.22 ms.
Analysis of socket (Stub) on depth 3 completed in 20.62 ms.
Analysis of select (Compiled) on depth 3 completed for library in 37.2 ms.
Analysis of math (Compiled) on depth 4 completed for library in 10.84 ms.
Analysis of errno (CompiledBuiltin) on depth 3 completed for library in 27.57 ms.
Analysis of opcode (Library) on depth 6 completed for library in 1.79 ms.
Analysis of ast (Stub) on depth 6 completed in 4.01 ms.
Analysis of dis (Stub) on depth 6 completed in 4.33 ms.
Analysis of pyexpat (Stub) on depth 5 completed in 1.84 ms.
Analysis of binascii (Compiled) on depth 3 completed for library in 15.01 ms.
Analysis of _operator (Stub) on depth 5 completed in 0.45 ms.
Analysis of readline (Compiled) on depth 5 completed for library in 0.77 ms.
Analysis of lib2to3.pgen2 (Library) on depth 3 completed for library in 2.54 ms.
Analysis of lib2to3.pgen2.tokenize (Stub) on depth 4 completed in 2.63 ms.
Analysis of lib2to3.pgen2.grammar (Stub) on depth 5 completed in 39.46 ms.
Analysis of lib2to3.pgen2.token (Library) on depth 3 completed for library in 80.22 ms.
Analysis of random (Stub) on depth 4 completed in 95.64 ms.
Analysis of _random (Compiled) on depth 4 completed for library in 1.77 ms.
Analysis of zlib (Compiled) on depth 4 completed for library in 3.59 ms.
Analysis of email.iterators (Stub) on depth 8 completed in 21.06 ms.
Analysis of email.encoders (Stub) on depth 9 completed in 0.62 ms.
Analysis of email (Stub) on depth 7 completed in 5.66 ms.
Analysis of email.feedparser (Stub) on depth 9 completed in 8.06 ms.
Analysis of email.generator (Stub) on depth 8 completed in 5.85 ms.
Analysis of time (CompiledBuiltin) on depth 2 completed for library in 12.61 ms.
Analysis of datetime (Stub) on depth 4 completed in 27.81 ms.
Analysis of multiprocessing.managers (Stub) on depth 5 completed in 7.86 ms.
Analysis of zipimport (CompiledBuiltin) on depth 4 completed for library in 14.43 ms.
Analysis of _imp (Stub) on depth 3 completed in 3.17 ms.
Analysis of logging (Stub) on depth 2 completed in 29.64 ms.
Analysis of gzip (Stub) on depth 6 completed in 2.08 ms.
Analysis of codeop (Library) on depth 6 completed for library in 14.91 ms.
Analysis of _threading_local (Stub) on depth 4 completed in 3.64 ms.
Analysis of multiprocessing.dummy (Stub) on depth 7 completed in 2.38 ms.
Analysis of modules loop on depth 2 in 16.9 ms:
    struct(Library)
    _struct(Library)
Analysis of _weakrefset (Library) on depth 3 completed for library in 23.35 ms.
Analysis of reprlib (Library) on depth 3 completed for library in 10.88 ms.
Analysis of _ast (CompiledBuiltin) on depth 6 completed for library in 267.65 ms.
Analysis of multiprocessing.connection (Stub) on depth 5 completed in 8.21 ms.
Analysis of xml.parsers.expat (Stub) on depth 4 completed in 3.93 ms.
Analysis of selectors (Stub) on depth 4 completed in 9.12 ms.
Analysis of lib2to3.pytree (Stub) on depth 4 completed in 7.74 ms.
Analysis of socketserver (Stub) on depth 8 completed in 12.78 ms.
Analysis of lib2to3.pygram (Stub) on depth 4 completed in 1.16 ms.
Analysis of ssl (Stub) on depth 9 completed in 12.77 ms.
Analysis of lib2to3.pgen2.pgen (Stub) on depth 5 completed in 4.26 ms.
Analysis of pyexpat (Compiled) on depth 4 completed for library in 6.11 ms.
Analysis of calendar (Stub) on depth 6 completed in 8.9 ms.
Analysis of _imp (CompiledBuiltin) on depth 2 completed for library in 0.48 ms.
Analysis of imp (Stub) on depth 2 completed in 1.67 ms.
Analysis of email.parser (Stub) on depth 8 completed in 10.18 ms.
Analysis of email.utils (Stub) on depth 8 completed in 0.82 ms.
Analysis of email.headerregistry (Stub) on depth 9 completed in 1.91 ms.
Analysis of unittest (Stub) on depth 5 completed in 23.53 ms.
Analysis of lib2to3.pgen2.driver (Stub) on depth 4 completed in 4.46 ms.
Analysis of lib2to3.pgen2.parse (Stub) on depth 5 completed in 0.88 ms.
Analysis of http.server (Stub) on depth 7 completed in 4.09 ms.
Analysis of modules loop on depth 4 in 10.3 ms:
Analysis of modules loop on depth 8 in 0.47 ms:
    xml.parsers(Stub)
    xml(Stub)
    multiprocessing(Stub)
    multiprocessing.synchronize(Stub)
    multiprocessing.context(Stub)
    multiprocessing.process(Stub)
Analysis of _py_abc (Library) on depth 3 completed for library in 22.34 ms.
Analysis of http.client (Stub) on depth 8 completed in 15.04 ms.
Analysis of xml.parsers (Library) on depth 7 completed for library in 0.05 ms.
Analysis of lib2to3.pgen2.parse (Library) on depth 4 completed for library in 0.89 ms.
Analysis of doctest (Stub) on depth 4 completed in 8.41 ms.
Analysis of abc (Library) on depth 2 completed for library in 8.91 ms.
Analysis of numbers (Library) on depth 9 completed for library in 8.88 ms.
Analysis of modules loop on depth 2 in 31.22 ms:
    io(Library)
    _io(Library)
Analysis of _compression (Library) on depth 5 completed for library in 9.53 ms.
Analysis of modules loop on depth 1 in 1915.88 ms:
    importlib.machinery(Library)
    platform(Library)
    re(Library)
    sys(Library)
    warnings(Library)
    importlib._bootstrap_external(Library)
    importlib(Library)
    importlib.util(Library)
    subprocess(Library)
    tempfile(Library)
    py_compile(Library)
    tokenize(Library)
    _collections_abc(Library)
    collections.abc(Library)
    importlib.abc(Library)
    contextlib(Library)
    token(Library)
    argparse(Library)
    fnmatch(Library)
    pprint(Library)
    operator(Library)
    keyword(Library)
    linecache(Library)
    difflib(Library)
    inspect(Library)
    pdb(Library)
    unittest(Library)
    unittest.result(Library)
    encodings.mbcs(Library)
    plistlib(Library)
    socket(Library)
    signal(Library)
    _signal(Library)
    enum(Library)
    unittest.util(Library)
    gettext(Library)
    textwrap(Library)
    sre_compile(Library)
    sre_parse(Library)
    _locale(Library)
    selectors(Library)
    cmd(Library)
    bdb(Library)
    dis(Library)
    code(Library)
    glob(Library)
    shlex(Library)
    runpy(Library)
    pydoc(Library)
    getopt(Library)
    locale(Library)
    datetime(Library)
    xml.parsers.expat(Library)
    _bootlocale(Library)
    ast(Library)
    pkgutil(Library)
    tracemalloc(Library)
    shutil(Library)
    random(Library)
    _operator(Library)
    urllib.parse(Library)
    http(Library)
    http.server(Library)
    email(Library)
    email.message(Library)
    webbrowser(Library)
    hashlib(Library)
    _strptime(Library)
    _datetime(Library)
    bz2(Library)
    lzma(Library)
    tarfile(Library)
    zipfile(Library)
    email.utils(Library)
    html(Library)
    http.client(Library)
    mimetypes(Library)
    socketserver(Library)
    base64(Library)
    email.parser(Library)
    ssl(Library)
    email._parseaddr(Library)
    email.charset(Library)
    uu(Library)
    quopri(Library)
    email._policybase(Library)
    email._encoded_words(Library)
    email.generator(Library)
    email.iterators(Library)
    email.policy(Library)
    calendar(Library)
    email.feedparser(Library)
    gzip(Library)
    optparse(Library)
    email.base64mime(Library)
    email.quoprimime(Library)
    email.encoders(Library)
    email.headerregistry(Library)
    email.contentmanager(Library)
    email.header(Library)
    email._header_value_parser(Library)
    doctest(Library)
    string(Library)
    pickle(Library)
    posixpath(Library)
    unittest.case(Library)
    unittest.loader(Library)
    logging(Library)
    os(Library)
    types(Library)
    traceback(Library)
    weakref(Library)
    collections(Library)
    threading(Library)
    codecs(Library)
    ntpath(Library)
    encodings(Library)
    unittest.suite(Library)
    unittest.main(Library)
    unittest.runner(Library)
    functools(Library)
    _threading_local(Library)
    posix(Library)
    genericpath(Library)
    copy(Library)
    heapq(Library)
    unittest.signals(Library)
    _collections(Library)
    _functools(Library)
Analysis of lib2to3.pgen2.literals (Library) on depth 5 completed for library in 0.22 ms.
Analysis of distutils (Library) on depth 1 completed for library in 0.09 ms.
Analysis of distutils.log (Library) on depth 2 completed for library in 1.2 ms.
Analysis of distutils.text_file (Library) on depth 3 completed for library in 9.38 ms.
Analysis of distutils.dep_util (Library) on depth 2 completed for library in 0.4 ms.
Analysis of hmac (Library) on depth 6 completed for library in 12.67 ms.
Analysis of imp (Library) on depth 1 completed for library in 16.19 ms.
Analysis of lib2to3.pgen2.grammar (Library) on depth 4 completed for library in 1.6 ms.
Analysis of distutils.debug (Library) on depth 3 completed for library in 12.23 ms.
Analysis of modules loop on depth 1 in 44.05 ms:
    ctypes(Library)
    ctypes._endian(Library)
Analysis of _pydecimal (Library) on depth 8 completed for library in 130.38 ms.
Analysis of queue (Library) on depth 6 completed for library in 8.89 ms.
Analysis of distutils.file_util (Library) on depth 2 completed for library in 13.28 ms.
Analysis of _osx_support (Library) on depth 2 completed for library in 16.74 ms.
Analysis of multiprocessing.dummy.connection (Library) on depth 7 completed for library in 1.98 ms.
Analysis of lib2to3.pgen2.tokenize (Library) on depth 3 completed for library in 32.78 ms.
Analysis of sysconfig (Library) on depth 1 completed for library in 22.41 ms.
Analysis of distutils.dir_util (Library) on depth 2 completed for library in 0.77 ms.
Analysis of lib2to3.pgen2.pgen (Library) on depth 4 completed for library in 4.21 ms.
Analysis of distutils.sysconfig (Library) on depth 2 completed for library in 12.65 ms.
Analysis of lib2to3.pgen2.driver (Library) on depth 3 completed for library in 2.9 ms.
Analysis of distutils.spawn (Library) on depth 2 completed for library in 1.25 ms.
Analysis of modules loop on depth 3 in 17.38 ms:
    lib2to3.pytree(Library)
    lib2to3.pygram(Library)
Analysis of lib2to3.patcomp (Library) on depth 4 completed for library in 5.92 ms.
Analysis of lib2to3.btm_utils (Library) on depth 4 completed for library in 14.14 ms.
Analysis of lib2to3.btm_matcher (Library) on depth 3 completed for library in 5.1 ms.
Analysis of lib2to3.fixer_util (Library) on depth 3 completed for library in 14.67 ms.
Analysis of decimal (Library) on depth 7 completed for library in 93.62 ms.
Analysis of xmlrpc.client (Library) on depth 6 completed for library in 30.36 ms.
Analysis of modules loop on depth 3 in 197.19 ms:
    multiprocessing(Library)
    multiprocessing.context(Library)
    multiprocessing.process(Library)
    multiprocessing.reduction(Library)
    multiprocessing.managers(Library)
    multiprocessing.connection(Library)
    multiprocessing.synchronize(Library)
    multiprocessing.queues(Library)
    multiprocessing.pool(Library)
    multiprocessing.sharedctypes(Library)
    multiprocessing.spawn(Library)
    multiprocessing.util(Library)
    multiprocessing.forkserver(Library)
    multiprocessing.popen_fork(Library)
    multiprocessing.popen_spawn_posix(Library)
    multiprocessing.popen_forkserver(Library)
    multiprocessing.popen_spawn_win32(Library)
    multiprocessing.resource_sharer(Library)
    multiprocessing.dummy(Library)
    multiprocessing.heap(Library)
    multiprocessing.semaphore_tracker(Library)
Analysis of lib2to3.refactor (Library) on depth 2 completed for library in 17.91 ms.
Analysis of modules loop on depth 1 in 10.4 ms:
    distutils.util(Library)
    distutils.filelist(Library)
Analysis of packaging.tags (User) on depth 0 completed in 25 ms.
Analysis complete: 468 modules in 10097.91 ms.
Analysis version 773 of 465 entries has been completed in 3706.99 ms.

```

</details>

## Code Snippet / Additional lnformation

https://github.com/pypa/packaging/blob/bb80ca79069f29deb771697b8305deac54295be0/packaging/tags.py#L326

image

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1775.

Try and while blocks were being walked twice, producing double diagnostics for code inside, as well as a likely performance hit from doing the same thing twice.

Need to run some more tests to make sure this isn't a regression (since I'm effectively removing a whole lot of walking on very common syntactic blocks).

### CODE REVIEW

**Comment by jakebailey** [comment]
Everything passes, completion looks the same as master, so this is probably fine, but certainly weird that we were double walking.

Perf comparison was inconclusive, at least with analysis time.

File: src/Analysis/Ast/Impl/Analyzer/AnalysisWalker.cs [hunk 1]
```diff
@@ -85,18 +85,12 @@ internal abstract class AnalysisWalker : PythonWalker {
         public override bool Walk(ImportStatement node) => ImportHandler.HandleImport(node);
         public override bool Walk(NonlocalStatement node) => NonLocalHandler.HandleNonLocal(node);
 
-        public override bool Walk(TryStatement node) {
-            TryExceptHandler.HandleTryExcept(node);
-            return base.Walk(node);
-        }
+        public override bool Walk(TryStatement node) => TryExceptHandler.HandleTryExcept(node);
```
Comment (bschnurr) [inline src/Analysis/Ast/Impl/Analyzer/AnalysisWalker.cs]: is there anyway to guard against double walking in the future?

Comment (jakebailey) [reply src/Analysis/Ast/Impl/Analyzer/AnalysisWalker.cs]: I'm not sure. Multiple walkers may be created and walk the same code, but perhaps AnalysisWalker should only ever see each node once...

Comment (bschnurr) [reply src/Analysis/Ast/Impl/Analyzer/AnalysisWalker.cs]: Maybe we could write a Test that creates a new type of Node for testing, which tracks counts calls to it's walk() function?
