### PR TITLE
Fix max length of short descriptions and tuple names

### LINKED ISSUE #50: RecursiveTuples test fails

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #50

- Recursive tuples analysis produced huge description string. Limit that.
- Reduce number of stored types (we don't really need to store various combinations of arguments and return types at all, but that's a different issue).

### CODE REVIEW

File: src/Analysis/Engine/Impl/AnalysisValue.cs [hunk 1]
```diff
@@ -67,23 +71,25 @@ public class AnalysisValue : IAnalysisValueOperations {
...
         public virtual string ShortDescription {
             get {
-                var hrd = this as IHasRichDescription;
-                if (hrd != null) {
-                    return string.Join("", hrd.GetRichDescription().TakeWhile(kv => kv.Key != WellKnownRichDescriptionKinds.EndOfDeclaration).Select(kv => kv.Value));
+                if (string.IsNullOrEmpty(_shortDescription) && this is IHasRichDescription hrd) {
+                    var sb = new StringBuilder();
+                    foreach (var item in hrd.GetRichDescription().TakeWhile(kv => kv.Key != WellKnownRichDescriptionKinds.EndOfDeclaration).Select(kv => kv.Value)) {
+                        if (sb.Length >= MaxShortDescriptionLength) {
+                            sb.Append("...");
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/AnalysisValue.cs]: Is it better than unicode ellipsis (https://www.fileformat.info/info/unicode/char/2026/index.htm)?

Comment (jakebailey) [reply src/Analysis/Engine/Impl/AnalysisValue.cs]: IMO probably, since it's also the same string for Python's ellipsis, and clients will typically render `...` how they see fit depending on the context (though in our case, this will come out to be monospaced).

Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/AnalysisValue.cs]: Existing code just does plain string - I think because doc text from Python uses plain string as well so appearance of `...` in tooltips etc will be consistent since otherwise some`...` will be different from others in UI appearance.

**Comment by jakebailey** [comment]
Do you have any tests for this new character limiting behavior? (Other than uncommenting the broken one.)

**Comment by jakebailey** [comment]
Though it may not matter since we're going to be changing some of this "protocol" stuff in the future anyway...

**Comment by MikhailArkhipov** [comment]
@jakebailey - I am planning to add the test in the upcoming PR for #347 since that PR will change the description text anyway.
