### PR TITLE
Fix matmul operator parsing

### LINKED ISSUE #1825: Failed parsing matmul operator
## Environment data

- Language Server version: 0.4.127.0
- OS and version: macOS 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.0

## Expected behaviour

Parser should be able to parse this code:

```python
a = (
    A
    @ B
)
```

## Actual behaviour

It causes parser error `unexpected token '<newline>'` at end of 2nd line.

Note that this happened only with `@` operator. (No parse error with `+` or `*` instead of `@`.)

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #1825

### CODE REVIEW

File: src/Parsing/Test/ParserTests.cs [hunk 1]
```diff
@@ -4445,6 +4463,8 @@ public class ParserTests {
             };
         }
 
+
```
Comment (jakebailey) [inline src/Parsing/Test/ParserTests.cs]: Nit, but weird whitespace added here.

File: src/Parsing/Impl/Parser.cs [hunk 2]
```diff
@@ -2986,7 +2986,6 @@ struct Name {
                 if (!(t is OperatorToken ot)) {
                     return ret;
                 }
-
```
Comment (jakebailey) [inline src/Parsing/Impl/Parser.cs]: Another nit, but the only change to this file is whitespace.

**Comment by MikhailArkhipov** [comment]
0.5.30+
