### PR TITLE
Fix caching of compiled modules, analysis hang

### LINKED ISSUE #1601: "Analyzing in background" message stuck with caching enabled (deadlock, no CPU usage)
## Environment data

- Language Server version: 0.4.24.0
- OS and version: Windows 10 1903 (18362.356)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3

## Expected behaviour

Python Language Server shouldn't get stuck analyzing files.

## Actual behaviour

After a random amount of time using PLS (e.g. after anywhere from 0 minutes to several days), Visual Studio Code gets stuck "Analyzing in background...".  The number of items is frequently small, but not always.

## Logs

See attached.  This is a log from several days, so that I could capture the issue
[analyzing - stuck.txt](https://github.com/microsoft/python-language-server/files/3668800/analyzing.-.stuck.txt)

## Additional

This repository is from https://github.com/xobs/haddecks

My local `settings.json` file looks like this:

```json
{
    "python.autoComplete.extraPaths": [
        "deps/litedram",
        "deps/litescope",
        "deps/litex",
        "deps/litex_boards",
        "deps/lxsocdoc",
        "deps/migen",
        "deps/spibone",
        "deps/valentyusb"
    ],
    "python.jediEnabled": false,
    "python.analysis.logLevel": "Trace"
}
```

There is no .env file present.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1601.

This fixes a number of things which when combined broke caching of compiled builtins on non-Windows platforms.

On lookup, the module type was hardcoded to "specialized". The module type is involved in calculating the unique name for a module, so depending on what module is being looked up, the wrong ID would be calculated. (Worse, an unexpected code path would be taken for a module, causing unhandled exceptions, something to work on later.) Now, pass the module type down when looking up a module so that the unique ID is always calculated with the same inputs.

`IsCompiled` is no longer used for checking builtins when calculating the unique name, just `ModuleType.CompiledBuiltin`. This would cause issues for top-level compiled files that weren't actually a part of the distribution.

The module cache no longer holds a lock when dealing with dependencies. The lock could have possibly caused a deadlock (partially fixed in #1713), and I do not believe that it is required because of the analysis ordering.

Why did this affect "compiled builtins"? Compiled builtins (like `_functools` or `_weakref`) are special in that they do not have any on-disk location. We must construct a fake filename in order to use later for producing scraper output file names and other calculation. Some checks rely on a file path and have to special case these compiled builtins, which means there's more bug surface.

### CODE REVIEW

**Comment by jakebailey** [comment]
This will conflict with #1686, and after it and this are merged the DB version will have to be upped (since the most recent changes are pretty impactful).

**Comment by jakebailey** [comment]
The reason for the hang is the unhandled exception I mention above. The crash happens when the parsing task in PythonModule finishes parsing and submits the AST to the analyzer via `EnqueueDocumentForAnalysis`. An exception is thrown, but because the parsing task is its own thing (see `PythonModule.Parse`'s use of `Task.Run`), the exception disappears into the void. I'm not a .NET tasking expert, so it'd be good to return to this part of the code to see if it can either be instrumented better, or run in a more reasonable context.

File: src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs [hunk 1]
```diff
@@ -84,8 +84,13 @@ public MainModuleResolution(string root, IServiceContainer services, ImmutableAr
                 }
             }
 
+            var moduleType = moduleImport.IsBuiltin ? ModuleType.CompiledBuiltin
+                : moduleImport.IsCompiled ? ModuleType.CompiledBuiltin
```
Comment (jakebailey) [inline src/Analysis/Ast/Impl/Modules/Resolution/MainModuleResolution.cs]: Oversight here. Should be Compiled.

**Comment by MikhailArkhipov** [comment]
👍 Found the same issue with hashing while working on #1728, but didn't strike me as related to #1601.

**Comment by jakebailey** [comment]
Going to merge #1686 first and then fix up this PR to match the new calls. Should be easier than trying to solve the conflicts the other way around.

**Comment by jakebailey** [comment]
This isn't playing nice with #1686 merged. With `import _functools` and caching enabled, it keeps looping forever.

**Comment by jakebailey** [comment]
Bumping the version stops the looping forever (some bad state? but I deleted my stored analysis...), but:

```
[Info  - 10:51:30 AM] Analysis cache path: /home/jake/.cache/Microsoft/Python Language Server
[Info  - 10:51:30 AM] Microsoft Python Language Server version 1.0.0.0
[Info  - 10:51:30 AM] Workspace root: /home/jake/work/issue1601
[Info  - 10:51:30 AM] GetCurrentSearchPaths /home/jake/work/issue1601/venv/bin/python3 
[Info  - 10:51:30 AM] Interpreter search paths:
[Info  - 10:51:30 AM]     /usr/lib/python3.7
[Info  - 10:51:30 AM]     /usr/lib/python3.7/lib-dynload
[Info  - 10:51:30 AM]     /home/jake/work/issue1601/venv/lib/python3.7/site-packages
[Info  - 10:51:30 AM] User search paths:
[Info  - 10:51:32 AM] Initializing for /home/jake/work/issue1601/venv/bin/python3
Watching /usr/lib/python3.7
Watching /home/jake/work/issue1601/venv/lib/python3.7/site-packages
[Info  - 10:51:33 AM] Analysis caching mode: System.
Opening document file:///home/jake/work/issue1601/main.py
Analysis of main (User) queued. Dependencies: functools
Import:  functools /usr/lib/python3.7/functools.py 
Analysis version 2 of 1 entries has started.
Analysis of main (User) on depth 0 completed in 1.36 ms.
Missing keys: functools(/usr/lib/python3.7/functools.py)
Analysis version 2 of 1 entries has been completed in 4.34 ms.
Analysis of functools (Library) queued. Dependencies: types, weakref, _functools, abc, collections, reprlib, _thread
Import:  types /usr/lib/python3.7/types.py 
Import:  weakref /usr/lib/python3.7/weakref.py 
Create built-in compiled (scraped) module:  _functools /home/jake/work/issue1601/venv/bin/python3 
Import:  abc /usr/lib/python3.7/abc.py 
Import:  collections /usr/lib/python3.7/collections/__init__.py 
Import:  reprlib /usr/lib/python3.7/reprlib.py 
Create built-in compiled (scraped) module:  _thread /home/jake/work/issue1601/venv/bin/python3 
Analysis version 4 of 2 entries has started.
Restored from database:  functools 
Analysis of functools (Library) on depth 1 completed in 32.54 ms.
Analysis of main (User) on depth 0 completed in 0.29 ms.
Missing keys: types(/usr/lib/python3.7/types.py), weakref(/usr/lib/python3.7/weakref.py), _functools(), abc(/usr/lib/python3.7/abc.py), collections(/usr/lib/python3.7/collections/__init__.py), reprlib(/usr/lib/python3.7/reprlib.py), _thread()
Analysis version 4 of 2 entries has been completed in 36.22 ms.
Analysis of _thread (CompiledBuiltin) queued. Dependencies: 
Analysis version 12 of 9 entries has started.
Analysis of abc(Library) canceled (no AST yet).
Analysis of collections(Library) canceled (no AST yet).
Analysis of reprlib(Library) canceled (no AST yet).
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 3.18 ms.
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of weakref(Library) canceled (no AST yet).
Analysis of types(Library) canceled (no AST yet).
Analysis version 12 has been completed in 3.79 ms with 7 entries analyzed and 2 entries skipped.
Analysis of reprlib (Library) queued. Dependencies: itertools, _thread
Create built-in compiled (scraped) module:  itertools /home/jake/work/issue1601/venv/bin/python3 
Analysis version 13 of 9 entries has started.
Analysis of abc(Library) canceled (no AST yet).
Analysis of collections(Library) canceled (no AST yet).
Restored from database:  reprlib 
Analysis of reprlib (Library) on depth 2 completed in 3.94 ms.
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of weakref(Library) canceled (no AST yet).
Analysis of types(Library) canceled (no AST yet).
Analysis version 13 has been completed in 4.52 ms with 6 entries analyzed and 3 entries skipped.
Analysis of itertools (CompiledBuiltin) queued. Dependencies: 
Analysis version 15 of 10 entries has started.
Analysis of abc(Library) canceled (no AST yet).
Analysis of collections(Library) canceled (no AST yet).
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 51.9 ms.
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of weakref(Library) canceled (no AST yet).
Analysis of types(Library) canceled (no AST yet).
Analysis version 15 has been completed in 52.85 ms with 6 entries analyzed and 4 entries skipped.
Analysis of collections (Library) queued. Dependencies: _collections_abc, sys, heapq, warnings, copy, operator, keyword, _weakref, itertools, reprlib, _collections
Import:  _collections_abc /usr/lib/python3.7/_collections_abc.py 
Create built-in compiled (scraped) module:  sys /home/jake/work/issue1601/venv/bin/python3 
Import:  heapq /usr/lib/python3.7/heapq.py 
Import:  warnings /usr/lib/python3.7/warnings.py 
Import:  copy /usr/lib/python3.7/copy.py 
Import:  operator /usr/lib/python3.7/operator.py 
Import:  keyword /usr/lib/python3.7/keyword.py 
Create built-in compiled (scraped) module:  _weakref /home/jake/work/issue1601/venv/bin/python3 
Create built-in compiled (scraped) module:  _collections /home/jake/work/issue1601/venv/bin/python3 
Analysis version 16 of 10 entries has started.
Analysis of abc(Library) canceled (no AST yet).
Restored from database:  collections 
Analysis of collections (Library) on depth 2 completed in 30.37 ms.
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of weakref(Library) canceled (no AST yet).
Analysis of types(Library) canceled (no AST yet).
Analysis version 16 has been completed in 31.11 ms with 5 entries analyzed and 5 entries skipped.
Analysis of _collections (CompiledBuiltin) queued. Dependencies: collections
Analysis version 26 of 19 entries has started.
Analysis of abc(Library) canceled (no AST yet).
Analysis of _collections_abc(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of heapq(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of copy(Library) canceled (no AST yet).
Analysis of operator(Library) canceled (no AST yet).
Analysis of keyword(Library) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Restored from database:  collections 
Restored from database:  _collections 
Fully cached modules cycle: collections, _collections
Analysis of _functools (CompiledBuiltin) queued. Dependencies: functools
Restored from database:  _functools 
Analysis of _functools (CompiledBuiltin) on depth 2 completed in 13.28 ms.
Analysis of weakref(Library) canceled (no AST yet).
Analysis of types(Library) canceled (no AST yet).
Analysis version 26 has been completed in 118.23 ms with 14 entries analyzed and 5 entries skipped.
Analysis version 27 of 19 entries has started.
Analysis of copy (Library) queued. Dependencies: types, weakref, copyreg
Import:  copyreg /usr/lib/python3.7/copyreg.py 
Analysis of warnings (Library) queued. Dependencies: sys, linecache, tracemalloc, re, traceback, _warnings
Import:  linecache /usr/lib/python3.7/linecache.py 
Import:  tracemalloc /usr/lib/python3.7/tracemalloc.py 
Import:  re /usr/lib/python3.7/re.py 
Analysis of abc (Library) queued. Dependencies: _abc, _py_abc
Analysis of heapq (Library) queued. Dependencies: doctest, _heapq
Import:  traceback /usr/lib/python3.7/traceback.py 
Create built-in compiled (scraped) module:  _warnings /home/jake/work/issue1601/venv/bin/python3 
Analysis of weakref (Library) queued. Dependencies: _collections_abc, sys, itertools, atexit, gc, _weakref, _weakrefset, copy
Create built-in compiled (scraped) module:  _abc /home/jake/work/issue1601/venv/bin/python3 
Import:  _py_abc /usr/lib/python3.7/_py_abc.py 
Import:  doctest /usr/lib/python3.7/doctest.py 
Analysis of copyreg (Library) queued. Dependencies: 
Analysis of _warnings (CompiledBuiltin) queued. Dependencies: 
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 84.05 ms.
Create compiled (scraped):  _heapq /usr/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of _collections_abc(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Create built-in compiled (scraped) module:  atexit /home/jake/work/issue1601/venv/bin/python3 
Create built-in compiled (scraped) module:  gc /home/jake/work/issue1601/venv/bin/python3 
Import:  _weakrefset /usr/lib/python3.7/_weakrefset.py 
Analysis of types (Library) queued. Dependencies: sys, functools, _collections_abc
Analysis of linecache (Library) queued. Dependencies: functools, sys, os, tokenize
Analysis of _weakrefset (Library) queued. Dependencies: _weakref
Import:  os /usr/lib/python3.7/os.py 
Import:  tokenize /usr/lib/python3.7/tokenize.py 
Analysis of _abc (CompiledBuiltin) queued. Dependencies: 
Analysis of _collections_abc (Library) queued. Dependencies: sys, abc
Restored from database:  heapq 
Analysis of heapq (Library) on depth 3 completed in 35.43 ms.
Analysis of operator (Library) queued. Dependencies: functools, _operator
Create built-in compiled (scraped) module:  _operator /home/jake/work/issue1601/venv/bin/python3 
Analysis of gc (CompiledBuiltin) queued. Dependencies: 
Analysis of _py_abc (Library) queued. Dependencies: _weakrefset
Analysis of tracemalloc (Library) queued. Dependencies: fnmatch, linecache, os, pickle, collections.abc, functools, _tracemalloc
Analysis of _heapq (Compiled) queued. Dependencies: 
Analysis of atexit (CompiledBuiltin) queued. Dependencies: 
Import:  fnmatch /usr/lib/python3.7/fnmatch.py 
Import:  pickle /usr/lib/python3.7/pickle.py 
Import:  collections.abc /usr/lib/python3.7/collections/abc.py 
Create built-in compiled (scraped) module:  _tracemalloc /home/jake/work/issue1601/venv/bin/python3 
Analysis of _tracemalloc (CompiledBuiltin) queued. Dependencies: 
Analysis of sys (CompiledBuiltin) queued. Dependencies: _io, types
Create built-in compiled (scraped) module:  _io /home/jake/work/issue1601/venv/bin/python3 
Analysis of collections.abc (Library) queued. Dependencies: _collections_abc
Analysis of tokenize (Library) queued. Dependencies: collections, itertools, re, sys, token, argparse, codecs, io
Analysis of traceback (Library) queued. Dependencies: collections, itertools, linecache, sys
Analysis of fnmatch (Library) queued. Dependencies: os, posixpath, re, functools
Analysis of _operator (CompiledBuiltin) queued. Dependencies: operator
Restored from database:  warnings 
Import:  token /usr/lib/python3.7/token.py 
Import:  argparse /usr/lib/python3.7/argparse.py 
Import:  codecs /usr/lib/python3.7/codecs.py 
Import:  io /usr/lib/python3.7/io.py 
Analysis of warnings (Library) on depth 3 completed in 175.09 ms.
Analysis of keyword (Library) queued. Dependencies: sys, re
Import:  posixpath /usr/lib/python3.7/posixpath.py 
Analysis of re (Library) queued. Dependencies: enum, sre_compile, sre_parse, functools, _locale, copyreg, sre_constants
Analysis of posixpath (Library) queued. Dependencies: os, sys, stat, genericpath, pwd, re
Import:  enum /usr/lib/python3.7/enum.py 
Import:  sre_compile /usr/lib/python3.7/sre_compile.py 
Import:  sre_parse /usr/lib/python3.7/sre_parse.py 
Create built-in compiled (scraped) module:  _locale /home/jake/work/issue1601/venv/bin/python3 
Import:  sre_constants /usr/lib/python3.7/sre_constants.py 
Import:  stat /usr/lib/python3.7/stat.py 
Analysis of _weakref (CompiledBuiltin) queued. Dependencies: 
Import:  genericpath /usr/lib/python3.7/genericpath.py 
Create built-in compiled (scraped) module:  pwd /home/jake/work/issue1601/venv/bin/python3 
Analysis of io (Library) queued. Dependencies: _io, abc
Restored from database:  copy 
Analysis of copy (Library) on depth 3 completed in 123.4 ms.
Analysis of os (Library) queued. Dependencies: abc, sys, stat, posixpath, posix, ntpath, warnings, subprocess, io, _collections_abc
Create built-in compiled (scraped) module:  posix /home/jake/work/issue1601/venv/bin/python3 
Import:  ntpath /usr/lib/python3.7/ntpath.py 
Import:  subprocess /usr/lib/python3.7/subprocess.py 
Restored from database:  operator 
Analysis of pickle (Library) queued. Dependencies: sys, re, io, codecs, _compat_pickle, doctest, argparse, pprint, types, copyreg, itertools, functools, struct, _pickle
Import:  _compat_pickle /usr/lib/python3.7/_compat_pickle.py 
Import:  pprint /usr/lib/python3.7/pprint.py 
Import:  struct /usr/lib/python3.7/struct.py 
Create compiled (scraped):  _pickle /usr/lib/python3.7/lib-dynload/_pickle.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of _io (CompiledBuiltin) queued. Dependencies: io
Analysis of operator (Library) on depth 3 completed in 49.84 ms.
Analysis of doctest (Library) queued. Dependencies: __future__, difflib, inspect, linecache, os, pdb, re, sys, traceback, unittest, argparse, io, collections
Import:  __future__ /usr/lib/python3.7/__future__.py 
Import:  difflib /usr/lib/python3.7/difflib.py 
Import:  inspect /usr/lib/python3.7/inspect.py 
Import:  pdb /usr/lib/python3.7/pdb.py 
Import:  unittest /usr/lib/python3.7/unittest/__init__.py 
Restored from database:  keyword 
Analysis of keyword (Library) on depth 3 completed in 2.67 ms.
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 3.5 ms.
Restored from database:  collections 
Restored from database:  _collections 
Fully cached modules cycle: collections, _collections
Restored from database:  abc 
Analysis of abc (Library) on depth 2 completed in 7.31 ms.
Restored from database:  weakref 
Analysis of weakref (Library) on depth 2 completed in 13.02 ms.
Restored from database:  types 
Analysis of types (Library) on depth 2 completed in 28.24 ms.
Restored from database:  _functools 
Restored from database:  functools 
Fully cached modules cycle: _functools, functools
Analysis version 27 has been completed in 638.5 ms with 16 entries analyzed and 3 entries skipped.
Analysis version 102 of 60 entries has started.
Restored from database:  copyreg 
Analysis of copyreg (Library) on depth 4 completed in 2.5 ms.
Restored from database:  _warnings 
Analysis of _warnings (CompiledBuiltin) on depth 4 completed in 1.58 ms.
Restored from database:  _abc 
Analysis of _abc (CompiledBuiltin) on depth 3 completed in 2.12 ms.
Restored from database:  _heapq 
Analysis of _heapq (Compiled) on depth 4 completed in 7.38 ms.
Restored from database:  atexit 
Analysis of atexit (CompiledBuiltin) on depth 3 completed in 2.71 ms.
Restored from database:  gc 
Analysis of gc (CompiledBuiltin) on depth 3 completed in 12.56 ms.
Restored from database:  _tracemalloc 
Analysis of _tracemalloc (CompiledBuiltin) on depth 5 completed in 1.94 ms.
Analysis of token(Library) canceled (no AST yet).
Analysis of argparse(Library) canceled (no AST yet).
Analysis of codecs(Library) canceled (no AST yet).
Analysis of enum(Library) canceled (no AST yet).
Analysis of sre_compile(Library) canceled (no AST yet).
Analysis of sre_parse(Library) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of sre_constants(Library) canceled (no AST yet).
Analysis of stat(Library) canceled (no AST yet).
Analysis of genericpath(Library) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of ntpath(Library) canceled (no AST yet).
Analysis of subprocess(Library) canceled (no AST yet).
Analysis of _compat_pickle(Library) canceled (no AST yet).
Analysis of pprint(Library) canceled (no AST yet).
Analysis of struct(Library) canceled (no AST yet).
Analysis of _pickle(Compiled) canceled (no AST yet).
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 2.59 ms.
Restored from database:  _weakrefset 
Analysis of _weakrefset (Library) on depth 3 completed in 6.83 ms.
Restored from database:  _py_abc 
Analysis of _py_abc (Library) on depth 3 completed in 3.93 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 33.87 ms.
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 3.3 ms.
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  posixpath 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, posixpath, functools
Analysis of pwd (CompiledBuiltin) queued. Dependencies: 
Analysis of stat (Library) queued. Dependencies: _stat
Create built-in compiled (scraped) module:  _stat /home/jake/work/issue1601/venv/bin/python3 
Analysis of _pickle (Compiled) queued. Dependencies: 
Analysis of struct (Library) queued. Dependencies: struct (stub), _struct
Create compiled (scraped):  _struct /usr/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis version 102 has been completed in 779.5 ms with 57 entries analyzed and 3 entries skipped.
Analysis version 111 of 59 entries has started.
Analysis of token(Library) canceled (no AST yet).
Analysis of argparse(Library) canceled (no AST yet).
Analysis of codecs(Library) canceled (no AST yet).
Analysis of enum(Library) canceled (no AST yet).
Analysis of sre_compile(Library) canceled (no AST yet).
Analysis of sre_parse(Library) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of sre_constants(Library) canceled (no AST yet).
Analysis of genericpath(Library) canceled (no AST yet).
Restored from database:  pwd 
Analysis of pwd (CompiledBuiltin) on depth 7 completed in 21.06 ms.
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of ntpath(Library) canceled (no AST yet).
Analysis of subprocess(Library) canceled (no AST yet).
Analysis of _compat_pickle(Library) canceled (no AST yet).
Analysis of pprint(Library) canceled (no AST yet).
Analysis of _struct (Compiled) queued. Dependencies: struct
Analysis of genericpath (Library) queued. Dependencies: os, stat
Analysis of __future__ (Library) queued. Dependencies: 
Analysis of unittest (Library) queued. Dependencies: os, unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals
Analysis of struct (Stub) queued. Dependencies: sys (stub), array (stub)
Import:  unittest.result /usr/lib/python3.7/unittest/result.py 
Analysis of _compat_pickle (Library) queued. Dependencies: 
Import:  unittest.case /usr/lib/python3.7/unittest/case.py 
Import:  unittest.suite /usr/lib/python3.7/unittest/suite.py 
Import:  unittest.loader /usr/lib/python3.7/unittest/loader.py 
Import:  unittest.main /usr/lib/python3.7/unittest/main.py 
Analysis of _stat (CompiledBuiltin) queued. Dependencies: 
Import:  unittest.runner /usr/lib/python3.7/unittest/runner.py 
Import:  unittest.signals /usr/lib/python3.7/unittest/signals.py 
Analysis of array (Stub) queued. Dependencies: sys (stub)
Analysis of struct (Library) on depth 6 completed in 79.4 ms.
Analysis of ntpath (Library) queued. Dependencies: os, sys, stat, genericpath, string
Import:  string /usr/lib/python3.7/string.py 
Restored from database:  _pickle 
Analysis of _pickle (Compiled) on depth 6 completed in 59.4 ms.
Analysis of string (Library) queued. Dependencies: _string, re, collections
Analysis of codecs (Library) queued. Dependencies: sys, encodings, _codecs
Create built-in compiled (scraped) module:  _string /home/jake/work/issue1601/venv/bin/python3 
Import:  encodings /usr/lib/python3.7/encodings/__init__.py 
Create built-in compiled (scraped) module:  _codecs /home/jake/work/issue1601/venv/bin/python3 
Analysis of subprocess (Library) queued. Dependencies: sys, io, os, time, signal, warnings, errno, threading, _posixsubprocess, select, selectors
Create built-in compiled (scraped) module:  time /home/jake/work/issue1601/venv/bin/python3 
Import:  signal /usr/lib/python3.7/signal.py 
Create built-in compiled (scraped) module:  errno /home/jake/work/issue1601/venv/bin/python3 
Import:  threading /usr/lib/python3.7/threading.py 
Create compiled (scraped):  _posixsubprocess /usr/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  select /usr/lib/python3.7/lib-dynload/select.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  selectors /usr/lib/python3.7/selectors.py 
Analysis of _codecs (CompiledBuiltin) queued. Dependencies: 
Analysis of sys (Stub) queued. Dependencies: types (stub), importlib.abc (stub)
Analysis of difflib (Library) queued. Dependencies: re, doctest, heapq, collections
Analysis of encodings (Library) queued. Dependencies: codecs, sys, encodings.mbcs, encodings.aliases
Analysis of importlib.abc (Stub) queued. Dependencies: abc (stub), os (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Analysis of sre_constants (Library) queued. Dependencies: _sre
Restored from database:  __future__ 
Analysis of __future__ (Library) on depth 5 completed in 151.45 ms.
Import:  encodings.mbcs /usr/lib/python3.7/encodings/mbcs.py 
Import:  encodings.aliases /usr/lib/python3.7/encodings/aliases.py 
Analysis of inspect (Library) queued. Dependencies: abc, dis, collections, collections.abc, enum, importlib, importlib.machinery, itertools, linecache, os, re, sys, tokenize, token, types, warnings, functools, ast, argparse, operator
Analysis of posix (CompiledBuiltin) queued. Dependencies: os
Analysis of enum (Library) queued. Dependencies: sys, warnings, types, _collections, collections
Analysis of pdb (Library) queued. Dependencies: os, re, sys, cmd, bdb, dis, code, glob, pprint, signal, inspect, traceback, linecache, readline, shlex, runpy, pydoc, getopt
Create built-in compiled (scraped) module:  _sre /home/jake/work/issue1601/venv/bin/python3 
Import:  dis /usr/lib/python3.7/dis.py 
Import:  importlib /usr/lib/python3.7/importlib/__init__.py 
Import:  importlib.machinery /usr/lib/python3.7/importlib/machinery.py 
Import:  ast /usr/lib/python3.7/ast.py 
Analysis of selectors (Library) queued. Dependencies: math, select, sys, abc, collections, collections.abc
Import:  cmd /usr/lib/python3.7/cmd.py 
Import:  bdb /usr/lib/python3.7/bdb.py 
Import:  code /usr/lib/python3.7/code.py 
Import:  glob /usr/lib/python3.7/glob.py 
Create compiled (scraped):  readline /usr/lib/python3.7/lib-dynload/readline.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  shlex /usr/lib/python3.7/shlex.py 
Import:  runpy /usr/lib/python3.7/runpy.py 
Import:  pydoc /usr/lib/python3.7/pydoc.py 
Import:  getopt /usr/lib/python3.7/getopt.py 
Create compiled (scraped):  math /usr/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Restored from database:  difflib 
Analysis of difflib (Library) on depth 5 completed in 85.74 ms.
Restored from database:  inspect 
Analysis of inspect (Library) on depth 5 completed in 135.04 ms.
Restored from database:  pdb 
Analysis of pdb (Library) on depth 5 completed in 27.53 ms.
Restored from database:  unittest 
Analysis of unittest (Library) on depth 5 completed in 33.92 ms.
Restored from database:  _stat 
Analysis of _stat (CompiledBuiltin) on depth 7 completed in 9.22 ms.
Restored from database:  stat 
Analysis of stat (Library) on depth 6 completed in 9.92 ms.
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 8.02 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 43.71 ms.
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 6.32 ms.
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  posixpath 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, posixpath, functools
Analysis version 111 has been completed in 1338.01 ms with 54 entries analyzed and 5 entries skipped.
Analysis version 168 of 93 entries has started.
Analysis of token(Library) canceled (no AST yet).
Analysis of argparse(Library) canceled (no AST yet).
Analysis of sre_compile(Library) canceled (no AST yet).
Analysis of sre_parse(Library) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Restored from database:  _compat_pickle 
Analysis of _compat_pickle (Library) on depth 6 completed in 23.37 ms.
Analysis of pprint(Library) canceled (no AST yet).
Analysis of unittest.result(Library) canceled (no AST yet).
Analysis of unittest.case(Library) canceled (no AST yet).
Analysis of unittest.suite(Library) canceled (no AST yet).
Analysis of unittest.loader(Library) canceled (no AST yet).
Analysis of unittest.main(Library) canceled (no AST yet).
Analysis of unittest.runner(Library) canceled (no AST yet).
Analysis of unittest.signals(Library) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Restored from database:  _codecs 
Analysis of _codecs (CompiledBuiltin) on depth 7 completed in 12.07 ms.
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of signal(Library) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of threading(Library) canceled (no AST yet).
Analysis of _posixsubprocess(Compiled) canceled (no AST yet).
Analysis of select(Compiled) canceled (no AST yet).
Analysis of types(Stub) canceled (no AST yet).
Analysis of encodings.mbcs(Library) canceled (no AST yet).
Analysis of encodings.aliases(Library) canceled (no AST yet).
Analysis of abc(Stub) canceled (no AST yet).
Analysis of os(Stub) canceled (no AST yet).
Analysis of _importlib_modulespec(Stub) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of dis(Library) canceled (no AST yet).
Analysis of importlib(Library) canceled (no AST yet).
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of ast(Library) canceled (no AST yet).
Analysis of modules loop on depth 8 in 83.39 ms:
    sys(Stub)
    importlib.abc(Stub)
Restored from database:  sre_constants 
Analysis of sre_constants (Library) on depth 5 completed in 6.96 ms.
Analysis of array (Stub) on depth 8 completed in 4.18 ms.
Analysis of struct (Stub) on depth 7 completed in 1.64 ms.
Analysis of modules loop on depth 6 in 5.07 ms:
    struct(Library)
    _struct(Compiled)
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 2.7 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 97.33 ms.
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 3.27 ms.
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  selectors 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, codecs, posixpath, enum, genericpath, posix, ntpath, subprocess, difflib, inspect, pdb, unittest, string, encodings, selectors, functools
Analysis version 168 has been completed in 999.57 ms with 83 entries analyzed and 10 entries skipped.
Analysis of _sre (CompiledBuiltin) queued. Dependencies: 
Analysis version 179 of 103 entries has started.
Analysis of token(Library) canceled (no AST yet).
Analysis of argparse(Library) canceled (no AST yet).
Analysis of sre_compile(Library) canceled (no AST yet).
Analysis of sre_parse(Library) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of pprint(Library) canceled (no AST yet).
Analysis of unittest.result(Library) canceled (no AST yet).
Analysis of unittest.case(Library) canceled (no AST yet).
Analysis of unittest.suite(Library) canceled (no AST yet).
Analysis of unittest.loader(Library) canceled (no AST yet).
Analysis of unittest.main(Library) canceled (no AST yet).
Analysis of unittest.runner(Library) canceled (no AST yet).
Analysis of unittest.signals(Library) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of signal(Library) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of threading(Library) canceled (no AST yet).
Analysis of _posixsubprocess(Compiled) canceled (no AST yet).
Analysis of select(Compiled) canceled (no AST yet).
Analysis of types(Stub) canceled (no AST yet).
Analysis of encodings.mbcs(Library) canceled (no AST yet).
Analysis of encodings.aliases(Library) canceled (no AST yet).
Analysis of abc(Stub) canceled (no AST yet).
Analysis of os(Stub) canceled (no AST yet).
Analysis of _importlib_modulespec(Stub) canceled (no AST yet).
Restored from database:  _sre 
Analysis of _sre (CompiledBuiltin) on depth 6 completed in 1.4 ms.
Analysis of dis(Library) canceled (no AST yet).
Analysis of _string (CompiledBuiltin) queued. Dependencies: 
Analysis of importlib(Library) canceled (no AST yet).
Analysis of importlib.machinery(Library) canceled (no AST yet).
Analysis of ast(Library) canceled (no AST yet).
Analysis of cmd(Library) canceled (no AST yet).
Analysis of bdb(Library) canceled (no AST yet).
Analysis of code(Library) canceled (no AST yet).
Analysis of glob(Library) canceled (no AST yet).
Analysis of readline(Compiled) canceled (no AST yet).
Analysis of shlex(Library) canceled (no AST yet).
Analysis of runpy(Library) canceled (no AST yet).
Analysis of pydoc(Library) canceled (no AST yet).
Analysis of getopt(Library) canceled (no AST yet).
Analysis of math(Compiled) canceled (no AST yet).
Analysis of ast (Library) queued. Dependencies: inspect, _ast, collections
Analysis of math (Compiled) queued. Dependencies: 
Create built-in compiled (scraped) module:  _ast /home/jake/work/issue1601/venv/bin/python3 
Analysis of unittest.signals (Library) queued. Dependencies: signal, weakref, functools
Analysis of importlib.machinery (Library) queued. Dependencies: _imp, importlib._bootstrap, importlib._bootstrap_external
Create built-in compiled (scraped) module:  _imp /home/jake/work/issue1601/venv/bin/python3 
Import:  importlib._bootstrap /usr/lib/python3.7/importlib/_bootstrap.py 
Import:  importlib._bootstrap_external /usr/lib/python3.7/importlib/_bootstrap_external.py 
Analysis of unittest.runner (Library) queued. Dependencies: sys, time, warnings, unittest, unittest.result, unittest.signals
Analysis of sre_parse (Library) queued. Dependencies: warnings, sre_constants
Analysis of pprint (Library) queued. Dependencies: collections, re, sys, types, time, io
Analysis of modules loop on depth 8 in 112.95 ms:
    sys(Stub)
    importlib.abc(Stub)
Analysis of types (Stub) queued. Dependencies: sys (stub), _importlib_modulespec (stub)
Analysis of modules loop on depth 6 in 41.28 ms:
    struct(Library)
    _struct(Compiled)
Analysis of time (CompiledBuiltin) queued. Dependencies: 
Analysis of dis (Library) queued. Dependencies: sys, types, collections, io, argparse, opcode
Import:  opcode /usr/lib/python3.7/opcode.py 
Analysis of unittest.main (Library) queued. Dependencies: sys, argparse, os, unittest, unittest.loader, unittest.runner, unittest.signals
Analysis of sre_compile (Library) queued. Dependencies: _sre, sre_parse, sys, sre_constants
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 17.56 ms.
Analysis of signal (Library) queued. Dependencies: _signal, functools, enum
Analysis of opcode (Library) queued. Dependencies: _opcode
Analysis of _locale (CompiledBuiltin) queued. Dependencies: locale
Analysis of unittest.result (Library) queued. Dependencies: io, sys, traceback, unittest, unittest.util, functools
Analysis of token (Library) queued. Dependencies: re, sys
Analysis of unittest.loader (Library) queued. Dependencies: os, re, sys, traceback, types, functools, warnings, fnmatch, unittest, unittest.case, unittest.suite, unittest.util
Analysis of encodings.mbcs (Library) queued. Dependencies: codecs
Analysis of importlib._bootstrap_external (Library) queued. Dependencies: tokenize
Create built-in compiled (scraped) module:  _signal /home/jake/work/issue1601/venv/bin/python3 
Create compiled (scraped):  _opcode /usr/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  locale /usr/lib/python3.7/locale.py 
Import:  unittest.util /usr/lib/python3.7/unittest/util.py 
Analysis of unittest.util (Library) queued. Dependencies: collections, os
Analysis of _ast (CompiledBuiltin) queued. Dependencies: 
Analysis of argparse (Library) queued. Dependencies: os, re, sys, copy, textwrap, gettext, warnings
Import:  textwrap /usr/lib/python3.7/textwrap.py 
Import:  gettext /usr/lib/python3.7/gettext.py 
Analysis of importlib (Library) queued. Dependencies: _imp, sys, types, warnings, importlib._bootstrap, importlib._bootstrap_external
Analysis of unittest.suite (Library) queued. Dependencies: sys, unittest, unittest.case, unittest.util
Analysis of encodings.aliases (Library) queued. Dependencies: 
Analysis of abc (Stub) queued. Dependencies: 
Analysis of _imp (CompiledBuiltin) queued. Dependencies: 
Analysis of getopt (Library) queued. Dependencies: os, sys, gettext
Analysis of _signal (CompiledBuiltin) queued. Dependencies: signal
Analysis of unittest.case (Library) queued. Dependencies: sys, functools, difflib, logging, pprint, re, warnings, collections, contextlib, traceback, unittest, unittest.result, unittest.util
Analysis of gettext (Library) queued. Dependencies: locale, os, re, sys, warnings, copy, struct, errno
Import:  logging /usr/lib/python3.7/logging/__init__.py 
Import:  contextlib /usr/lib/python3.7/contextlib.py 
Analysis of importlib._bootstrap (Library) queued. Dependencies: 
Restored from database:  _io 
Analysis of locale (Library) queued. Dependencies: sys, encodings, encodings.aliases, re, _collections_abc, functools, warnings, _locale, os, _bootlocale
Import:  _bootlocale /usr/lib/python3.7/_bootlocale.py 
Restored from database:  io 
Fully cached modules cycle: _io, io
Analysis of os (Stub) queued. Dependencies: io (stub), sys (stub), posix (stub), os.path (stub)
Analysis of os.path (Stub) queued. Dependencies: posix (stub), sys (stub)
Analysis of posix (Stub) queued. Dependencies: 
Analysis of io (Stub) queued. Dependencies: codecs (stub), mmap (stub), sys (stub), types (stub)
Analysis of mmap (Stub) queued. Dependencies: sys (stub)
Analysis of codecs (Stub) queued. Dependencies: sys (stub), abc (stub), types (stub)
Analysis of textwrap (Library) queued. Dependencies: re
Analysis of errno (CompiledBuiltin) queued. Dependencies: 
Analysis of _opcode (Compiled) queued. Dependencies: 
Analysis of _importlib_modulespec (Stub) queued. Dependencies: abc (stub), sys (stub)
Analysis of threading (Library) queued. Dependencies: os, sys, _thread, warnings, time, traceback, _weakrefset, itertools, _collections, collections, _threading_local
Import:  _threading_local /usr/lib/python3.7/_threading_local.py 
Analysis of _threading_local (Library) queued. Dependencies: weakref, contextlib, threading
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 4.14 ms.
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 15.52 ms.
Analysis of _posixsubprocess (Compiled) queued. Dependencies: 
Analysis of _bootlocale (Library) queued. Dependencies: sys, _locale, locale
Analysis of select (Compiled) queued. Dependencies: 
Analysis of glob (Library) queued. Dependencies: os, re, fnmatch
Analysis of readline (Compiled) queued. Dependencies: 
Analysis of shlex (Library) queued. Dependencies: os, re, sys, collections, io
Analysis of contextlib (Library) queued. Dependencies: abc, sys, _collections_abc, collections, functools
Analysis of runpy (Library) queued. Dependencies: sys, importlib, importlib.machinery, importlib.util, types, pkgutil, warnings
Analysis of code (Library) queued. Dependencies: sys, traceback, readline, argparse, codeop
Import:  importlib.util /usr/lib/python3.7/importlib/util.py 
Analysis of cmd (Library) queued. Dependencies: string, sys, readline
Import:  pkgutil /usr/lib/python3.7/pkgutil.py 
Import:  codeop /usr/lib/python3.7/codeop.py 
Restored from database:  types 
Analysis of bdb (Library) queued. Dependencies: fnmatch, sys, os, linecache, reprlib, inspect
Analysis of importlib.util (Library) queued. Dependencies: _imp, functools, sys, types, warnings, importlib, importlib.abc, importlib._bootstrap, importlib._bootstrap_external, contextlib
Import:  importlib.abc /usr/lib/python3.7/importlib/abc.py 
Analysis of codeop (Library) queued. Dependencies: __future__
Analysis of pkgutil (Library) queued. Dependencies: importlib, importlib.util, importlib.machinery, os, sys, warnings, marshal, inspect, zipimport, collections, functools, types
Create built-in compiled (scraped) module:  marshal /home/jake/work/issue1601/venv/bin/python3 
Analysis of marshal (CompiledBuiltin) queued. Dependencies: 
Analysis of pydoc (Library) queued. Dependencies: importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, importlib.util, inspect, io, os, pkgutil, platform, re, sys, time, tokenize, urllib, urllib.parse, warnings, tempfile, subprocess, tty, pydoc_data, pydoc_data.topics, textwrap, http, http.server, email, email.message, select, threading, webbrowser, getopt, collections, reprlib, traceback
Create built-in compiled (scraped) module:  zipimport /home/jake/work/issue1601/venv/bin/python3 
Analysis of importlib.abc (Library) queued. Dependencies: abc, warnings, importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery
Analysis of zipimport (CompiledBuiltin) queued. Dependencies: 
Restored from database:  weakref 
Import:  platform /usr/lib/python3.7/platform.py 
Import:  urllib /usr/lib/python3.7/urllib/__init__.py 
Import:  urllib.parse /usr/lib/python3.7/urllib/parse.py 
Import:  tempfile /usr/lib/python3.7/tempfile.py 
Import:  tty /usr/lib/python3.7/tty.py 
Import:  pydoc_data /usr/lib/python3.7/pydoc_data/__init__.py 
Import:  pydoc_data.topics /usr/lib/python3.7/pydoc_data/topics.py 
Import:  http /usr/lib/python3.7/http/__init__.py 
Import:  http.server /usr/lib/python3.7/http/server.py 
Import:  email /usr/lib/python3.7/email/__init__.py 
Import:  email.message /usr/lib/python3.7/email/message.py 
Import:  webbrowser /usr/lib/python3.7/webbrowser.py 
Analysis of logging (Library) queued. Dependencies: sys, os, time, io, traceback, warnings, weakref, collections, collections.abc, threading, pickle, atexit, string
Restored from database:  _functools 
Analysis of urllib (Library) queued. Dependencies: 
Analysis of pydoc_data (Library) queued. Dependencies: 
Analysis of tty (Library) queued. Dependencies: termios
Create compiled (scraped):  termios /usr/lib/python3.7/lib-dynload/termios.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of urllib.parse (Library) queued. Dependencies: re, sys, collections, unicodedata
Create compiled (scraped):  unicodedata /usr/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of platform (Library) queued. Dependencies: collections, sys, os, re, subprocess, warnings, plistlib, socket, struct
Import:  plistlib /usr/lib/python3.7/plistlib.py 
Import:  socket /usr/lib/python3.7/socket.py 
Analysis of tempfile (Library) queued. Dependencies: functools, warnings, io, os, shutil, errno, weakref, _thread, random
Import:  shutil /usr/lib/python3.7/shutil.py 
Import:  random /usr/lib/python3.7/random.py 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  selectors 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, codecs, posixpath, enum, genericpath, posix, ntpath, subprocess, difflib, inspect, pdb, unittest, string, encodings, selectors, functools
Analysis version 179 has been completed in 2000.9 ms with 88 entries analyzed and 15 entries skipped.
Analysis version 293 of 145 entries has started.
Restored from database:  pwd 
Analysis of pwd (CompiledBuiltin) on depth 7 completed in 2.44 ms.
Restored from database:  _compat_pickle 
Analysis of _compat_pickle (Library) on depth 6 completed in 12.4 ms.
Restored from database:  _pickle 
Analysis of _pickle (Compiled) on depth 6 completed in 4.52 ms.
Restored from database:  __future__ 
Analysis of __future__ (Library) on depth 5 completed in 3.18 ms.
Restored from database:  _stat 
Analysis of _stat (CompiledBuiltin) on depth 7 completed in 4.08 ms.
Restored from database:  _string 
Analysis of _string (CompiledBuiltin) on depth 8 completed in 1.75 ms.
Restored from database:  _codecs 
Analysis of _codecs (CompiledBuiltin) on depth 7 completed in 8.88 ms.
Restored from database:  time 
Analysis of time (CompiledBuiltin) on depth 7 completed in 26.66 ms.
Restored from database:  errno 
Analysis of errno (CompiledBuiltin) on depth 7 completed in 4.65 ms.
Restored from database:  _posixsubprocess 
Analysis of _posixsubprocess (Compiled) on depth 7 completed in 2.28 ms.
Restored from database:  select 
Analysis of select (Compiled) on depth 7 completed in 7.76 ms.
Restored from database:  encodings.aliases 
Analysis of encodings.aliases (Library) on depth 7 completed in 4.25 ms.
Analysis of abc (Stub) on depth 10 completed in 1.96 ms.
Restored from database:  _sre 
Analysis of _sre (CompiledBuiltin) on depth 6 completed in 2.04 ms.
Restored from database:  readline 
Analysis of readline (Compiled) on depth 6 completed in 3.93 ms.
Restored from database:  math 
Analysis of math (Compiled) on depth 8 completed in 12.49 ms.
Restored from database:  _ast 
Analysis of _ast (CompiledBuiltin) on depth 7 completed in 48.35 ms.
Restored from database:  _imp 
Analysis of _imp (CompiledBuiltin) on depth 7 completed in 3.24 ms.
Restored from database:  importlib._bootstrap 
Analysis of importlib._bootstrap (Library) on depth 7 completed in 28.49 ms.
Restored from database:  _opcode 
Analysis of _opcode (Compiled) on depth 8 completed in 1.52 ms.
Analysis of posix (Stub) on depth 11 completed in 1.96 ms.
Restored from database:  marshal 
Analysis of marshal (CompiledBuiltin) on depth 8 completed in 9.44 ms.
Restored from database:  zipimport 
Analysis of zipimport (CompiledBuiltin) on depth 8 completed in 1.97 ms.
Restored from database:  urllib 
Analysis of urllib (Library) on depth 7 completed in 0.81 ms.
Restored from database:  pydoc_data 
Analysis of pydoc_data (Library) on depth 7 completed in 0.73 ms.
Analysis of pydoc_data.topics(Library) canceled (no AST yet).
Analysis of http(Library) canceled (no AST yet).
Analysis of http.server(Library) canceled (no AST yet).
Analysis of email(Library) canceled (no AST yet).
Analysis of email.message(Library) canceled (no AST yet).
Analysis of webbrowser(Library) canceled (no AST yet).
Analysis of termios(Compiled) canceled (no AST yet).
Analysis of unicodedata(Compiled) canceled (no AST yet).
Analysis of plistlib(Library) canceled (no AST yet).
Analysis of socket(Library) canceled (no AST yet).
Restored from database:  codeop 
Analysis of codeop (Library) on depth 7 completed in 2.64 ms.
Restored from database:  opcode 
Analysis of opcode (Library) on depth 7 completed in 23.4 ms.
Analysis of modules loop on depth 8 in 107.28 ms:
    types(Stub)
    os(Stub)
    _importlib_modulespec(Stub)
    io(Stub)
    os.path(Stub)
    codecs(Stub)
    mmap(Stub)
    sys(Stub)
    importlib.abc(Stub)
Restored from database:  tty 
Analysis of tty (Library) on depth 7 completed in 6.74 ms.
Analysis of modules loop on depth 6 in 2.39 ms:
    struct(Library)
    _struct(Compiled)
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 2.54 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 15.1 ms.
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 16.4 ms.
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  token 
Restored from database:  argparse 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  sre_compile 
Restored from database:  sre_parse 
Restored from database:  _locale 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  pprint 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  unittest.result 
Restored from database:  unittest.case 
Restored from database:  unittest.suite 
Restored from database:  unittest.loader 
Restored from database:  unittest.main 
Restored from database:  unittest.runner 
Restored from database:  unittest.signals 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  signal 
Restored from database:  threading 
Restored from database:  selectors 
Restored from database:  encodings.mbcs 
Restored from database:  dis 
Restored from database:  importlib 
Restored from database:  importlib.machinery 
Restored from database:  ast 
Restored from database:  cmd 
Restored from database:  bdb 
Restored from database:  code 
Restored from database:  glob 
Restored from database:  shlex 
Restored from database:  runpy 
Restored from database:  pydoc 
Restored from database:  getopt 
Restored from database:  importlib._bootstrap_external 
Restored from database:  _signal 
Restored from database:  locale 
Restored from database:  unittest.util 
Restored from database:  textwrap 
Restored from database:  gettext 
Restored from database:  logging 
Restored from database:  contextlib 
Restored from database:  _bootlocale 
Restored from database:  _threading_local 
Restored from database:  importlib.util 
Restored from database:  pkgutil 
Restored from database:  importlib.abc 
Restored from database:  platform 
Restored from database:  urllib.parse 
Restored from database:  tempfile 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, token, argparse, codecs, posixpath, enum, sre_compile, sre_parse, _locale, genericpath, posix, ntpath, subprocess, pprint, difflib, inspect, pdb, unittest, unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, string, encodings, signal, threading, selectors, encodings.mbcs, dis, importlib, importlib.machinery, ast, cmd, bdb, code, glob, shlex, runpy, pydoc, getopt, importlib._bootstrap_external, _signal, locale, unittest.util, textwrap, gettext, logging, contextlib, _bootlocale, _threading_local, importlib.util, pkgutil, importlib.abc, platform, urllib.parse, tempfile, functools
Analysis version 293 has been completed in 1876.32 ms with 136 entries analyzed and 9 entries skipped.
Analysis of pydoc_data.topics (Library) queued. Dependencies: 
Analysis version 296 of 113 entries has started.
Restored from database:  sre_constants 
Analysis of sre_constants (Library) on depth 5 completed in 30.99 ms.
Restored from database:  stat 
Analysis of stat (Library) on depth 6 completed in 47.92 ms.
Analysis of array (Stub) on depth 8 completed in 4.29 ms.
Restored from database:  opcode 
Analysis of opcode (Library) on depth 7 completed in 2.76 ms.
Restored from database:  codeop 
Analysis of codeop (Library) on depth 7 completed in 10.54 ms.
Restored from database:  pydoc_data.topics 
Analysis of pydoc_data.topics (Library) on depth 7 completed in 360.55 ms.
Analysis of http(Library) canceled (no AST yet).
Analysis of http.server(Library) canceled (no AST yet).
Analysis of email(Library) canceled (no AST yet).
Analysis of email.message(Library) canceled (no AST yet).
Analysis of webbrowser(Library) canceled (no AST yet).
Analysis of termios(Compiled) canceled (no AST yet).
Analysis of unicodedata(Compiled) canceled (no AST yet).
Analysis of plistlib(Library) canceled (no AST yet).
Analysis of socket(Library) canceled (no AST yet).
Analysis of shutil(Library) canceled (no AST yet).
Analysis of random(Library) canceled (no AST yet).
Analysis of modules loop on depth 6 in 3.92 ms:
    struct(Library)
    _struct(Compiled)
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 3.39 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Analysis of unicodedata (Compiled) queued. Dependencies: 
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 104.76 ms.
Analysis of termios (Compiled) queued. Dependencies: 
Analysis of socket (Library) queued. Dependencies: _socket, os, sys, io, selectors, errno, enum
Analysis of http (Library) queued. Dependencies: enum
Create compiled (scraped):  _socket /usr/lib/python3.7/lib-dynload/_socket.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of email (Library) queued. Dependencies: email.parser
Import:  email.parser /usr/lib/python3.7/email/parser.py 
Analysis of random (Library) queued. Dependencies: itertools, bisect, os, _random, time, warnings, types, math, _collections_abc, hashlib
Import:  bisect /usr/lib/python3.7/bisect.py 
Create compiled (scraped):  _random /usr/lib/python3.7/lib-dynload/_random.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  hashlib /usr/lib/python3.7/hashlib.py 
Analysis of plistlib (Library) queued. Dependencies: binascii, codecs, contextlib, datetime, enum, itertools, os, re, struct, io, warnings, xml.parsers.expat
Restored from database:  itertools 
Create compiled (scraped):  binascii /usr/lib/python3.7/lib-dynload/binascii.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  datetime /usr/lib/python3.7/datetime.py 
Import:  xml.parsers.expat /usr/lib/python3.7/xml/parsers/expat.py 
Analysis of shutil (Library) queued. Dependencies: os, sys, stat, fnmatch, collections, errno, zlib, bz2, lzma, tarfile, zipfile, pwd, grp
Analysis of email.parser (Library) queued. Dependencies: io, email.feedparser, email._policybase
Create compiled (scraped):  zlib /usr/lib/python3.7/lib-dynload/zlib.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  bz2 /usr/lib/python3.7/bz2.py 
Import:  lzma /usr/lib/python3.7/lzma.py 
Import:  tarfile /usr/lib/python3.7/tarfile.py 
Import:  zipfile /usr/lib/python3.7/zipfile.py 
Create compiled (scraped):  grp /usr/lib/python3.7/lib-dynload/grp.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  email.feedparser /usr/lib/python3.7/email/feedparser.py 
Import:  email._policybase /usr/lib/python3.7/email/_policybase.py 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 238.71 ms.
Analysis of _socket (Compiled) queued. Dependencies: 
Analysis of email.message (Library) queued. Dependencies: re, uu, quopri, io, email, email.utils, email.errors, email._policybase, email.charset, email._encoded_words, email.generator, email.iterators, email.policy
Import:  uu /usr/lib/python3.7/uu.py 
Analysis of http.server (Library) queued. Dependencies: copy, datetime, email, email.utils, html, http, http.client, io, mimetypes, os, posixpath, select, shutil, socket, socketserver, sys, time, urllib, urllib.parse, pwd, base64, binascii, subprocess, argparse, functools
Import:  quopri /usr/lib/python3.7/quopri.py 
Import:  email.utils /usr/lib/python3.7/email/utils.py 
Import:  email.errors /usr/lib/python3.7/email/errors.py 
Import:  email.charset /usr/lib/python3.7/email/charset.py 
Import:  email._encoded_words /usr/lib/python3.7/email/_encoded_words.py 
Import:  email.generator /usr/lib/python3.7/email/generator.py 
Import:  email.iterators /usr/lib/python3.7/email/iterators.py 
Import:  email.policy /usr/lib/python3.7/email/policy.py 
Analysis of email.policy (Library) queued. Dependencies: re, sys, email._policybase, email.utils, email.headerregistry, email.contentmanager, email.message
Import:  html /usr/lib/python3.7/html/__init__.py 
Import:  http.client /usr/lib/python3.7/http/client.py 
Import:  mimetypes /usr/lib/python3.7/mimetypes.py 
Import:  socketserver /usr/lib/python3.7/socketserver.py 
Import:  base64 /usr/lib/python3.7/base64.py 
Import:  email.headerregistry /usr/lib/python3.7/email/headerregistry.py 
Import:  email.contentmanager /usr/lib/python3.7/email/contentmanager.py 
Analysis of email.contentmanager (Library) queued. Dependencies: binascii, email, email.charset, email.message, email.errors, email.quoprimime
Import:  email.quoprimime /usr/lib/python3.7/email/quoprimime.py 
Analysis of email.quoprimime (Library) queued. Dependencies: re, string
Analysis of email.headerregistry (Library) queued. Dependencies: types, email, email.utils, email.errors, email._header_value_parser
Import:  email._header_value_parser /usr/lib/python3.7/email/_header_value_parser.py 
Analysis of email._header_value_parser (Library) queued. Dependencies: re, sys, urllib, string, collections, operator, email, email._encoded_words, email.errors, email.utils
Analysis of base64 (Library) queued. Dependencies: re, struct, binascii, warnings, sys, getopt
Analysis of socketserver (Library) queued. Dependencies: socket, selectors, os, sys, threading, traceback, io, time
Analysis of mimetypes (Library) queued. Dependencies: os, sys, posixpath, urllib, urllib.parse, getopt
Analysis of http.client (Library) queued. Dependencies: email, email.parser, email.message, http, io, re, socket, collections, collections.abc, ssl, warnings, urllib.parse
Import:  ssl /usr/lib/python3.7/ssl.py 
Analysis of ssl (Library) queued. Dependencies: sys, os, _ssl, socket, base64, errno, warnings, collections, enum, time, calendar
Create compiled (scraped):  _ssl /usr/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Import:  calendar /usr/lib/python3.7/calendar.py 
Analysis of calendar (Library) queued. Dependencies: sys, datetime, locale, argparse, itertools
Analysis of _ssl (Compiled) queued. Dependencies: 
Analysis of html (Library) queued. Dependencies: re, html.entities
Import:  html.entities /usr/lib/python3.7/html/entities.py 
Analysis of html.entities (Library) queued. Dependencies: 
Analysis of email.iterators (Library) queued. Dependencies: sys, io
Analysis of email.generator (Library) queued. Dependencies: re, sys, time, random, copy, io, email.utils
Analysis of email._encoded_words (Library) queued. Dependencies: re, base64, binascii, functools, string, email, email.errors
Analysis of _random (Compiled) queued. Dependencies: 
Analysis of xml.parsers.expat (Library) queued. Dependencies: sys, pyexpat
Create compiled (scraped):  pyexpat /usr/lib/python3.7/lib-dynload/pyexpat.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of email.charset (Library) queued. Dependencies: email, email.base64mime, email.quoprimime, functools, email.errors, email.encoders
Analysis of hashlib (Library) queued. Dependencies: _sha1, _md5, _sha256, _sha512, _blake2, _sha3, _hashlib, logging
Analysis of binascii (Compiled) queued. Dependencies: 
Import:  email.base64mime /usr/lib/python3.7/email/base64mime.py 
Analysis of email._policybase (Library) queued. Dependencies: abc, email, email.header, email.charset, email.utils
Import:  email.encoders /usr/lib/python3.7/email/encoders.py 
Create compiled (scraped):  _sha1 /usr/lib/python3.7/lib-dynload/_sha1.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _md5 /usr/lib/python3.7/lib-dynload/_md5.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha256 /usr/lib/python3.7/lib-dynload/_sha256.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha512 /usr/lib/python3.7/lib-dynload/_sha512.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _blake2 /usr/lib/python3.7/lib-dynload/_blake2.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha3 /usr/lib/python3.7/lib-dynload/_sha3.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _hashlib /usr/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of bisect (Library) queued. Dependencies: _bisect
Analysis of email.feedparser (Library) queued. Dependencies: re, email, email.errors, email._policybase, collections, io, email.message
Analysis of pyexpat (Compiled) queued. Dependencies: 
Analysis of email.errors (Library) queued. Dependencies: 
Import:  email.header /usr/lib/python3.7/email/header.py 
Create compiled (scraped):  _bisect /usr/lib/python3.7/lib-dynload/_bisect.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of email.encoders (Library) queued. Dependencies: base64, quopri
Analysis of grp (Compiled) queued. Dependencies: 
Analysis of _bisect (Compiled) queued. Dependencies: 
Analysis of _sha1 (Compiled) queued. Dependencies: 
Analysis of _md5 (Compiled) queued. Dependencies: 
Analysis of email.base64mime (Library) queued. Dependencies: base64, binascii
Restored from database:  types 
Analysis of _hashlib (Compiled) queued. Dependencies: 
Analysis of uu (Library) queued. Dependencies: binascii, os, sys, optparse
Analysis of datetime (Library) queued. Dependencies: time, math, sys, _strptime, _datetime
Import:  optparse /usr/lib/python3.7/optparse.py 
Import:  _strptime /usr/lib/python3.7/_strptime.py 
Create compiled (scraped):  _datetime /usr/lib/python3.7/lib-dynload/_datetime.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of email.header (Library) queued. Dependencies: re, binascii, email, email.quoprimime, email.base64mime, email.errors, email.charset
Analysis of webbrowser (Library) queued. Dependencies: os, shlex, shutil, sys, subprocess, threading, copy, glob, pwd, socket, tempfile, getopt
Restored from database:  weakref 
Restored from database:  _functools 
Analysis of zipfile (Library) queued. Dependencies: io, os, importlib, importlib.util, sys, time, stat, shutil, struct, binascii, threading, zlib, bz2, lzma, warnings, py_compile, argparse
Import:  py_compile /usr/lib/python3.7/py_compile.py 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  token 
Restored from database:  argparse 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  sre_compile 
Restored from database:  sre_parse 
Restored from database:  _locale 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  pprint 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  unittest.result 
Restored from database:  unittest.case 
Restored from database:  unittest.suite 
Restored from database:  unittest.loader 
Restored from database:  unittest.main 
Restored from database:  unittest.runner 
Restored from database:  unittest.signals 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  signal 
Restored from database:  threading 
Restored from database:  selectors 
Restored from database:  encodings.mbcs 
Restored from database:  dis 
Restored from database:  importlib 
Restored from database:  importlib.machinery 
Restored from database:  ast 
Restored from database:  cmd 
Restored from database:  bdb 
Restored from database:  code 
Restored from database:  glob 
Restored from database:  shlex 
Restored from database:  runpy 
Restored from database:  pydoc 
Restored from database:  getopt 
Restored from database:  importlib._bootstrap_external 
Restored from database:  _signal 
Restored from database:  locale 
Restored from database:  unittest.util 
Restored from database:  textwrap 
Restored from database:  gettext 
Restored from database:  logging 
Restored from database:  contextlib 
Restored from database:  _bootlocale 
Restored from database:  _threading_local 
Restored from database:  importlib.util 
Restored from database:  pkgutil 
Restored from database:  importlib.abc 
Restored from database:  platform 
Restored from database:  urllib.parse 
Restored from database:  tempfile 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, token, argparse, codecs, posixpath, enum, sre_compile, sre_parse, _locale, genericpath, posix, ntpath, subprocess, pprint, difflib, inspect, pdb, unittest, unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, string, encodings, signal, threading, selectors, encodings.mbcs, dis, importlib, importlib.machinery, ast, cmd, bdb, code, glob, shlex, runpy, pydoc, getopt, importlib._bootstrap_external, _signal, locale, unittest.util, textwrap, gettext, logging, contextlib, _bootlocale, _threading_local, importlib.util, pkgutil, importlib.abc, platform, urllib.parse, tempfile, functools
Analysis version 296 has been completed in 3153.97 ms with 106 entries analyzed and 7 entries skipped.
Analysis version 400 of 160 entries has started.
Analysis of struct (Stub) on depth 7 completed in 3.09 ms.
Restored from database:  termios 
Analysis of termios (Compiled) on depth 8 completed in 7.19 ms.
Restored from database:  unicodedata 
Analysis of unicodedata (Compiled) on depth 8 completed in 2.97 ms.
Restored from database:  _socket 
Analysis of _socket (Compiled) on depth 9 completed in 24.95 ms.
Restored from database:  _random 
Analysis of _random (Compiled) on depth 9 completed in 2.6 ms.
Restored from database:  binascii 
Analysis of binascii (Compiled) on depth 8 completed in 2.36 ms.
Analysis of zlib(Compiled) canceled (no AST yet).
Analysis of bz2(Library) canceled (no AST yet).
Analysis of lzma(Library) canceled (no AST yet).
Analysis of tarfile(Library) canceled (no AST yet).
Restored from database:  grp 
Analysis of grp (Compiled) on depth 9 completed in 1.37 ms.
Analysis of quopri(Library) canceled (no AST yet).
Analysis of email.utils(Library) canceled (no AST yet).
Restored from database:  email.errors 
Analysis of email.errors (Library) on depth 8 completed in 2.84 ms.
Restored from database:  _ssl 
Analysis of _ssl (Compiled) on depth 10 completed in 33.92 ms.
Restored from database:  html.entities 
Analysis of html.entities (Library) on depth 9 completed in 25.09 ms.
Restored from database:  pyexpat 
Analysis of pyexpat (Compiled) on depth 10 completed in 2.45 ms.
Restored from database:  _sha1 
Analysis of _sha1 (Compiled) on depth 10 completed in 1.04 ms.
Restored from database:  _md5 
Analysis of _md5 (Compiled) on depth 10 completed in 0.93 ms.
Analysis of _sha256(Compiled) canceled (no AST yet).
Analysis of _sha512(Compiled) canceled (no AST yet).
Analysis of _blake2(Compiled) canceled (no AST yet).
Analysis of _sha3(Compiled) canceled (no AST yet).
Restored from database:  _hashlib 
Analysis of _hashlib (Compiled) on depth 10 completed in 1.96 ms.
Restored from database:  _bisect 
Analysis of _bisect (Compiled) on depth 10 completed in 2.34 ms.
Analysis of optparse(Library) canceled (no AST yet).
Analysis of _strptime(Library) canceled (no AST yet).
Analysis of _datetime(Compiled) canceled (no AST yet).
Analysis of modules loop on depth 6 in 4.25 ms:
    struct(Library)
    _struct(Compiled)
Restored from database:  bisect 
Analysis of bisect (Library) on depth 9 completed in 2.48 ms.
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 2.64 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 37.52 ms.
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 8.5 ms.
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  token 
Restored from database:  argparse 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  sre_compile 
Restored from database:  sre_parse 
Restored from database:  _locale 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  pprint 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  unittest.result 
Restored from database:  unittest.case 
Restored from database:  unittest.suite 
Restored from database:  unittest.loader 
Restored from database:  unittest.main 
Restored from database:  unittest.runner 
Restored from database:  unittest.signals 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  signal 
Restored from database:  threading 
Restored from database:  selectors 
Restored from database:  encodings.mbcs 
Restored from database:  dis 
Restored from database:  importlib 
Restored from database:  importlib.machinery 
Restored from database:  ast 
Restored from database:  cmd 
Restored from database:  bdb 
Restored from database:  code 
Restored from database:  glob 
Restored from database:  shlex 
Restored from database:  runpy 
Restored from database:  pydoc 
Restored from database:  getopt 
Restored from database:  importlib._bootstrap_external 
Restored from database:  _signal 
Restored from database:  locale 
Restored from database:  unittest.util 
Restored from database:  textwrap 
Restored from database:  gettext 
Restored from database:  logging 
Restored from database:  contextlib 
Restored from database:  _bootlocale 
Restored from database:  _threading_local 
Restored from database:  importlib.util 
Restored from database:  pkgutil 
Restored from database:  importlib.abc 
Restored from database:  platform 
Restored from database:  urllib.parse 
Restored from database:  tempfile 
Restored from database:  http 
Restored from database:  http.server 
Restored from database:  email 
Restored from database:  email.message 
Restored from database:  webbrowser 
Restored from database:  plistlib 
Restored from database:  socket 
Restored from database:  shutil 
Restored from database:  random 
Restored from database:  email.parser 
Restored from database:  hashlib 
Restored from database:  datetime 
Restored from database:  xml.parsers.expat 
Restored from database:  zipfile 
Restored from database:  email.feedparser 
Restored from database:  email._policybase 
Restored from database:  uu 
Restored from database:  email.charset 
Restored from database:  email._encoded_words 
Restored from database:  email.generator 
Restored from database:  email.iterators 
Restored from database:  email.policy 
Restored from database:  html 
Restored from database:  http.client 
Restored from database:  mimetypes 
Restored from database:  socketserver 
Restored from database:  base64 
Restored from database:  email.headerregistry 
Restored from database:  email.contentmanager 
Restored from database:  email.quoprimime 
Restored from database:  email._header_value_parser 
Restored from database:  ssl 
Restored from database:  calendar 
Restored from database:  email.base64mime 
Restored from database:  email.encoders 
Restored from database:  email.header 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, token, argparse, codecs, posixpath, enum, sre_compile, sre_parse, _locale, genericpath, posix, ntpath, subprocess, pprint, difflib, inspect, pdb, unittest, unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, string, encodings, signal, threading, selectors, encodings.mbcs, dis, importlib, importlib.machinery, ast, cmd, bdb, code, glob, shlex, runpy, pydoc, getopt, importlib._bootstrap_external, _signal, locale, unittest.util, textwrap, gettext, logging, contextlib, _bootlocale, _threading_local, importlib.util, pkgutil, importlib.abc, platform, urllib.parse, tempfile, http, http.server, email, email.message, webbrowser, plistlib, socket, shutil, random, email.parser, hashlib, datetime, xml.parsers.expat, zipfile, email.feedparser, email._policybase, uu, email.charset, email._encoded_words, email.generator, email.iterators, email.policy, html, http.client, mimetypes, socketserver, base64, email.headerregistry, email.contentmanager, email.quoprimime, email._header_value_parser, ssl, calendar, email.base64mime, email.encoders, email.header, functools
Analysis version 400 has been completed in 2496.93 ms with 154 entries analyzed and 6 entries skipped.
Analysis of optparse (Library) queued. Dependencies: sys, os, textwrap, gettext
Analysis version 402 of 153 entries has started.
Restored from database:  tty 
Analysis of tty (Library) on depth 7 completed in 7.33 ms.
Analysis of zlib(Compiled) canceled (no AST yet).
Analysis of bz2(Library) canceled (no AST yet).
Analysis of lzma(Library) canceled (no AST yet).
Analysis of tarfile(Library) canceled (no AST yet).
Analysis of quopri(Library) canceled (no AST yet).
Analysis of email.utils(Library) canceled (no AST yet).
Analysis of _sha256(Compiled) canceled (no AST yet).
Analysis of _sha512(Compiled) canceled (no AST yet).
Analysis of _blake2(Compiled) canceled (no AST yet).
Analysis of _sha3(Compiled) canceled (no AST yet).
Analysis of _strptime(Library) canceled (no AST yet).
Analysis of _datetime(Compiled) canceled (no AST yet).
Analysis of py_compile(Library) canceled (no AST yet).
Analysis of _sha512 (Compiled) queued. Dependencies: 
Restored from database:  _weakref 
Analysis of _sha256 (Compiled) queued. Dependencies: 
Analysis of py_compile (Library) queued. Dependencies: enum, importlib, importlib._bootstrap_external, importlib.machinery, importlib.util, os, sys, traceback
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 44.85 ms.
Analysis of _blake2 (Compiled) queued. Dependencies: 
Analysis of email.utils (Library) queued. Dependencies: os, re, time, random, socket, datetime, urllib, urllib.parse, email._parseaddr, email.charset
Analysis of _strptime (Library) queued. Dependencies: time, locale, calendar, re, datetime, _thread
Import:  email._parseaddr /usr/lib/python3.7/email/_parseaddr.py 
Analysis of _datetime (Compiled) queued. Dependencies: datetime
Analysis of email._parseaddr (Library) queued. Dependencies: time, calendar
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 317.16 ms.
Analysis of _sha3 (Compiled) queued. Dependencies: 
Analysis of zlib (Compiled) queued. Dependencies: 
Restored from database:  itertools 
Analysis of quopri (Library) queued. Dependencies: sys, getopt, binascii, io
Analysis of lzma (Library) queued. Dependencies: io, os, _compression, _lzma
Import:  _compression /usr/lib/python3.7/_compression.py 
Analysis of bz2 (Library) queued. Dependencies: io, os, warnings, _compression, threading, _bz2
Restored from database:  _io 
Create compiled (scraped):  _lzma /usr/lib/python3.7/lib-dynload/_lzma.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Create compiled (scraped):  _bz2 /usr/lib/python3.7/lib-dynload/_bz2.cpython-37m-x86_64-linux-gnu.so /usr/lib/python3.7/lib-dynload 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 407.81 ms.
Analysis of tarfile (Library) queued. Dependencies: sys, os, io, shutil, stat, time, struct, copy, re, pwd, grp, warnings, zlib, bz2, lzma, gzip, argparse
Restored from database:  io 
Import:  gzip /usr/lib/python3.7/gzip.py 
Fully cached modules cycle: _io, io
Analysis of _bz2 (Compiled) queued. Dependencies: 
Analysis of _compression (Library) queued. Dependencies: io
Analysis of gzip (Library) queued. Dependencies: struct, sys, time, os, zlib, io, _compression, warnings, errno
Analysis of _lzma (Compiled) queued. Dependencies: 
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  token 
Restored from database:  argparse 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  sre_compile 
Restored from database:  sre_parse 
Restored from database:  _locale 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  pprint 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  unittest.result 
Restored from database:  unittest.case 
Restored from database:  unittest.suite 
Restored from database:  unittest.loader 
Restored from database:  unittest.main 
Restored from database:  unittest.runner 
Restored from database:  unittest.signals 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  signal 
Restored from database:  threading 
Restored from database:  selectors 
Restored from database:  encodings.mbcs 
Restored from database:  dis 
Restored from database:  importlib 
Restored from database:  importlib.machinery 
Restored from database:  ast 
Restored from database:  cmd 
Restored from database:  bdb 
Restored from database:  code 
Restored from database:  glob 
Restored from database:  shlex 
Restored from database:  runpy 
Restored from database:  pydoc 
Restored from database:  getopt 
Restored from database:  importlib._bootstrap_external 
Restored from database:  _signal 
Restored from database:  locale 
Restored from database:  unittest.util 
Restored from database:  textwrap 
Restored from database:  gettext 
Restored from database:  logging 
Restored from database:  contextlib 
Restored from database:  _bootlocale 
Restored from database:  _threading_local 
Restored from database:  importlib.util 
Restored from database:  pkgutil 
Restored from database:  importlib.abc 
Restored from database:  platform 
Restored from database:  urllib.parse 
Restored from database:  tempfile 
Restored from database:  http 
Restored from database:  http.server 
Restored from database:  email 
Restored from database:  email.message 
Restored from database:  webbrowser 
Restored from database:  plistlib 
Restored from database:  socket 
Restored from database:  shutil 
Restored from database:  random 
Restored from database:  email.parser 
Restored from database:  hashlib 
Restored from database:  datetime 
Restored from database:  xml.parsers.expat 
Restored from database:  zipfile 
Restored from database:  email.feedparser 
Restored from database:  email._policybase 
Restored from database:  uu 
Restored from database:  email.charset 
Restored from database:  email._encoded_words 
Restored from database:  email.generator 
Restored from database:  email.iterators 
Restored from database:  email.policy 
Restored from database:  html 
Restored from database:  http.client 
Restored from database:  mimetypes 
Restored from database:  socketserver 
Restored from database:  base64 
Restored from database:  email.headerregistry 
Restored from database:  email.contentmanager 
Restored from database:  email.quoprimime 
Restored from database:  email._header_value_parser 
Restored from database:  ssl 
Restored from database:  calendar 
Restored from database:  email.base64mime 
Restored from database:  email.encoders 
Restored from database:  email.header 
Restored from database:  optparse 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, token, argparse, codecs, posixpath, enum, sre_compile, sre_parse, _locale, genericpath, posix, ntpath, subprocess, pprint, difflib, inspect, pdb, unittest, unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, string, encodings, signal, threading, selectors, encodings.mbcs, dis, importlib, importlib.machinery, ast, cmd, bdb, code, glob, shlex, runpy, pydoc, getopt, importlib._bootstrap_external, _signal, locale, unittest.util, textwrap, gettext, logging, contextlib, _bootlocale, _threading_local, importlib.util, pkgutil, importlib.abc, platform, urllib.parse, tempfile, http, http.server, email, email.message, webbrowser, plistlib, socket, shutil, random, email.parser, hashlib, datetime, xml.parsers.expat, zipfile, email.feedparser, email._policybase, uu, email.charset, email._encoded_words, email.generator, email.iterators, email.policy, html, http.client, mimetypes, socketserver, base64, email.headerregistry, email.contentmanager, email.quoprimime, email._header_value_parser, ssl, calendar, email.base64mime, email.encoders, email.header, optparse, functools
Analysis version 402 has been completed in 2796.85 ms with 138 entries analyzed and 15 entries skipped.
Analysis version 425 of 157 entries has started.
Restored from database:  zlib 
Analysis of zlib (Compiled) on depth 9 completed in 4.29 ms.
Restored from database:  grp 
Analysis of grp (Compiled) on depth 9 completed in 2.65 ms.
Restored from database:  email.errors 
Analysis of email.errors (Library) on depth 8 completed in 4.63 ms.
Restored from database:  _ssl 
Analysis of _ssl (Compiled) on depth 10 completed in 48.63 ms.
Restored from database:  html.entities 
Analysis of html.entities (Library) on depth 9 completed in 27.71 ms.
Restored from database:  pyexpat 
Analysis of pyexpat (Compiled) on depth 10 completed in 4.11 ms.
Restored from database:  _sha1 
Analysis of _sha1 (Compiled) on depth 10 completed in 1.52 ms.
Restored from database:  _md5 
Analysis of _md5 (Compiled) on depth 10 completed in 1.26 ms.
Restored from database:  _sha256 
Analysis of _sha256 (Compiled) on depth 10 completed in 1.35 ms.
Restored from database:  _sha512 
Analysis of _sha512 (Compiled) on depth 10 completed in 1.85 ms.
Restored from database:  _blake2 
Analysis of _blake2 (Compiled) on depth 10 completed in 3.85 ms.
Restored from database:  _sha3 
Analysis of _sha3 (Compiled) on depth 10 completed in 8.53 ms.
Restored from database:  _hashlib 
Analysis of _hashlib (Compiled) on depth 10 completed in 3.6 ms.
Restored from database:  _bisect 
Analysis of _bisect (Compiled) on depth 10 completed in 3.19 ms.
Restored from database:  _lzma 
Analysis of _lzma (Compiled) on depth 10 completed in 4.86 ms.
Restored from database:  _bz2 
Analysis of _bz2 (Compiled) on depth 10 completed in 3.08 ms.
Restored from database:  bisect 
Analysis of bisect (Library) on depth 9 completed in 2.47 ms.
Restored from database:  _weakref 
Analysis of _weakref (CompiledBuiltin) on depth 3 completed in 3.15 ms.
Restored from database:  _weakrefset 
Analysis of _weakrefset (Library) on depth 3 completed in 8.75 ms.
Restored from database:  _py_abc 
Analysis of _py_abc (Library) on depth 3 completed in 2.75 ms.
Restored from database:  abc 
Analysis of abc (Library) on depth 2 completed in 3.45 ms.
Restored from database:  _io 
Restored from database:  io 
Fully cached modules cycle: _io, io
Restored from database:  _compression 
Analysis of _compression (Library) on depth 10 completed in 3.58 ms.
Restored from database:  itertools 
Analysis of itertools (CompiledBuiltin) on depth 3 completed in 35.14 ms.
Restored from database:  _thread 
Analysis of _thread (CompiledBuiltin) on depth 2 completed in 4.06 ms.
Restored from database:  reprlib 
Analysis of reprlib (Library) on depth 2 completed in 6.23 ms.
Restored from database:  types 
Restored from database:  weakref 
Restored from database:  _functools 
Restored from database:  collections 
Restored from database:  _collections_abc 
Restored from database:  sys 
Restored from database:  heapq 
Restored from database:  warnings 
Restored from database:  copy 
Restored from database:  operator 
Restored from database:  keyword 
Restored from database:  _collections 
Restored from database:  linecache 
Restored from database:  tracemalloc 
Restored from database:  re 
Restored from database:  traceback 
Restored from database:  doctest 
Restored from database:  os 
Restored from database:  tokenize 
Restored from database:  _operator 
Restored from database:  fnmatch 
Restored from database:  pickle 
Restored from database:  collections.abc 
Restored from database:  token 
Restored from database:  argparse 
Restored from database:  codecs 
Restored from database:  posixpath 
Restored from database:  enum 
Restored from database:  sre_compile 
Restored from database:  sre_parse 
Restored from database:  _locale 
Restored from database:  genericpath 
Restored from database:  posix 
Restored from database:  ntpath 
Restored from database:  subprocess 
Restored from database:  pprint 
Restored from database:  difflib 
Restored from database:  inspect 
Restored from database:  pdb 
Restored from database:  unittest 
Restored from database:  unittest.result 
Restored from database:  unittest.case 
Restored from database:  unittest.suite 
Restored from database:  unittest.loader 
Restored from database:  unittest.main 
Restored from database:  unittest.runner 
Restored from database:  unittest.signals 
Restored from database:  string 
Restored from database:  encodings 
Restored from database:  signal 
Restored from database:  threading 
Restored from database:  selectors 
Restored from database:  encodings.mbcs 
Restored from database:  dis 
Restored from database:  importlib 
Restored from database:  importlib.machinery 
Restored from database:  ast 
Restored from database:  cmd 
Restored from database:  bdb 
Restored from database:  code 
Restored from database:  glob 
Restored from database:  shlex 
Restored from database:  runpy 
Restored from database:  pydoc 
Restored from database:  getopt 
Restored from database:  importlib._bootstrap_external 
Restored from database:  _signal 
Restored from database:  locale 
Restored from database:  unittest.util 
Restored from database:  textwrap 
Restored from database:  gettext 
Restored from database:  logging 
Restored from database:  contextlib 
Restored from database:  _bootlocale 
Restored from database:  _threading_local 
Restored from database:  importlib.util 
Restored from database:  pkgutil 
Restored from database:  importlib.abc 
Restored from database:  platform 
Restored from database:  urllib.parse 
Restored from database:  tempfile 
Restored from database:  http 
Restored from database:  http.server 
Restored from database:  email 
Restored from database:  email.message 
Restored from database:  webbrowser 
Restored from database:  plistlib 
Restored from database:  socket 
Restored from database:  shutil 
Restored from database:  random 
Restored from database:  email.parser 
Restored from database:  hashlib 
Restored from database:  datetime 
Restored from database:  xml.parsers.expat 
Restored from database:  bz2 
Restored from database:  lzma 
Restored from database:  tarfile 
Restored from database:  zipfile 
Restored from database:  email.feedparser 
Restored from database:  email._policybase 
Restored from database:  uu 
Restored from database:  quopri 
Restored from database:  email.utils 
Restored from database:  email.charset 
Restored from database:  email._encoded_words 
Restored from database:  email.generator 
Restored from database:  email.iterators 
Restored from database:  email.policy 
Restored from database:  html 
Restored from database:  http.client 
Restored from database:  mimetypes 
Restored from database:  socketserver 
Restored from database:  base64 
Restored from database:  email.headerregistry 
Restored from database:  email.contentmanager 
Restored from database:  email.quoprimime 
Restored from database:  email._header_value_parser 
Restored from database:  ssl 
Restored from database:  calendar 
Restored from database:  email.base64mime 
Restored from database:  email.encoders 
Restored from database:  email.header 
Restored from database:  optparse 
Restored from database:  _strptime 
Restored from database:  _datetime 
Restored from database:  py_compile 
Restored from database:  email._parseaddr 
Restored from database:  gzip 
Restored from database:  functools 
Fully cached modules cycle: types, weakref, _functools, collections, _collections_abc, sys, heapq, warnings, copy, operator, keyword, _collections, linecache, tracemalloc, re, traceback, doctest, os, tokenize, _operator, fnmatch, pickle, collections.abc, token, argparse, codecs, posixpath, enum, sre_compile, sre_parse, _locale, genericpath, posix, ntpath, subprocess, pprint, difflib, inspect, pdb, unittest, unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, string, encodings, signal, threading, selectors, encodings.mbcs, dis, importlib, importlib.machinery, ast, cmd, bdb, code, glob, shlex, runpy, pydoc, getopt, importlib._bootstrap_external, _signal, locale, unittest.util, textwrap, gettext, logging, contextlib, _bootlocale, _threading_local, importlib.util, pkgutil, importlib.abc, platform, urllib.parse, tempfile, http, http.server, email, email.message, webbrowser, plistlib, socket, shutil, random, email.parser, hashlib, datetime, xml.parsers.expat, bz2, lzma, tarfile, zipfile, email.feedparser, email._policybase, uu, quopri, email.utils, email.charset, email._encoded_words, email.generator, email.iterators, email.policy, html, http.client, mimetypes, socketserver, base64, email.headerregistry, email.contentmanager, email.quoprimime, email._header_value_parser, ssl, calendar, email.base64mime, email.encoders, email.header, optparse, _strptime, _datetime, py_compile, email._parseaddr, gzip, functools
Analysis of main (User) on depth 0 completed in 0.3 ms.
Analysis complete: 213 modules in 19486.64 ms.
Analysis version 425 of 157 entries has been completed in 2549 ms.
```

The ending of:

```
Analysis of main (User) on depth 0 completed in 0.3 ms.
Analysis complete: 213 modules in 19486.64 ms.
Analysis version 425 of 157 entries has been completed in 2549 ms.
```

Is nowhere near what it was before #1686.

**Comment by MikhailArkhipov** [comment]
Frankly I would switch off caching for now as it is changing. Loop resolution fix is not completely tested with caching either. But up to you.

**Comment by jakebailey** [comment]
I'll probably have to disable it, though I think this PR needs to be going in anyway (since I think the existing behavior produces weird results and I'd rather not leave partially broken code around when I have a fix).
