### PR TITLE
Multiple analysis fixes

### LINKED ISSUE #1151: Reliable way to determine final analysis of a module
Continuation of #1143.

This will
- improve performance since we can delay some activities, such as linting run until everything is settled for the module. 
- Prevent unnecessary reloads and reparses when AST was dropped too early per https://github.com/microsoft/python-language-server/pull/1134 for #1088 .
- Better determine when module analysis can be persisted into a database.

One possible way is to simulate analysis run, i.e.

Run all sessions but with only parsing in order determine final session and then
Run analysis without parsing repeating the above.
Technically end point should be the same.

### LINKED ISSUE #1201: NRE in SymbolCollector.AddProperty
```
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddProperty(FunctionDefinition, IPythonType, Boolean) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 170
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.TryAddProperty(FunctionDefinition, IPythonType) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 158
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddFunctionOrProperty(FunctionDefinition) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 101
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.Walk(FunctionDefinition) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 77
Microsoft.Python.Parsing.Ast.FunctionDefinition.Walk(PythonWalker) in Parsing\Impl\Ast\FunctionDefinition.cs:line 197
```

Not sure what could be null at line 170, though. Maybe it's getting optimized and `fd` is null and is breaking at `fd.Name`.

### LINKED ISSUE #1228: NRE in TryFindMissingDependencies
```
Microsoft.Python.Analysis.Dependencies.DependencyResolver`2.TryFindMissingDependencies(ImmutableArray`1&, ImmutableArray`1&, Int32) in Analysis\Ast\Impl\Dependencies\DependencyResolver.cs:line 563
Microsoft.Python.Analysis.Dependencies.DependencyResolver`2.TryCreateWalker(Int32, Int32, IDependencyChainWalker`2&) in Analysis\Ast\Impl\Dependencies\DependencyResolver.cs:line 214
Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.TryCreateSession(Int32, PythonAnalyzerEntry, PythonAnalyzerSession&) in Analysis\Ast\Impl\Analyzer\PythonAnalyzer.cs:line 246
Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.AnalyzeDocument(AnalysisModuleKey, PythonAnalyzerEntry, ImmutableArray`1) in Analysis\Ast\Impl\Analyzer\PythonAnalyzer.cs:line 224
```

Line 563 is just `version != _version`, neither of which can ever be null (they're `int`!!!). Happening just as often as the GetBodyStartIndex NRE.

cc @AlexanderSher

### LINKED ISSUE #1294: Handle valid case for reloading AST
1. Create module with code `import datetime`
2. Wait for analysis to complete. `LibraryAnalysis` will be created for `datetime` module
3. F12 on `datetime`

Opened module should be correctly handled.

### LINKED ISSUE #1295: FindReferences doesn't work on package init members
`package/__init__.py`:
```
x = 1
```
`module.py`:
```
import package
y = package.x
```

FindReferences doesn't show reference in `module.py`

### LINKED ISSUE #1296: DependencyResolver graph misses intermediate imports
If `module` is imported as `import package.module` and `package` has `__init__.py`, `package` won't be a dependency in DependencyResolver. As a result, `package` is analyzed later than it should and additional iteration of analysis is triggered.

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fixes #1151: Reliable way to determine final analysis of a module
- Fixes #1201: NRE in SymbolCollector.AddProperty
- Fixes #1228: NRE in TryFindMissingDependencies
- Fixes #1294: Handle valid case for reloading AST
- Fixes #1295: FindReferences doesn't work on package init members
- Fixes #1296: DependencyResolver graph misses intermediate imports
- Part of the fix for #1174: All references are not listed when using ms language server (bug isn't fully fixed).

### CODE REVIEW

File: src/Analysis/Ast/Impl/Analyzer/ActivityTracker.cs [hunk 1]
```diff
@@ -19,48 +19,21 @@
 
 namespace Microsoft.Python.Analysis.Analyzer {
     internal static class ActivityTracker {
-        private static readonly Dictionary<string, AnalysisState> _modules = new Dictionary<string, AnalysisState>();
+        private static readonly HashSet<string> _modules = new HashSet<string>();
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/ActivityTracker.cs]: `AnalysisState` has never been used

File: src/Analysis/Ast/Impl/Analyzer/AnalysisModuleKey.cs [hunk 2]
```diff
@@ -15,39 +15,56 @@
...
-    internal struct AnalysisModuleKey : IEquatable<AnalysisModuleKey> {
+    internal readonly struct AnalysisModuleKey : IEquatable<AnalysisModuleKey> {
+        private enum KeyType { Default, Typeshed, LibraryAsDocument }
+
+        private readonly KeyType _type;
         public string Name { get; }
         public string FilePath { get; }
-        public bool IsTypeshed { get; }
+        public bool IsTypeshed => _type == KeyType.Typeshed;
+        public bool IsLibraryAsDocument => _type == KeyType.LibraryAsDocument;
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/AnalysisModuleKey.cs]: This is a change for the #1294. Opened library module may be part of the loop, so with `LibraryAnalysis` it will trigger reparsing of all the modules in the loop. As a workaroung, we create new instance of the `PythonAnalyzerEntry` that will contain `DocumentAnalysis`.

File: src/Analysis/Ast/Impl/Analyzer/Definitions/IPythonAnalyzer.cs [hunk 3]
```diff
@@ -20,14 +20,15 @@
...
+using Microsoft.Python.Parsing.Ast;
 
 namespace Microsoft.Python.Analysis.Analyzer {
     public interface IPythonAnalyzer {
         Task WaitForCompleteAnalysisAsync(CancellationToken cancellationToken = default);
         /// <summary>
         /// Schedules module for analysis. Module will be scheduled if version of AST is greater than the one used to get previous analysis
         /// </summary>
-        void EnqueueDocumentForAnalysis(IPythonModule module, int version);
+        void EnqueueDocumentForAnalysis(IPythonModule module, PythonAst ast, int version);
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/Definitions/IPythonAnalyzer.cs]: There were several cases when `ast` was out of sync, so we need to pass to `PythonAnalyzer` explicitly.

File: src/Analysis/Ast/Impl/Analyzer/Handlers/ImportHandler.cs [hunk 4]
```diff
@@ -56,19 +56,22 @@ internal sealed partial class ImportHandler : StatementHandler {
             // import_module('fob.oar.baz')
             var importNames = ImmutableArray<string>.Empty;
             var variableModule = default(PythonVariableModule);
+            var importedNamesCount = 0;
             foreach (var nameExpression in moduleImportExpression.Names) {
                 importNames = importNames.Add(nameExpression.Name);
                 var imports = ModuleResolution.CurrentPathResolver.GetImportsFromAbsoluteName(Module.FilePath, importNames, forceAbsolute);
                 if (!HandleImportSearchResult(imports, variableModule, asNameExpression, moduleImportExpression, out variableModule)) {
-                    return;
+                    break;
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/Handlers/ImportHandler.cs]: This handles a case when `import package.subpackage.module` fails on `subpackage` part, but `package` has `__init__.py` and successfully imported.

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs [hunk 5]
```diff
@@ -120,11 +122,13 @@ public Task WaitForCompleteAnalysisAsync(CancellationToken cancellationToken = d
         }
 
         public void RemoveAnalysis(IPythonModule module) {
+            AnalysisModuleKey key;
             lock (_syncObj) {
-                _analysisEntries.Remove(new AnalysisModuleKey(module));
+                key = new AnalysisModuleKey(module);
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs]: Since `key` reads `IsOpen` property of the `IDocument`, we need to access it under lock.

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs [hunk 6]
```diff
@@ -144,24 +148,36 @@ public Task WaitForCompleteAnalysisAsync(CancellationToken cancellationToken = d
...
+
             lock (_syncObj) {
+                key = new AnalysisModuleKey(module);
                 version = _version + 1;
                 if (_analysisEntries.TryGetValue(key, out entry)) {
                     if (entry.BufferVersion >= bufferVersion) {
                         return;
                     }
+
+                    // It is possible that parsing request for the library has been started when document is open,
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs]: This happens when `Go to definition` is done by `Ctrl+Click`. We got three events in a row: `didOpen`, `didClose`, `didOpen`.

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs [hunk 7]
```diff
@@ -205,12 +221,12 @@ public Task WaitForCompleteAnalysisAsync(CancellationToken cancellationToken = d
...
             => AnalysisComplete?.Invoke(this, new AnalysisCompleteEventArgs(moduleCount, msElapsed));
 
-        private void AnalyzeDocument(AnalysisModuleKey key, PythonAnalyzerEntry entry, ImmutableArray<AnalysisModuleKey> dependencies) {
+        private void AnalyzeDocument(in AnalysisModuleKey key, in PythonAnalyzerEntry entry, in ImmutableArray<AnalysisModuleKey> dependencies) {
             _analysisCompleteEvent.Reset();
             ActivityTracker.StartTracking();
             _log?.Log(TraceEventType.Verbose, $"Analysis of {entry.Module.Name}({entry.Module.ModuleType}) queued");
 
-            var graphVersion = _dependencyResolver.ChangeValue(key, entry, entry.IsUserModule, dependencies);
+            var graphVersion = _dependencyResolver.ChangeValue(key, entry, entry.IsUserOrBuiltin || key.IsLibraryAsDocument, dependencies);
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs]: Since library module is added to the graph as a separate entry, it doesn't have any references. So we need to add it as root to trigger analysis.

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerEntry.cs [hunk 8]
```diff
@@ -285,8 +297,14 @@ private class DependencyWalker : PythonWalker {
             }
 
             public override bool Walk(ImportStatement import) {
+                var forceAbsolute = import.ForceAbsolute;
                 foreach (var moduleName in import.Names) {
-                    HandleSearchResults(_pathResolver.FindImports(_module.FilePath, moduleName, import.ForceAbsolute));
+                    var importNames = ImmutableArray<string>.Empty;
```
Comment (AlexanderSher) [inline src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerEntry.cs]: This fixes #1296

File: src/Analysis/Ast/Impl/Analyzer/Definitions/IPythonAnalyzer.cs (hunk 3 above)
Comment (jakebailey) [reply src/Analysis/Ast/Impl/Analyzer/Definitions/IPythonAnalyzer.cs]: Wouldn't this indicate some other race condition, if the module's Ast is changing during an analysis? When would this occur? When the user modifies their code?

Comment (AlexanderSher) [reply src/Analysis/Ast/Impl/Analyzer/Definitions/IPythonAnalyzer.cs]: Any change to the file, including opening/closing it. I'm not sure that having separate Parse/Analyze queue is still valuable for us, cause we don't have analysis on demand anymore - we use a graph, but that would be a separate change that I don't want to make until database support is in master.
