### PR TITLE
Merge persistence work into master

### LINKED ISSUE #1531: CompletionItemKind of 0 (None) causes language server clients to fail
## Environment data

- Language Server version: `master` branch (last compiled on `51b2532ddc0161aecadda182b33f1b15ed6093b0`
- OS and version: MacOS 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4

## Expected behaviour

Python Language Server emits valid completion items.

## Actual behaviour

Python Language Server emits completion items with `kind` value of `0` as described in https://github.com/autozimu/LanguageClient-neovim/issues/633#issuecomment-515240338

Zero is not a valid `CompletionItemKind` according to the Language Server specification
https://microsoft.github.io/language-server-protocol/specification

>```
>/**
> * The kind of a completion entry.
> */
>namespace CompletionItemKind {
>	export const Text = 1;
>	export const Method = 2;
>	export const Function = 3;
>	export const Constructor = 4;
>	export const Field = 5;
>	export const Variable = 6;
>	export const Class = 7;
>	export const Interface = 8;
>	export const Module = 9;
>	export const Property = 10;
>	export const Unit = 11;
>	export const Value = 12;
>	export const Enum = 13;
>	export const Keyword = 14;
>	export const Snippet = 15;
>	export const Color = 16;
>	export const File = 17;
>	export const Reference = 18;
>	export const Folder = 19;
>	export const EnumMember = 20;
>	export const Constant = 21;
>	export const Struct = 22;
>	export const Event = 23;
>	export const Operator = 24;
>	export const TypeParameter = 25;
>}
>```

The result of Python Language Server emitting completion items with `"kind":0` breaks completion for language clients, like LanguageClient-neovim, that are set up to handle the Language Client spec.

## Logs

N/A

## Code Snippet / Additional lnformation

The example I gave in https://github.com/autozimu/LanguageClient-neovim/issues/633#issuecomment-515240338 was

```python
import logging

logging.getLogge
```

### LINKED ISSUE #1534: NRE from ToAbsolutePath via DefinitionSourceBase.TryFromVariable
```
   at Microsoft.Python.Core.UriExtensions.ToAbsolutePath(Uri uri) in E:\A\_work\3\s\src\Core\Impl\Extensions\UriExtensions.cs:line 22
   at Microsoft.Python.Analysis.Modules.PythonModule.get_Definition() in E:\A\_work\3\s\src\Analysis\Ast\Impl\Modules\PythonModule.cs:line 173
   at Microsoft.Python.LanguageServer.Sources.DefinitionSourceBase.TryFromVariable(String name, IDocumentAnalysis analysis, SourceLocation location, Node statement, ILocatedMember& definingMember) in E:\A\_work\3\s\src\LanguageServer\Impl\Sources\DefinitionSource.cs:line 209
   at Microsoft.Python.LanguageServer.Sources.DefinitionSourceBase.FindDefinition(IDocumentAnalysis analysis, SourceLocation location, ILocatedMember& definingMember) in E:\A\_work\3\s\src\LanguageServer\Impl\Sources\DefinitionSource.cs:line 105
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken) in E:\A\_work\3\s\src\LanguageServer\Impl\Implementation\Server.Editor.cs:
```

Similar to #1018 but a different backtrace. This comes from a `PythonModule` with a null URI. The code in `PythonModule` is written to allow null URIs `uri?.LocalPath`, but the `Definition` property still constructs a `LocationInfo` unconditionally.

I almost think `LocationInfo` could do with some cleanup; it double-stores paths via URI and filepath, among some other weirdness with `PythonModule.FilePath` being inconsistent with `LocationInfo` being "absolute" in some places but not others...

### LINKED ISSUE #1550: Testing libraries analysis with system modules cache
Testing libraries analysis with system modules cache: numpy, plotly, matplotlib, tensorflow, ... with caching of system libraries on.

Part of https://github.com/microsoft/python-language-server/pull/1482

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
We accumulated many bug fixes in db branch so it will be useful to merge it to master. Will turn off persistence service before merging.

Fixes #1531.
Fixes #1534
Fixes #1550.

### CODE REVIEW

File: src/Analysis/Ast/Impl/Dependencies/IDependencyProvider.cs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+using Microsoft.Python.Parsing.Ast;
+
+namespace Microsoft.Python.Analysis.Dependencies {
+    /// <summary>
+    /// Implements provider that can supply list of imports to the dependency analysis.
+    /// Regular modules provide dependency from the AST, persistent/database modules
+    /// provide dependencies from their models.
+    /// </summary>
+    internal interface IDependencyProvider {
+        HashSet<AnalysisModuleKey> GetDependencies(PythonAst ast);
```
Comment (jakebailey) [inline src/Analysis/Ast/Impl/Dependencies/IDependencyProvider.cs]: Should this be an `ISet` to keep the interface an interface? Not sure it much matters, since it's internal, but curious.

File: src/Analysis/Ast/Test/AssignmentTests.cs [hunk 2]
```diff
@@ -319,13 +319,13 @@ class D: ...
         }
 
         [TestMethod, Priority(0)]
-        public async Task AssignAfterClassDef() {
+        public async Task NoClassAssign() {
```
Comment (jakebailey) [inline src/Analysis/Ast/Test/AssignmentTests.cs]: Will this undo #1422?

File: src/Caching/Impl/Models/CallableModel.cs [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+            }
+            if(callable is IPythonFunctionType ft) {
+                if(ft.IsClassMethod) {
+                    Attributes |= FunctionAttributes.ClassMethod;
+                }
+                if (ft.IsStatic) {
+                    Attributes |= FunctionAttributes.Static;
+                }
+            }
+            //if (callable is IPythonPropertyType p) {
```
Comment (jakebailey) [inline src/Caching/Impl/Models/CallableModel.cs]: Should this just be removed since there's a property model? Or are you keeping this for something later?

File: src/Caching/Impl/ModuleDatabase.cs [hunk 4]
```diff
@@ -0,0 +1,259 @@
...
+using Microsoft.Python.Analysis.Modules;
+using Microsoft.Python.Analysis.Types;
+using Microsoft.Python.Core;
+using Microsoft.Python.Core.IO;
+using Microsoft.Python.Core.Logging;
+using Microsoft.Python.Parsing.Ast;
+
+namespace Microsoft.Python.Analysis.Caching {
+    internal sealed class ModuleDatabase : IModuleDatabaseService {
+        private const int _databaseFormatVersion = 1;
```
Comment (jakebailey) [inline src/Caching/Impl/ModuleDatabase.cs]: Would this be better named `DatabaseFormatVersion` to indicate that this isn't a member of the database (but some global-ish constant)?

File: src/Analysis/Ast/Test/AssignmentTests.cs (hunk 2 above)
Comment (MikhailArkhipov) [reply src/Analysis/Ast/Test/AssignmentTests.cs]: Workaround for enum.py unfortunately. See `AssignmentHandler`
```cs
                if(m?.MemberType == PythonMemberType.Class) {
                    // Ignore assignments to classes: enum.py does Enum = None
                    // which prevents persistence from restoring proper type from enum:Enum.
                    continue; 
                }
```

File: src/Analysis/Ast/Test/TypeshedTests.cs [hunk 5]
```diff
@@ -45,7 +45,7 @@ import sys
 e1, e2, e3 = sys.exc_info()
 ";
             var analysis = await GetAnalysisAsync(code);
-            // sys.exc_info() -> (exception_type, exception_value, traceback)
+            // def exc_info() -> Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]: ...
```
Comment (jakebailey) [inline src/Analysis/Ast/Test/TypeshedTests.cs]: A note to check https://github.com/microsoft/python-language-server/issues/1371#issuecomment-515232161 with this PR merged. The cumulative fixes might make typeshed updatable.

File: src/LanguageServer/Test/HoverTests.cs [hunk 6]
```diff
@@ -89,7 +89,7 @@ class C:
 import datetime
 datetime.datetime.now().day
 ";
-            var analysis = await GetAnalysisAsync(code, PythonVersions.LatestAvailable3X);
+            var analysis = await GetAnalysisAsync(code, is3x ? PythonVersions.LatestAvailable3X : PythonVersions.LatestAnaconda2X);
```
Comment (jakebailey) [inline src/LanguageServer/Test/HoverTests.cs]: `LatestAvailable2X`? Weird to use Anaconda here.

File: src/Analysis/Ast/Test/AssignmentTests.cs (hunk 2 above)
Comment (MikhailArkhipov) [reply src/Analysis/Ast/Test/AssignmentTests.cs]: Restored

**Comment by AlexanderSher** [comment]
Let's merge it so I can apply numpy fixes over it.
