### PR TITLE
Linter for undefined variables

### LINKED ISSUE #395: Use-before-def reported for class fields without default values
Environment data
VS Code version: 1.29.0
Extension version (available under the Extensions sidebar): 2018.10.1
OS and version: OSX
Python version (& distribution if applicable, e.g. Anaconda): python 3.7
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv

Actual behavior
Python 3.7 dataclass properties are incorrectly reported as "used before definition". The same syntax with default values added is not reported. 

screen shot 2018-11-14 at 07 54 00

Expected behavior
The properties are not reported.

Steps to reproduce:
See screenshot above.

BTW: is it possible (as a workaround to above issue) to suppress warnings for a given block/line?

### LINKED ISSUE #461: Using the collecting variable of iterable unpacking causes "used before definition" error
Microsoft/vscode-python#3543

```python
a, *b, c = range(5)
print(b)
```

`b` ends up being reported as used before definition.

### LINKED ISSUE #475: Variable used before definition
@azdanov commented on [Sat Dec 08 2018](https://github.com/Microsoft/vscode-python/issues/3598)

## Environment data

- VS Code version: 1.29.1 (1.29.1)
- Extension version (available under the Extensions sidebar): 2018.11.0
- OS and version: macOS Mojave 10.14.1 (18B75)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.1 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 
- Relevant/affected Python packages and their versions: -

## Expected behaviour

When running provided code snippet there should be no warning.

```python
from typing import Dict

fallbackName: Dict[str, str] = {"firstName": "First", "lastName": "Last"}

NAME = " ".join(str(x) for x in fallbackName.values())

print(f"Hi, {NAME}!")
```

## Actual behaviour

A warning is generated: `'fallbackName' used before definition`
```json
{
	"resource": "/Users/_____/Projects/python/sandbox/index.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "use-before-def",
	"severity": 4,
	"message": "'fallbackName' used before definition",
	"source": "Python",
	"startLineNumber": 5,
	"startColumn": 33,
	"endLineNumber": 5,
	"endColumn": 45
}
```

## Additional Info

This does not happen when type hinting is removed:

```python
FALLBACK_NAME = {"first_name": "First", "last_name": "Last"}

NAME = " ".join(str(x) for x in FALLBACK_NAME.values())

print(f"Hi, {NAME}!")
```

## Steps to reproduce:
1. Create a new project, `python3 -m venv new/venv`.
2. Insert code into `new/index.py`.
3. Lint.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.66.0
Initializing for /Users/_____/Projects/python/sandbox/venv/bin/python
##########Linting Output - prospector##########
{
  "summary": {
    "started": "2018-12-08 12:13:01.666245",
    "libraries": [],
    "strictness": "from profile",
    "profiles": ".prospector.yaml, full_pep8, doc_warnings, strictness_veryhigh, no_member_warnings",
    "tools": [
      "dodgy",
      "mccabe",
      "mypy",
      "pep257",
      "pep8",
      "profile-validator",
      "pyflakes",
      "pylint"
    ],
    "message_count": 0,
    "completed": "2018-12-08 12:13:02.171521",
    "time_taken": "0.51",
    "formatter": "json"
  },
  "messages": []
}
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
 INFO no standard startup: not a new window
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern */python
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern */*/python
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Register Intepreter Watcher, Arg 1: {"$mid":1,"fsPath":"/Users/_____/Projects/python/sandbox","external":"file:///Users/_____/Projects/python/sandbox","path":"/Users/_____/Projects/python/sandbox","scheme":"file"}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern */python
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern */*/python
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Build the workspace interpreter watcher, Arg 1: {"$mid":1,"fsPath":"/Users/_____/Projects/python/sandbox","external":"file:///Users/_____/Projects/python/sandbox","path":"/Users/_____/Projects/python/sandbox","scheme":"file"}, Return Value: UNABLE TO DETERMINE VALUE
console.ts:134 [Extension Host] Python Extension: Register Intepreter Watcher, Arg 1: undefined, Return Value: 
console.ts:134 [Extension Host] Python Extension: Build the workspace interpreter watcher, Arg 1: undefined, Return Value: UNABLE TO DETERMINE VALUE
console.ts:134 [Extension Host] Python Extension: Get language server folder name, , Return Value: "languageServer.0.1.66"
6console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
```

---

@yehorb commented on [Sat Dec 08 2018](https://github.com/Microsoft/vscode-python/issues/3598#issuecomment-445496364)

I have a similar issue with my Python.
VS Code version: 1.29.1 (1.29.1)
Extension version (available under the Extensions sidebar): 2018.11.0
OS and version: Ubuntu 18.04.1 LTS
Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.7 64-bit
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
Relevant/affected Python packages and their versions: not relevant

Issues disappear if you reload window, but reappear if I make even the slightest edit to the code written. Sometimes they appear as I type (e.g. I type "return True" and issues are " 're' used before definition", " 'ret' used before definition" and so on).

Issue appears to occur more in longer files.

screenshot from 2018-12-09 00-47-41
screenshot from 2018-12-09 00-47-53

---

@azdanov commented on [Sat Dec 08 2018](https://github.com/Microsoft/vscode-python/issues/3598#issuecomment-445517763)

@yehorb Could you create a minimal Github repo with a reproducible error? It will help a lot in fixing this issue.

In my case, this happens because of `typing`.

---

@yehorb commented on [Mon Dec 10 2018](https://github.com/Microsoft/vscode-python/issues/3598#issuecomment-445784058)

Here:
https://github.com/yehorb/VSCode-use-before-def-bug

This is the output I get:
screenshot from 2018-12-10 12-59-08
screenshot from 2018-12-10 12-59-19
screenshot from 2018-12-10 12-59-32
screenshot from 2018-12-10 12-59-51
screenshot from 2018-12-10 13-00-12
screenshot from 2018-12-10 13-00-32
screenshot from 2018-12-10 13-00-38
screenshot from 2018-12-10 13-00-46

---

@azdanov commented on [Mon Dec 10 2018](https://github.com/Microsoft/vscode-python/issues/3598#issuecomment-445798647)

@yehorb Awesome, thanks! Now it's just waiting for a maintainer to triage this issue. 🤷‍♂️

### LINKED ISSUE #476: Class variable used in class comprehension lints "used before definition."
@rnapier commented on [Thu Dec 06 2018](https://github.com/Microsoft/vscode-python/issues/3575)

## Environment data

- VS Code version: Version 1.29.1 (1.29.1)
- Extension version (available under the Extensions sidebar): 2018.11.0
- OS and version: macOS 10.14.1 (18B75)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

Given the following code:

```
class C:
    EVENTS = ["x"]
    x = [(e, e) for e in EVENTS]
    y = EVENTS
```

The linter should discover no issues.

## Actual behaviour

The use of `EVENTS` in the definition of `x` is linted as "used before definition" (use-before-def). (The definition of `y` does not generate a linter message.)

## Steps to reproduce:
1. Create python 3.6 file with above code.
2. Python: Run Linting

## Logs

None

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

None

### LINKED ISSUE #513: PLS incorrectly reports error for self-assignment to local variable
The analyzer incorrectly flags the following (admittedly strange) code with a use-before-def error/warning.

screen shot 2018-12-26 at 10 45 46 am

The problem is due to a somewhat hacky piece of code in `DDG.Walk(AssignmentStatement node)` that attempts to detect the case "fob = fob" and temporarily manipulate the scope before evaluating the RHS of the assignment. This hack is problematic for a number of reasons. For example, it doesn't properly handle other more complex expressions like "fob = fob + 1".

I think the preferable solution is to remove the hack but modify the logic to allow _reading_ of symbols in outer scopes even if `VisibleToChildren` is false. This property should probably be renamed `WritableByChildren` since Python allows reading of symbols from outer scopes.

See the following documentation in [section 2.1 of the official Python docs](https://docs.python.org/3.7/tutorial/classes.html).

screen shot 2018-12-26 at 10 59 02 am

### LINKED ISSUE #639: Implement detection of undefined variables
Replacement using new LS

### LINKED ISSUE #682: Implement tracking variable values by location
For better intellisense we need to track variable assignment locations so in

```python
x = 1
x. # yields completions for int
x = 's'
x. # yields completions for str
```
see also #668 for `isinstance` so

```python
from typing import Union, List

class Foo: pass
class Bar: pass

FB = Union[Foo, List[Bar]]

def do(fb: FB):
    if isinstance(fb, list):
        fb. # completions for list
        return fb[0]
    else:
        fb. # completions for Foo
```

### LINKED ISSUE #734: local variables don't show up in completion
image

Repro code:
```py
from flake8.formatting.base import BaseFormatter
from xml.etree import ElementTree as ET

class Flake8formatter(BaseFormatter):
    def format(self, error):
        return '{0!r}'.format(error)
   
    def show_benchmarks(self, benchmarks):
        for benchmark, value in benchmarks:
            if ben
            testcase = ET.Element('benchmark')
            testcase.attrib['classname'] = 'flake8.benchmarks'
            testcase.attrib['name'] = benchmark
            testcase.attrib['value'] = value

```

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #639 
Fixes #395 
Fixes #461 
Fixes #475 
Fixes #476 
Fixes #513
Fixes #682
Fixes #734

- Walk AST post analysis and use analysis to find out declared variables. Special filtering and handling of comprehensions. Includes #711
- Adds support for analysis of comprehensions. Fixes issue when comprehension variables were not declared in scope. Adds handling of tuple expressions in `for in` loops.
- Adds support for lambdas. Enables related tests.

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
Added settings plumbing to turn linter on/off via existing extension setting.

File: src/LanguageServer/Impl/LanguageServer.cs [hunk 1]
```diff
@@ -111,6 +112,9 @@ private void OnApplyWorkspaceEdit(object sender, ApplyWorkspaceEditEventArgs e)
                 settings.symbolsHierarchyDepthLimit = GetSetting(analysis, "symbolsHierarchyDepthLimit", 10);
                 settings.symbolsHierarchyMaxSymbols = GetSetting(analysis, "symbolsHierarchyMaxSymbols", 1000);
 
+                var linting = pythonSection["linting"];
+                _optionsProvider.Options.LintingEnabled = GetSetting(linting, "enabled", true);
```
Comment (jakebailey) [inline src/LanguageServer/Impl/LanguageServer.cs]: I don't like using `python.linting.enabled` for our toggle. That's what the extension already uses for toggling pylint/pycodestyle/etc, and having it enabled means prompts and buttons unrelated to the language server. I'd rather use `python.analysis.linting` or something for now.

**Comment by jakebailey** [comment]
There are a few false positives, which can be seen in `least_angle.py` in the scikit-learn repo

- Builtin types (`str`, `DeprecationWarning`)
- Uses of function parameters.
- Some builtin functions like `print`, `isinstance`, `abs`.

File: src/LanguageServer/Impl/LanguageServer.cs (hunk 1 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/LanguageServer.cs]: That's a question to @qubitron since multiple almost same settings confuse users. They don't know what analysis is and what is the difference.

Comment (jakebailey) [reply src/LanguageServer/Impl/LanguageServer.cs]: Seems like the extension now has `python.linting.pylintEnabled` (and so on), so maybe this wouldn't be a big deal. We probably need to look at `python.linting.enabled`, then at something like `python.linting.plsEnabled` or similar to match that pattern.

@DonJayamanne

**Comment by MikhailArkhipov** [comment]
Any specific for function arguments?

**Comment by jakebailey** [comment]
`lars_path`:

image

**Comment by jakebailey** [comment]
image

But:

```python
def lars_path(X, y, Xy=None, Gram=None, max_iter=500,
              alpha_min=0, method='lar', copy_X=True,
              eps=np.finfo(np.float).eps,
              copy_Gram=True, verbose=0, return_path=True,
              return_n_iter=False, positive=False):
```

**Comment by jakebailey** [comment]
That seemed to fix many of the cases, but some still seem to be reported, like:

image

`method` is still reported (it's also a param), but `X` and `y` aren't anymore with that commit. `alpha_min`, `copy_Gram` are reported, and `drop` is too though it's a local variable and not a parameter, defined as `drop = False` at the topmost level of that function.

**Comment by MikhailArkhipov** [comment]
Yes, analysis was missing handling of comprehension (list) statements, handling of tuple expressions in for loops as well as handling of lambdas. Basically analysis issues, less of that of the linter. Related #734 which also requires the above.

**Comment by jakebailey** [comment]
Working a lot better now, one more thing in scikit-learn's `k_means_.py`:

image

Which is caused by a `pyx` import:

image

However if I try to make a minimal example where I do `from idontexist import foo` and use `foo`, it doesn't warn.

**Comment by jakebailey** [comment]
This one seems to be tuple/iterator related as well (`hierarchical.py` next to `k_means_.py`):

image

**Comment by MikhailArkhipov** [comment]
Speaking of imports @AlexanderSher can comment. I think there are different cases when imported variable was declared as unknown (and hence IS defined technically) vs code didn't even reach state of declarations as, I guess, happens with `pyx`.

I'll look into the iterator

**Comment by AlexanderSher** [comment]
> Which is caused by a pyx import:

Yes, we don't support CPython.

**Comment by jakebailey** [comment]
Right, but I think what is weird is that in one case, if the imported module doesn't exist like `from idontexist import foo`, `foo` is declared, but when it's `idontexist.pyx` or similar, then doing the same thing causes `foo` to not be declared.

File: src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs [hunk 2]
```diff
@@ -60,6 +57,9 @@ public sealed class PythonInterpreter : IPythonInterpreter {
                     = UnknownType = new PythonType("Unknown", builtinModule, string.Empty, LocationInfo.Empty);
             }
             await _moduleResolution.LoadBuiltinTypesAsync(cancellationToken);
+
+            _stubResolution = new TypeshedResolution(sm);
```
Comment (jakebailey) [inline src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: Was this intentional or a merge issue? (#723)

Comment (MikhailArkhipov) [reply src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: As soon as typeshed init starts, it wants Unknown type. It least for me.

Comment (MikhailArkhipov) [reply src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: @AlexanderSher may comment I guess. After merge all tests fail for me since init of typeshed yielded analysis and all tests failed. Lemme see what it wants...

Comment (jakebailey) [reply src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: Perhaps my PR can be reverted if Alex's PR was the "true" fix. I know that when I tested before either of them, a module would be added and then make it back to the interpreter and crash trying to access _stubResolution.

Comment (MikhailArkhipov) [reply src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: For me
```
>	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.PythonModule.Parse() Line 337	C#
 	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.PythonModule.InitializeContent(string content) Line 220	C#
 	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.PythonModule.PythonModule(Microsoft.Python.Analysis.Modules.ModuleCreationOptions creationOptions, Microsoft.Python.Core.IServiceContainer services) Line 113	C#
 	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.PythonModule.PythonModule(string moduleName, string filePath, Microsoft.Python.Analysis.Modules.ModuleType moduleType, Microsoft.Python.Analysis.Types.IPythonModule stub, Microsoft.Python.Core.IServiceContainer services) Line 85	C#
 	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.CompiledPythonModule.CompiledPythonModule(string moduleName, Microsoft.Python.Analysis.Modules.ModuleType moduleType, string filePath, Microsoft.Python.Analysis.Types.IPythonModule stub, Microsoft.Python.Core.IServiceContainer services) Line 32	C#
 	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.BuiltinsPythonModule.BuiltinsPythonModule(string moduleName, string filePath, Microsoft.Python.Core.IServiceContainer services) Line 37	C#
 	Microsoft.Python.Analysis.dll!Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.InitializeAsync(System.Threading.CancellationToken cancellationToken) Line 51	C#

```
so main resolver init starts parsing and then analyzing builtins. So it is unlucky and reaches analysis stage before we populate Unknown, it crashes.

Comment (jakebailey) [reply src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: I'm fine with putting it back, I just hope that the other failure doesn't happen (if it was the scraper the whole time then moving it back up will be fine).

Comment (MikhailArkhipov) [reply src/Analysis/Ast/Impl/Analyzer/PythonInterpreter.cs]: No, old one was wrong too. Sorted it out.
