### PR TITLE
Specialize 'open' for various modes

### LINKED ISSUE #1000: No intellisense for file.write
@xiaofeng0123 commented on [Mon Apr 22 2019](https://github.com/Microsoft/vscode-python/issues/5399)

Visual Studio Code - Insiders: 1.34.0-insider
python-insider: 2019.4.6962-rc
python version: Python 3.7.3 64bit
Install Anaconda

Repro steps:
1.Git clone https://github.com/qubitron/pydemo
2.Open Anaconda Prompt window
3.Cd pydemo
4.Run py -3 setup.py
5.Set "python.jediEnabled" to "false" in "Settings.json"
6. Create a new folder named "newapp" and open this folder
7. Create a virtual env using "py -3 -m venv env"
8. Set current python environment to virtual env
9. Install "requests" package
10. Create a py file named "stackoverflow.py"
11. Input below code:
import requests
request=requests.get("https://drive.google.com/uc?export=download&id=1_9On2-nsBQIw3JiY43sWbrF8EjrqrR4U")
with open("survey2017.zip","wb") as file:
      file.write

Actual Result:
No intellisense for file.write
image

Expect Result:
Completion for file.write should be shown
image

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #1000

### CODE REVIEW

File: src/Analysis/Ast/Impl/Specializations/BuiltinsSpecializations.cs [hunk 1]
```diff
@@ -92,15 +92,29 @@ public static IMember List(IPythonInterpreter interpreter, IPythonFunctionOverlo
...
+                binary = modeString.Contains("b");
+                writable = modeString.Contains("w") || modeString.Contains("a") || modeString.Contains("x");
+                readWrite = writable && modeString.Contains("r");
             }
 
+            string returnTypeName;
             var io = declaringModule.Interpreter.ModuleResolution.GetImportedModule("io");
-            var ioBase = io?.GetMember(bytes ? "BufferedIOBase" : "TextIOWrapper")?.GetPythonType();
-            return ioBase != null ? new PythonInstance(ioBase) : null;
+            if (binary) {
```
Comment (jakebailey) [inline src/Analysis/Ast/Impl/Specializations/BuiltinsSpecializations.cs]: I think these are technically only true for Python 3, but I think that's okay.
