### PR TITLE
Lazy types in caching

### LINKED ISSUE #1514: Numpy persistence

### LINKED ISSUE #1515: Pandas persistence

### LINKED ISSUE #1516: Matplotlib persistence

### LINKED ISSUE #1517: Sklearn persistence

### LINKED ISSUE #1518: Scipy persistence

### LINKED ISSUE #1569: With caching enabled, analysis message in status bar never completes; numpy/pandas completions don't work
These are probably dups and arguably should be two issues but filing as one as they may be related.

Repros with caching set to System or Library. Things work okay when caching is disabled.

tl;dr: status bar spinner never ends and with "pd." or "np." on Pandas or numpy I get global level completions, not package level.

As the logs are long, I am splitting this report up over separate comments to make it easier to separate the stages.

I have the pytest repo checked out at commit 55b78ff780caf822bec63d7690d146cbaabda818, and I have the repo directory open in VS Code. 

LS version 0.4.20 through 0.4.22; not sure when it started)
OS: MacOS 10.14.6
VSC version: 1.38.1
Python extension version: 2019.9.34911
Python version 3.7.3

I open a file such as src/_pytest/outcomes.py (I don't think it really matters; I can repro this with Pandas too in a much smaller file of my own creation).

At the end I see:

image

and that number never goes down.

The trace logs are:

```
[Info  - 4:32:22 PM] Microsoft Python Language Server version 0.4.20.0
[Info  - 4:32:22 PM] Workspace root: /Users/grwheele/repos/pytest
[Info  - 4:32:23 PM] Analysis cache path: /Users/grwheele/Library/Caches/Microsoft/Python Language Server
[Info  - 4:32:23 PM] GetCurrentSearchPaths /Users/grwheele/anaconda3/envs/default/bin/python 
[Info  - 4:32:23 PM] Interpreter search paths:
[Info  - 4:32:23 PM]     /Users/grwheele/anaconda3/envs/default/lib/python3.7
[Info  - 4:32:23 PM]     /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload
[Info  - 4:32:23 PM]     /Users/grwheele/.vscode/extensions/ms-python.devicesimulatorexpress-2019.0.35146/out
[Info  - 4:32:23 PM]     /Users/grwheele/.local/lib/python3.7/site-packages
[Info  - 4:32:23 PM]     /Users/grwheele/anaconda3/envs/default/lib/python3.7/site-packages
[Info  - 4:32:23 PM] User search paths:
[Info  - 4:32:23 PM]     /Users/grwheele/repos/pytest/src
[Info  - 4:32:30 PM] Initializing for /Users/grwheele/anaconda3/envs/default/bin/python
Watching /Users/grwheele/.local/lib/python3.7/site-packages
Watching /Users/grwheele/anaconda3/envs/default/lib/python3.7
Watching /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload
Watching /Users/grwheele/anaconda3/envs/default/lib/python3.7/site-packages
Watching /Users/grwheele/.vscode/extensions/ms-python.devicesimulatorexpress-2019.0.35146/out
[Info  - 4:32:30 PM] Analysis caching mode: Library.
Opening document file:///Users/grwheele/repos/pytest/src/_pytest/outcomes.py
Analysis of _pytest.outcomes (User) queued. Dependencies: __future__, sys, warnings, pkg_resources
Import:  __future__ /Users/grwheele/anaconda3/envs/default/lib/python3.7/__future__.py 
Analysis of __future__ (Stub) queued. Dependencies: sys (stub)
Analysis of __future__ (Library) queued. Dependencies: __future__ (stub)
Create built-in compiled (scraped) module:  sys /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of sys (Stub) queued. Dependencies: types (stub), importlib.abc (stub)
Import:  warnings /Users/grwheele/anaconda3/envs/default/lib/python3.7/warnings.py 
Analysis of warnings (Stub) queued. Dependencies: types (stub)
Import:  pkg_resources /Users/grwheele/.local/lib/python3.7/site-packages/pkg_resources/__init__.py 
Analysis of warnings (Library) queued. Dependencies: warnings (stub), sys, linecache, tracemalloc, re, traceback, _warnings
Analysis of pkg_resources (Stub) queued. Dependencies: abc (stub), importlib (stub), importlib.abc (stub), types (stub), zipimport (stub)
Analysis of types (Stub) queued. Dependencies: sys (stub), _importlib_modulespec (stub)
Import:  linecache /Users/grwheele/anaconda3/envs/default/lib/python3.7/linecache.py 
Analysis of importlib.abc (Stub) queued. Dependencies: abc (stub), os (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Analysis of linecache (Stub) queued. Dependencies: sys (stub)
Import:  tracemalloc /Users/grwheele/anaconda3/envs/default/lib/python3.7/tracemalloc.py 
Analysis of linecache (Library) queued. Dependencies: linecache (stub), functools, sys, os, tokenize
Analysis of tracemalloc (Stub) queued. Dependencies: sys (stub)
Import:  re /Users/grwheele/anaconda3/envs/default/lib/python3.7/re.py 
Analysis of re (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of tracemalloc (Library) queued. Dependencies: tracemalloc (stub), collections.abc, functools, fnmatch, linecache, os, pickle, _tracemalloc
Import:  traceback /Users/grwheele/anaconda3/envs/default/lib/python3.7/traceback.py 
Analysis of re (Library) queued. Dependencies: re (stub), enum, sre_compile, sre_parse, functools, _locale, copyreg, sre_constants
Analysis of traceback (Stub) queued. Dependencies: types (stub), sys (stub)
Create built-in compiled (scraped) module:  _warnings /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of _warnings (Stub) queued. Dependencies: 
Analysis of abc (Stub) queued. Dependencies: 
Analysis of importlib (Stub) queued. Dependencies: importlib.util (stub), importlib.abc (stub), sys (stub), types (stub)
Analysis of zipimport (Stub) queued. Dependencies: types (stub)
Analysis of _importlib_modulespec (Stub) queued. Dependencies: abc (stub), sys (stub)
Analysis version 26 of 13 entries has started.
Analysis of pkg_resources(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of os (Stub) queued. Dependencies: io (stub), sys (stub), posix (stub), os.path (stub)
Analysis of traceback (Library) queued. Dependencies: traceback (stub), collections, itertools, linecache, sys
Import:  functools /Users/grwheele/anaconda3/envs/default/lib/python3.7/functools.py 
Analysis of pkg_resources (Library) queued. Dependencies: pkg_resources (stub), __future__, sys, os, io, time, re, types, zipfile, zipimport, warnings, stat, functools, pkgutil, operator, platform, collections, plistlib, email, email.parser, errno, tempfile, textwrap, itertools, inspect, ntpath, posixpath, _imp, imp, pkg_resources.extern, importlib, importlib.machinery, pkg_resources.py31compat, sysconfig, linecache
Analysis of functools (Stub) queued. Dependencies: sys (stub)
Import:  os /Users/grwheele/anaconda3/envs/default/lib/python3.7/os.py 
Import:  tokenize /Users/grwheele/anaconda3/envs/default/lib/python3.7/tokenize.py 
Analysis of tokenize (Stub) queued. Dependencies: sys (stub), token (stub), os (stub)
Analysis of enum (Stub) queued. Dependencies: sys (stub), abc (stub)
Import:  collections.abc /Users/grwheele/anaconda3/envs/default/lib/python3.7/collections/abc.py 
Analysis of collections.abc (Stub) queued. Dependencies: sys (stub), collections (stub)
Analysis of os (Library) queued. Dependencies: os (stub), abc, sys, stat, posix, posixpath, ntpath, warnings, _collections_abc, subprocess, io
Analysis of collections.abc (Library) queued. Dependencies: collections.abc (stub), _collections_abc
Analysis of tokenize (Library) queued. Dependencies: tokenize (stub), codecs, collections, io, itertools, re, sys, token, argparse
Import:  fnmatch /Users/grwheele/anaconda3/envs/default/lib/python3.7/fnmatch.py 
Analysis of fnmatch (Stub) queued. Dependencies: 
Analysis of functools (Library) queued. Dependencies: functools (stub), _functools, abc, collections, reprlib, _thread, types, weakref
Analysis of fnmatch (Library) queued. Dependencies: fnmatch (stub), os, posixpath, re, functools
Import:  pickle /Users/grwheele/anaconda3/envs/default/lib/python3.7/pickle.py 
Analysis of pickle (Stub) queued. Dependencies: sys (stub)
Create built-in compiled (scraped) module:  _tracemalloc /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of _tracemalloc (Stub) queued. Dependencies: 
Import:  enum /Users/grwheele/anaconda3/envs/default/lib/python3.7/enum.py 
Import:  sre_compile /Users/grwheele/anaconda3/envs/default/lib/python3.7/sre_compile.py 
Import:  sre_parse /Users/grwheele/anaconda3/envs/default/lib/python3.7/sre_parse.py 
Create built-in compiled (scraped) module:  _locale /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of enum (Library) queued. Dependencies: enum (stub), sys, types, _collections, collections, warnings
Analysis of pickle (Library) queued. Dependencies: pickle (stub), types, copyreg, itertools, functools, sys, struct, re, io, codecs, _compat_pickle, _pickle, doctest, argparse, pprint
Import:  copyreg /Users/grwheele/anaconda3/envs/default/lib/python3.7/copyreg.py 
Import:  sre_constants /Users/grwheele/anaconda3/envs/default/lib/python3.7/sre_constants.py 
Analysis of sre_compile (Stub) queued. Dependencies: sys (stub), sre_parse (stub), sre_constants (stub)
Analysis of sre_parse (Stub) queued. Dependencies: sre_constants (stub)
Analysis of sre_constants (Library) queued. Dependencies: sre_constants (stub), _sre
Analysis of importlib.util (Stub) queued. Dependencies: importlib (stub), importlib.abc (stub), importlib.machinery (stub), sys (stub), types (stub)
Analysis of copyreg (Library) queued. Dependencies: 
Analysis of sre_constants (Stub) queued. Dependencies: 
Analysis of sre_compile (Library) queued. Dependencies: sre_compile (stub), _sre, sre_parse, sre_constants, sys
Import:  collections /Users/grwheele/anaconda3/envs/default/lib/python3.7/collections/__init__.py 
Analysis of io (Stub) queued. Dependencies: codecs (stub), mmap (stub), sys (stub), types (stub)
Analysis of sre_parse (Library) queued. Dependencies: sre_parse (stub), sre_constants, warnings
Create built-in compiled (scraped) module:  itertools /Users/grwheele/anaconda3/envs/default/bin/python 
Import:  io /Users/grwheele/anaconda3/envs/default/lib/python3.7/io.py 
Analysis of posix (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  time /Users/grwheele/anaconda3/envs/default/bin/python 
Import:  types /Users/grwheele/anaconda3/envs/default/lib/python3.7/types.py 
Import:  zipfile /Users/grwheele/anaconda3/envs/default/lib/python3.7/zipfile.py 
Create built-in compiled (scraped) module:  zipimport /Users/grwheele/anaconda3/envs/default/bin/python 
Import:  stat /Users/grwheele/anaconda3/envs/default/lib/python3.7/stat.py 
Import:  pkgutil /Users/grwheele/anaconda3/envs/default/lib/python3.7/pkgutil.py 
Import:  operator /Users/grwheele/anaconda3/envs/default/lib/python3.7/operator.py 
Import:  platform /Users/grwheele/anaconda3/envs/default/lib/python3.7/platform.py 
Analysis of types (Stub) on depth 3 completed in 104.45 ms.
Import:  plistlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/plistlib.py 
Import:  email /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/__init__.py 
Import:  email.parser /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/parser.py 
Create built-in compiled (scraped) module:  errno /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of importlib.abc (Stub) on depth 4 completed in 7.62 ms.
Import:  tempfile /Users/grwheele/anaconda3/envs/default/lib/python3.7/tempfile.py 
Import:  textwrap /Users/grwheele/anaconda3/envs/default/lib/python3.7/textwrap.py 
Analysis of sys (Stub) on depth 3 completed in 4.76 ms.
Analysis of __future__ (Stub) on depth 2 completed in 0.27 ms.
Import:  inspect /Users/grwheele/anaconda3/envs/default/lib/python3.7/inspect.py 
Import:  ntpath /Users/grwheele/anaconda3/envs/default/lib/python3.7/ntpath.py 
Import:  posixpath /Users/grwheele/anaconda3/envs/default/lib/python3.7/posixpath.py 
Create built-in compiled (scraped) module:  _imp /Users/grwheele/anaconda3/envs/default/bin/python 
Import:  imp /Users/grwheele/anaconda3/envs/default/lib/python3.7/imp.py 
Import:  pkg_resources.extern /Users/grwheele/.local/lib/python3.7/site-packages/pkg_resources/extern/__init__.py 
Analysis of __future__ (Library) on depth 1 completed in 10.43 ms.
Import:  importlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/importlib/__init__.py 
Import:  importlib.machinery /Users/grwheele/anaconda3/envs/default/lib/python3.7/importlib/machinery.py 
Import:  pkg_resources.py31compat /Users/grwheele/.local/lib/python3.7/site-packages/pkg_resources/py31compat.py 
Analysis of warnings (Stub) on depth 2 completed in 8.56 ms.
Import:  sysconfig /Users/grwheele/anaconda3/envs/default/lib/python3.7/sysconfig.py 
Import:  abc /Users/grwheele/anaconda3/envs/default/lib/python3.7/abc.py 
Analysis of os.path (Stub) queued. Dependencies: posix (stub), sys (stub)
Analysis of itertools (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  posix /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of sysconfig (Library) queued. Dependencies: sysconfig (stub), os, sys, re, importlib, importlib.util, pprint, types, _osx_support, warnings
Import:  _collections_abc /Users/grwheele/anaconda3/envs/default/lib/python3.7/_collections_abc.py 
Analysis of collections (Stub) queued. Dependencies: sys (stub), collections.abc (stub)
Import:  subprocess /Users/grwheele/anaconda3/envs/default/lib/python3.7/subprocess.py 
Analysis of token (Stub) queued. Dependencies: sys (stub)
Import:  codecs /Users/grwheele/anaconda3/envs/default/lib/python3.7/codecs.py 
Analysis of collections (Library) queued. Dependencies: collections (stub), _collections_abc, operator, keyword, sys, heapq, _weakref, itertools, reprlib, _collections, warnings, copy
Analysis of abc (Library) queued. Dependencies: abc (stub), _abc, _py_abc
Import:  token /Users/grwheele/anaconda3/envs/default/lib/python3.7/token.py 
Import:  argparse /Users/grwheele/anaconda3/envs/default/lib/python3.7/argparse.py 
Create built-in compiled (scraped) module:  _functools /Users/grwheele/anaconda3/envs/default/bin/python 
Import:  reprlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/reprlib.py 
Analysis of io (Library) queued. Dependencies: io (stub), _io, abc
Analysis of _collections_abc (Library) queued. Dependencies: abc, sys
Analysis of warnings (Library) on depth 1 completed in 55.85 ms.
Analysis of _pytest.outcomes (User) on depth 0 completed in 20.42 ms.
Analysis version 26 has been completed in 215.75 ms with 10 entries analyzed and 3 entries skipped.
Analysis of subprocess (Stub) queued. Dependencies: sys (stub), types (stub)
Create built-in compiled (scraped) module:  _thread /Users/grwheele/anaconda3/envs/default/bin/python 
Import:  weakref /Users/grwheele/anaconda3/envs/default/lib/python3.7/weakref.py 
Analysis version 102 of 46 entries has started.
Create built-in compiled (scraped) module:  _collections /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of fnmatch (Stub) on depth 4 completed in 0.74 ms.
Analysis of time (Stub) queued. Dependencies: sys (stub), types (stub)
Import:  struct /Users/grwheele/anaconda3/envs/default/lib/python3.7/struct.py 
Analysis of codecs (Stub) queued. Dependencies: sys (stub), abc (stub), types (stub)
Import:  _compat_pickle /Users/grwheele/anaconda3/envs/default/lib/python3.7/_compat_pickle.py 
Create compiled (scraped):  _pickle /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of codecs (Library) queued. Dependencies: codecs (stub), sys, _codecs, encodings
Import:  doctest /Users/grwheele/anaconda3/envs/default/lib/python3.7/doctest.py 
Analysis of subprocess (Library) queued. Dependencies: subprocess (stub), sys, io, os, time, signal, warnings, errno, threading, _posixsubprocess, select, selectors
Import:  pprint /Users/grwheele/anaconda3/envs/default/lib/python3.7/pprint.py 
Create built-in compiled (scraped) module:  _sre /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of token (Library) queued. Dependencies: token (stub), re, sys
Analysis of reprlib (Stub) queued. Dependencies: array (stub)
Analysis of reprlib (Library) queued. Dependencies: reprlib (stub), itertools, _thread
Analysis of zipfile (Stub) queued. Dependencies: types (stub), os (stub), sys (stub)
Analysis of _thread (Stub) queued. Dependencies: 
Analysis of types (Library) queued. Dependencies: types (stub), sys, functools, _collections_abc
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Import:  importlib.util /Users/grwheele/anaconda3/envs/default/lib/python3.7/importlib/util.py 
Analysis of argparse (Stub) queued. Dependencies: sys (stub)
Analysis of mmap (Stub) queued. Dependencies: sys (stub)
Analysis of struct (Stub) queued. Dependencies: sys (stub), array (stub)
Import:  _osx_support /Users/grwheele/anaconda3/envs/default/lib/python3.7/_osx_support.py 
Analysis of pprint (Library) queued. Dependencies: pprint (stub), collections, re, sys, types, io, time
Analysis of weakref (Stub) queued. Dependencies: sys (stub), types (stub), _weakref (stub), _weakrefset (stub)
Analysis of importlib.util (Library) queued. Dependencies: importlib.util (stub), importlib, importlib.abc, importlib._bootstrap, importlib._bootstrap_external, contextlib, _imp, functools, sys, types, warnings
Analysis of weakref (Library) queued. Dependencies: weakref (stub), _weakref, _weakrefset, _collections_abc, sys, itertools, copy, atexit, gc
Analysis of pprint (Stub) queued. Dependencies: sys (stub)
Analysis of struct (Library) queued. Dependencies: struct (stub), _struct
Analysis of sysconfig (Stub) queued. Dependencies: 
Analysis of abc (Stub) on depth 3 completed in 0.57 ms.
Analysis of _osx_support (Library) queued. Dependencies: os, re, sys, contextlib, tempfile, distutils, distutils.log
Analysis of _pickle (Compiled) queued. Dependencies: 
Analysis of _compat_pickle (Library) queued. Dependencies: 
Import:  keyword /Users/grwheele/anaconda3/envs/default/lib/python3.7/keyword.py 
Import:  heapq /Users/grwheele/anaconda3/envs/default/lib/python3.7/heapq.py 
Analysis of doctest (Stub) queued. Dependencies: sys (stub), types (stub), unittest (stub)
Analysis of os (Stub) on depth 3 completed in 62.45 ms.
Analysis of argparse (Library) queued. Dependencies: argparse (stub), os, re, sys, gettext, copy, textwrap, warnings
Create built-in compiled (scraped) module:  _weakref /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of _importlib_modulespec (Stub) on depth 4 completed in 1.92 ms.
Analysis of collections.abc (Stub) on depth 4 completed in 0.22 ms.
Analysis of zipfile (Library) queued. Dependencies: zipfile (stub), io, os, importlib, importlib.util, sys, time, stat, shutil, struct, binascii, threading, zlib, bz2, lzma, warnings, py_compile, argparse
Analysis of zipimport (Stub) on depth 3 completed in 0.69 ms.
Import:  copy /Users/grwheele/anaconda3/envs/default/lib/python3.7/copy.py 
Analysis of builtins (Stub) queued. Dependencies: abc (stub), types (stub), sys (stub)
Create built-in compiled (scraped) module:  _abc /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of doctest (Library) queued. Dependencies: doctest (stub), __future__, difflib, inspect, linecache, os, pdb, re, sys, traceback, unittest, io, collections, argparse
Analysis of collections.abc (Library) on depth 3 completed in 12.79 ms.
Analysis of stat (Stub) queued. Dependencies: sys (stub)
Analysis of stat (Library) queued. Dependencies: stat (stub), _stat
Analysis of pkgutil (Stub) queued. Dependencies: sys (stub), importlib.abc (stub)
Analysis of keyword (Stub) queued. Dependencies: 
Import:  _py_abc /Users/grwheele/anaconda3/envs/default/lib/python3.7/_py_abc.py 
Create built-in compiled (scraped) module:  _io /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of functools (Stub) on depth 3 completed in 3.42 ms.
Analysis of pkgutil (Library) queued. Dependencies: pkgutil (stub), collections, functools, importlib, importlib.util, importlib.machinery, os, sys, types, warnings, marshal, inspect, zipimport
Analysis of operator (Stub) queued. Dependencies: sys (stub)
Analysis of heapq (Stub) queued. Dependencies: sys (stub)
Analysis of _weakref (Stub) queued. Dependencies: sys (stub)
Analysis of keyword (Library) queued. Dependencies: keyword (stub), sys, re
Analysis of copy (Stub) queued. Dependencies: 
Analysis of platform (Stub) queued. Dependencies: os (stub)
Analysis of plistlib (Stub) queued. Dependencies: sys (stub), enum (stub)
Create built-in compiled (scraped) module:  _codecs /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of heapq (Library) queued. Dependencies: heapq (stub), _heapq, doctest
Analysis of operator (Library) queued. Dependencies: operator (stub), functools, _operator
Analysis of copy (Library) queued. Dependencies: copy (stub), types, weakref, copyreg
Analysis of platform (Library) queued. Dependencies: platform (stub), collections, sys, os, re, subprocess, warnings, plistlib, socket, struct
Import:  encodings /Users/grwheele/anaconda3/envs/default/lib/python3.7/encodings/__init__.py 
Analysis of email (Stub) queued. Dependencies: sys (stub), email.message (stub), email.policy (stub)
Import:  signal /Users/grwheele/anaconda3/envs/default/lib/python3.7/signal.py 
Analysis of plistlib (Library) queued. Dependencies: plistlib (stub), binascii, codecs, contextlib, datetime, enum, io, itertools, os, re, struct, warnings, xml.parsers.expat
Import:  threading /Users/grwheele/anaconda3/envs/default/lib/python3.7/threading.py 
Create compiled (scraped):  _posixsubprocess /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  select /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/select.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Import:  selectors /Users/grwheele/anaconda3/envs/default/lib/python3.7/selectors.py 
Analysis of email (Library) queued. Dependencies: email (stub), email.parser
Analysis of email.parser (Stub) queued. Dependencies: email (stub), email.feedparser (stub), email.message (stub), email.policy (stub)
Analysis of errno (Stub) queued. Dependencies: sys (stub)
Analysis of email.parser (Library) queued. Dependencies: email.parser (stub), io, email.feedparser, email._policybase
Analysis of functools (Library) on depth 2 completed in 39.09 ms.
Analysis of _py_abc (Library) queued. Dependencies: _weakrefset
Import:  importlib.abc /Users/grwheele/anaconda3/envs/default/lib/python3.7/importlib/abc.py 
Analysis of array (Stub) queued. Dependencies: sys (stub)
Analysis of _weakrefset (Stub) queued. Dependencies: 
Analysis of tempfile (Stub) queued. Dependencies: sys (stub), types (stub)
Import:  importlib._bootstrap /Users/grwheele/anaconda3/envs/default/lib/python3.7/importlib/_bootstrap.py 
Import:  importlib._bootstrap_external /Users/grwheele/anaconda3/envs/default/lib/python3.7/importlib/_bootstrap_external.py 
Analysis of traceback (Stub) on depth 3 completed in 35.42 ms.
Import:  contextlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/contextlib.py 
Import:  _weakrefset /Users/grwheele/anaconda3/envs/default/lib/python3.7/_weakrefset.py 
Analysis of selectors (Library) queued. Dependencies: selectors (stub), abc, collections, collections.abc, math, select, sys
Create built-in compiled (scraped) module:  atexit /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of tempfile (Library) queued. Dependencies: tempfile (stub), functools, warnings, io, os, shutil, errno, random, weakref, _thread
Analysis of traceback (Library) on depth 2 completed in 6.14 ms.
Create built-in compiled (scraped) module:  gc /Users/grwheele/anaconda3/envs/default/bin/python 
Create compiled (scraped):  _struct /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of enum (Stub) on depth 4 completed in 6.91 ms.
Import:  distutils /Users/grwheele/anaconda3/envs/default/lib/python3.7/distutils/__init__.py 
Analysis of pkg_resources.py31compat (Library) queued. Dependencies: os, errno, sys, pkg_resources.extern
Analysis of re (Stub) on depth 3 completed in 1.39 ms.
Import:  distutils.log /Users/grwheele/anaconda3/envs/default/lib/python3.7/distutils/log.py 
Analysis of textwrap (Stub) queued. Dependencies: 
Analysis of _codecs (Stub) queued. Dependencies: sys (stub), codecs (stub)
Import:  gettext /Users/grwheele/anaconda3/envs/default/lib/python3.7/gettext.py 
Analysis of re (Library) on depth 2 completed in 3.72 ms.
Analysis of importlib.abc (Library) queued. Dependencies: importlib.abc (stub), importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, abc, warnings
Analysis of textwrap (Library) queued. Dependencies: textwrap (stub), re
Import:  shutil /Users/grwheele/anaconda3/envs/default/lib/python3.7/shutil.py 
Create compiled (scraped):  binascii /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of importlib._bootstrap (Library) queued. Dependencies: 
Create compiled (scraped):  zlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/zlib.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Import:  bz2 /Users/grwheele/anaconda3/envs/default/lib/python3.7/bz2.py 
Analysis of os (Library) queued. Dependencies: os (stub), abc, sys, stat, posix, posixpath, ntpath, warnings, _collections_abc, subprocess, io
Import:  lzma /Users/grwheele/anaconda3/envs/default/lib/python3.7/lzma.py 
Import:  py_compile /Users/grwheele/anaconda3/envs/default/lib/python3.7/py_compile.py 
Import:  difflib /Users/grwheele/anaconda3/envs/default/lib/python3.7/difflib.py 
Analysis of py_compile (Library) queued. Dependencies: py_compile (stub), enum, importlib, importlib._bootstrap_external, importlib.machinery, importlib.util, os, sys, traceback
Import:  pdb /Users/grwheele/anaconda3/envs/default/lib/python3.7/pdb.py 
Import:  unittest /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/__init__.py 
Create built-in compiled (scraped) module:  _stat /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of contextlib (Stub) queued. Dependencies: types (stub), sys (stub)
Create built-in compiled (scraped) module:  marshal /Users/grwheele/anaconda3/envs/default/bin/python 
Create compiled (scraped):  _heapq /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of _weakrefset (Library) queued. Dependencies: _weakrefset (stub), _weakref
Analysis of inspect (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of contextlib (Library) queued. Dependencies: contextlib (stub), abc, sys, _collections_abc, collections, functools
Create built-in compiled (scraped) module:  _operator /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of atexit (Stub) queued. Dependencies: 
Analysis of gc (Stub) queued. Dependencies: 
Import:  socket /Users/grwheele/anaconda3/envs/default/lib/python3.7/socket.py 
Analysis of importlib._bootstrap_external (Library) queued. Dependencies: tokenize
Analysis of tokenize (Stub) on depth 4 completed in 1.17 ms.
Analysis of _struct (Compiled) queued. Dependencies: struct
Import:  datetime /Users/grwheele/anaconda3/envs/default/lib/python3.7/datetime.py 
Import:  xml.parsers.expat /Users/grwheele/anaconda3/envs/default/lib/python3.7/xml/parsers/expat.py 
Analysis of xml.parsers.expat (Library) queued. Dependencies: xml.parsers.expat (stub), sys, pyexpat
Analysis of binascii (Stub) queued. Dependencies: sys (stub)
Import:  email.feedparser /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/feedparser.py 
Analysis of email.feedparser (Stub) queued. Dependencies: sys (stub), email.message (stub), email.policy (stub)
Analysis of xml.parsers.expat (Stub) queued. Dependencies: pyexpat (stub), pyexpat.errors (stub), pyexpat.model (stub)
Import:  email._policybase /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/_policybase.py 
Analysis of distutils (Stub) queued. Dependencies: 
Analysis of importlib (Stub) on depth 3 completed in 0.61 ms.
Create compiled (scraped):  math /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of email._policybase (Library) queued. Dependencies: abc, email, email.header, email.charset, email.utils
Import:  random /Users/grwheele/anaconda3/envs/default/lib/python3.7/random.py 
Analysis of selectors (Stub) queued. Dependencies: abc (stub), socket (stub)
Analysis of distutils (Library) queued. Dependencies: distutils (stub), sys
Analysis of distutils.log (Stub) queued. Dependencies: 
Create compiled (scraped):  pyexpat /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/pyexpat.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of random (Library) queued. Dependencies: random (stub), warnings, types, math, os, _collections_abc, hashlib, itertools, bisect, _random, time
Analysis of tokenize (Library) queued. Dependencies: tokenize (stub), codecs, collections, io, itertools, re, sys, token, argparse
Import:  email.header /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/header.py 
Analysis of pkg_resources (Stub) on depth 2 completed in 16.53 ms.
Import:  email.charset /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/charset.py 
Analysis of os (Library) on depth 2 completed in 91.72 ms.
Import:  email.utils /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/utils.py 
Analysis of inspect (Library) queued. Dependencies: inspect (stub), abc, dis, collections, collections.abc, enum, importlib, importlib.machinery, itertools, linecache, os, re, sys, tokenize, token, types, warnings, functools, operator, ast, argparse
Import:  hashlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/hashlib.py 
Analysis of select (Compiled) queued. Dependencies: select (stub)
Analysis of email.feedparser (Library) queued. Dependencies: email.feedparser (stub), re, email, email.errors, email._policybase, collections, io, email.message
Import:  bisect /Users/grwheele/anaconda3/envs/default/lib/python3.7/bisect.py 
Create compiled (scraped):  _random /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_random.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of _random (Compiled) queued. Dependencies: _random (stub)
Import:  dis /Users/grwheele/anaconda3/envs/default/lib/python3.7/dis.py 
Import:  ast /Users/grwheele/anaconda3/envs/default/lib/python3.7/ast.py 
Analysis of tokenize (Library) on depth 3 completed in 67 ms.
Analysis of distutils.log (Library) queued. Dependencies: distutils.log (stub), sys
Import:  email.errors /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/errors.py 
Analysis of select (Stub) queued. Dependencies: sys (stub)
Import:  email.message /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/message.py 
Analysis of ast (Library) queued. Dependencies: ast (stub), _ast, inspect, collections
Analysis of _posixsubprocess (Compiled) queued. Dependencies: _posixsubprocess (stub)
Analysis of encodings (Stub) queued. Dependencies: codecs (stub)
Analysis of _posixsubprocess (Stub) queued. Dependencies: 
Analysis of gettext (Stub) queued. Dependencies: 
Create built-in compiled (scraped) module:  _ast /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of unittest (Stub) queued. Dependencies: logging (stub), sys (stub), types (stub)
Analysis of math (Stub) queued. Dependencies: sys (stub)
Analysis of dis (Stub) queued. Dependencies: sys (stub), types (stub), opcode (stub)
Analysis of email.message (Library) queued. Dependencies: email.message (stub), re, uu, quopri, io, email, email.utils, email.errors, email._policybase, email.charset, email._encoded_words, email.generator, email.iterators, email.policy
Analysis of linecache (Stub) on depth 3 completed in 0.31 ms.
Analysis of logging (Stub) queued. Dependencies: string (stub), time (stub), types (stub), sys (stub), threading (stub)
Analysis of threading (Library) queued. Dependencies: threading (stub), os, sys, _thread, time, traceback, _weakrefset, itertools, _collections, collections, warnings, _threading_local
Import:  uu /Users/grwheele/anaconda3/envs/default/lib/python3.7/uu.py 
Analysis of math (Compiled) queued. Dependencies: math (stub)
Analysis of gettext (Library) queued. Dependencies: gettext (stub), locale, os, re, sys, warnings, struct, errno, copy
Import:  quopri /Users/grwheele/anaconda3/envs/default/lib/python3.7/quopri.py 
Import:  email._encoded_words /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/_encoded_words.py 
Import:  email.generator /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/generator.py 
Analysis of _ast (Stub) queued. Dependencies: sys (stub)
Import:  email.iterators /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/iterators.py 
Import:  email.policy /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/policy.py 
Analysis of email.policy (Library) queued. Dependencies: email.policy (stub), re, email._policybase, email.utils, email.headerregistry, email.contentmanager, email.message
Import:  _threading_local /Users/grwheele/anaconda3/envs/default/lib/python3.7/_threading_local.py 
Analysis of ntpath (Stub) queued. Dependencies: sys (stub)
Import:  locale /Users/grwheele/anaconda3/envs/default/lib/python3.7/locale.py 
Analysis of _threading_local (Library) queued. Dependencies: _threading_local (stub), weakref, contextlib, threading
Analysis of ast (Stub) queued. Dependencies: _ast (stub)
Import:  email.headerregistry /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/headerregistry.py 
Analysis of dis (Library) queued. Dependencies: dis (stub), sys, types, collections, io, opcode, argparse
Import:  email.contentmanager /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/contentmanager.py 
Analysis of tracemalloc (Stub) on depth 3 completed in 3.2 ms.
Import:  opcode /Users/grwheele/anaconda3/envs/default/lib/python3.7/opcode.py 
Analysis of _threading_local (Stub) queued. Dependencies: weakref (stub)
Analysis of shutil (Stub) queued. Dependencies: os (stub), sys (stub)
Analysis of string (Stub) queued. Dependencies: 
Analysis of email.contentmanager (Library) queued. Dependencies: email.contentmanager (stub), binascii, email, email.charset, email.message, email.errors, email.quoprimime
Analysis of opcode (Library) queued. Dependencies: opcode (stub), _opcode
Analysis of email.contentmanager (Stub) queued. Dependencies: email.message (stub)
Analysis of binascii (Compiled) queued. Dependencies: binascii (stub)
Import:  email.quoprimime /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/quoprimime.py 
Analysis of locale (Library) queued. Dependencies: locale (stub), sys, encodings, encodings.aliases, re, _collections_abc, functools, _locale, warnings, os, _bootlocale
Analysis of threading (Stub) queued. Dependencies: types (stub), sys (stub)
Analysis of difflib (Stub) queued. Dependencies: sys (stub)
Create compiled (scraped):  _opcode /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_opcode.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of signal (Library) queued. Dependencies: signal (stub), _signal, functools, enum
Analysis of _opcode (Compiled) queued. Dependencies: 
Import:  encodings.aliases /Users/grwheele/anaconda3/envs/default/lib/python3.7/encodings/aliases.py 
Analysis of signal (Stub) queued. Dependencies: sys (stub), enum (stub), types (stub)
Import:  _bootlocale /Users/grwheele/anaconda3/envs/default/lib/python3.7/_bootlocale.py 
Analysis of shutil (Library) queued. Dependencies: shutil (stub), os, sys, stat, fnmatch, collections, errno, zlib, bz2, lzma, pwd, grp, tarfile, zipfile
Create built-in compiled (scraped) module:  _signal /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of pdb (Stub) queued. Dependencies: sys (stub)
Analysis of _bootlocale (Library) queued. Dependencies: sys, _locale, locale
Analysis of email.quoprimime (Library) queued. Dependencies: re, string
Create built-in compiled (scraped) module:  pwd /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of encodings (Library) queued. Dependencies: encodings (stub), codecs, sys, encodings.aliases, encodings.mbcs
Create compiled (scraped):  grp /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/grp.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of ntpath (Library) queued. Dependencies: ntpath (stub), os, sys, stat, genericpath, string
Import:  tarfile /Users/grwheele/anaconda3/envs/default/lib/python3.7/tarfile.py 
Import:  string /Users/grwheele/anaconda3/envs/default/lib/python3.7/string.py 
Analysis of posixpath (Stub) queued. Dependencies: sys (stub)
Import:  encodings.mbcs /Users/grwheele/anaconda3/envs/default/lib/python3.7/encodings/mbcs.py 
Import:  genericpath /Users/grwheele/anaconda3/envs/default/lib/python3.7/genericpath.py 
Analysis of string (Library) queued. Dependencies: string (stub), _string, re, collections
Analysis of encodings.mbcs (Library) queued. Dependencies: codecs
Create built-in compiled (scraped) module:  _string /Users/grwheele/anaconda3/envs/default/bin/python 
Analysis of genericpath (Library) queued. Dependencies: os, stat
Analysis of difflib (Library) queued. Dependencies: difflib (stub), heapq, collections, re, doctest
Analysis of random (Stub) queued. Dependencies: _random (stub), sys (stub)
Analysis of email.headerregistry (Library) queued. Dependencies: email.headerregistry (stub), types, email, email.utils, email.errors, email._header_value_parser
Analysis of unittest (Library) queued. Dependencies: unittest (stub), unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, os
Import:  email._header_value_parser /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/_header_value_parser.py 
Import:  unittest.result /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/result.py 
Analysis of email.headerregistry (Stub) queued. Dependencies: datetime (stub), email.errors (stub), email.policy (stub)
Import:  unittest.case /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/case.py 
Import:  unittest.suite /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/suite.py 
Analysis of pdb (Library) queued. Dependencies: pdb (stub), os, re, sys, cmd, bdb, dis, code, glob, pprint, signal, inspect, traceback, linecache, readline, shlex, runpy, pydoc, getopt
Analysis of tarfile (Library) queued. Dependencies: tarfile (stub), sys, os, io, shutil, stat, time, struct, copy, re, pwd, grp, warnings, zlib, bz2, lzma, gzip, argparse
Analysis of email.header (Stub) queued. Dependencies: email.charset (stub)
Import:  unittest.loader /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/loader.py 
Import:  unittest.main /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/main.py 
Import:  unittest.runner /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/runner.py 
Import:  unittest.signals /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/signals.py 
Import:  cmd /Users/grwheele/anaconda3/envs/default/lib/python3.7/cmd.py 
Analysis of unittest.signals (Library) queued. Dependencies: signal, weakref, functools
Import:  bdb /Users/grwheele/anaconda3/envs/default/lib/python3.7/bdb.py 
Analysis of unittest.loader (Library) queued. Dependencies: os, re, sys, traceback, types, functools, warnings, fnmatch, unittest, unittest.case, unittest.suite, unittest.util
Analysis of email._header_value_parser (Library) queued. Dependencies: re, urllib, string, collections, operator, email, email._encoded_words, email.errors, email.utils
Import:  code /Users/grwheele/anaconda3/envs/default/lib/python3.7/code.py 
Import:  glob /Users/grwheele/anaconda3/envs/default/lib/python3.7/glob.py 
Create compiled (scraped):  readline /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of unittest.case (Library) queued. Dependencies: sys, functools, difflib, logging, pprint, re, warnings, collections, contextlib, traceback, unittest, unittest.result, unittest.util
Import:  shlex /Users/grwheele/anaconda3/envs/default/lib/python3.7/shlex.py 
Import:  runpy /Users/grwheele/anaconda3/envs/default/lib/python3.7/runpy.py 
Import:  pydoc /Users/grwheele/anaconda3/envs/default/lib/python3.7/pydoc.py 
Import:  getopt /Users/grwheele/anaconda3/envs/default/lib/python3.7/getopt.py 
Import:  gzip /Users/grwheele/anaconda3/envs/default/lib/python3.7/gzip.py 
Import:  unittest.util /Users/grwheele/anaconda3/envs/default/lib/python3.7/unittest/util.py 
Analysis of tarfile (Stub) queued. Dependencies: os (stub), sys (stub), types (stub)
Analysis of unittest.runner (Library) queued. Dependencies: sys, time, warnings, unittest, unittest.result, unittest.signals
Analysis of grp (Compiled) queued. Dependencies: grp (stub)
Import:  urllib /Users/grwheele/anaconda3/envs/default/lib/python3.7/urllib/__init__.py 
Import:  logging /Users/grwheele/anaconda3/envs/default/lib/python3.7/logging/__init__.py 
Analysis of urllib (Library) queued. Dependencies: urllib (stub)
Analysis of grp (Stub) queued. Dependencies: 
Analysis of urllib (Stub) queued. Dependencies: 
Analysis of gzip (Library) queued. Dependencies: gzip (stub), struct, sys, time, os, zlib, io, _compression, warnings, errno
Analysis of unittest.main (Library) queued. Dependencies: sys, argparse, os, unittest, unittest.loader, unittest.runner, unittest.signals
Analysis of unittest.util (Library) queued. Dependencies: collections, os
Analysis of pwd (Stub) queued. Dependencies: 
Analysis of gzip (Stub) queued. Dependencies: os.path (stub), _compression (stub), zlib (stub)
Analysis of encodings.aliases (Library) queued. Dependencies: 
Analysis of unittest.suite (Library) queued. Dependencies: sys, unittest, unittest.case, unittest.util
Import:  _compression /Users/grwheele/anaconda3/envs/default/lib/python3.7/_compression.py 
Analysis of posixpath (Library) queued. Dependencies: posixpath (stub), os, sys, stat, genericpath, pwd, re
Analysis of email.iterators (Library) queued. Dependencies: email.iterators (stub), sys, io
Analysis of email.iterators (Stub) queued. Dependencies: email.message (stub)
Analysis of cmd (Stub) queued. Dependencies: 
Analysis of _compression (Library) queued. Dependencies: _compression (stub), io
Analysis of locale (Stub) queued. Dependencies: decimal (stub), sys (stub)
Analysis of _compression (Stub) queued. Dependencies: io (stub)
Analysis of _stat (Stub) queued. Dependencies: 
Analysis of _imp (Stub) queued. Dependencies: sys (stub), types (stub), importlib.machinery (stub)
Analysis of marshal (Stub) queued. Dependencies: 
Analysis of getopt (Library) queued. Dependencies: getopt (stub), os, gettext, sys
Analysis of email.generator (Library) queued. Dependencies: email.generator (stub), re, sys, time, random, copy, io, email.utils
Analysis of getopt (Stub) queued. Dependencies: 
Analysis of email.generator (Stub) queued. Dependencies: email.message (stub), email.policy (stub)
Analysis of _heapq (Stub) queued. Dependencies: 
Analysis of logging (Library) queued. Dependencies: logging (stub), sys, os, time, io, traceback, warnings, weakref, collections, collections.abc, string, threading, pickle, atexit
Analysis of imp (Stub) queued. Dependencies: os (stub), sys (stub), types (stub), _imp (stub)
Analysis of email._encoded_words (Library) queued. Dependencies: re, base64, binascii, functools, string, email, email.errors
Analysis of decimal (Stub) queued. Dependencies: 
Analysis of unittest.result (Library) queued. Dependencies: io, sys, traceback, unittest, unittest.util, functools
Analysis of quopri (Library) queued. Dependencies: quopri (stub), binascii, io, sys, getopt
Import:  base64 /Users/grwheele/anaconda3/envs/default/lib/python3.7/base64.py 
Analysis of email.header (Library) queued. Dependencies: email.header (stub), re, binascii, email, email.quoprimime, email.base64mime, email.errors, email.charset
Analysis of quopri (Stub) queued. Dependencies: 
Analysis of _heapq (Compiled) queued. Dependencies: _heapq (stub)
Analysis of imp (Library) queued. Dependencies: imp (stub), _imp, importlib._bootstrap, importlib._bootstrap_external, importlib, importlib.machinery, importlib.util, os, sys, tokenize, types, warnings
Analysis of uu (Library) queued. Dependencies: uu (stub), binascii, os, sys, optparse
Analysis of pkg_resources.extern (Library) queued. Dependencies: sys
Analysis of uu (Stub) queued. Dependencies: sys (stub)
Analysis of base64 (Stub) queued. Dependencies: sys (stub)
Analysis of opcode (Stub) queued. Dependencies: sys (stub)
Analysis of email.charset (Stub) queued. Dependencies: 
Analysis of _operator (Stub) queued. Dependencies: sys (stub), operator (stub)
Analysis of email.errors (Library) queued. Dependencies: email.errors (stub)
Analysis of base64 (Library) queued. Dependencies: base64 (stub), re, struct, binascii, warnings, sys, getopt
Analysis of email.errors (Stub) queued. Dependencies: 
Import:  email.base64mime /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/base64mime.py 
Analysis of email.utils (Stub) queued. Dependencies: email.charset (stub), datetime (stub)
Analysis of email.charset (Library) queued. Dependencies: email.charset (stub), functools, email, email.base64mime, email.quoprimime, email.errors, email.encoders
Analysis of cmd (Library) queued. Dependencies: cmd (stub), string, sys, readline
Import:  optparse /Users/grwheele/anaconda3/envs/default/lib/python3.7/optparse.py 
Analysis of email.utils (Library) queued. Dependencies: email.utils (stub), os, re, time, random, socket, datetime, urllib, urllib.parse, email._parseaddr, email.charset
Import:  email.encoders /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/encoders.py 
Analysis of pydoc (Library) queued. Dependencies: importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, importlib.util, inspect, io, os, pkgutil, platform, re, sys, time, tokenize, urllib, urllib.parse, warnings, collections, reprlib, traceback, tempfile, subprocess, tty, pydoc_data, pydoc_data.topics, textwrap, http, http.server, email, email.message, select, threading, webbrowser, getopt
Analysis of email.encoders (Library) queued. Dependencies: email.encoders (stub), base64, quopri
Import:  urllib.parse /Users/grwheele/anaconda3/envs/default/lib/python3.7/urllib/parse.py 
Analysis of importlib (Library) queued. Dependencies: importlib (stub), _imp, sys, importlib._bootstrap, importlib._bootstrap_external, types, warnings
Import:  email._parseaddr /Users/grwheele/anaconda3/envs/default/lib/python3.7/email/_parseaddr.py 
Analysis of runpy (Library) queued. Dependencies: runpy (stub), sys, importlib, importlib.machinery, importlib.util, types, pkgutil, warnings
Analysis of optparse (Library) queued. Dependencies: optparse (stub), sys, os, textwrap, gettext
Import:  tty /Users/grwheele/anaconda3/envs/default/lib/python3.7/tty.py 
Analysis of optparse (Stub) queued. Dependencies: sys (stub)
Import:  pydoc_data /Users/grwheele/anaconda3/envs/default/lib/python3.7/pydoc_data/__init__.py 
Analysis of email._parseaddr (Library) queued. Dependencies: time, calendar
Analysis of email.base64mime (Library) queued. Dependencies: base64, binascii
Import:  pydoc_data.topics /Users/grwheele/anaconda3/envs/default/lib/python3.7/pydoc_data/topics.py 
Analysis of urllib.parse (Library) queued. Dependencies: urllib.parse (stub), re, sys, collections, unicodedata
Import:  http /Users/grwheele/anaconda3/envs/default/lib/python3.7/http/__init__.py 
Import:  http.server /Users/grwheele/anaconda3/envs/default/lib/python3.7/http/server.py 
Import:  webbrowser /Users/grwheele/anaconda3/envs/default/lib/python3.7/webbrowser.py 
Analysis of runpy (Stub) queued. Dependencies: 
Analysis of email.encoders (Stub) queued. Dependencies: email.message (stub)
Import:  calendar /Users/grwheele/anaconda3/envs/default/lib/python3.7/calendar.py 
Analysis of shlex (Library) queued. Dependencies: shlex (stub), os, re, sys, collections, io
Analysis of shlex (Stub) queued. Dependencies: sys (stub)
Analysis of webbrowser (Library) queued. Dependencies: webbrowser (stub), os, shlex, shutil, sys, subprocess, threading, copy, glob, pwd, socket, tempfile, getopt
Create compiled (scraped):  unicodedata /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/unicodedata.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of readline (Compiled) queued. Dependencies: readline (stub)
Analysis of webbrowser (Stub) queued. Dependencies: sys (stub)
Analysis of readline (Stub) queued. Dependencies: sys (stub)
Analysis of importlib.machinery (Stub) queued. Dependencies: importlib (stub), importlib.abc (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Analysis of calendar (Library) queued. Dependencies: calendar (stub), sys, datetime, locale, itertools, argparse
Analysis of glob (Library) queued. Dependencies: glob (stub), os, re, fnmatch
Analysis of hashlib (Stub) queued. Dependencies: sys (stub)
Analysis of glob (Stub) queued. Dependencies: sys (stub)
Analysis of unicodedata (Compiled) queued. Dependencies: unicodedata (stub)
Analysis of unicodedata (Stub) queued. Dependencies: 
Analysis of code (Library) queued. Dependencies: code (stub), sys, traceback, codeop, readline, argparse
Analysis of socket (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of code (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of urllib.parse (Stub) queued. Dependencies: sys (stub)
Analysis of calendar (Stub) queued. Dependencies: datetime (stub), sys (stub), time (stub)
Analysis of importlib.machinery (Library) queued. Dependencies: importlib.machinery (stub), _imp, importlib._bootstrap, importlib._bootstrap_external
Analysis of _random (Stub) queued. Dependencies: sys (stub)
Analysis of tty (Stub) queued. Dependencies: 
Analysis of bisect (Library) queued. Dependencies: bisect (stub), _bisect
Analysis of http.server (Library) queued. Dependencies: http.server (stub), copy, datetime, email, email.utils, html, http, http.client, io, mimetypes, os, posixpath, select, shutil, socket, socketserver, sys, time, urllib, urllib.parse, functools, pwd, base64, binascii, subprocess, argparse
Analysis of bdb (Library) queued. Dependencies: fnmatch, sys, os, inspect, linecache, reprlib
Import:  codeop /Users/grwheele/anaconda3/envs/default/lib/python3.7/codeop.py 
Analysis of socket (Library) queued. Dependencies: socket (stub), _socket, os, sys, io, selectors, enum, errno
Analysis of email.message (Stub) queued. Dependencies: sys (stub), email.charset (stub), email.errors (stub), email.header (stub), email.policy (stub), email.contentmanager (stub)
Create compiled (scraped):  _bisect /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_bisect.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of tty (Library) queued. Dependencies: tty (stub), termios
Analysis of zlib (Stub) queued. Dependencies: sys (stub)
Analysis of http.server (Stub) queued. Dependencies: sys (stub), socketserver (stub), email (stub), email.message (stub)
Analysis of bz2 (Stub) queued. Dependencies: io (stub), sys (stub), os (stub)
Analysis of zlib (Compiled) queued. Dependencies: zlib (stub)
Analysis of email.policy (Stub) queued. Dependencies: abc (stub), sys (stub), email.message (stub), email.errors (stub), email.header (stub), email.contentmanager (stub)
Analysis of _bisect (Compiled) queued. Dependencies: _bisect (stub)
Analysis of http (Library) queued. Dependencies: http (stub), enum
Analysis of lzma (Stub) queued. Dependencies: io (stub), sys (stub), os (stub)
Analysis of _bisect (Stub) queued. Dependencies: 
Analysis of pydoc_data (Library) queued. Dependencies: 
Analysis of bz2 (Library) queued. Dependencies: bz2 (stub), io, os, warnings, _compression, threading, _bz2
Analysis of http (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of codeop (Library) queued. Dependencies: codeop (stub), __future__
Analysis of bisect (Stub) queued. Dependencies: 
Analysis of hashlib (Library) queued. Dependencies: hashlib (stub), _sha1, _md5, _sha256, _sha512, _blake2, _sha3, _hashlib, logging
Analysis of datetime (Stub) queued. Dependencies: sys (stub), time (stub)
Analysis of codeop (Stub) queued. Dependencies: types (stub)
Import:  html /Users/grwheele/anaconda3/envs/default/lib/python3.7/html/__init__.py 
Analysis of lzma (Library) queued. Dependencies: lzma (stub), io, os, _lzma, _compression
Import:  http.client /Users/grwheele/anaconda3/envs/default/lib/python3.7/http/client.py 
Import:  mimetypes /Users/grwheele/anaconda3/envs/default/lib/python3.7/mimetypes.py 
Import:  socketserver /Users/grwheele/anaconda3/envs/default/lib/python3.7/socketserver.py 
Analysis of datetime (Library) queued. Dependencies: datetime (stub), time, math, sys, _strptime, _datetime
Create compiled (scraped):  _socket /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  termios /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/termios.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _bz2 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_bz2.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of pydoc_data.topics (Library) queued. Dependencies: 
Create compiled (scraped):  _sha1 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_sha1.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _md5 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_md5.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha256 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_sha256.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha512 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_sha512.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _blake2 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_blake2.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha3 /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_sha3.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _hashlib /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_hashlib.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Create compiled (scraped):  _lzma /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_lzma.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of _hashlib (Compiled) queued. Dependencies: 
Import:  _strptime /Users/grwheele/anaconda3/envs/default/lib/python3.7/_strptime.py 
Analysis of linecache (Library) on depth 2 completed in 1.77 ms.
Analysis of _lzma (Compiled) queued. Dependencies: 
Create compiled (scraped):  _datetime /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_datetime.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of fnmatch (Library) on depth 3 completed in 15.68 ms.
Analysis of _sha3 (Compiled) queued. Dependencies: 
Analysis of _datetime (Compiled) queued. Dependencies: datetime
Analysis of _blake2 (Compiled) queued. Dependencies: 
Analysis of pyexpat (Stub) queued. Dependencies: pyexpat.errors (stub), pyexpat.model (stub)
Analysis of _sha512 (Compiled) queued. Dependencies: 
Analysis of html (Stub) queued. Dependencies: 
Analysis of _sha256 (Compiled) queued. Dependencies: 
Analysis of pyexpat.errors (Stub) queued. Dependencies: sys (stub)
Analysis of pyexpat (Compiled) queued. Dependencies: pyexpat (stub)
Analysis of py_compile (Stub) queued. Dependencies: sys (stub)
Analysis of pyexpat.model (Stub) queued. Dependencies: 
Analysis of _strptime (Library) queued. Dependencies: time, locale, calendar, re, datetime, _thread
Analysis of html (Library) queued. Dependencies: html (stub), re, html.entities
Analysis of http.client (Stub) queued. Dependencies: email (stub), email.message (stub), io (stub), socket (stub), sys (stub), ssl (stub), types (stub)
Analysis of mimetypes (Stub) queued. Dependencies: sys (stub)
Analysis of _md5 (Compiled) queued. Dependencies: 
Analysis of socketserver (Stub) queued. Dependencies: socket (stub), sys (stub), types (stub)
Analysis of mimetypes (Library) queued. Dependencies: mimetypes (stub), os, sys, posixpath, urllib, urllib.parse, getopt
Import:  html.entities /Users/grwheele/anaconda3/envs/default/lib/python3.7/html/entities.py 
Analysis of tracemalloc (Library) queued. Dependencies: tracemalloc (stub), collections.abc, functools, fnmatch, linecache, os, pickle, _tracemalloc, io
Analysis of http.client (Library) queued. Dependencies: http.client (stub), email, email.parser, email.message, http, io, re, socket, collections, collections.abc, urllib.parse, ssl, warnings
Analysis of termios (Stub) queued. Dependencies: 
Analysis of ssl (Stub) queued. Dependencies: socket (stub), sys (stub)
Analysis of tracemalloc (Library) on depth 2 completed in 22.48 ms.
Analysis of _socket (Compiled) queued. Dependencies: 
Analysis of socketserver (Library) queued. Dependencies: socketserver (stub), socket, selectors, os, sys, threading, io, time, traceback
Analysis of _bz2 (Compiled) queued. Dependencies: 
Analysis of termios (Compiled) queued. Dependencies: termios (stub)
Import:  ssl /Users/grwheele/anaconda3/envs/default/lib/python3.7/ssl.py 
Analysis of html.entities (Library) queued. Dependencies: html.entities (stub)
Analysis of _sha1 (Compiled) queued. Dependencies: 
Analysis of html.entities (Stub) queued. Dependencies: 
Analysis of ssl (Library) queued. Dependencies: ssl (stub), sys, os, collections, enum, _ssl, socket, base64, errno, warnings, time, calendar
Create compiled (scraped):  _ssl /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so /Users/grwheele/anaconda3/envs/default/lib/python3.7/lib-dynload 
Analysis of _ssl (Compiled) queued. Dependencies: 
Analysis of pkg_resources (Library) queued. Dependencies: pkg_resources (stub), __future__, sys, os, io, time, re, types, zipfile, zipimport, warnings, stat, functools, pkgutil, operator, platform, collections, plistlib, email, email.parser, errno, tempfile, textwrap, itertools, inspect, ntpath, posixpath, _imp, imp, pkg_resources.extern, importlib, importlib.machinery, pkg_resources.py31compat, sysconfig, linecache
Analysis of pkg_resources (Library) on depth 1 completed in 76.42 ms.
Analysis version 102 has been completed in 783.84 ms with 27 entries analyzed and 19 entries skipped.
Analysis version 517 of 488 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of abc (Stub) on depth 3 completed in 0.59 ms.
Analysis of posix (Stub) on depth 4 completed in 0.64 ms.
Analysis of _compat_pickle (Library) on depth 4 completed in 0.95 ms.
Analysis of copyreg (Library) on depth 3 completed in 1.04 ms.
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of sysconfig (Stub) on depth 3 completed in 0.69 ms.
Analysis of mmap (Stub) on depth 4 completed in 1.26 ms.
Analysis of _pickle (Compiled) on depth 4 completed in 1.74 ms.
Analysis of sre_constants (Stub) on depth 4 completed in 2.28 ms.
Analysis of _weakrefset (Stub) on depth 5 completed in 3.66 ms.
Analysis of importlib._bootstrap (Library) on depth 3 completed in 8.35 ms.
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of keyword (Stub) on depth 4 completed in 0.25 ms.
Analysis of copy (Stub) on depth 4 completed in 0.34 ms.
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of _struct (Compiled) on depth 4 completed in 0.47 ms.
Analysis of textwrap (Stub) on depth 3 completed in 1.24 ms.
Analysis of distutils (Stub) on depth 5 completed in 0.02 ms.
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of pyexpat.model (Stub) on depth 5 completed in 0.06 ms.
Analysis of _posixsubprocess (Stub) on depth 5 completed in 0.22 ms.
Analysis of distutils.log (Stub) on depth 5 completed in 0.53 ms.
Analysis of gettext (Stub) on depth 5 completed in 0.99 ms.
Analysis of string (Stub) on depth 4 completed in 1.15 ms.
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of _opcode (Compiled) on depth 5 completed in 0.16 ms.
Analysis of email.contentmanager (Stub) on depth 5 completed in 0.48 ms.
Analysis of encodings.mbcs (Library) on depth 5 completed in 0.67 ms.
Analysis of email.errors (Stub) on depth 5 completed in 5.24 ms.
Analysis of urllib (Stub) on depth 6 completed in 0.01 ms.
Analysis of grp (Stub) on depth 5 completed in 0.36 ms.
Analysis of getopt (Stub) on depth 7 completed in 0.47 ms.
Analysis of pydoc_data (Library) on depth 7 completed in 0.07 ms.
Analysis of email.charset (Stub) on depth 5 completed in 0.75 ms.
Analysis of _heapq (Stub) on depth 5 completed in 0.32 ms.
Analysis of pydoc_data.topics (Library) on depth 7 completed in 0.28 ms.
Analysis of quopri (Stub) on depth 6 completed in 0.19 ms.
Analysis of tty (Stub) on depth 8 completed in 0.31 ms.
Analysis of cmd (Stub) on depth 7 completed in 1.22 ms.
Analysis of runpy (Stub) on depth 7 completed in 0.45 ms.
Analysis of encodings.aliases (Library) on depth 5 completed in 6.82 ms.
Analysis of bisect (Stub) on depth 5 completed in 0.33 ms.
Analysis of unicodedata (Stub) on depth 7 completed in 1.01 ms.
Analysis of _socket (Compiled) on depth 4 completed in 2.9 ms.
Analysis of _sha512 (Compiled) on depth 5 completed in 4.57 ms.
Analysis of _md5 (Compiled) on depth 5 completed in 4.65 ms.
Analysis of _sha256 (Compiled) on depth 5 completed in 4.67 ms.
Analysis of _sha1 (Compiled) on depth 5 completed in 4.73 ms.
Analysis of _bisect (Stub) on depth 6 completed in 4.8 ms.
Analysis of _bz2 (Compiled) on depth 4 completed in 5.19 ms.
Analysis of _blake2 (Compiled) on depth 5 completed in 0.81 ms.
Analysis of html (Stub) on depth 9 completed in 0.15 ms.
Analysis of html.entities (Stub) on depth 10 completed in 0.14 ms.
Analysis of pkg_resources.extern (Library) on depth 2 completed in 0.82 ms.
Analysis of _hashlib (Compiled) on depth 5 completed in 1.12 ms.
Analysis of _lzma (Compiled) on depth 4 completed in 1.49 ms.
Analysis of _sha3 (Compiled) on depth 5 completed in 7.2 ms.
Analysis of decimal (Stub) on depth 7 completed in 17.17 ms.
Analysis of termios (Stub) on depth 9 completed in 8.93 ms.
Analysis of io (Stub) on depth 3 completed in 10.38 ms.
Analysis of distutils (Library) on depth 4 completed in 0.31 ms.
Analysis of _posixsubprocess (Compiled) on depth 4 completed in 0.36 ms.
Analysis of sre_constants (Library) queued. Dependencies: sre_constants (stub), _sre, io
Analysis of _weakrefset (Library) on depth 4 completed in 2.21 ms.
Analysis of distutils.log (Library) on depth 4 completed in 2.45 ms.
Analysis of email.header (Stub) on depth 5 completed in 0.71 ms.
Analysis of sre_parse (Stub) on depth 4 completed in 3.34 ms.
Analysis of _heapq (Compiled) on depth 4 completed in 0.36 ms.
Analysis of _bisect (Compiled) on depth 5 completed in 0.17 ms.
Analysis of urllib (Library) on depth 5 completed in 0.14 ms.
Analysis of grp (Compiled) on depth 4 completed in 1.11 ms.
Analysis of unicodedata (Compiled) on depth 6 completed in 1.32 ms.
Analysis of _ssl (Compiled) on depth 10 completed in 22.98 ms.
Analysis of importlib._bootstrap_external (Library) on depth 3 completed in 42.64 ms.
Analysis of sre_constants (Library) on depth 3 completed in 13.53 ms.
Analysis of email.errors (Library) on depth 4 completed in 21.53 ms.
Analysis of html.entities (Library) on depth 9 completed in 26.69 ms.
Analysis of bisect (Library) on depth 4 completed in 0.64 ms.
Analysis of os.path (Stub) on depth 4 completed in 3.46 ms.
Analysis of _py_abc (Library) on depth 4 completed in 4.96 ms.
Analysis of codecs (Stub) on depth 4 completed in 5.47 ms.
Analysis of sre_compile (Stub) on depth 4 completed in 0.39 ms.
Analysis of token (Stub) on depth 4 completed in 1.36 ms.
Analysis of pickle (Stub) on depth 4 completed in 1.39 ms.
Analysis of abc (Library) on depth 3 completed in 2.13 ms.
Analysis of time (Stub) on depth 5 completed in 1.61 ms.
Analysis of array (Stub) on depth 5 completed in 16.23 ms.
Analysis of subprocess (Stub) on depth 4 completed in 16.35 ms.
Analysis of stat (Stub) on depth 3 completed in 0.5 ms.
Analysis of pprint (Stub) on depth 4 completed in 0.61 ms.
Analysis of pkgutil (Stub) on depth 3 completed in 0.79 ms.
Analysis of _weakref (Stub) on depth 5 completed in 0.91 ms.
Analysis of heapq (Stub) on depth 4 completed in 0.51 ms.
Analysis of zipfile (Stub) on depth 3 completed in 1.82 ms.
Analysis of tempfile (Stub) on depth 3 completed in 0.98 ms.
Analysis of py_compile (Stub) on depth 4 completed in 0.47 ms.
Analysis of email.policy (Stub) on depth 4 completed in 4.32 ms.
Analysis of binascii (Stub) on depth 4 completed in 3.47 ms.
Analysis of pyexpat.errors (Stub) on depth 5 completed in 0.29 ms.
Analysis of _random (Stub) on depth 5 completed in 0.37 ms.
Analysis of opcode (Stub) on depth 5 completed in 0.57 ms.
Analysis of contextlib (Stub) on depth 4 completed in 5.09 ms.
Analysis of select (Stub) on depth 5 completed in 1.8 ms.
Analysis of math (Stub) on depth 5 completed in 5.47 ms.
Analysis of operator (Stub) on depth 3 completed in 11.21 ms.
Analysis of threading (Stub) on depth 4 completed in 6.61 ms.
Analysis of inspect (Stub) on depth 3 completed in 11.46 ms.
Analysis of argparse (Stub) on depth 4 completed in 13.74 ms.
Analysis of ntpath (Stub) on depth 3 completed in 1.29 ms.
Analysis of difflib (Stub) on depth 6 completed in 2.12 ms.
Analysis of locale (Stub) on depth 6 completed in 2.13 ms.
Analysis of pdb (Stub) on depth 6 completed in 0.48 ms.
Analysis of shutil (Stub) on depth 4 completed in 2.79 ms.
Analysis of posixpath (Stub) on depth 3 completed in 1.11 ms.
Analysis of zlib (Stub) on depth 4 completed in 1.37 ms.
Analysis of uu (Stub) on depth 6 completed in 0.43 ms.
Analysis of base64 (Stub) on depth 7 completed in 0.98 ms.
Analysis of shlex (Stub) on depth 7 completed in 6.4 ms.
Analysis of glob (Stub) on depth 7 completed in 0.3 ms.
Analysis of readline (Stub) on depth 7 completed in 0.86 ms.
Analysis of tarfile (Stub) on depth 5 completed in 9.01 ms.
Analysis of hashlib (Stub) on depth 5 completed in 1.34 ms.
Analysis of urllib.parse (Stub) on depth 6 completed in 12.45 ms.
Analysis of code (Stub) on depth 7 completed in 0.9 ms.
Analysis of webbrowser (Stub) on depth 8 completed in 6.6 ms.
Analysis of lzma (Stub) on depth 4 completed in 5.08 ms.
Analysis of bz2 (Stub) on depth 4 completed in 0.94 ms.
Analysis of encodings (Stub) on depth 5 completed in 0.12 ms.
Analysis of mimetypes (Stub) on depth 9 completed in 1.06 ms.
Analysis of platform (Stub) on depth 3 completed in 1.17 ms.
Analysis of codeop (Stub) on depth 8 completed in 0.53 ms.
Analysis of _compression (Stub) on depth 5 completed in 3.56 ms.
Analysis of plistlib (Stub) on depth 3 completed in 1.08 ms.
Analysis of importlib.machinery (Stub) on depth 3 completed in 2.67 ms.
Analysis of optparse (Stub) on depth 7 completed in 20.74 ms.
Analysis of termios (Compiled) on depth 8 completed in 59.61 ms.
Analysis of socket (Stub) on depth 4 completed in 8.07 ms.
Analysis of _ast (Stub) on depth 5 completed in 27.11 ms.
Analysis of reprlib (Stub) on depth 4 completed in 0.82 ms.
Analysis of http (Stub) on depth 8 completed in 2.18 ms.
Analysis of struct (Stub) on depth 4 completed in 1.63 ms.
Analysis of signal (Stub) on depth 5 completed in 9.43 ms.
Analysis of io (Library) on depth 2 completed in 9.54 ms.
Analysis of datetime (Stub) on depth 4 completed in 11.66 ms.
Analysis of stat (Library) on depth 2 completed in 16.94 ms.
Analysis of _random (Compiled) on depth 4 completed in 0.62 ms.
Analysis of pyexpat (Stub) on depth 5 completed in 1.23 ms.
Analysis of binascii (Compiled) on depth 3 completed in 1.65 ms.
Analysis of dis (Stub) on depth 4 completed in 1.34 ms.
Analysis of collections (Stub) on depth 3 completed in 21.72 ms.
Analysis of weakref (Stub) on depth 4 completed in 4.4 ms.
Analysis of email.message (Stub) on depth 4 completed in 8.39 ms.
Analysis of random (Stub) on depth 4 completed in 8.58 ms.
Analysis of opcode (Library) on depth 4 completed in 5.03 ms.
Analysis of math (Compiled) on depth 4 completed in 6.86 ms.
Analysis of readline (Compiled) on depth 6 completed in 0.96 ms.
Analysis of codeop (Library) on depth 7 completed in 1.19 ms.
Analysis of gzip (Stub) on depth 6 completed in 1.7 ms.
Analysis of encodings (Library) on depth 4 completed in 2.56 ms.
Analysis of importlib.util (Stub) on depth 4 completed in 1.32 ms.
Analysis of selectors (Stub) on depth 5 completed in 2.51 ms.
Analysis of ast (Stub) on depth 4 completed in 1.23 ms.
Analysis of tty (Library) on depth 7 completed in 3.1 ms.
Analysis of socketserver (Stub) on depth 9 completed in 7.68 ms.
Analysis of zlib (Compiled) on depth 3 completed in 13.82 ms.
Analysis of reprlib (Library) on depth 3 completed in 8.59 ms.
Analysis of ssl (Stub) on depth 10 completed in 9.96 ms.
Analysis of logging (Stub) on depth 6 completed in 14.37 ms.
Analysis of struct (Library) on depth 3 completed in 0.42 ms.
Analysis of email.utils (Stub) on depth 5 completed in 0.9 ms.
Analysis of _collections_abc (Library) on depth 3 completed in 46.42 ms.
Analysis of _compression (Library) on depth 4 completed in 5.89 ms.
Analysis of select (Compiled) on depth 4 completed in 24.92 ms.
Analysis of calendar (Stub) on depth 6 completed in 6.49 ms.
Analysis of email (Stub) on depth 3 completed in 0.38 ms.
Analysis of email.feedparser (Stub) on depth 4 completed in 0.58 ms.
Analysis of _threading_local (Stub) on depth 5 completed in 0.93 ms.
Analysis of xml.parsers.expat (Stub) on depth 4 completed in 1.33 ms.
Analysis of email.generator (Stub) on depth 6 completed in 0.87 ms.
Analysis of pyexpat (Compiled) on depth 4 completed in 2.7 ms.
Analysis of email.iterators (Stub) on depth 6 completed in 0.21 ms.
Analysis of email.encoders (Stub) on depth 6 completed in 0.16 ms.
Analysis of email.headerregistry (Stub) on depth 7 completed in 12.63 ms.
Analysis of importlib.machinery (Library) on depth 2 completed in 12.69 ms.
Analysis of _imp (Stub) on depth 4 completed in 19.46 ms.
Analysis of email.parser (Stub) on depth 3 completed in 1.09 ms.
Analysis of xml.parsers.expat (Library) on depth 3 completed in 21 ms.
Analysis of codecs (Library) on depth 3 completed in 35.74 ms.
Analysis of email.iterators (Library) on depth 5 completed in 0.5 ms.
Analysis of unittest (Stub) on depth 6 completed in 35.95 ms.
Analysis of imp (Stub) on depth 3 completed in 1.09 ms.
Analysis of http.server (Stub) on depth 8 completed in 7.03 ms.
Analysis of doctest (Stub) on depth 5 completed in 5.83 ms.
Analysis of http.client (Stub) on depth 9 completed in 8.45 ms.
Analysis of pydoc (Library) on depth 6 completed in 93.79 ms.
Analysis of pdb (Library) on depth 5 completed in 23.11 ms.
Analysis of doctest (Library) on depth 4 completed in 20.42 ms.
Analysis of heapq (Library) on depth 3 completed in 2.1 ms.
Analysis of difflib (Library) on depth 5 completed in 22.12 ms.
Analysis of collections (Library) on depth 2 completed in 27.29 ms.
Analysis of shlex (Library) on depth 6 completed in 1.62 ms.
Analysis of unittest.util (Library) on depth 7 completed in 6.83 ms.
Analysis of string (Library) on depth 3 completed in 9.94 ms.
Analysis of selectors (Library) on depth 4 completed in 13.3 ms.
Analysis of contextlib (Library) on depth 3 completed in 13.54 ms.
Analysis of urllib.parse (Library) on depth 5 completed in 23.55 ms.
Analysis of unittest.case (Library) on depth 6 completed in 31.88 ms.
Analysis of cmd (Library) on depth 6 completed in 1.59 ms.
Analysis of email.utils (Library) on depth 4 completed in 1.97 ms.
Analysis of types (Library) on depth 2 completed in 4.69 ms.
Analysis of email.quoprimime (Library) on depth 5 completed in 5.88 ms.
Analysis of operator (Library) on depth 2 completed in 6.29 ms.
Analysis of ntpath (Library) on depth 2 completed in 10.27 ms.
Analysis of mimetypes (Library) on depth 8 completed in 8.83 ms.
Analysis of logging (Library) on depth 5 completed in 37.59 ms.
Analysis of copy (Library) on depth 3 completed in 6.5 ms.
Analysis of genericpath (Library) on depth 3 completed in 10.67 ms.
Analysis of email.generator (Library) on depth 5 completed in 10.89 ms.
Analysis of glob (Library) on depth 6 completed in 10.39 ms.
Analysis of lzma (Library) on depth 3 completed in 19.03 ms.
Analysis of getopt (Library) on depth 6 completed in 12.2 ms.
Analysis of unittest.loader (Library) on depth 6 completed in 26.02 ms.
Analysis of hashlib (Library) on depth 4 completed in 6.09 ms.
Analysis of bdb (Library) on depth 6 completed in 19.21 ms.
Analysis of posixpath (Library) on depth 2 completed in 7.67 ms.
Analysis of gzip (Library) on depth 5 completed in 15.59 ms.
Analysis of quopri (Library) on depth 5 completed in 2.75 ms.
Analysis of base64 (Library) on depth 6 completed in 10.88 ms.
Analysis of ssl (Library) on depth 9 completed in 58.95 ms.
Analysis of weakref (Library) on depth 3 completed in 19.4 ms.
Analysis of optparse (Library) on depth 6 completed in 21.96 ms.
Analysis of unittest.main (Library) on depth 6 completed in 6.58 ms.
Analysis of socketserver (Library) on depth 8 completed in 27.71 ms.
Analysis of random (Library) on depth 3 completed in 7.98 ms.
Analysis of email._header_value_parser (Library) on depth 7 completed in 76.55 ms.
Analysis of tarfile (Library) on depth 4 completed in 34.89 ms.
Analysis of email.encoders (Library) on depth 5 completed in 3.38 ms.
Analysis of unittest (Library) on depth 5 completed in 5.23 ms.
Analysis of uu (Library) on depth 5 completed in 6.76 ms.
Analysis of email.base64mime (Library) on depth 5 completed in 7.96 ms.
Analysis of tempfile (Library) on depth 2 completed in 10.2 ms.
Analysis of email.headerregistry (Library) on depth 6 completed in 15.11 ms.
Analysis of shutil (Library) on depth 3 completed in 16.44 ms.
Analysis of unittest.result (Library) on depth 6 completed in 6.39 ms.
Analysis of email.policy (Library) on depth 5 completed in 6.38 ms.
Analysis of unittest.runner (Library) on depth 6 completed in 8.98 ms.
Analysis of unittest.suite (Library) on depth 6 completed in 9.32 ms.
Analysis of webbrowser (Library) on depth 7 completed in 16.89 ms.
Analysis of enum (Library) on depth 3 completed in 23.38 ms.
Analysis of importlib (Library) on depth 2 completed in 1.37 ms.
Analysis of http.client (Library) on depth 8 completed in 43.53 ms.
Analysis of runpy (Library) on depth 6 completed in 8.46 ms.
Analysis of importlib.abc (Library) on depth 4 completed in 8.88 ms.
Analysis of email.message (Library) on depth 4 completed in 16.11 ms.
Analysis of sre_parse (Library) on depth 3 completed in 17.31 ms.
Analysis of signal (Library) on depth 4 completed in 1.56 ms.
Analysis of importlib.util (Library) on depth 3 completed in 4.08 ms.
Analysis of http (Library) on depth 7 completed in 9.64 ms.
Analysis of locale (Library) on depth 5 completed in 28.56 ms.
Analysis of email.feedparser (Library) on depth 3 completed in 15.94 ms.
Analysis of zipfile (Library) on depth 2 completed in 62.87 ms.
Analysis of email.contentmanager (Library) on depth 6 completed in 16.9 ms.
Analysis of sre_compile (Library) on depth 3 completed in 30.91 ms.
Analysis of _bootlocale (Library) on depth 6 completed in 0.67 ms.
Analysis of unittest.signals (Library) on depth 6 completed in 3.99 ms.
Analysis of textwrap (Library) on depth 2 completed in 6.35 ms.
Analysis of keyword (Library) on depth 3 completed in 2.03 ms.
Analysis of email.parser (Library) on depth 2 completed in 13.02 ms.
Analysis of html (Library) on depth 8 completed in 5.5 ms.
Analysis of email (Library) on depth 2 completed in 0.61 ms.
Analysis of email.charset (Library) on depth 4 completed in 1.32 ms.
Analysis of http.server (Library) on depth 7 completed in 51.04 ms.
Analysis of gettext (Library) on depth 4 completed in 16.88 ms.
Analysis of email._encoded_words (Library) on depth 5 completed in 8.03 ms.
Analysis of _strptime (Library) on depth 4 completed in 23.15 ms.
Analysis of pprint (Library) on depth 3 completed in 23.89 ms.
Analysis of email.header (Library) on depth 4 completed in 18.86 ms.
Analysis of token (Library) on depth 3 completed in 40.32 ms.
Analysis of email._policybase (Library) on depth 3 completed in 5.67 ms.
Analysis of argparse (Library) on depth 3 completed in 35.44 ms.
Analysis of code (Library) on depth 6 completed in 7.6 ms.
Analysis of socket (Library) on depth 3 completed in 102.14 ms.
Analysis of py_compile (Library) on depth 3 completed in 12.43 ms.
Analysis of dis (Library) on depth 3 completed in 16.83 ms.
Analysis of datetime (Library) on depth 3 completed in 56.19 ms.
Analysis of _datetime (Compiled) on depth 4 completed in 0.31 ms.
Analysis of threading (Library) on depth 3 completed in 30.49 ms.
Analysis of _threading_local (Library) on depth 4 completed in 7.64 ms.
Analysis of bz2 (Library) on depth 3 completed in 8.66 ms.
Analysis of plistlib (Library) on depth 2 completed in 20.83 ms.
Analysis of calendar (Library) on depth 5 completed in 27.92 ms.
Analysis of email._parseaddr (Library) on depth 5 completed in 8.86 ms.
Analysis of platform (Library) on depth 2 completed in 16.52 ms.
Analysis of subprocess (Library) on depth 3 completed in 46.19 ms.
Analysis of pickle (Library) on depth 3 completed in 91.45 ms.
Analysis of inspect (Library) on depth 2 completed in 75.04 ms.
Analysis of ast (Library) on depth 3 completed in 1.99 ms.
Analysis of pkgutil (Library) on depth 2 completed in 7.99 ms.
Analysis of pkg_resources.py31compat (Library) on depth 2 completed in 0.6 ms.
Analysis of imp (Library) on depth 2 completed in 4.76 ms.
Analysis of _osx_support (Library) on depth 3 completed in 10.62 ms.
Analysis of sysconfig (Library) on depth 2 completed in 7.83 ms.
Analysis version 517 has been completed in 732.62 ms with 320 entries analyzed and 168 entries skipped.
Analysis version 518 of 488 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of abc (Stub) on depth 3 completed in 0.6 ms.
Analysis of copyreg (Library) on depth 3 completed in 0.99 ms.
Analysis version 518 has been completed in 1.33 ms with 26 entries analyzed and 462 entries skipped.
```

### LINKED ISSUE #1680: All non-trivial completions missing in imported modules
No idea what's going on or when this started exactly, but the completions for all imported modules are showing the exact same Python built-in symbols and nothing defined in the module itself. I've tested built-in and 3rd-party modules and this happens in all of them.

Screen Shot 2019-10-11 at 7 57 16 PM
Screen Shot 2019-10-11 at 7 57 25 PM

Example log below. The last line about the analysis of `sys` being canceled seems suspicious. 

```
[Info  - 7:58:58 PM] Microsoft Python Language Server version 0.4.68.0
[Info  - 7:58:58 PM] Workspace root: /Users/malmaud/q
[Info  - 7:58:58 PM] Analysis cache path: /Users/malmaud/Library/Caches/Microsoft/Python Language Server
[Info  - 7:58:58 PM] GetCurrentSearchPaths /Users/malmaud/anaconda3/bin/python 
[Info  - 7:58:58 PM] Interpreter search paths:
[Info  - 7:58:58 PM]     /Users/malmaud/anaconda3/lib/python3.7
[Info  - 7:58:58 PM]     /Users/malmaud/anaconda3/lib/python3.7/lib-dynload
[Info  - 7:58:58 PM]     /Users/malmaud/.local/lib/python3.7/site-packages
[Info  - 7:58:58 PM]     /Users/malmaud/anaconda3/lib/python3.7/site-packages
[Info  - 7:58:58 PM]     /Users/malmaud/anaconda3/lib/python3.7/site-packages/aeosa
[Info  - 7:58:58 PM] User search paths:
[Info  - 7:59:02 PM] Initializing for /Users/malmaud/anaconda3/bin/python
Watching /Users/malmaud/anaconda3/lib/python3.7
Watching /Users/malmaud/.local/lib/python3.7/site-packages
[Info  - 7:59:02 PM] Analysis caching mode: System.
Opening document file:///Users/malmaud/q/hi.py
Analysis of hi (User) queued. Dependencies: os
Import:  os /Users/malmaud/anaconda3/lib/python3.7/os.py 
Analysis version 2 of 1 entries has started.
Analysis of hi (User) queued. Dependencies: os
Analysis of hi (User) on depth 0 completed in 16.35 ms.
Analysis version 2 of 1 entries has been completed in 17.49 ms.
Analysis version 4 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 4 has been completed in 4.42 ms with 1 entries analyzed and 1 entries skipped.
Analysis of os (Stub) queued. Dependencies: io (stub), sys (stub), posix (stub), os.path (stub)
Analysis version 5 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 5 has been completed in 0.27 ms with 1 entries analyzed and 1 entries skipped.
Analysis of io (Stub) queued. Dependencies: codecs (stub), mmap (stub), sys (stub), types (stub)
Analysis version 10 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 10 has been completed in 0.17 ms with 1 entries analyzed and 1 entries skipped.
Analysis of sys (Stub) queued. Dependencies: types (stub), importlib.abc (stub)
Analysis version 14 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 14 has been completed in 0.15 ms with 1 entries analyzed and 1 entries skipped.
Analysis of types (Stub) queued. Dependencies: sys (stub), _importlib_modulespec (stub)
Analysis of importlib.abc (Stub) queued. Dependencies: abc (stub), os (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Analysis of os.path (Stub) queued. Dependencies: posix (stub), sys (stub)
Analysis of _importlib_modulespec (Stub) queued. Dependencies: abc (stub), sys (stub)
Analysis of abc (Stub) queued. Dependencies: 
Analysis version 22 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 22 has been completed in 0.13 ms with 1 entries analyzed and 1 entries skipped.
Analysis of codecs (Stub) queued. Dependencies: sys (stub), abc (stub), types (stub)
Analysis version 23 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 23 has been completed in 0.14 ms with 1 entries analyzed and 1 entries skipped.
Analysis of posix (Stub) queued. Dependencies: 
Analysis version 24 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 24 has been completed in 0.14 ms with 1 entries analyzed and 1 entries skipped.
Analysis of mmap (Stub) queued. Dependencies: sys (stub)
Analysis version 25 of 2 entries has started.
Analysis of os(Library) canceled (no AST yet).
Analysis version 25 has been completed in 0.14 ms with 1 entries analyzed and 1 entries skipped.
Completions in file:///Users/malmaud/q/hi.py at (3, 1)
Analysis of os (Library) queued. Dependencies: os (stub), abc, sys, stat, posix, posixpath, ntpath, warnings, _collections_abc, subprocess, io
Import:  abc /Users/malmaud/anaconda3/lib/python3.7/abc.py 
Create built-in compiled (scraped) module:  sys /Users/malmaud/anaconda3/bin/python 
Import:  stat /Users/malmaud/anaconda3/lib/python3.7/stat.py 
Create built-in compiled (scraped) module:  posix /Users/malmaud/anaconda3/bin/python 
Import:  posixpath /Users/malmaud/anaconda3/lib/python3.7/posixpath.py 
Import:  ntpath /Users/malmaud/anaconda3/lib/python3.7/ntpath.py 
Import:  warnings /Users/malmaud/anaconda3/lib/python3.7/warnings.py 
Import:  _collections_abc /Users/malmaud/anaconda3/lib/python3.7/_collections_abc.py 
Analysis of ntpath (Stub) queued. Dependencies: sys (stub)
Import:  subprocess /Users/malmaud/anaconda3/lib/python3.7/subprocess.py 
Import:  io /Users/malmaud/anaconda3/lib/python3.7/io.py 
Analysis version 34 of 29 entries has started.
Analysis of abc(Library) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of stat(Library) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of posixpath(Library) canceled (no AST yet).
Analysis of ntpath(Library) canceled (no AST yet).
Analysis of warnings(Library) canceled (no AST yet).
Analysis of ntpath (Library) queued. Dependencies: ntpath (stub), os, sys, stat, genericpath, string
Import:  genericpath /Users/malmaud/anaconda3/lib/python3.7/genericpath.py 
Import:  string /Users/malmaud/anaconda3/lib/python3.7/string.py 
Analysis of string (Library) queued. Dependencies: string (stub), _string, re, collections
Create built-in compiled (scraped) module:  _string /Users/malmaud/anaconda3/bin/python 
Analysis of warnings (Stub) queued. Dependencies: types (stub)
Import:  re /Users/malmaud/anaconda3/lib/python3.7/re.py 
Import:  collections /Users/malmaud/anaconda3/lib/python3.7/collections/__init__.py 
Analysis of posixpath (Library) queued. Dependencies: posixpath (stub), os, sys, stat, genericpath, pwd, re
Analysis of subprocess (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of stat (Library) queued. Dependencies: stat (stub), _stat
Analysis of stat (Stub) queued. Dependencies: sys (stub)
Analysis of posixpath (Stub) queued. Dependencies: sys (stub)
Analysis of io (Library) queued. Dependencies: io (stub), _io, abc
Create built-in compiled (scraped) module:  pwd /Users/malmaud/anaconda3/bin/python 
Analysis of subprocess (Library) queued. Dependencies: subprocess (stub), sys, io, os, time, signal, warnings, errno, threading, _posixsubprocess, select, selectors
Analysis of pwd (Stub) queued. Dependencies: 
Analysis of abc (Stub) on depth 5 completed in 34.56 ms.
Create built-in compiled (scraped) module:  time /Users/malmaud/anaconda3/bin/python 
Analysis of abc (Library) queued. Dependencies: abc (stub), _abc, _py_abc
Import:  signal /Users/malmaud/anaconda3/lib/python3.7/signal.py 
Analysis of posix (Stub) on depth 3 completed in 10.55 ms.
Create built-in compiled (scraped) module:  errno /Users/malmaud/anaconda3/bin/python 
Analysis of warnings (Library) queued. Dependencies: warnings (stub), sys, linecache, tracemalloc, re, traceback, _warnings
Import:  threading /Users/malmaud/anaconda3/lib/python3.7/threading.py 
Create compiled (scraped):  _posixsubprocess /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  select /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/select.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Import:  selectors /Users/malmaud/anaconda3/lib/python3.7/selectors.py 
Create built-in compiled (scraped) module:  _stat /Users/malmaud/anaconda3/bin/python 
Create built-in compiled (scraped) module:  _io /Users/malmaud/anaconda3/bin/python 
Analysis of collections (Library) queued. Dependencies: collections (stub), _collections_abc, operator, keyword, sys, heapq, _weakref, itertools, reprlib, _collections, warnings, copy
Analysis of signal (Library) queued. Dependencies: signal (stub), _signal, functools, enum
Analysis of errno (Stub) queued. Dependencies: sys (stub)
Analysis of hi (User) queued. Dependencies: os
Create built-in compiled (scraped) module:  _abc /Users/malmaud/anaconda3/bin/python 
Analysis of _stat (Stub) queued. Dependencies: 
Import:  _py_abc /Users/malmaud/anaconda3/lib/python3.7/_py_abc.py 
Analysis of signal (Stub) queued. Dependencies: sys (stub), enum (stub), types (stub)
Analysis of genericpath (Library) queued. Dependencies: os, stat
Analysis of string (Stub) queued. Dependencies: 
Import:  linecache /Users/malmaud/anaconda3/lib/python3.7/linecache.py 
Import:  tracemalloc /Users/malmaud/anaconda3/lib/python3.7/tracemalloc.py 
Import:  traceback /Users/malmaud/anaconda3/lib/python3.7/traceback.py 
Analysis of threading (Stub) queued. Dependencies: types (stub), sys (stub)
Create built-in compiled (scraped) module:  _warnings /Users/malmaud/anaconda3/bin/python 
Import:  operator /Users/malmaud/anaconda3/lib/python3.7/operator.py 
Analysis of _warnings (Stub) queued. Dependencies: 
Import:  keyword /Users/malmaud/anaconda3/lib/python3.7/keyword.py 
Analysis of time (Stub) queued. Dependencies: sys (stub), types (stub)
Import:  heapq /Users/malmaud/anaconda3/lib/python3.7/heapq.py 
Create built-in compiled (scraped) module:  _weakref /Users/malmaud/anaconda3/bin/python 
Create built-in compiled (scraped) module:  itertools /Users/malmaud/anaconda3/bin/python 
Import:  reprlib /Users/malmaud/anaconda3/lib/python3.7/reprlib.py 
Create built-in compiled (scraped) module:  _collections /Users/malmaud/anaconda3/bin/python 
Import:  copy /Users/malmaud/anaconda3/lib/python3.7/copy.py 
Create built-in compiled (scraped) module:  _signal /Users/malmaud/anaconda3/bin/python 
Import:  functools /Users/malmaud/anaconda3/lib/python3.7/functools.py 
Import:  enum /Users/malmaud/anaconda3/lib/python3.7/enum.py 
Analysis of _posixsubprocess (Stub) queued. Dependencies: 
Analysis of operator (Stub) queued. Dependencies: sys (stub)
Analysis of _posixsubprocess (Compiled) queued. Dependencies: _posixsubprocess (stub)
Analysis of mmap (Stub) on depth 4 completed in 39.14 ms.
Analysis of select (Stub) queued. Dependencies: sys (stub)
Analysis of collections (Stub) queued. Dependencies: sys (stub), collections.abc (stub)
Analysis of enum (Library) queued. Dependencies: enum (stub), sys, types, _collections, collections, warnings
Import:  types /Users/malmaud/anaconda3/lib/python3.7/types.py 
Analysis of _collections_abc (Library) queued. Dependencies: abc, sys
Analysis of selectors (Library) queued. Dependencies: selectors (stub), abc, collections, collections.abc, math, select, sys
Import:  collections.abc /Users/malmaud/anaconda3/lib/python3.7/collections/abc.py 
Create compiled (scraped):  math /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of math (Compiled) queued. Dependencies: math (stub)
Analysis of threading (Library) queued. Dependencies: threading (stub), os, sys, _thread, time, traceback, _weakrefset, itertools, _collections, collections, warnings, _threading_local
Create built-in compiled (scraped) module:  _thread /Users/malmaud/anaconda3/bin/python 
Analysis of math (Stub) queued. Dependencies: sys (stub)
Import:  _weakrefset /Users/malmaud/anaconda3/lib/python3.7/_weakrefset.py 
Import:  _threading_local /Users/malmaud/anaconda3/lib/python3.7/_threading_local.py 
Analysis of collections.abc (Library) queued. Dependencies: collections.abc (stub), _collections_abc
Analysis of _threading_local (Library) queued. Dependencies: _threading_local (stub), weakref, contextlib, threading
Import:  weakref /Users/malmaud/anaconda3/lib/python3.7/weakref.py 
Analysis of selectors (Stub) queued. Dependencies: abc (stub), socket (stub)
Import:  contextlib /Users/malmaud/anaconda3/lib/python3.7/contextlib.py 
Analysis of contextlib (Library) queued. Dependencies: contextlib (stub), abc, sys, _collections_abc, collections, functools
Analysis of socket (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of contextlib (Stub) queued. Dependencies: types (stub), sys (stub)
Analysis of select (Compiled) queued. Dependencies: select (stub)
Analysis of _thread (Stub) queued. Dependencies: 
Analysis of operator (Library) queued. Dependencies: operator (stub), functools, _operator
Create built-in compiled (scraped) module:  _operator /Users/malmaud/anaconda3/bin/python 
Analysis of weakref (Library) queued. Dependencies: weakref (stub), _weakref, _weakrefset, _collections_abc, sys, itertools, copy, atexit, gc
Create built-in compiled (scraped) module:  atexit /Users/malmaud/anaconda3/bin/python 
Analysis of _operator (Stub) queued. Dependencies: sys (stub), operator (stub)
Create built-in compiled (scraped) module:  gc /Users/malmaud/anaconda3/bin/python 
Analysis of _weakrefset (Stub) queued. Dependencies: 
Analysis of _weakrefset (Library) queued. Dependencies: _weakrefset (stub), _weakref
Analysis of gc (Stub) queued. Dependencies: 
Analysis of _threading_local (Stub) queued. Dependencies: weakref (stub)
Analysis of weakref (Stub) queued. Dependencies: sys (stub), types (stub), _weakref (stub), _weakrefset (stub)
Analysis of atexit (Stub) queued. Dependencies: 
Analysis of heapq (Stub) queued. Dependencies: sys (stub)
Analysis of keyword (Stub) queued. Dependencies: 
Analysis of keyword (Library) queued. Dependencies: keyword (stub), sys, re
Analysis of _weakref (Stub) queued. Dependencies: sys (stub)
Analysis of heapq (Library) queued. Dependencies: heapq (stub), _heapq, doctest
Create compiled (scraped):  _heapq /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of itertools (Stub) queued. Dependencies: 
Import:  doctest /Users/malmaud/anaconda3/lib/python3.7/doctest.py 
Analysis of _heapq (Compiled) queued. Dependencies: _heapq (stub)
Analysis of _heapq (Stub) queued. Dependencies: 
Analysis of doctest (Stub) queued. Dependencies: sys (stub), types (stub), unittest (stub)
Analysis of unittest (Stub) queued. Dependencies: logging (stub), sys (stub), types (stub)
Analysis of logging (Stub) queued. Dependencies: string (stub), time (stub), types (stub), sys (stub), threading (stub)
Analysis of reprlib (Stub) queued. Dependencies: array (stub)
Analysis of array (Stub) queued. Dependencies: sys (stub)
Analysis of doctest (Library) queued. Dependencies: doctest (stub), __future__, difflib, inspect, linecache, os, pdb, re, sys, traceback, unittest, io, collections, argparse
Import:  __future__ /Users/malmaud/anaconda3/lib/python3.7/__future__.py 
Import:  difflib /Users/malmaud/anaconda3/lib/python3.7/difflib.py 
Import:  inspect /Users/malmaud/anaconda3/lib/python3.7/inspect.py 
Import:  pdb /Users/malmaud/anaconda3/lib/python3.7/pdb.py 
Import:  unittest /Users/malmaud/anaconda3/lib/python3.7/unittest/__init__.py 
Import:  argparse /Users/malmaud/anaconda3/lib/python3.7/argparse.py 
Analysis of reprlib (Library) queued. Dependencies: reprlib (stub), itertools, _thread
Analysis of __future__ (Stub) queued. Dependencies: sys (stub)
Analysis of __future__ (Library) queued. Dependencies: __future__ (stub)
Analysis of difflib (Stub) queued. Dependencies: sys (stub)
Analysis of re (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of argparse (Library) queued. Dependencies: argparse (stub), os, re, sys, gettext, copy, textwrap, warnings
Import:  gettext /Users/malmaud/anaconda3/lib/python3.7/gettext.py 
Import:  textwrap /Users/malmaud/anaconda3/lib/python3.7/textwrap.py 
Analysis of difflib (Library) queued. Dependencies: difflib (stub), heapq, collections, re, doctest
Analysis of textwrap (Library) queued. Dependencies: textwrap (stub), re
Analysis of textwrap (Stub) queued. Dependencies: 
Analysis of gettext (Library) queued. Dependencies: gettext (stub), locale, os, re, sys, warnings, struct, errno, copy
Import:  locale /Users/malmaud/anaconda3/lib/python3.7/locale.py 
Import:  struct /Users/malmaud/anaconda3/lib/python3.7/struct.py 
Analysis of struct (Library) queued. Dependencies: struct (stub), _struct
Create compiled (scraped):  _struct /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _struct (Compiled) queued. Dependencies: struct
Analysis of struct (Stub) queued. Dependencies: sys (stub), array (stub)
Analysis of locale (Library) queued. Dependencies: locale (stub), sys, encodings, encodings.aliases, re, _collections_abc, functools, _locale, warnings, os, _bootlocale
Import:  encodings /Users/malmaud/anaconda3/lib/python3.7/encodings/__init__.py 
Import:  encodings.aliases /Users/malmaud/anaconda3/lib/python3.7/encodings/aliases.py 
Create built-in compiled (scraped) module:  _locale /Users/malmaud/anaconda3/bin/python 
Import:  _bootlocale /Users/malmaud/anaconda3/lib/python3.7/_bootlocale.py 
Analysis of _bootlocale (Library) queued. Dependencies: sys, _locale, locale
Analysis of encodings.aliases (Library) queued. Dependencies: 
Analysis of encodings (Library) queued. Dependencies: encodings (stub), codecs, sys, encodings.aliases, encodings.mbcs
Import:  codecs /Users/malmaud/anaconda3/lib/python3.7/codecs.py 
Import:  encodings.mbcs /Users/malmaud/anaconda3/lib/python3.7/encodings/mbcs.py 
Analysis of encodings.mbcs (Library) queued. Dependencies: codecs
Analysis of codecs (Library) queued. Dependencies: codecs (stub), sys, _codecs, encodings
Create built-in compiled (scraped) module:  _codecs /Users/malmaud/anaconda3/bin/python 
Analysis of _codecs (Stub) queued. Dependencies: sys (stub), codecs (stub)
Analysis of encodings (Stub) queued. Dependencies: codecs (stub)
Analysis of locale (Stub) queued. Dependencies: decimal (stub), sys (stub)
Analysis of decimal (Stub) queued. Dependencies: 
Analysis of gettext (Stub) queued. Dependencies: 
Analysis of argparse (Stub) queued. Dependencies: sys (stub)
Analysis of unittest (Library) queued. Dependencies: unittest (stub), unittest.result, unittest.case, unittest.suite, unittest.loader, unittest.main, unittest.runner, unittest.signals, os
Import:  unittest.result /Users/malmaud/anaconda3/lib/python3.7/unittest/result.py 
Import:  unittest.case /Users/malmaud/anaconda3/lib/python3.7/unittest/case.py 
Import:  unittest.suite /Users/malmaud/anaconda3/lib/python3.7/unittest/suite.py 
Import:  unittest.loader /Users/malmaud/anaconda3/lib/python3.7/unittest/loader.py 
Import:  unittest.main /Users/malmaud/anaconda3/lib/python3.7/unittest/main.py 
Import:  unittest.runner /Users/malmaud/anaconda3/lib/python3.7/unittest/runner.py 
Import:  unittest.signals /Users/malmaud/anaconda3/lib/python3.7/unittest/signals.py 
Analysis of unittest.signals (Library) queued. Dependencies: signal, weakref, functools
Analysis of unittest.runner (Library) queued. Dependencies: sys, time, warnings, unittest, unittest.result, unittest.signals
Analysis of unittest.main (Library) queued. Dependencies: sys, argparse, os, unittest, unittest.loader, unittest.runner, unittest.signals
Analysis of unittest.loader (Library) queued. Dependencies: os, re, sys, traceback, types, functools, warnings, fnmatch, unittest, unittest.case, unittest.suite, unittest.util
Import:  fnmatch /Users/malmaud/anaconda3/lib/python3.7/fnmatch.py 
Import:  unittest.util /Users/malmaud/anaconda3/lib/python3.7/unittest/util.py 
Analysis of unittest.util (Library) queued. Dependencies: collections, os
Analysis of fnmatch (Library) queued. Dependencies: fnmatch (stub), os, posixpath, re, functools
Analysis of fnmatch (Stub) queued. Dependencies: 
Analysis of unittest.suite (Library) queued. Dependencies: sys, unittest, unittest.case, unittest.util
Analysis of unittest.case (Library) queued. Dependencies: sys, functools, difflib, logging, pprint, re, warnings, collections, contextlib, traceback, unittest, unittest.result, unittest.util
Import:  logging /Users/malmaud/anaconda3/lib/python3.7/logging/__init__.py 
Import:  pprint /Users/malmaud/anaconda3/lib/python3.7/pprint.py 
Analysis of pprint (Library) queued. Dependencies: pprint (stub), collections, re, sys, types, io, time
Analysis of pprint (Stub) queued. Dependencies: sys (stub)
Analysis of logging (Library) queued. Dependencies: logging (stub), sys, os, time, io, traceback, warnings, weakref, collections, collections.abc, string, threading, pickle, atexit
Import:  pickle /Users/malmaud/anaconda3/lib/python3.7/pickle.py 
Analysis of pickle (Library) queued. Dependencies: pickle (stub), types, copyreg, itertools, functools, sys, struct, re, io, codecs, _compat_pickle, _pickle, doctest, argparse, pprint
Import:  copyreg /Users/malmaud/anaconda3/lib/python3.7/copyreg.py 
Import:  _compat_pickle /Users/malmaud/anaconda3/lib/python3.7/_compat_pickle.py 
Create compiled (scraped):  _pickle /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _pickle (Compiled) queued. Dependencies: 
Analysis of _compat_pickle (Library) queued. Dependencies: 
Analysis of copyreg (Library) queued. Dependencies: 
Analysis of pickle (Stub) queued. Dependencies: sys (stub)
Analysis of unittest.result (Library) queued. Dependencies: io, sys, traceback, unittest, unittest.util, functools
Analysis of pdb (Library) queued. Dependencies: pdb (stub), os, re, sys, cmd, bdb, dis, code, glob, pprint, signal, inspect, traceback, linecache, readline, shlex, runpy, pydoc, getopt
Import:  cmd /Users/malmaud/anaconda3/lib/python3.7/cmd.py 
Import:  bdb /Users/malmaud/anaconda3/lib/python3.7/bdb.py 
Import:  dis /Users/malmaud/anaconda3/lib/python3.7/dis.py 
Import:  code /Users/malmaud/anaconda3/lib/python3.7/code.py 
Import:  glob /Users/malmaud/anaconda3/lib/python3.7/glob.py 
Create compiled (scraped):  readline /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Import:  shlex /Users/malmaud/anaconda3/lib/python3.7/shlex.py 
Import:  runpy /Users/malmaud/anaconda3/lib/python3.7/runpy.py 
Import:  pydoc /Users/malmaud/anaconda3/lib/python3.7/pydoc.py 
Import:  getopt /Users/malmaud/anaconda3/lib/python3.7/getopt.py 
Analysis of copy (Stub) queued. Dependencies: 
Analysis of types (Library) queued. Dependencies: types (stub), sys, functools, _collections_abc
Analysis of inspect (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of collections.abc (Stub) queued. Dependencies: sys (stub), collections (stub)
Analysis of pdb (Stub) queued. Dependencies: sys (stub)
Analysis of cmd (Stub) queued. Dependencies: 
Analysis of enum (Stub) queued. Dependencies: sys (stub), abc (stub)
Completions in file:///Users/malmaud/q/hi.py at (3, 3)
Analysis of cmd (Library) queued. Dependencies: cmd (stub), string, sys, readline
Analysis of hi (User) queued. Dependencies: os
Analysis of dis (Stub) queued. Dependencies: sys (stub), types (stub), opcode (stub)
Analysis of opcode (Stub) queued. Dependencies: sys (stub)
Out of order analysis of hi(User) completed in 24.78 ms.
Analysis of io (Stub) on depth 3 completed in 32.22 ms.
Analysis of copy (Library) queued. Dependencies: copy (stub), types, weakref, copyreg
Analysis of code (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of re (Library) queued. Dependencies: re (stub), enum, sre_compile, sre_parse, functools, _locale, copyreg, sre_constants
Analysis of functools (Library) queued. Dependencies: functools (stub), _functools, abc, collections, reprlib, _thread, types, weakref
Analysis of code (Library) queued. Dependencies: code (stub), sys, traceback, codeop, readline, argparse
Analysis of functools (Stub) queued. Dependencies: sys (stub)
Analysis of inspect (Library) queued. Dependencies: inspect (stub), abc, dis, collections, collections.abc, enum, importlib, importlib.machinery, itertools, linecache, os, re, sys, tokenize, token, types, warnings, functools, operator, ast, argparse
Analysis of glob (Stub) queued. Dependencies: sys (stub)
Analysis of linecache (Stub) queued. Dependencies: sys (stub)
Import:  sre_compile /Users/malmaud/anaconda3/lib/python3.7/sre_compile.py 
Analysis of bdb (Library) queued. Dependencies: fnmatch, sys, os, inspect, linecache, reprlib
Import:  sre_parse /Users/malmaud/anaconda3/lib/python3.7/sre_parse.py 
Analysis of sre_compile (Stub) queued. Dependencies: sys (stub), sre_parse (stub), sre_constants (stub)
Import:  sre_constants /Users/malmaud/anaconda3/lib/python3.7/sre_constants.py 
Analysis of linecache (Library) queued. Dependencies: linecache (stub), functools, sys, os, tokenize
Analysis of tracemalloc (Stub) queued. Dependencies: sys (stub)
Create built-in compiled (scraped) module:  _functools /Users/malmaud/anaconda3/bin/python 
Analysis of sre_constants (Library) queued. Dependencies: sre_constants (stub), _sre
Import:  codeop /Users/malmaud/anaconda3/lib/python3.7/codeop.py 
Analysis of sre_constants (Stub) queued. Dependencies: 
Analysis of codeop (Library) queued. Dependencies: codeop (stub), __future__
Import:  importlib /Users/malmaud/anaconda3/lib/python3.7/importlib/__init__.py 
Import:  importlib.machinery /Users/malmaud/anaconda3/lib/python3.7/importlib/machinery.py 
Import:  tokenize /Users/malmaud/anaconda3/lib/python3.7/tokenize.py 
Analysis of codeop (Stub) queued. Dependencies: types (stub)
Import:  token /Users/malmaud/anaconda3/lib/python3.7/token.py 
Analysis of tracemalloc (Library) queued. Dependencies: tracemalloc (stub), collections.abc, functools, fnmatch, linecache, os, pickle, _tracemalloc
Import:  ast /Users/malmaud/anaconda3/lib/python3.7/ast.py 
Create built-in compiled (scraped) module:  _sre /Users/malmaud/anaconda3/bin/python 
Analysis of sre_parse (Stub) queued. Dependencies: sre_constants (stub)
Analysis of readline (Stub) queued. Dependencies: sys (stub)
Create built-in compiled (scraped) module:  _tracemalloc /Users/malmaud/anaconda3/bin/python 
Analysis of dis (Library) queued. Dependencies: dis (stub), sys, types, collections, io, opcode, argparse
Analysis of _tracemalloc (Stub) queued. Dependencies: 
Analysis of ast (Library) queued. Dependencies: ast (stub), _ast, inspect, collections
Analysis of importlib (Stub) queued. Dependencies: importlib.util (stub), importlib.abc (stub), sys (stub), types (stub)
Analysis of ast (Stub) queued. Dependencies: _ast (stub)
Analysis of _py_abc (Library) queued. Dependencies: _weakrefset
Import:  opcode /Users/malmaud/anaconda3/lib/python3.7/opcode.py 
Analysis of token (Library) queued. Dependencies: token (stub), re, sys
Create built-in compiled (scraped) module:  _ast /Users/malmaud/anaconda3/bin/python 
Analysis of token (Stub) queued. Dependencies: sys (stub)
Analysis of traceback (Stub) queued. Dependencies: types (stub), sys (stub)
Analysis of importlib.util (Stub) queued. Dependencies: importlib (stub), importlib.abc (stub), importlib.machinery (stub), sys (stub), types (stub)
Analysis of importlib.machinery (Stub) queued. Dependencies: importlib (stub), importlib.abc (stub), sys (stub), types (stub), _importlib_modulespec (stub)
Analysis of readline (Compiled) queued. Dependencies: readline (stub)
Analysis of tokenize (Library) queued. Dependencies: tokenize (stub), codecs, collections, io, itertools, re, sys, token, argparse
Analysis of _ast (Stub) queued. Dependencies: sys (stub)
Analysis of tokenize (Stub) queued. Dependencies: sys (stub), token (stub), os (stub)
Analysis of shlex (Stub) queued. Dependencies: sys (stub)
Analysis of importlib.machinery (Library) queued. Dependencies: importlib.machinery (stub), _imp, importlib._bootstrap, importlib._bootstrap_external
Analysis of glob (Library) queued. Dependencies: glob (stub), os, re, fnmatch
Analysis of runpy (Stub) queued. Dependencies: 
Analysis of sre_parse (Library) queued. Dependencies: sre_parse (stub), sre_constants, warnings
Create built-in compiled (scraped) module:  _imp /Users/malmaud/anaconda3/bin/python 
Analysis of runpy (Library) queued. Dependencies: runpy (stub), sys, importlib, importlib.machinery, importlib.util, types, pkgutil, warnings
Import:  importlib._bootstrap /Users/malmaud/anaconda3/lib/python3.7/importlib/_bootstrap.py 
Import:  importlib._bootstrap_external /Users/malmaud/anaconda3/lib/python3.7/importlib/_bootstrap_external.py 
Analysis of traceback (Library) queued. Dependencies: traceback (stub), collections, itertools, linecache, sys
Import:  importlib.util /Users/malmaud/anaconda3/lib/python3.7/importlib/util.py 
Analysis of opcode (Library) queued. Dependencies: opcode (stub), _opcode
Import:  pkgutil /Users/malmaud/anaconda3/lib/python3.7/pkgutil.py 
Analysis of _imp (Stub) queued. Dependencies: sys (stub), types (stub), importlib.machinery (stub)
Create compiled (scraped):  _opcode /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_opcode.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _opcode (Compiled) queued. Dependencies: 
Analysis of getopt (Stub) queued. Dependencies: 
Analysis of pkgutil (Library) queued. Dependencies: pkgutil (stub), collections, functools, importlib, importlib.util, importlib.machinery, os, sys, types, warnings, marshal, inspect, zipimport
Create built-in compiled (scraped) module:  marshal /Users/malmaud/anaconda3/bin/python 
Analysis of pkgutil (Stub) queued. Dependencies: sys (stub), importlib.abc (stub)
Analysis of marshal (Stub) queued. Dependencies: 
Analysis of importlib (Library) queued. Dependencies: importlib (stub), _imp, sys, importlib._bootstrap, importlib._bootstrap_external, types, warnings
Create built-in compiled (scraped) module:  zipimport /Users/malmaud/anaconda3/bin/python 
Analysis of zipimport (Stub) queued. Dependencies: types (stub)
Analysis of importlib._bootstrap_external (Library) queued. Dependencies: tokenize
Analysis of sre_compile (Library) queued. Dependencies: sre_compile (stub), _sre, sre_parse, sre_constants, sys
Analysis of pydoc (Library) queued. Dependencies: importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, importlib.util, inspect, io, os, pkgutil, platform, re, sys, time, tokenize, urllib, urllib.parse, warnings, collections, reprlib, traceback, tempfile, subprocess, tty, pydoc_data, pydoc_data.topics, textwrap, http, http.server, email, email.message, select, threading, webbrowser, getopt
Analysis of importlib.util (Library) queued. Dependencies: importlib.util (stub), importlib, importlib.abc, importlib._bootstrap, importlib._bootstrap_external, contextlib, _imp, functools, sys, types, warnings
Analysis of shlex (Library) queued. Dependencies: shlex (stub), os, re, sys, collections, io
Analysis of importlib._bootstrap (Library) queued. Dependencies: 
Import:  platform /Users/malmaud/anaconda3/lib/python3.7/platform.py 
Import:  urllib /Users/malmaud/anaconda3/lib/python3.7/urllib/__init__.py 
Analysis of urllib (Stub) queued. Dependencies: 
Analysis of platform (Stub) queued. Dependencies: os (stub)
Analysis of platform (Library) queued. Dependencies: platform (stub), collections, sys, os, re, subprocess, warnings, plistlib, socket, struct
Import:  urllib.parse /Users/malmaud/anaconda3/lib/python3.7/urllib/parse.py 
Import:  tempfile /Users/malmaud/anaconda3/lib/python3.7/tempfile.py 
Import:  tty /Users/malmaud/anaconda3/lib/python3.7/tty.py 
Import:  pydoc_data /Users/malmaud/anaconda3/lib/python3.7/pydoc_data/__init__.py 
Import:  pydoc_data.topics /Users/malmaud/anaconda3/lib/python3.7/pydoc_data/topics.py 
Import:  http /Users/malmaud/anaconda3/lib/python3.7/http/__init__.py 
Import:  http.server /Users/malmaud/anaconda3/lib/python3.7/http/server.py 
Import:  email /Users/malmaud/anaconda3/lib/python3.7/email/__init__.py 
Import:  email.message /Users/malmaud/anaconda3/lib/python3.7/email/message.py 
Import:  webbrowser /Users/malmaud/anaconda3/lib/python3.7/webbrowser.py 
Import:  importlib.abc /Users/malmaud/anaconda3/lib/python3.7/importlib/abc.py 
Import:  plistlib /Users/malmaud/anaconda3/lib/python3.7/plistlib.py 
Import:  socket /Users/malmaud/anaconda3/lib/python3.7/socket.py 
Analysis of os (Stub) on depth 2 completed in 153.3 ms.
Analysis of getopt (Library) queued. Dependencies: getopt (stub), os, gettext, sys
Analysis of urllib (Library) queued. Dependencies: urllib (stub)
Analysis of importlib.abc (Library) queued. Dependencies: importlib.abc (stub), importlib, importlib._bootstrap, importlib._bootstrap_external, importlib.machinery, abc, warnings
Analysis of plistlib (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of plistlib (Library) queued. Dependencies: plistlib (stub), binascii, codecs, contextlib, datetime, enum, io, itertools, os, re, struct, warnings, xml.parsers.expat
Create compiled (scraped):  binascii /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Import:  datetime /Users/malmaud/anaconda3/lib/python3.7/datetime.py 
Import:  xml.parsers.expat /Users/malmaud/anaconda3/lib/python3.7/xml/parsers/expat.py 
Analysis of xml.parsers.expat (Library) queued. Dependencies: xml.parsers.expat (stub), sys, pyexpat
Create compiled (scraped):  pyexpat /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/pyexpat.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of pyexpat (Compiled) queued. Dependencies: pyexpat (stub)
Analysis of pyexpat (Stub) queued. Dependencies: pyexpat.errors (stub), pyexpat.model (stub)
Analysis of pyexpat.model (Stub) queued. Dependencies: 
Analysis of pyexpat.errors (Stub) queued. Dependencies: sys (stub)
Analysis of xml.parsers.expat (Stub) queued. Dependencies: pyexpat (stub), pyexpat.errors (stub), pyexpat.model (stub)
Analysis of binascii (Stub) queued. Dependencies: sys (stub)
Analysis of binascii (Compiled) queued. Dependencies: binascii (stub)
Analysis of datetime (Stub) queued. Dependencies: sys (stub), time (stub)
Analysis of urllib.parse (Stub) queued. Dependencies: sys (stub)
Analysis of socket (Library) queued. Dependencies: socket (stub), _socket, os, sys, io, selectors, enum, errno
Create compiled (scraped):  _socket /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _socket (Compiled) queued. Dependencies: 
Analysis of datetime (Library) queued. Dependencies: datetime (stub), time, math, sys, _strptime, _datetime
Import:  _strptime /Users/malmaud/anaconda3/lib/python3.7/_strptime.py 
Create compiled (scraped):  _datetime /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_datetime.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _datetime (Compiled) queued. Dependencies: datetime
Analysis of importlib.abc (Stub) on depth 4 completed in 2.39 ms.
Analysis of sys (Stub) on depth 3 completed in 8.66 ms.
Analysis of _strptime (Library) queued. Dependencies: time, locale, calendar, re, datetime, _thread
Import:  calendar /Users/malmaud/anaconda3/lib/python3.7/calendar.py 
Analysis of _importlib_modulespec (Stub) on depth 5 completed in 0.89 ms.
Analysis of calendar (Library) queued. Dependencies: calendar (stub), sys, datetime, locale, itertools, argparse
Analysis of calendar (Stub) queued. Dependencies: datetime (stub), sys (stub), time (stub)
Analysis of types (Stub) on depth 4 completed in 11.32 ms.
Analysis of urllib.parse (Library) queued. Dependencies: urllib.parse (stub), re, sys, collections, unicodedata
Create compiled (scraped):  unicodedata /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/unicodedata.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of unicodedata (Compiled) queued. Dependencies: unicodedata (stub)
Analysis of unicodedata (Stub) queued. Dependencies: 
Analysis of codecs (Stub) on depth 4 completed in 7.78 ms.
Analysis of tempfile (Stub) queued. Dependencies: sys (stub), types (stub)
Analysis of os.path (Stub) on depth 3 completed in 1.89 ms.
Analysis of tempfile (Library) queued. Dependencies: tempfile (stub), functools, warnings, io, os, shutil, errno, random, weakref, _thread
Import:  shutil /Users/malmaud/anaconda3/lib/python3.7/shutil.py 
Import:  random /Users/malmaud/anaconda3/lib/python3.7/random.py 
Analysis of random (Library) queued. Dependencies: random (stub), warnings, types, math, os, _collections_abc, hashlib, itertools, bisect, _random, time
Import:  hashlib /Users/malmaud/anaconda3/lib/python3.7/hashlib.py 
Import:  bisect /Users/malmaud/anaconda3/lib/python3.7/bisect.py 
Create compiled (scraped):  _random /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_random.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _random (Compiled) queued. Dependencies: _random (stub)
Analysis of _random (Stub) queued. Dependencies: sys (stub)
Analysis of bisect (Library) queued. Dependencies: bisect (stub), _bisect
Create compiled (scraped):  _bisect /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_bisect.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _bisect (Compiled) queued. Dependencies: _bisect (stub)
Analysis of _bisect (Stub) queued. Dependencies: 
Analysis of bisect (Stub) queued. Dependencies: 
Analysis of hashlib (Library) queued. Dependencies: hashlib (stub), _sha1, _md5, _sha256, _sha512, _blake2, _sha3, _hashlib, logging
Create compiled (scraped):  _sha1 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_sha1.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  _md5 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_md5.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha256 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_sha256.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha512 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_sha512.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  _blake2 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_blake2.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  _sha3 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_sha3.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Create compiled (scraped):  _hashlib /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_hashlib.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _hashlib (Compiled) queued. Dependencies: 
Analysis of _sha3 (Compiled) queued. Dependencies: 
Analysis of _blake2 (Compiled) queued. Dependencies: 
Analysis of _sha512 (Compiled) queued. Dependencies: 
Analysis of _sha256 (Compiled) queued. Dependencies: 
Analysis of _md5 (Compiled) queued. Dependencies: 
Analysis of _sha1 (Compiled) queued. Dependencies: 
Analysis of hashlib (Stub) queued. Dependencies: sys (stub)
Analysis of random (Stub) queued. Dependencies: _random (stub), sys (stub)
Analysis of os (Library) queued. Dependencies: os (stub), abc, sys, stat, posix, posixpath, ntpath, warnings, _collections_abc, subprocess, io
Analysis of shutil (Library) queued. Dependencies: shutil (stub), os, sys, stat, fnmatch, collections, errno, zlib, bz2, lzma, pwd, grp, tarfile, zipfile
Create compiled (scraped):  zlib /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/zlib.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Import:  bz2 /Users/malmaud/anaconda3/lib/python3.7/bz2.py 
Import:  lzma /Users/malmaud/anaconda3/lib/python3.7/lzma.py 
Create compiled (scraped):  grp /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/grp.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Import:  tarfile /Users/malmaud/anaconda3/lib/python3.7/tarfile.py 
Import:  zipfile /Users/malmaud/anaconda3/lib/python3.7/zipfile.py 
Analysis of os (Library) on depth 1 completed in 62.18 ms.
Analysis version 34 has been completed in 726.23 ms with 19 entries analyzed and 10 entries skipped.
Analysis version 422 of 358 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of zipfile (Library) queued. Dependencies: zipfile (stub), io, os, importlib, importlib.util, sys, time, stat, shutil, struct, binascii, threading, zlib, bz2, lzma, warnings, py_compile, argparse
Analysis of string (Stub) on depth 4 completed in 0.74 ms.
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of _stat(CompiledBuiltin) canceled (no AST yet).
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of _posixsubprocess (Stub) on depth 4 completed in 0.17 ms.
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _operator(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Import:  py_compile /Users/malmaud/anaconda3/lib/python3.7/py_compile.py 
Analysis of py_compile (Library) queued. Dependencies: py_compile (stub), enum, importlib, importlib._bootstrap_external, importlib.machinery, importlib.util, os, sys, traceback
Analysis of py_compile (Stub) queued. Dependencies: sys (stub)
Analysis of _weakrefset (Stub) on depth 5 completed in 2.91 ms.
Analysis of zipfile (Stub) queued. Dependencies: types (stub), os (stub), sys (stub)
Analysis of keyword (Stub) on depth 6 completed in 0.12 ms.
Analysis of _heapq (Stub) on depth 7 completed in 0.21 ms.
Analysis of textwrap (Stub) on depth 7 completed in 0.65 ms.
Analysis of gettext (Stub) on depth 7 completed in 0.81 ms.
Analysis of _struct (Compiled) on depth 6 completed in 0.33 ms.
Analysis of encodings.aliases (Library) on depth 7 completed in 2.04 ms.
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of encodings.mbcs (Library) on depth 7 completed in 0.47 ms.
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of tarfile (Library) queued. Dependencies: tarfile (stub), sys, os, io, shutil, stat, time, struct, copy, re, pwd, grp, warnings, zlib, bz2, lzma, gzip, argparse
Import:  gzip /Users/malmaud/anaconda3/lib/python3.7/gzip.py 
Analysis of gzip (Library) queued. Dependencies: gzip (stub), struct, sys, time, os, zlib, io, _compression, warnings, errno
Analysis of decimal (Stub) on depth 9 completed in 16.89 ms.
Analysis of fnmatch (Stub) on depth 5 completed in 0.15 ms.
Import:  _compression /Users/malmaud/anaconda3/lib/python3.7/_compression.py 
Analysis of _compression (Library) queued. Dependencies: _compression (stub), io
Analysis of copyreg (Library) on depth 4 completed in 1.31 ms.
Analysis of _compression (Stub) queued. Dependencies: io (stub)
Analysis of _compat_pickle (Library) on depth 5 completed in 0.91 ms.
Analysis of gzip (Stub) queued. Dependencies: os.path (stub), _compression (stub), zlib (stub)
Analysis of _pickle (Compiled) on depth 5 completed in 3.98 ms.
Analysis of copy (Stub) on depth 6 completed in 0.19 ms.
Analysis of tarfile (Stub) queued. Dependencies: os (stub), sys (stub), types (stub)
Analysis of cmd (Stub) on depth 8 completed in 1.06 ms.
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of grp (Compiled) queued. Dependencies: grp (stub)
Analysis of grp (Stub) queued. Dependencies: 
Analysis of sre_constants (Stub) on depth 5 completed in 1.7 ms.
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of lzma (Library) queued. Dependencies: lzma (stub), io, os, _lzma, _compression
Create compiled (scraped):  _lzma /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_lzma.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _lzma (Compiled) queued. Dependencies: 
Analysis of lzma (Stub) queued. Dependencies: io (stub), sys (stub), os (stub)
Analysis of bz2 (Library) queued. Dependencies: bz2 (stub), io, os, warnings, _compression, threading, _bz2
Create compiled (scraped):  _bz2 /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_bz2.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of _bz2 (Compiled) queued. Dependencies: 
Analysis of bz2 (Stub) queued. Dependencies: io (stub), sys (stub), os (stub)
Analysis of zlib (Compiled) queued. Dependencies: zlib (stub)
Analysis of zlib (Stub) queued. Dependencies: sys (stub)
Analysis of shutil (Stub) queued. Dependencies: os (stub), sys (stub)
Analysis of tty (Stub) queued. Dependencies: 
Analysis of importlib._bootstrap (Library) on depth 8 completed in 20.1 ms.
Analysis of runpy (Stub) on depth 8 completed in 0.62 ms.
Analysis of _opcode (Compiled) on depth 9 completed in 0.17 ms.
Analysis of getopt (Stub) on depth 8 completed in 0.41 ms.
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of tty(Library) canceled (no AST yet).
Analysis of pydoc_data(Library) canceled (no AST yet).
Analysis of pydoc_data.topics(Library) canceled (no AST yet).
Analysis of http(Library) canceled (no AST yet).
Analysis of http.server(Library) canceled (no AST yet).
Analysis of email(Library) canceled (no AST yet).
Analysis of email.message(Library) canceled (no AST yet).
Analysis of webbrowser(Library) canceled (no AST yet).
Analysis of urllib (Stub) on depth 9 completed in 0.01 ms.
Analysis of pyexpat.model (Stub) on depth 12 completed in 0.06 ms.
Analysis of tty (Library) queued. Dependencies: tty (stub), termios
Analysis of _socket (Compiled) on depth 10 completed in 15.85 ms.
Analysis of _datetime (Compiled) on depth 11 completed in 0.19 ms.
Analysis of unicodedata (Stub) on depth 10 completed in 1.05 ms.
Create compiled (scraped):  termios /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/termios.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of bisect (Stub) on depth 11 completed in 0.33 ms.
Analysis of termios (Compiled) queued. Dependencies: termios (stub)
Analysis of termios (Stub) queued. Dependencies: 
Analysis of _bisect (Stub) on depth 12 completed in 4.61 ms.
Analysis of pydoc_data (Library) queued. Dependencies: 
Analysis of _sha1 (Compiled) on depth 11 completed in 0.19 ms.
Analysis of _md5 (Compiled) on depth 11 completed in 0.19 ms.
Analysis of _sha256 (Compiled) on depth 11 completed in 0.2 ms.
Analysis of _sha512 (Compiled) on depth 11 completed in 0.24 ms.
Analysis of posix (Stub) on depth 3 completed in 0.35 ms.
Analysis of _blake2 (Compiled) on depth 11 completed in 3.28 ms.
Analysis of _hashlib (Compiled) on depth 11 completed in 3.24 ms.
Analysis of _posixsubprocess (Compiled) on depth 3 completed in 0.16 ms.
Analysis of _weakrefset (Library) on depth 4 completed in 6 ms.
Analysis of _heapq (Compiled) on depth 6 completed in 0.34 ms.
Analysis of sre_parse (Stub) on depth 5 completed in 1.99 ms.
Analysis of sre_constants (Library) queued. Dependencies: sre_constants (stub), _sre, io
Analysis of sre_constants (Library) on depth 4 completed in 7.51 ms.
Analysis of urllib (Library) on depth 8 completed in 0.09 ms.
Analysis of unicodedata (Compiled) on depth 9 completed in 0.79 ms.
Analysis of _bisect (Compiled) on depth 11 completed in 0.12 ms.
Analysis of pydoc_data.topics (Library) queued. Dependencies: 
Analysis of http (Stub) queued. Dependencies: sys (stub), enum (stub)
Analysis of mmap (Stub) on depth 4 completed in 0.87 ms.
Analysis of _py_abc (Library) on depth 3 completed in 6.3 ms.
Analysis of abc (Stub) on depth 3 completed in 0.3 ms.
Analysis of ntpath (Stub) on depth 3 completed in 0.6 ms.
Analysis of posixpath (Stub) on depth 3 completed in 0.6 ms.
Analysis of bisect (Library) on depth 10 completed in 1.53 ms.
Analysis of subprocess (Stub) on depth 3 completed in 1.72 ms.
Analysis of _sha3 (Compiled) on depth 11 completed in 1.97 ms.
Analysis of http (Library) queued. Dependencies: http (stub), enum
Analysis of http.server (Stub) queued. Dependencies: sys (stub), socketserver (stub), email (stub), email.message (stub)
Analysis of socketserver (Stub) queued. Dependencies: socket (stub), sys (stub), types (stub)
Analysis of abc (Library) on depth 2 completed in 3.02 ms.
Analysis of stat (Stub) on depth 3 completed in 0.54 ms.
Analysis of http.server (Library) queued. Dependencies: http.server (stub), copy, datetime, email, email.utils, html, http, http.client, io, mimetypes, os, posixpath, select, shutil, socket, socketserver, sys, time, urllib, urllib.parse, functools, pwd, base64, binascii, subprocess, argparse
Import:  email.utils /Users/malmaud/anaconda3/lib/python3.7/email/utils.py 
Import:  html /Users/malmaud/anaconda3/lib/python3.7/html/__init__.py 
Analysis of collections (Stub) on depth 5 completed in 28.1 ms.
Import:  http.client /Users/malmaud/anaconda3/lib/python3.7/http/client.py 
Import:  mimetypes /Users/malmaud/anaconda3/lib/python3.7/mimetypes.py 
Import:  socketserver /Users/malmaud/anaconda3/lib/python3.7/socketserver.py 
Import:  base64 /Users/malmaud/anaconda3/lib/python3.7/base64.py 
Analysis of base64 (Library) queued. Dependencies: base64 (stub), re, struct, binascii, warnings, sys, getopt
Analysis of operator (Stub) on depth 6 completed in 5.51 ms.
Analysis of base64 (Stub) queued. Dependencies: sys (stub)
Analysis of select (Stub) on depth 4 completed in 1.14 ms.
Analysis of socketserver (Library) queued. Dependencies: socketserver (stub), socket, selectors, os, sys, threading, io, time, traceback
Analysis of math (Stub) on depth 5 completed in 3.28 ms.
Analysis of mimetypes (Library) queued. Dependencies: mimetypes (stub), os, sys, posixpath, urllib, urllib.parse, getopt
Analysis of mimetypes (Stub) queued. Dependencies: sys (stub)
Analysis of contextlib (Stub) on depth 6 completed in 3.81 ms.
Analysis of _weakref (Stub) on depth 7 completed in 0.65 ms.
Analysis of heapq (Stub) on depth 6 completed in 0.35 ms.
Analysis of array (Stub) on depth 7 completed in 1.62 ms.
Analysis of __future__ (Stub) on depth 7 completed in 0.22 ms.
Analysis of difflib (Stub) on depth 7 completed in 1.41 ms.
Analysis of http.client (Library) queued. Dependencies: http.client (stub), email, email.parser, email.message, http, io, re, socket, collections, collections.abc, urllib.parse, ssl, warnings
Import:  email.parser /Users/malmaud/anaconda3/lib/python3.7/email/parser.py 
Import:  ssl /Users/malmaud/anaconda3/lib/python3.7/ssl.py 
Analysis of enum (Stub) on depth 5 completed in 2.53 ms.
Analysis of email.utils (Stub) queued. Dependencies: email.charset (stub), datetime (stub)
Analysis of threading (Stub) on depth 4 completed in 8.31 ms.
Analysis of email (Stub) queued. Dependencies: sys (stub), email.message (stub), email.policy (stub)
Analysis of email.policy (Stub) queued. Dependencies: abc (stub), sys (stub), email.message (stub), email.errors (stub), email.header (stub), email.contentmanager (stub)
Analysis of ssl (Library) queued. Dependencies: ssl (stub), sys, os, collections, enum, _ssl, socket, base64, errno, warnings, time, calendar
Analysis of html (Stub) queued. Dependencies: 
Create compiled (scraped):  _ssl /Users/malmaud/anaconda3/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so /Users/malmaud/anaconda3/lib/python3.7/lib-dynload 
Analysis of ssl (Stub) queued. Dependencies: socket (stub), sys (stub)
Analysis of email (Library) queued. Dependencies: email (stub), email.parser
Analysis of email.utils (Library) queued. Dependencies: email.utils (stub), os, re, time, random, socket, datetime, urllib, urllib.parse, email._parseaddr, email.charset
Analysis of email.parser (Library) queued. Dependencies: email.parser (stub), io, email.feedparser, email._policybase
Analysis of html (Library) queued. Dependencies: html (stub), re, html.entities
Import:  email._parseaddr /Users/malmaud/anaconda3/lib/python3.7/email/_parseaddr.py 
Import:  email.charset /Users/malmaud/anaconda3/lib/python3.7/email/charset.py 
Analysis of _ssl (Compiled) queued. Dependencies: 
Analysis of email.charset (Stub) queued. Dependencies: 
Analysis of http.client (Stub) queued. Dependencies: email (stub), email.message (stub), io (stub), socket (stub), sys (stub), ssl (stub), types (stub)
Analysis of email.contentmanager (Stub) queued. Dependencies: email.message (stub)
Analysis of email.errors (Stub) queued. Dependencies: 
Analysis of email.header (Stub) queued. Dependencies: email.charset (stub)
Import:  email.feedparser /Users/malmaud/anaconda3/lib/python3.7/email/feedparser.py 
Analysis of webbrowser (Stub) queued. Dependencies: sys (stub)
Analysis of email.parser (Stub) queued. Dependencies: email (stub), email.feedparser (stub), email.message (stub), email.policy (stub)
Analysis of email.feedparser (Stub) queued. Dependencies: sys (stub), email.message (stub), email.policy (stub)
Analysis of email._parseaddr (Library) queued. Dependencies: time, calendar
Analysis of email.charset (Library) queued. Dependencies: email.charset (stub), functools, email, email.base64mime, email.quoprimime, email.errors, email.encoders
Import:  email._policybase /Users/malmaud/anaconda3/lib/python3.7/email/_policybase.py 
Import:  html.entities /Users/malmaud/anaconda3/lib/python3.7/html/entities.py 
Analysis of email.message (Stub) queued. Dependencies: sys (stub), email.charset (stub), email.errors (stub), email.header (stub), email.policy (stub), email.contentmanager (stub)
Analysis of time (Stub) on depth 9 completed in 48.99 ms.
Analysis of html.entities (Stub) queued. Dependencies: 
Analysis of email.feedparser (Library) queued. Dependencies: email.feedparser (stub), re, email, email.errors, email._policybase, collections, io, email.message
Analysis of email._policybase (Library) queued. Dependencies: abc, email, email.header, email.charset, email.utils
Import:  email.base64mime /Users/malmaud/anaconda3/lib/python3.7/email/base64mime.py 
Analysis of email.base64mime (Library) queued. Dependencies: base64, binascii
Import:  email.quoprimime /Users/malmaud/anaconda3/lib/python3.7/email/quoprimime.py 
Analysis of email.message (Library) queued. Dependencies: email.message (stub), re, uu, quopri, io, email, email.utils, email.errors, email._policybase, email.charset, email._encoded_words, email.generator, email.iterators, email.policy
Import:  email.errors /Users/malmaud/anaconda3/lib/python3.7/email/errors.py 
Import:  email.encoders /Users/malmaud/anaconda3/lib/python3.7/email/encoders.py 
Analysis of email.encoders (Stub) queued. Dependencies: email.message (stub)
Analysis of email.errors (Library) queued. Dependencies: email.errors (stub)
Analysis of email.quoprimime (Library) queued. Dependencies: re, string
Analysis of email.encoders (Library) queued. Dependencies: email.encoders (stub), base64, quopri
Analysis of webbrowser (Library) queued. Dependencies: webbrowser (stub), os, shlex, shutil, sys, subprocess, threading, copy, glob, pwd, socket, tempfile, getopt
Import:  email.header /Users/malmaud/anaconda3/lib/python3.7/email/header.py 
Import:  uu /Users/malmaud/anaconda3/lib/python3.7/uu.py 
Import:  quopri /Users/malmaud/anaconda3/lib/python3.7/quopri.py 
Import:  email._encoded_words /Users/malmaud/anaconda3/lib/python3.7/email/_encoded_words.py 
Import:  email.generator /Users/malmaud/anaconda3/lib/python3.7/email/generator.py 
Analysis of html.entities (Library) queued. Dependencies: html.entities (stub)
Import:  email.iterators /Users/malmaud/anaconda3/lib/python3.7/email/iterators.py 
Import:  email.policy /Users/malmaud/anaconda3/lib/python3.7/email/policy.py 
Analysis of email.policy (Library) queued. Dependencies: email.policy (stub), re, email._policybase, email.utils, email.headerregistry, email.contentmanager, email.message
Analysis of quopri (Stub) queued. Dependencies: 
Analysis of email.generator (Stub) queued. Dependencies: email.message (stub), email.policy (stub)
Analysis of email.iterators (Library) queued. Dependencies: email.iterators (stub), sys, io
Analysis of email.iterators (Stub) queued. Dependencies: email.message (stub)
Import:  email.headerregistry /Users/malmaud/anaconda3/lib/python3.7/email/headerregistry.py 
Analysis of email.header (Library) queued. Dependencies: email.header (stub), re, binascii, email, email.quoprimime, email.base64mime, email.errors, email.charset
Import:  email.contentmanager /Users/malmaud/anaconda3/lib/python3.7/email/contentmanager.py 
Analysis of email.generator (Library) queued. Dependencies: email.generator (stub), re, sys, time, random, copy, io, email.utils
Analysis of email.headerregistry (Stub) queued. Dependencies: datetime (stub), email.errors (stub), email.policy (stub)
Analysis of uu (Stub) queued. Dependencies: sys (stub)
Analysis of email.contentmanager (Library) queued. Dependencies: email.contentmanager (stub), binascii, email, email.charset, email.message, email.errors, email.quoprimime
Analysis of uu (Library) queued. Dependencies: uu (stub), binascii, os, sys, optparse
Analysis of email.headerregistry (Library) queued. Dependencies: email.headerregistry (stub), types, email, email.utils, email.errors, email._header_value_parser
Import:  optparse /Users/malmaud/anaconda3/lib/python3.7/optparse.py 
Analysis of email._encoded_words (Library) queued. Dependencies: re, base64, binascii, functools, string, email, email.errors
Analysis of quopri (Library) queued. Dependencies: quopri (stub), binascii, io, sys, getopt
Analysis of optparse (Stub) queued. Dependencies: sys (stub)
Import:  email._header_value_parser /Users/malmaud/anaconda3/lib/python3.7/email/_header_value_parser.py 
Analysis of optparse (Library) queued. Dependencies: optparse (stub), sys, os, textwrap, gettext
Analysis of argparse (Stub) on depth 6 completed in 104.91 ms.
Analysis of pdb (Stub) on depth 7 completed in 0.46 ms.
Analysis of pickle (Stub) on depth 5 completed in 1.98 ms.
Analysis of locale (Stub) on depth 8 completed in 3.29 ms.
Analysis of pprint (Stub) on depth 6 completed in 19.74 ms.
Analysis of inspect (Stub) on depth 7 completed in 23.27 ms.
Analysis of opcode (Stub) on depth 9 completed in 0.79 ms.
Analysis of glob (Stub) on depth 8 completed in 0.72 ms.
Analysis of linecache (Stub) on depth 4 completed in 4.4 ms.
Analysis of code (Stub) on depth 8 completed in 5.87 ms.
Analysis of sre_compile (Stub) on depth 5 completed in 5.39 ms.
Analysis of email._header_value_parser (Library) queued. Dependencies: re, urllib, string, collections, operator, email, email._encoded_words, email.errors, email.utils
Analysis of functools (Stub) on depth 5 completed in 6.77 ms.
Analysis of readline (Stub) on depth 8 completed in 0.86 ms.
Analysis of importlib (Stub) on depth 8 completed in 1.54 ms.
Analysis of tracemalloc (Stub) on depth 4 completed in 2.33 ms.
Analysis of token (Stub) on depth 6 completed in 4.32 ms.
Analysis of traceback (Stub) on depth 4 completed in 5.29 ms.
Analysis of pkgutil (Stub) on depth 9 completed in 0.85 ms.
Analysis of pyexpat.errors (Stub) on depth 12 completed in 0.45 ms.
Analysis of shlex (Stub) on depth 8 completed in 1.12 ms.
Analysis of binascii (Stub) on depth 11 completed in 0.75 ms.
Analysis of tempfile (Stub) on depth 9 completed in 1.89 ms.
Analysis of _random (Stub) on depth 11 completed in 0.4 ms.
Analysis of urllib.parse (Stub) on depth 9 completed in 3.44 ms.
Analysis of hashlib (Stub) on depth 11 completed in 2.31 ms.
Analysis of codeop (Stub) on depth 9 completed in 0.51 ms.
Analysis of encodings (Stub) on depth 7 completed in 0.5 ms.
Analysis of warnings (Stub) on depth 3 completed in 0.92 ms.
Analysis of platform (Stub) on depth 9 completed in 1.35 ms.
Analysis of io (Library) on depth 2 completed in 2.96 ms.
Analysis of _ast (Stub) on depth 9 completed in 23.59 ms.
Analysis of stat (Library) on depth 2 completed in 11.38 ms.
Analysis of collections.abc (Stub) on depth 5 completed in 2.27 ms.
Analysis of math (Compiled) on depth 4 completed in 3.93 ms.
Analysis of reprlib (Stub) on depth 6 completed in 0.82 ms.
Analysis of struct (Stub) on depth 6 completed in 0.8 ms.
Analysis of weakref (Stub) on depth 6 completed in 5.14 ms.
Analysis of __future__ (Library) on depth 6 completed in 3.55 ms.
Analysis of signal (Stub) on depth 4 completed in 2.33 ms.
Analysis of select (Compiled) on depth 3 completed in 14.08 ms.
Analysis of _collections_abc (Library) on depth 2 completed in 26.45 ms.
Analysis of socket (Stub) on depth 5 completed in 6.63 ms.
Analysis of plistlib (Stub) on depth 10 completed in 1.02 ms.
Analysis of re (Stub) on depth 4 completed in 4.1 ms.
Analysis of datetime (Stub) on depth 11 completed in 6.68 ms.
Analysis of dis (Stub) on depth 8 completed in 3.1 ms.
Analysis of readline (Compiled) on depth 7 completed in 3.1 ms.
Analysis of opcode (Library) on depth 8 completed in 3.2 ms.
Analysis of logging (Stub) on depth 8 completed in 10.56 ms.
Analysis of pyexpat (Stub) on depth 12 completed in 1.07 ms.
Analysis of tokenize (Stub) on depth 5 completed in 1.64 ms.
Analysis of importlib.machinery (Stub) on depth 8 completed in 2.56 ms.
Analysis of binascii (Compiled) on depth 10 completed in 2.73 ms.
Analysis of _random (Compiled) on depth 10 completed in 0.71 ms.
Analysis of ast (Stub) on depth 8 completed in 1.27 ms.
Analysis of random (Stub) on depth 10 completed in 4.04 ms.
Analysis of struct (Library) on depth 5 completed in 2.9 ms.
Analysis of _threading_local (Stub) on depth 5 completed in 0.56 ms.
Analysis of encodings (Library) on depth 6 completed in 5.33 ms.
Analysis of codeop (Library) on depth 8 completed in 2.17 ms.
Analysis of reprlib (Library) on depth 5 completed in 3.43 ms.
Analysis of selectors (Stub) on depth 4 completed in 2.36 ms.
Analysis of calendar (Stub) on depth 13 completed in 3.69 ms.
Analysis of xml.parsers.expat (Stub) on depth 11 completed in 1.14 ms.
Analysis of pyexpat (Compiled) on depth 11 completed in 4.73 ms.
Analysis of importlib.util (Stub) on depth 9 completed in 1.13 ms.
Analysis of unittest (Stub) on depth 7 completed in 9.8 ms.
Analysis of codecs (Library) on depth 5 completed in 22.46 ms.
Analysis of xml.parsers.expat (Library) on depth 10 completed in 2.65 ms.
Analysis of doctest (Stub) on depth 6 completed in 4.73 ms.
Analysis of datetime (Library) on depth 10 completed in 41.65 ms.
Analysis of collections.abc (Library) on depth 4 completed in 8.73 ms.
Analysis of calendar (Library) on depth 12 completed in 8.18 ms.
Analysis of plistlib (Library) on depth 9 completed in 9.02 ms.
Analysis of _strptime (Library) on depth 11 completed in 6.74 ms.
Analysis of platform (Library) on depth 8 completed in 14.45 ms.
Analysis of pydoc (Library) on depth 7 completed in 43.37 ms.
Analysis of pdb (Library) on depth 6 completed in 19.35 ms.
Analysis of doctest (Library) on depth 5 completed in 13.92 ms.
Analysis of heapq (Library) on depth 5 completed in 3.38 ms.
Analysis of pickle (Library) on depth 4 completed in 27.2 ms.
Analysis of tracemalloc (Library) on depth 3 completed in 6.3 ms.
Analysis of warnings (Library) on depth 2 completed in 6.63 ms.
Analysis of logging (Library) on depth 8 completed in 22.96 ms.
Analysis of importlib.abc (Library) on depth 9 completed in 9.94 ms.
Analysis of hashlib (Library) on depth 10 completed in 3.41 ms.
Analysis of importlib.util (Library) on depth 8 completed in 2.26 ms.
Analysis of random (Library) on depth 9 completed in 3.72 ms.
Analysis of sre_parse (Library) on depth 4 completed in 10.97 ms.
Analysis of importlib (Library) on depth 7 completed in 1.2 ms.
Analysis of pkgutil (Library) on depth 8 completed in 6.23 ms.
Analysis of unittest.case (Library) on depth 7 completed in 15.64 ms.
Analysis of tempfile (Library) on depth 8 completed in 5.73 ms.
Analysis of inspect (Library) on depth 6 completed in 28.27 ms.
Analysis of sre_compile (Library) on depth 4 completed in 16.09 ms.
Analysis of bdb (Library) on depth 7 completed in 6.82 ms.
Analysis of runpy (Library) on depth 7 completed in 2.42 ms.
Analysis of re (Library) on depth 3 completed in 2.66 ms.
Analysis of unittest.loader (Library) on depth 7 completed in 10.51 ms.
Analysis of ast (Library) on depth 7 completed in 2.33 ms.
Analysis of keyword (Library) on depth 5 completed in 1.19 ms.
Analysis of difflib (Library) on depth 6 completed in 14.85 ms.
Analysis of textwrap (Library) on depth 6 completed in 1.64 ms.
Analysis of pprint (Library) on depth 5 completed in 9.59 ms.
Analysis of urllib.parse (Library) on depth 8 completed in 11.81 ms.
Analysis of token (Library) on depth 5 completed in 9.69 ms.
Analysis of collections (Library) on depth 4 completed in 16.5 ms.
Analysis of tokenize (Library) on depth 4 completed in 15.25 ms.
Analysis of selectors (Library) on depth 3 completed in 7.2 ms.
Analysis of unittest.main (Library) on depth 7 completed in 2.17 ms.
Analysis of string (Library) on depth 3 completed in 7.5 ms.
Analysis of functools (Library) on depth 4 completed in 10.42 ms.
Analysis of enum (Library) on depth 4 completed in 9.96 ms.
Analysis of importlib._bootstrap_external (Library) on depth 8 completed in 19.52 ms.
Analysis of contextlib (Library) on depth 5 completed in 10.19 ms.
Completions in file:///Users/malmaud/q/hi.py at (3, 3)
Analysis of cmd (Library) on depth 7 completed in 0.89 ms.
Analysis of types (Library) on depth 5 completed in 2.72 ms.
Analysis of signal (Library) on depth 3 completed in 0.59 ms.
Analysis of importlib.machinery (Library) on depth 7 completed in 4.43 ms.
Analysis of copy (Library) on depth 5 completed in 1.77 ms.
Analysis of unittest.signals (Library) on depth 7 completed in 0.6 ms.
Analysis of weakref (Library) on depth 5 completed in 9.13 ms.
Analysis of linecache (Library) on depth 3 completed in 0.53 ms.
Analysis of operator (Library) on depth 5 completed in 6.3 ms.
Analysis of traceback (Library) on depth 3 completed in 6.56 ms.
Analysis of code (Library) on depth 7 completed in 0.98 ms.
Analysis of unittest (Library) on depth 6 completed in 3.63 ms.
Analysis of unittest.runner (Library) on depth 7 completed in 3.88 ms.
Analysis of threading (Library) on depth 3 completed in 6.91 ms.
Analysis of _threading_local (Library) on depth 4 completed in 5.14 ms.
Analysis of unittest.suite (Library) on depth 7 completed in 10.08 ms.
Analysis of unittest.result (Library) on depth 7 completed in 1.63 ms.
Analysis of subprocess (Library) on depth 2 completed in 25.65 ms.
Analysis of genericpath (Library) on depth 3 completed in 1.77 ms.
Analysis of unittest.util (Library) on depth 8 completed in 3.41 ms.
Analysis of shlex (Library) on depth 7 completed in 6.54 ms.
Analysis of getopt (Library) on depth 7 completed in 2.02 ms.
Analysis of locale (Library) on depth 7 completed in 22.22 ms.
Analysis of fnmatch (Library) on depth 4 completed in 0.9 ms.
Analysis of glob (Library) on depth 7 completed in 1.77 ms.
Analysis of socket (Library) on depth 9 completed in 41.59 ms.
Analysis of posixpath (Library) on depth 2 completed in 6.9 ms.
Analysis of ntpath (Library) on depth 2 completed in 13.99 ms.
Analysis of gettext (Library) on depth 6 completed in 15.26 ms.
Analysis of _bootlocale (Library) on depth 8 completed in 0.51 ms.
Analysis of shutil (Library) on depth 9 completed in 16.74 ms.
Analysis of argparse (Library) on depth 5 completed in 21.76 ms.
Analysis of dis (Library) on depth 7 completed in 6.38 ms.
Analysis version 422 has been completed in 860.25 ms with 250 entries analyzed and 108 entries skipped.
Analysis version 558 of 477 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of abc (Stub) on depth 3 completed in 0.48 ms.
Analysis of posix (Stub) on depth 3 completed in 0.54 ms.
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _operator(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of pydoc_data (Library) on depth 8 completed in 0.13 ms.
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of _stat(CompiledBuiltin) canceled (no AST yet).
Analysis of mmap (Stub) on depth 4 completed in 1.52 ms.
Analysis of pydoc_data.topics (Library) on depth 8 completed in 0.49 ms.
Analysis of grp (Stub) on depth 11 completed in 0.3 ms.
Analysis of tty (Stub) on depth 9 completed in 0.93 ms.
Analysis of _bz2 (Compiled) on depth 11 completed in 0.9 ms.
Analysis of _lzma (Compiled) on depth 11 completed in 2.33 ms.
Analysis of email.charset (Stub) on depth 10 completed in 5.66 ms.
Analysis of email.contentmanager (Stub) on depth 10 completed in 0.45 ms.
Analysis of email.errors (Stub) on depth 10 completed in 1.35 ms.
Analysis of termios (Stub) on depth 10 completed in 7.69 ms.
Analysis of _ssl (Compiled) on depth 11 completed in 8.16 ms.
Analysis of html (Stub) on depth 10 completed in 0.15 ms.
Analysis of html.entities (Stub) on depth 11 completed in 0.2 ms.
Analysis of quopri (Stub) on depth 10 completed in 0.2 ms.
Analysis of grp (Compiled) on depth 10 completed in 1 ms.
Analysis of email.header (Stub) on depth 10 completed in 0.68 ms.
Analysis of html.entities (Library) on depth 10 completed in 31.75 ms.
Analysis of email.errors (Library) on depth 9 completed in 33.78 ms.
Analysis of zipfile (Stub) on depth 11 completed in 3.58 ms.
Analysis of shutil (Stub) on depth 10 completed in 3.56 ms.
Analysis of py_compile (Stub) on depth 12 completed in 0.52 ms.
Analysis of zlib (Stub) on depth 11 completed in 1.31 ms.
Analysis of lzma (Stub) on depth 11 completed in 3.2 ms.
Analysis of tarfile (Stub) on depth 11 completed in 4.97 ms.
Analysis of bz2 (Stub) on depth 11 completed in 4.84 ms.
Analysis of base64 (Stub) on depth 10 completed in 1.01 ms.
Analysis of mimetypes (Stub) on depth 10 completed in 1.21 ms.
Analysis of email.policy (Stub) on depth 10 completed in 2.89 ms.
Analysis of uu (Stub) on depth 10 completed in 0.31 ms.
Analysis of webbrowser (Stub) on depth 9 completed in 5.66 ms.
Analysis of termios (Compiled) on depth 9 completed in 55.62 ms.
Analysis of optparse (Stub) on depth 11 completed in 13.67 ms.
Analysis of _compression (Stub) on depth 12 completed in 0.71 ms.
Analysis of http (Stub) on depth 9 completed in 3.49 ms.
Analysis of email.message (Stub) on depth 9 completed in 5.77 ms.
Analysis of zlib (Compiled) on depth 10 completed in 3.75 ms.
Analysis of ssl (Stub) on depth 11 completed in 4.7 ms.
Analysis of tty (Library) on depth 8 completed in 2.03 ms.
Analysis of gzip (Stub) on depth 12 completed in 4.47 ms.
Analysis of socketserver (Stub) on depth 10 completed in 4.54 ms.
Analysis of email.utils (Stub) on depth 10 completed in 1.14 ms.
Analysis of email (Stub) on depth 9 completed in 1.88 ms.
Analysis of _compression (Library) on depth 11 completed in 2.12 ms.
Analysis of email.headerregistry (Stub) on depth 11 completed in 1.93 ms.
Analysis of email.iterators (Stub) on depth 10 completed in 0.24 ms.
Analysis of email.feedparser (Stub) on depth 11 completed in 0.51 ms.
Analysis of email.generator (Stub) on depth 10 completed in 0.79 ms.
Analysis of email.encoders (Stub) on depth 11 completed in 0.16 ms.
Analysis of http.server (Stub) on depth 9 completed in 2.42 ms.
Analysis of email.iterators (Library) on depth 9 completed in 0.58 ms.
Analysis of email.utils (Library) on depth 9 completed in 2.11 ms.
Analysis of email.parser (Stub) on depth 10 completed in 0.95 ms.
Analysis of http.client (Stub) on depth 10 completed in 3.81 ms.
Analysis of email._header_value_parser (Library) on depth 11 completed in 44.08 ms.
Analysis of email.headerregistry (Library) on depth 10 completed in 6.9 ms.
Analysis of email.policy (Library) on depth 9 completed in 1.6 ms.
Analysis of email.message (Library) on depth 8 completed in 8.03 ms.
Analysis of email.contentmanager (Library) on depth 10 completed in 5.17 ms.
Analysis of email.feedparser (Library) on depth 10 completed in 5.54 ms.
Analysis of email.parser (Library) on depth 9 completed in 1.3 ms.
Analysis of email (Library) on depth 8 completed in 0.81 ms.
Analysis of http.client (Library) on depth 9 completed in 30.56 ms.
Analysis of http.server (Library) on depth 8 completed in 17.8 ms.
Analysis of bz2 (Library) on depth 10 completed in 2.44 ms.
Analysis of base64 (Library) on depth 9 completed in 7.44 ms.
Analysis of gzip (Library) on depth 11 completed in 10.16 ms.
Analysis of ssl (Library) on depth 10 completed in 20.92 ms.
Analysis of email.encoders (Library) on depth 10 completed in 0.39 ms.
Analysis of email.base64mime (Library) on depth 10 completed in 2.18 ms.
Analysis of email._encoded_words (Library) on depth 9 completed in 4.39 ms.
Analysis of tarfile (Library) on depth 10 completed in 29.58 ms.
Analysis of email.charset (Library) on depth 9 completed in 2.09 ms.
Analysis of py_compile (Library) on depth 11 completed in 4.33 ms.
Analysis of email.generator (Library) on depth 9 completed in 8.15 ms.
Analysis of webbrowser (Library) on depth 8 completed in 26.18 ms.
Analysis of html (Library) on depth 9 completed in 1.19 ms.
Analysis of email.quoprimime (Library) on depth 10 completed in 3.33 ms.
Analysis of email.header (Library) on depth 10 completed in 5.82 ms.
Analysis of http (Library) on depth 8 completed in 5.2 ms.
Analysis of email._policybase (Library) on depth 9 completed in 6.39 ms.
Analysis of mimetypes (Library) on depth 9 completed in 15.58 ms.
Analysis of socketserver (Library) on depth 9 completed in 18.54 ms.
Analysis of quopri (Library) on depth 9 completed in 2.65 ms.
Analysis of lzma (Library) on depth 10 completed in 10.48 ms.
Analysis of zipfile (Library) on depth 10 completed in 48.73 ms.
Analysis of email._parseaddr (Library) on depth 10 completed in 16.62 ms.
Analysis of optparse (Library) on depth 10 completed in 14.04 ms.
Analysis of uu (Library) on depth 9 completed in 2.63 ms.
Analysis version 558 has been completed in 350.92 ms with 118 entries analyzed and 359 entries skipped.
Analysis of hi (User) queued. Dependencies: os
Analysis version 559 of 477 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of _stat(CompiledBuiltin) canceled (no AST yet).
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _operator(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of posix (Stub) on depth 3 completed in 2.4 ms.
Analysis of abc (Stub) on depth 3 completed in 4.91 ms.
Analysis of mmap (Stub) on depth 4 completed in 5.36 ms.
Analysis version 559 has been completed in 6.28 ms with 30 entries analyzed and 447 entries skipped.
Analysis of hi (User) queued. Dependencies: 
Analysis version 560 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 3.81 ms.
Analysis complete: 340 modules in 4691.65 ms.
Analysis version 560 of 1 entries has been completed in 4.31 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 561 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 3.75 ms.
Analysis complete: 1 modules in 9.84 ms.
Analysis version 561 of 1 entries has been completed in 7.5 ms.
Completions in file:///Users/malmaud/q/hi.py at (0, 1)
Analysis of hi (User) queued. Dependencies: 
Analysis version 562 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.75 ms.
Analysis complete: 1 modules in 1.52 ms.
Analysis version 562 of 1 entries has been completed in 0.98 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 563 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.13 ms.
Analysis complete: 1 modules in 0.64 ms.
Analysis version 563 of 1 entries has been completed in 0.27 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 564 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.13 ms.
Analysis complete: 1 modules in 0.81 ms.
Analysis version 564 of 1 entries has been completed in 0.3 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 565 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.89 ms.
Analysis complete: 1 modules in 3.54 ms.
Analysis version 565 of 1 entries has been completed in 2.23 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 566 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.27 ms.
Analysis complete: 1 modules in 1.41 ms.
Analysis version 566 of 1 entries has been completed in 0.54 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 567 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.06 ms.
Analysis complete: 1 modules in 0.45 ms.
Analysis version 567 of 1 entries has been completed in 0.17 ms.
Analysis of hi (User) queued. Dependencies: 
Analysis version 568 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.84 ms.
Analysis complete: 1 modules in 2.71 ms.
Analysis version 568 of 1 entries has been completed in 1.82 ms.
Completions in file:///Users/malmaud/q/hi.py at (0, 8)
Analysis of hi (User) queued. Dependencies: 
Analysis version 569 of 1 entries has started.
Analysis of hi (User) on depth 0 completed in 0.45 ms.
Analysis complete: 1 modules in 1.24 ms.
Analysis version 569 of 1 entries has been completed in 0.6 ms.
Analysis of hi (User) queued. Dependencies: sys
Analysis version 570 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 570 has been completed in 0.14 ms with 1 entries analyzed and 1 entries skipped.
Analysis of hi (User) queued. Dependencies: sys
Analysis version 571 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 571 has been completed in 0.15 ms with 1 entries analyzed and 1 entries skipped.
Analysis of hi (User) queued. Dependencies: sys
Analysis version 572 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 572 has been completed in 0.09 ms with 1 entries analyzed and 1 entries skipped.
Completions in file:///Users/malmaud/q/hi.py at (2, 1)
Analysis of hi (User) queued. Dependencies: sys
Analysis version 573 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 573 has been completed in 0.3 ms with 1 entries analyzed and 1 entries skipped.
Analysis of hi (User) queued. Dependencies: sys
Analysis version 574 of 2 entries has started.
Analysis of hi (User) queued. Dependencies: sys
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 574 has been completed in 0.12 ms with 1 entries analyzed and 1 entries skipped.
Analysis version 575 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 575 has been completed in 0.11 ms with 1 entries analyzed and 1 entries skipped.
Analysis of hi (User) queued. Dependencies: sys
Completions in file:///Users/malmaud/q/hi.py at (2, 4)
Analysis version 576 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 576 has been completed in 0.1 ms with 1 entries analyzed and 1 entries skipped.
Completions in file:///Users/malmaud/q/hi.py at (2, 4)
Analysis of hi (User) queued. Dependencies: sys
Analysis version 577 of 2 entries has started.
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis version 577 has been completed in 0.4 ms with 1 entries analyzed and 1 entries skipped.
```

### LINKED ISSUE #1728: Lazy restoration of cached modules
Currently module analysis is restored from the database as regular analysis with dependencies is running. I.e., instead of evaluating code, result is read from the database. This allowed to integrate caching into the existing analysis workflow (the dependency walk) easily, but, unfortunately, there is a drawback.

Namely, often IO operations (i.e. reading from the database) take almost as long as the original analysis. It is not the database performance issue, raw serialization into flat binary file and reading back is not much faster than binary JSON used by the LiteDB. 

Changes:
- Instead of restoring everything, only main module (such as numpy) is restored. Module the claims to have no dependencies so analysis does not run on its submodules. This should provide first level of completions. 
- Types coming from submodules should be kept lazy – for example, class that comes from a submodule, remains lazy. When deeper member is requested, such as when user types ‘numpy.A.’ where ‘A’ is from ‘numpy.core’, then ‘numpy.core’ analysis is restored from the db, and so on – on demand. 
- Types that never used may never be restored yielding memory savings. Obviously, there may be hit for really complex members than chain multiple modules, but it should be one time hit. 
- Top-level module database will then need to store more information about inner types (such as function signature and documentation rather than relying on fetching those off the inner restored type).

The approach does not require changes to the analysis workflow. If module is cached, it will be restored and if analysis of some non-cached module requires deeper members, process is the same as if user requested said members.

### LINKED ISSUE #1758: Endless loop in analysis with caching set to "system"
Sorry if it's a dupe 😁
## Environment data

- Language Server version: 0.4.96.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3, venv

Background analysis gets stuck in an endless loop:

LSloop

Packages installed in this environment: 

atomicwrites==1.3.0
attrs==19.2.0
Click==7.0
colorama==0.4.1
Flask==1.1.1
importlib-metadata==0.23
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
more-itertools==7.2.0
numpy==1.17.3
packaging==19.2
pluggy==0.13.0
py==1.8.0
pyparsing==2.4.2
pytest==5.2.1
PyYAML==5.1.2
six==1.12.0
wcwidth==0.1.7
Werkzeug==0.15.6
zipp==0.6.0

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #1728
Fixes #1758
Fixes #1514
Fixes #1515 
Fixes #1516 
Fixes #1517
Fixes #1518
Fixes #1569
Fixes #1680

- Instead of restoring analysis, restore complete module and claim there are no dependencies. 
- Introduces lazy types. Lazy types expose documentation and names, but members, function return types and parameters are populated only when requested.
- Allow creating of caches for stub-only modules like `posix` or `mmap`.
- Delay cache writing to after analysis completes so it does not steal CPU time from analysis.
- Limit how much IO threads run at the same time in the cache writer.

TODO (later): 
- Functions should store signatures so documentation in completion list won't need to fully restore type.

Related
- https://github.com/microsoft/python-language-server/issues/1753
- https://github.com/microsoft/python-language-server/issues/1697

### CODE REVIEW

File: src/LanguageServer/Impl/Program.cs [hunk 1]
```diff
@@ -13,7 +13,7 @@
 // See the Apache Version 2.0 License for specific language governing
 // permissions and limitations under the License.
 
-// #define WAIT_FOR_DEBUGGER
+#define WAIT_FOR_DEBUGGER
```
Comment (MikhailArkhipov) [inline src/LanguageServer/Impl/Program.cs]: Will remove eventually

**Comment by MikhailArkhipov** [comment]
image

File: src/Caching/Impl/ModuleDatabase.cs [hunk 2]
```diff
@@ -60,7 +59,7 @@ internal sealed class ModuleDatabase : IModuleDatabaseService {
         }
 
         public string CacheFolderBaseName => "analysis.v";
-        public int DatabaseFormatVersion => 2;
+        public int DatabaseFormatVersion => 3;
```
Comment (jakebailey) [inline src/Caching/Impl/ModuleDatabase.cs]: This is 4 at master, so you will have to bump to 5.

File: src/Caching/Impl/ModuleUniqueId.cs [hunk 3]
```diff
@@ -57,75 +50,12 @@ internal static class ModuleUniqueId {
...
-
-                    if (child is IImportChildrenSource childSource) {
-                        hash = unchecked(hash * 31 ^ HashModuleFileSizes(childSource));
-                    }
-                }
-            }
-
-            return hash;
+            var config = interpreter.Configuration;
+            return $"{moduleName}({config.Version.Major}.{config.Version.Minor})";
```
Comment (jakebailey) [inline src/Caching/Impl/ModuleUniqueId.cs]: I'm not really sure if going all the way to python-versions is a good idea either...

Comment (MikhailArkhipov) [reply src/Caching/Impl/ModuleUniqueId.cs]: Yes, we need to tell if module was updated. Now, version if typically reflected in the path like `dist.info` so adding hash of the path is cheap way. 

However, this does not cover case when module path does not change (such as when it does not have version), but content does.
Hashing module sizes of all the child modules is expensive, so here I am not yet sure what to do.

Comment (MikhailArkhipov) [reply src/Caching/Impl/ModuleUniqueId.cs]: Restored most of the original, instead of file system walk code look into path directly. Also caches unique id per triplet in order to avoid multiple calculations for separate calls. Better, but still not quite. Needs some more profiling. Some time is taken by cache writing, of course.
```
Analysis complete: 2987 modules in 73918.4 ms.
```
Uncached
```
Analysis complete: 2987 modules in 60060.78 ms.
```

Comment (MikhailArkhipov) [reply src/Caching/Impl/ModuleUniqueId.cs]: Delayed cache writing to after analysis, look OK.

File: src/Caching/Impl/ModuleDatabase.cs [hunk 4]
```diff
@@ -17,151 +17,117 @@
...
-            CacheFolder = Path.Combine(cfs.CacheFolder, $"{CacheFolderBaseName}{DatabaseFormatVersion}");
+        private readonly AnalysisCachingLevel _defaultCachingLevel;
+        private readonly CacheWriter _cacheWriter;
+        private AnalysisCachingLevel? _cachingLevel;
+
+        public ModuleDatabase(IServiceManager sm, string cacheFolder = null) {
+            _services = sm;
+            _log = _services.GetService<ILogger>();
+            _fs = _services.GetService<IFileSystem>();
+            _defaultCachingLevel = AnalysisCachingLevel.Library;
```
Comment (jakebailey) [inline src/Caching/Impl/ModuleDatabase.cs]: What makes this level differ from the other default?

Comment (MikhailArkhipov) [reply src/Caching/Impl/ModuleDatabase.cs]: It is mostly for tests so default is full functionality. If not provided, like in tests, `Library` is used since there are now tests for full restore, i.e. analysis - write cache, reset analyzer - reload. If provided, such as from settings in the real case, the provided one will be used.

**Comment by jakebailey** [comment]
Re-reviewing this now. Some test failures:

```
 GenericClassInstantiationByValue
   Source: GenericsTests.cs line 503
   Duration: 1 sec

  Message: 
    Expected Type.TypeId to be Int, but found Unknown.
  Stack Trace: 
    LateBoundTestFramework.Throw(String message)
    TestFrameworkProvider.Throw(String message)
    DefaultAssertionStrategy.HandleFailure(String message)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(String message, Object[] args)
    ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
    MemberAssertions.HaveType(BuiltinTypeId typeId, String because, Object[] reasonArgs) line 292
    VariableAssertions.HaveType(BuiltinTypeId typeId, String because, Object[] reasonArgs) line 40
    GenericsTests.GenericClassInstantiationByValue() line 523
    ThreadOperations.ExecuteWithAbortSafety(Action action)

   Open additional output for this result
```

This one probably because something's not being loaded anymore for the code action code to read.

```
 ModuleNotReachableFromUserDocument
   Source: MissingImportCodeActionTests.cs line 305
   Duration: 1 sec

  Message: 
    Test method Microsoft.Python.LanguageServer.Tests.MissingImportCodeActionTests.ModuleNotReachableFromUserDocument threw exception: 
    System.InvalidOperationException: Sequence contains no matching element
  Stack Trace: 
    ThrowHelper.ThrowNoMatchException()
    Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
    MissingImportCodeActionTests.TestCodeActionAsync(String markup, String title, String newText, Boolean enableIndexManager) line 462
    MissingImportCodeActionTests.ModuleNotReachableFromUserDocument() line 306
    ThreadOperations.ExecuteWithAbortSafety(Action action)

   Open additional output for this result
```

**Comment by jakebailey** [comment]
Missed this one:
```
 WithIOStatement
   Source: ValuesTests.cs line 166

Test has multiple result outcomes
   1 Passed
   2 Failed

Results

    1)  WithIOStatement
      Duration: 10 sec

    2)  WithIOStatement (V27)
      Duration: 923 ms

      Message: 
        Expected Type.Name to be 
        "TextIOWrapper" with a length of 13, but 
        "Unknown" has a length of 7, differs near "Unk" (index 0).
      Stack Trace: 
        LateBoundTestFramework.Throw(String message)
        TestFrameworkProvider.Throw(String message)
        DefaultAssertionStrategy.HandleFailure(String message)
        AssertionScope.FailWith(Func`1 failReasonFunc)
        AssertionScope.FailWith(Func`1 failReasonFunc)
        StringEqualityValidator.ValidateAgainstLengthDifferences()
        StringValidator.Validate()
        StringAssertions.Be(String expected, String because, Object[] becauseArgs)
        MemberAssertions.HaveType(String typeName, String because, Object[] reasonArgs) line 300
        VariableAssertionsExtensions.OfType[TAssertion](AndWhichConstraint`2 andWhichConstraint, String typeName, String because, Object[] reasonArgs) line 33
        ValuesTests.WithIOStatement(PythonLanguageVersion version) line 187
        ThreadOperations.ExecuteWithAbortSafety(Action action)

       Open additional output for this result

    3)  WithIOStatement (V37)
      Duration: 9 sec

       Open additional output for this result
```

But you can probably run the suite to see.

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs [hunk 5]
```diff
@@ -208,12 +210,14 @@ public Task WaitForCompleteAnalysisAsync(CancellationToken cancellationToken = d
         #endregion
 
         internal void RaiseAnalysisComplete(int moduleCount, double msElapsed) {
-            var analsysComplete = false;
+            var analisysComplete = false;
```
Comment (jakebailey) [inline src/Analysis/Ast/Impl/Analyzer/PythonAnalyzer.cs]: `analysis`, not `analisys`.

File: src/Core/Impl/Services/ServiceManager.cs [hunk 6]
```diff
@@ -79,7 +79,7 @@ public sealed class ServiceManager : IServiceManager {
                 value = _s.FirstOrDefault(kvp => type.GetTypeInfo().IsAssignableFrom(kvp.Key)).Value;
             }
 
-            return (T)CheckDisposed(value as T ?? (value as Lazy<object>)?.Value);
```
Comment (jakebailey) [inline src/Core/Impl/Services/ServiceManager.cs]: Maybe also a comment with the old code for consistency?

File: src/Analysis/Ast/Test/DependencyResolverTests.cs [hunk 7]
```diff
@@ -494,59 +494,6 @@ public void TestInitialize()
             walker.Remaining.Should().Be(0);
         }
 
-        [TestMethod]
-        public async Task ChangeValue_RemoveKeys() {
```
Comment (jakebailey) [inline src/Analysis/Ast/Test/DependencyResolverTests.cs]: Is this a case that won't pop up anymore?

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs [hunk 8]
```diff
@@ -147,30 +146,26 @@ internal sealed class PythonAnalyzerSession {
...
-                        //#if DEBUG
-                        //                        var notReady = _analyzer.LoadedModules.Where(m => (m.ModuleType == ModuleType.Library || m.ModuleType == ModuleType.Stub) && m.Analysis is EmptyAnalysis).ToArray();
-                        //                        Debug.Assert(notReady.Length == 0);
-                        //#endif
-                    }
+                if (isFinal) {
+                    var (modulesCount, totalMilliseconds) = ActivityTracker.EndTracking();
+                    totalMilliseconds = Math.Round(totalMilliseconds, 2);
+                    _analyzer.RaiseAnalysisComplete(modulesCount, totalMilliseconds);
+                    _log?.Log(TraceEventType.Verbose, $"Analysis complete: {modulesCount} modules in {totalMilliseconds} ms.");
```
Comment (jakebailey) [inline src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs]: One thing I'm seeing here is that due to the lazy loading, we're (in a way) under-reporting the number of modules we're working with. Hopefully that's not such a big deal if the work also disappears, but it may end up appearing as though we're not "improving" per-module because for the N modules we still have to load, we have to do the same work.

File: src/LanguageServer/Impl/LanguageServer.cs [hunk 9]
```diff
@@ -308,7 +308,7 @@ private void OnApplyWorkspaceEdit(object sender, ApplyWorkspaceEditEventArgs e)
         public async Task ClearAnalysisCache(CancellationToken cancellationToken) {
             using (_requestTimer.Time("python/clearAnalysisCache"))
             using (await _prioritizer.ConfigurationPriorityAsync(cancellationToken)) {
-                Debug.Assert(_initialized);
+                // Debug.Assert(_initialized);
```
Comment (jakebailey) [inline src/LanguageServer/Impl/LanguageServer.cs]: Is this call valid when the server isn't yet initialized? I think some caching stuff gets set up during init.

File: src/Caching/Impl/ModuleUniqueId.cs [hunk 10]
```diff
@@ -70,23 +91,37 @@ public static string GetUniqueId(this IPythonModule module, IServiceContainer se
...
+                if (moduleType == ModuleType.CompiledBuiltin || string.IsNullOrEmpty(filePath) || modulePathType == PythonLibraryPathType.StdLib) {
+                    // If module is a standard library, unique id is its name + interpreter version.
+                    id = $"{moduleName}({config.Version.Major}.{config.Version.Minor})";
+                }
+            }
+
+            if (id == null) {
+                var parent = moduleResolution.CurrentPathResolver.GetModuleParentFromModuleName(moduleName);
+                if (parent == null) {
+                    id = moduleName;
```
Comment (jakebailey) [inline src/Caching/Impl/ModuleUniqueId.cs]: Won't this string just be something like "foo.bar" without any versioning? If the version needs to come from a parent, I'd expect to have seen recursion or something. Maybe I'm just reading this wrong.

File: src/Analysis/Ast/Test/DependencyResolverTests.cs (hunk 7 above)
Comment (MikhailArkhipov) [reply src/Analysis/Ast/Test/DependencyResolverTests.cs]: Yes. This is no longer needed.

Comment (jakebailey) [reply src/Analysis/Ast/Test/DependencyResolverTests.cs]: I should rephrase, would the test pass if it weren't removed?

File: src/LanguageServer/Impl/LanguageServer.cs (hunk 9 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/LanguageServer.cs]: Generally deleting is just FS operation having nothing to do with init. The reason it is commented out is that `LsDeleteAnalysisCache` test that needs to do `ls.Start` but fully initializing the server is now a long envdeavour.

Comment (jakebailey) [reply src/LanguageServer/Impl/LanguageServer.cs]: Sure, my point was that:

```csharp
_services.AddService(new ModuleDatabase(_services));
```

Is in `initialized`, and `ClearAnalysisCache` fetches this service and uses it without any checks, so there's potential for this call to break in an edge case if the command is sent too early.

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs (hunk 8 above)
Comment (MikhailArkhipov) [reply src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs]: Not entirely happy with `RaiseAnalysisComplete` being bool, but I can make it return if it actually raised the event. Somewhat ugly, but implementation uses data internal to the analyzer which i'd rather not make public.

File: src/Caching/Impl/ModuleUniqueId.cs (hunk 10 above)
Comment (MikhailArkhipov) [reply src/Caching/Impl/ModuleUniqueId.cs]: This is an edge case just to handle `GetModuleParentFromModuleName` that can return `null` since hashing needs parent `IImportChildrenSource`.

File: src/LanguageServer/Impl/LanguageServer.cs (hunk 9 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/LanguageServer.cs]: It is just AF which is not affecting real life case. in RL it won't go through b/c of the prioritizer. In test, it makes it less cumbersome since it takes some acrobatics to have server fully initialized.

File: src/Analysis/Ast/Test/DependencyResolverTests.cs (hunk 7 above)
Comment (MikhailArkhipov) [reply src/Analysis/Ast/Test/DependencyResolverTests.cs]: No, it wont as it was designed to remove random keys and the only case where we actually used it was complete reset - which was replaced by complete wipe out sans builtins.

Comment (jakebailey) [reply src/Analysis/Ast/Test/DependencyResolverTests.cs]: Ah, I see now. I didn't notice this test was using `RemoveKeys` (which you dropped in favor of a `Reset`).

File: src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs (hunk 8 above)
Comment (jakebailey) [reply src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs]: I'm not sure what you mean by returning a bool, I'm more talking about the fact that we'll log "123 modules analyzed", when maybe there are a bunch more that weren't "loaded" because they'll be fetched from disk.

You don't have to change anything for this comment, I was more thinking about the impact of lazyness on our reporting.

Comment (MikhailArkhipov) [reply src/Analysis/Ast/Impl/Analyzer/PythonAnalyzerSession.cs]: I mean returning bool from `RaiseAnalysisComplete` and then only reporting when it is really done.

**Comment by jakebailey** [comment]
Caching isn't perfect for all libraries, but the default is None and we want the rest of the fixes too. Approving.
