### PR TITLE
Bug fixes

### LINKED ISSUE #378: "Object reference not set to an instance of an object" when trying Go To Symbol in Workspace
This is a follow up on #137 that was closed prior to version 0.1.60.0.

Here is the full error message with the new version:

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.60.0
Initializing for /opt/venvs/py37/bin/python
[Error - 12:01:32 PM] Request workspace/symbol failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.Server.<>c__DisplayClass133_0.<GetModuleVariables>b__4(ILocationInfo l)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Python.LanguageServer.Implementation.Server.<>c__DisplayClass133_0.<GetModuleVariables>b__2(IMemberResult m)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Python.LanguageServer.Implementation.Server.GetModuleVariablesAsync(ProjectEntry entry, GetMemberOptions opts, String prefix, Int32 timeout, CancellationToken token)
   at Microsoft.Python.LanguageServer.Implementation.Server.WorkspaceSymbols(WorkspaceSymbolParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.WorkspaceSymbols(JToken token, CancellationToken cancellationToken)
```

### LINKED ISSUE #379: "Hash code changed when merging AnalysisValues" while analyzing scikit-learn
I get this Debug.Fail while attached to PLS when it's analyzing scikit-learn. The key seems to be changing:

```
key: {tuple[?, ?]tuple[str, list[float], list[float], ...][list, None, tuple, ]}
newKey: {tuple[[MockDataFrame, bytes, str, list, tuple, list...][float, list[str, str], None, tuple, ]tuple[str, list[float], list[float]...}
```

Copy/paste from the Call Stack pane:

```
>	System.Private.CoreLib.dll!System.Diagnostics.Debug.Assert(bool condition, string message, string detailMessage) Line 107	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(ref Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.BucketSet buckets, Microsoft.PythonTools.Analysis.AnalysisValue key, int hc, System.Collections.Generic.IEqualityComparer<Microsoft.PythonTools.Analysis.AnalysisValue> comparer) Line 425	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(ref Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.BucketSet buckets, Microsoft.PythonTools.Analysis.AnalysisValue key, System.Collections.Generic.IEqualityComparer<Microsoft.PythonTools.Analysis.AnalysisValue> comparer) Line 329	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.AddOne(Microsoft.PythonTools.Analysis.AnalysisValue key) Line 318	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Add(Microsoft.PythonTools.Analysis.AnalysisValue item, out bool wasChanged, bool canMutate) Line 161	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet.Add(Microsoft.PythonTools.Analysis.AnalysisValue item, out bool wasChanged, bool canMutate) Line 156	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo.AddType(Microsoft.PythonTools.Analysis.AnalysisValue ns) Line 117	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.TypedDef<Microsoft.PythonTools.Analysis.Analyzer.ReferenceableDependencyInfo>.AddTypes(Microsoft.PythonTools.Analysis.IVersioned projectEntry, Microsoft.PythonTools.Analysis.IAnalysisSet newTypes, bool enqueue, Microsoft.PythonTools.Analysis.IProjectEntry declaringScope) Line 261	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.FunctionScope.UpdateParameters(Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit unit, Microsoft.PythonTools.Analysis.Values.ArgumentSet others, bool enqueue, Microsoft.PythonTools.Analysis.Analyzer.FunctionScope scopeWithDefaultParameters, bool usePlaceholders) Line 199	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.UpdateParameters(Microsoft.PythonTools.Analysis.Values.ArgumentSet callArgs, bool enqueue) Line 63	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Values.FunctionInfo.DoCall(Microsoft.PythonTools.Parsing.Ast.Node node, Microsoft.PythonTools.Analysis.AnalysisUnit callingUnit, Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit calledUnit, Microsoft.PythonTools.Analysis.Values.ArgumentSet callArgs) Line 156	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Values.FunctionInfo.Call(Microsoft.PythonTools.Parsing.Ast.Node node, Microsoft.PythonTools.Analysis.AnalysisUnit unit, Microsoft.PythonTools.Analysis.IAnalysisSet[] args, Microsoft.PythonTools.Parsing.Ast.NameExpression[] keywordArgNames) Line 98	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator ee, Microsoft.PythonTools.Parsing.Ast.Node node) Line 378	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Microsoft.PythonTools.Parsing.Ast.Node node) Line 211	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Microsoft.PythonTools.Parsing.Ast.Expression node) Line 55	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(Microsoft.PythonTools.Parsing.Ast.AssignmentStatement node) Line 137	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Parsing.Ast.AssignmentStatement.Walk(Microsoft.PythonTools.Parsing.Ast.PythonWalker walker) Line 41	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(Microsoft.PythonTools.Parsing.Ast.SuiteStatement node) Line 665	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(Microsoft.PythonTools.Parsing.Ast.PythonWalker walker) Line 34	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(Microsoft.PythonTools.Parsing.Ast.IfStatement node) Line 522	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(Microsoft.PythonTools.Parsing.Ast.PythonWalker walker) Line 45	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(Microsoft.PythonTools.Parsing.Ast.SuiteStatement node) Line 665	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(Microsoft.PythonTools.Parsing.Ast.PythonWalker walker) Line 34	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(Microsoft.PythonTools.Analysis.Analyzer.DDG ddg, System.Threading.CancellationToken cancel) Line 88	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(Microsoft.PythonTools.Analysis.Analyzer.DDG ddg, System.Threading.CancellationToken cancel) Line 139	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Microsoft.PythonTools.Analysis.Deque<Microsoft.PythonTools.Analysis.AnalysisUnit> queue, System.Threading.CancellationToken cancel, System.Action<int> reportQueueSize, int reportQueueInterval) Line 75	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(System.Threading.CancellationToken cancel) Line 907	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(System.Threading.CancellationToken cancel) Line 229	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Intellisense.AnalysisQueue.HandleAnalyzable(Microsoft.PythonTools.Analysis.IAnalyzable item, Microsoft.PythonTools.Intellisense.AnalysisPriority priority, System.Threading.CancellationToken cancellationToken) Line 152	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Intellisense.AnalysisQueue.Enqueue.AnonymousMethod__0(System.Threading.CancellationToken ct) Line 136	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Intellisense.AnalysisQueue.ConsumerLoop() Line 64	C#
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 167	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.PythonTools.Intellisense.AnalysisQueue.<ConsumerLoop>d__25>.MoveNext() Line 559	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox box, bool allowInlining) Line 798	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject) Line 3276	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem>.TrySetResult(Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem result) Line 421	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem>.SetExistingTaskResult(Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem result) Line 639	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem>.SetResult(Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem result) Line 629	C#
 	Microsoft.Python.Analysis.Engine.dll!Microsoft.PythonTools.Intellisense.AnalysisQueue.ConsumeAsync() Line 89	C#
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 167	C#
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.PythonTools.Intellisense.AnalysisQueue.QueueItem>.AsyncStateMachineBox<Microsoft.PythonTools.Intellisense.AnalysisQueue.<ConsumeAsync>d__26>.MoveNext() Line 559	C#
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 588	C#

```

### LINKED ISSUE #383: Python Language Server crash "Value cannot be null."
_From @saulshanabrook on November 11, 2018 19:10_

## Environment data

- VS Code version: 1.29.0-insider
- Extension version (available under the Extensions sidebar): 2018.10.1
- OS and version: macOS High Sierra 10.13.6 (17G65)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.6 Anaconda
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
- Relevant/affected Python packages and their versions: N/A

## Actual behavior

No python intellisense when not using jedi.

## Expected  behavior

Python intellesense even when jedi is off

## Steps to reproduce:
1. Open any Python file when jedi is disabled

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.60.0
Initializing for /usr/local/miniconda3/envs/uarray/bin/python
##########Linting Output - mypy##########
##########Linting Output - flake8##########
[Error - 2:05:45 PM] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.PythonTools.Analysis.AnalysisValue.Microsoft.PythonTools.Analysis.IAnalysisSet.Union(IEnumerable`1 items, Boolean& wasChanged, Boolean canMutate)
   at Microsoft.PythonTools.Analysis.AnalysisSet.UnionAll(IAnalysisSet set, IEnumerable`1 sets, Boolean& wasChanged, Boolean canMutate)
   at Microsoft.PythonTools.Analysis.Values.ProtocolInfo.BinaryOperation(Node node, AnalysisUnit unit, PythonOperator operation, IAnalysisSet rhs)
   at Microsoft.PythonTools.Analysis.AnalysisValueSetExtensions.BinaryOperation(IAnalysisSet self, Node node, AnalysisUnit unit, PythonOperator operation, IAnalysisSet rhs)
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.HandleAnalyzable(IAnalyzable item, AnalysisPriority priority, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.ConsumerLoop()

```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3306 [naereen.makefiles-support-for-vscode]: Unknown language in `contributes.grammars.language`. Provided value: Makefile
g._logMessageInConsole @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3306
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1446  INFO no standard startup: not a new window
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Create file systemwatcher with pattern */python (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Create file systemwatcher with pattern */*/python (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Create file systemwatcher with pattern */python (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Create file systemwatcher with pattern */*/python (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Notify locators are locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Register Intepreter Watcher, Arg 1: {"$mid":1,"fsPath":"/Users/saul/p/uarray/uarray","external":"file:///Users/saul/p/uarray/uarray","path":"/Users/saul/p/uarray/uarray","scheme":"file"}, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Register Intepreter Watcher, Arg 1: undefined, Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Build the workspace interpreter watcher, Arg 1: {"$mid":1,"fsPath":"/Users/saul/p/uarray/uarray","external":"file:///Users/saul/p/uarray/uarray","path":"/Users/saul/p/uarray/uarray","scheme":"file"}, Return Value: UNABLE TO DETERMINE VALUE (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Build the workspace interpreter watcher, Arg 1: undefined, Return Value: UNABLE TO DETERMINE VALUE (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Get language server folder name, , Return Value: "languageServer.0.1.60" (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Failed to get conda environment list from conda Error: spawn conda ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9) (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:46:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: All locators have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value:  (at Logger.logInformation (/Users/saul/.vscode-insiders/extensions/ms-python.python-2018.10.1/out/client/common/logger.js:49:21))
```

_Copied from original issue: Microsoft/vscode-python#3302_

### LINKED ISSUE #397: TypeAnnotationTests get "tupletuple[...]" instead of "tuple[...]"
TypingModuleContainerAnalysis fails with:

```
Message: Expected description of 'module.dct_s_i_items'
to have description 'dict_items[tuple[str, int]]',
but found 'dict_items[tupletuple[str, int]]' or 'dict_items[tupletuple[str, int]]'.
```

And TypingModuleDocumentationExample_03 with:

```
Message: Assert.AreEqual failed.
Expected:<broadcast_message(message:str, servers:list[tuple[tuple[str, int], dict[str, str]]]) -> None>.
Actual:<broadcast_message(message:str, servers:list[tupletuple[tupletuple[str, int], dict[str, str]]]) -> None>.
```

Which I bisected back to commit 028b284d0ec24ecf35a736c91153f4b3e5830bc7.

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #397 (remove name protocol from tuple)
Fixes #383 (do not return nulls, return empty sets)
Fixes #378 (null check)
Fixes #379 (explicit protocol comparison)

### CODE REVIEW

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs [hunk 1]
```diff
@@ -78,10 +78,9 @@ await GetModuleVariablesAsync(entry as ProjectEntry, opts, @params.query, 50, ca
             var all = breadthFirst.SelectMany(c => analysis.GetAllAvailableMembersFromScope(c, opts));
             var result = all
                 .Where(m => {
-                    if (m.Values.Any(v => v.DeclaringModule == entry || v.Locations.Any(l => l.DocumentUri == entry.DocumentUri))) {
-                        if (string.IsNullOrEmpty(prefix) || m.Name.StartsWithOrdinal(prefix, ignoreCase: true)) {
-                            return true;
-                        }
+                    if (m.Values.Any(v => v.DeclaringModule == entry || 
+                        v.Locations.MaybeEnumerate().Any(l => l.DocumentUri == entry.DocumentUri))) {
```
Comment (jakebailey) [inline src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Unless I'm misreading it, the stack trace in #378 seems to indicate that the exception comes from inside the function given to the second `Any`. Are we sure `DocumentUri` is never null?

Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: It appears to fail on `GetModuleVariables>b__4(ILocationInfo l)` which may happen if `v.Locations` is null - which is possible. `MaybeEnumerate` handles null to the empty enumeration.  Now, `DocumentUri` does can be null but that's OK.

Comment (jakebailey) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Sorry, I misspoke. I meant that `l` is null, i.e. an element inside of `Locations`. I read the exception as "we tried to access `l.DocumentUri` and that failed because `l` was null. If `v.Locations` were null, the crash can't have come from inside the function, because `Any` would have failed before actually calling it.

Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Interesting point. I do see other places do `Locations.MaybeEnumerate()` which means `Locations` can be null. However, I don't see anything checking the actual location in the collection for nulls.

Comment (jakebailey) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: For what it's worth, when I was trying to debug this myself, I removed all of the "wait for analysis" from the top of these calls, and did end up with exceptions with a slightly different stack trace which indicated that `Locations` was null. I added a load of debug assertions to this function for every one of these checks, but couldn't make them trigger on my desktop (and did not get around to trying it out on my laptop where I was able to reproduce the issue).

File: src/Analysis/Engine/Impl/Values/ProtocolInfo.cs [hunk 2]
```diff
@@ -268,85 +268,78 @@ public override IAnalysisSet Call(Node node, AnalysisUnit unit, IAnalysisSet[] a
...
-        }
+        internal override bool UnionEquals(AnalysisValue av, int strength)
+            => av is ProtocolInfo pi ? ObjectComparer.Instance.Equals(_protocols, pi._protocols) : false;
 
-        internal override int UnionHashCode(int strength) {
-            if (strength > 0) {
-                return Name.GetHashCode();
-            }
-            return GetHashCode();
+    internal override int UnionHashCode(int strength) {
```
Comment (jakebailey) [inline src/Analysis/Engine/Impl/Values/ProtocolInfo.cs]: This file's indention got all screwed up.

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs [hunk 3]
```diff
@@ -95,7 +98,7 @@ await GetModuleVariablesAsync(entry as ProjectEntry, opts, @params.query, 50, ca
                 _kind = m.MemberType.ToString().ToLowerInvariant()
             };
 
-            var loc = m.Locations.FirstOrDefault(l => !string.IsNullOrEmpty(l.FilePath));
+            var loc = m.Locations.MaybeEnumerate().FirstOrDefault(l => !string.IsNullOrEmpty(l.FilePath));
```
Comment (jakebailey) [inline src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Does this (and the other `MaybeEnumerate()` call below) need `WhereNotNull()` like the change above?

File: src/Analysis/Engine/Impl/Values/ProtocolInfo.cs (hunk 2 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Values/ProtocolInfo.cs]: Fixed

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Yep. Added.

Comment (jakebailey) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: You added `WhereNotNull` to the lines below, but not this line.

File: src/Analysis/Engine/Impl/ModuleTable.cs [hunk 4]
```diff
@@ -416,7 +416,7 @@ private class InitializedModuleLoadState : ModuleLoadState {
                                     return false;
                                 }
 
-                                foreach (var location in type.Locations) {
+                                foreach (var location in type.Locations.WhereNotNull()) {
```
Comment (jakebailey) [inline src/Analysis/Engine/Impl/ModuleTable.cs]: Does this need a `MaybeEnumerate`, or is `type.Locations` known to be non-null at this point?

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs [hunk 5]
```diff
@@ -152,7 +158,11 @@ await GetModuleVariablesAsync(entry as ProjectEntry, opts, @params.query, 50, ca
                 res.children = Array.Empty<DocumentSymbol>();
             }
 
-            var loc = m.Locations.FirstOrDefault(l => !string.IsNullOrEmpty(l.FilePath));
+            var loc = m.Locations
```
Comment (AlexanderSher) [inline src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: The only implementation of `IMemberResult` is a struct `MemberResult`. We should either use that struct directly (without interface) or make it a class. 
Also, `Locations` can't be null, and I'd actually expect `IEnumerable<T>` properties and methods to never return null. `MaybeEnumerate` is an anti-pattern.

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs [hunk 6]
```diff
@@ -152,7 +158,11 @@ await GetModuleVariablesAsync(entry as ProjectEntry, opts, @params.query, 50, ca
...
+                .MaybeEnumerate()
+                .WhereNotNull()
```
Comment (AlexanderSher) [inline src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: It is better to filter out `null` locations in the `MemberResult` itself, though I don't know when it actually can be null.

File: src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs [hunk 7]
```diff
@@ -208,52 +209,17 @@ abstract class SpecializedNamespace : AnalysisValue {
...
 
-        public override IEnumerable<ILocationInfo> Locations {
-            get {
-                if (_original == null) {
-                    return new LocationInfo[0];
-                }
-                return _original.Locations;
-            }
-        }
+        public override IEnumerable<ILocationInfo> Locations => _original.Locations?.MaybeEnumerate();
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs]: Original check was about `_original` field being `null`, not its `Locations` property. Is that an expected change?

File: src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs [hunk 8]
```diff
@@ -208,52 +209,17 @@ abstract class SpecializedNamespace : AnalysisValue {
...
 
-        public override string Name => _original == null ? base.Name : this._original.Name;
+        public override string Name => _original == null ? base.Name : _original.Name;
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs]: Why in this case we call `base.Name`, and in previous explicitly return empty enumerable instead of calling `base.Locations`, which also returns empty enumerable?

File: src/Analysis/Engine/Impl/Values/ProtocolInfo.cs [hunk 9]
```diff
@@ -273,22 +268,10 @@ class ProtocolInfo : AnalysisValue, IHasRichDescription {
...
-        internal override bool UnionEquals(AnalysisValue av, int strength) {
-            if (av is ProtocolInfo pi) {
-                if (strength > 0) {
-                    return Name == pi.Name;
-                }
-                return ObjectComparer.Instance.Equals(_protocols, pi._protocols);
-            }
-            return false;
-        }
+        internal override bool UnionEquals(AnalysisValue av, int strength)
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Values/ProtocolInfo.cs]: `av is ProtocolInfo pi && ObjectComparer.Instance.Equals(_protocols, pi._protocols)`

File: src/Analysis/Engine/Impl/Values/ProtocolInfo.cs [hunk 10]
```diff
@@ -129,17 +129,15 @@ class ProtocolInfo : AnalysisValue, IHasRichDescription {
...
 
         public override IEnumerable<ILocationInfo> Locations {
             get {
-                ReferenceList defns;
-                if (!_references.TryGetValue(DeclaringModule, out defns)) {
+                if (!_references.TryGetValue(DeclaringModule, out var defns)) {
                     return Enumerable.Empty<ILocationInfo>();
                 }
-                return defns.Definitions.Select(l => l.GetLocationInfo()).Where(l => l != null);
+                return defns.Definitions.Select(l => l.GetLocationInfo()).ExcludeDefault();
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/Values/ProtocolInfo.cs]: Looks like we have two almost identical methods: `ExcludeDefaults` and `WhereNotNull`.

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs (hunk 5 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Actually they do can be null. It may be poor design and we can try and clean it up, but that's how it is today... For the sake of not crashing, just following current code patterns.

File: src/Analysis/Engine/Impl/Values/ProtocolInfo.cs (hunk 10 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Values/ProtocolInfo.cs]: Yes `ExcludeDefault` came from RTVS extensions, looks like `WhereNotNull` is local thing

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs (hunk 6 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: OK

File: src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs (hunk 7 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs]: Fixed

File: src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs (hunk 8 above)
Comment (MikhailArkhipov) [reply src/Analysis/Engine/Impl/Values/SpecializedNamespace.cs]: Good question. No idea.

File: src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs (hunk 5 above)
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.WorkspaceSymbols.cs]: Take it back, not in the member result.
