### PR TITLE
Fix wait for analysis complete, fix tests and avoid reload on all config changes

### LINKED ISSUE #111: Any change in configuration causes module reload
Which leads to memory leak as in #109

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #111 

- Improves #109 - avoid reloading modules on any configuration change. Still need to debug why reloading modules leaks.

- Improves test stability as well as Rename/FindReferences/DocumentSymbols/GotoDefinition by waiting for the complete analysis.

### CODE REVIEW

File: src/Analysis/Engine/Test/AnalysisTest.cs [hunk 1]
```diff
@@ -5451,2147 +5413,2147 @@ class C(object):
...
-/*
-        [TestMethod, Priority(0)]
-        public void PackageRelativeImport() {
-            using (var state = CreateAnalyzer()) {
-                state.CreateProjectOnDisk = true;
-
-                var package = state.AddModule("fob", "from .y import abc", "fob\\__init__.py");
-                var x = state.AddModule("fob.x", "from .y import abc");
-                var y = state.AddModule("fob.y", "abc = 42");
+        /*
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Test/AnalysisTest.cs]: We don't need this offset.

File: src/LanguageServer/Impl/Implementation/Server.cs [hunk 2]
```diff
@@ -712,5 +703,39 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
             return false;
         }
         #endregion
+
+        internal Task WaitForCompleteAnalysisAsync(CancellationToken cancellationToken) {
+            var tcs = new TaskCompletionSource<object>();
```
Comment (AlexanderSher) [inline src/LanguageServer/Impl/Implementation/Server.cs]:
```cs
=> Task.WhenAny(WaitForCompleteAnalysisWorker(cancellationToken), Task.Delay(Timeout.Infinite, cancellationToken)).Unwrap();
```

File: src/LanguageServer/Impl/LanguageServer.cs [hunk 3]
```diff
@@ -83,6 +87,7 @@ public sealed partial class LanguageServer: IDisposable {
         }
 
         public void Dispose() {
+            _shutdownCts.Cancel();
```
Comment (AlexanderSher) [inline src/LanguageServer/Impl/LanguageServer.cs]: `_shutdownCts` can be added to `_disposables`

File: src/Analysis/Engine/Impl/ProjectEntry.cs [hunk 4]
```diff
@@ -157,9 +157,13 @@ private class ActivePythonParse : IPythonParse {
 
         internal void SetCompleteAnalysis() {
             lock (this) {
-                _analysisTcs.TrySetResult(Analysis);
+                if (AnalysisVersion == _expectedParse) {
```
Comment (AlexanderSher) [inline src/Analysis/Engine/Impl/ProjectEntry.cs]: this can be simplified a bit:
```cs
lock (this) {
    if (AnalysisVersion != _expectedParse) {
        return;
    }
    _analysisTcs.TrySetResult(Analysis);
}
RaiseNewAnalysis(); 
```

File: src/LanguageServer/Impl/Implementation/Server.cs [hunk 5]
```diff
@@ -624,22 +611,14 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
...
-                cookieTask.ContinueWith(t => {
-                    if (t.IsFaulted) {
-                        // Happens when file got deleted before processing
-                        p.Dispose();
-                        LogMessage(MessageType.Error, t.Exception.Message);
-                        return;
-                    }
-                    OnDocumentChangeProcessingComplete(doc, t.Result as VersionCookie, enqueueForAnalysis, priority, p);
-                }).DoNotWait();
+                await OnDocumentChangeProcessingCompleteAsync(doc, cookie as VersionCookie, enqueueForAnalysis, priority, p);
```
Comment (AlexanderSher) [inline src/LanguageServer/Impl/Implementation/Server.cs]: Before the change, `EnqueueItem` has been completed before `ParseQueue.EnqueueAsync` was completed. Now it waits for the parse to finish. Also, before the change exceptions from `ParseQueue.Enqueue` were logged but didn't affect the caller. Right now, exception will be propagated up to the `DidChangeTextDocument`.

Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/Server.cs]: Maybe it should be 

```cs
catch {
      pending?.Dispose();
      throw
  }
```
```

File: src/LanguageServer/Impl/Implementation/ProjectFiles.cs [hunk 6]
```diff
@@ -100,5 +101,10 @@ internal sealed class ProjectFiles : IDisposable {
                 throw new ObjectDisposedException(nameof(ProjectFiles));
             }
         }
+
+        #region IEnumerable<IProjectEntry>
+        public IEnumerator<IProjectEntry> GetEnumerator() => All.GetEnumerator();
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/ProjectFiles.cs]: Used to be foreach (var pf in ProjectFiles.All), enumerabe makes it simpler

File: src/LanguageServer/Impl/Implementation/EditorFiles.cs [hunk 7]
```diff
@@ -121,6 +122,7 @@ internal sealed class EditorFile {
                     })
                 ));
 
+                cancellationToken.ThrowIfCancellationRequested();
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply src/LanguageServer/Impl/Implementation/EditorFiles.cs]: Sure
