### PR TITLE
Handle null docstrings in docstring converter

### LINKED ISSUE #1192: null docstring exceptions when converting docstrings
```
Microsoft.Python.LanguageServer.Documentation.DocstringConverter.SplitDocstring(String) in LanguageServer\Impl\Documentation\DocstringConverter.cs:line 505
Microsoft.Python.LanguageServer.Documentation.DocstringConverter..ctor(String) in LanguageServer\Impl\Documentation\DocstringConverter.cs:line 82
Microsoft.Python.LanguageServer.Sources.MarkdownDocumentationSource.FormatDocumentation(String) in LanguageServer\Impl\Sources\MarkdownDocumentationSource.cs:line 71
Microsoft.Python.LanguageServer.Sources.SignatureSource.GetSignature(IDocumentAnalysis, SourceLocation) in LanguageServer\Impl\Sources\SignatureSource.cs:line 99
Microsoft.Python.LanguageServer.Implementation.Server.SignatureHelp(TextDocumentPositionParams, CancellationToken) in LanguageServer\Impl\Implementation\Server.Editor.cs:line 69
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1192.

### CODE REVIEW

File: src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs [hunk 1]
```diff
@@ -23,12 +23,12 @@ namespace Microsoft.Python.LanguageServer.Tests.FluentAssertions {
     [ExcludeFromCodeCoverage]
     internal static class DocstringAssertions {
         public static AndConstraint<StringAssertions> ConvertToPlaintext(this StringAssertions a, string plaintext, string because = "", params object[] reasonArgs) {
-            DocstringConverter.ToPlaintext(a.Subject.NormalizeLineEndings()).Should().Be(plaintext.NormalizeLineEndings().TrimEnd(), because, reasonArgs);
+            DocstringConverter.ToPlaintext(a.Subject?.NormalizeLineEndings()).Should().Be(plaintext?.NormalizeLineEndings().TrimEnd(), because, reasonArgs);
```
Comment (AlexanderSher) [inline src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs]: Since this is the only place `NormalizeLineEndings` is used, we can check for `null` in the extension method itself.

Comment (AlexanderSher) [reply src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs]: `plaintext` is an expected string, we shouldn't change it in assertion.

Comment (AlexanderSher) [reply src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs]: something like `DocstringConverter.ToPlaintext(a.Subject.NormalizeLineEndings()).Should().Be(plaintext, because, reasonArgs);`

Comment (jakebailey) [reply src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs]: If I don't normalize the expected output, then all of my other tests will need to make this call, as they would depend on the line endings of the source file and the system line endings.

Comment (AlexanderSher) [reply src/LanguageServer/Test/FluentAssertions/DocstringConverterAssertions.cs]: Hm... ok, let's leave it as it is.
